frontend/src/components/KeyValueTable/KeyValueTable.tsx, frontend/src/pages/Player/ResourcesContext/ResourcesContext.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindow/ErrorsPage/components/ErrorModal/ErrorModal.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindow/ResourceOrErrorDetailPanel/ResourceOrErrorDetailPanel.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindow/ResourcePage/components/ResourceDetailsModal/ResourceDetailsModal.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/utils.ts
This fixes the following issue:
local click test on a copy of the session;
go to https://frontend-pr-3579.onrender.com/1/sessions/ezXja9PhDAU9ig8A3TYWP8vC08X6 and check that clicking on the error in the second bar does not crash the app
no
=> fix(HIG-3725): abstract ops crash

backend/hubspot/hubspot.go, backend/private-graph/graph/resolver_test.go
Missed a Hubspot call in #3597. Adding the argument to populate the "Referral" property here.
I did not test locally.
Will click test the whole flow once live.
=> [hotfix] Add referral argument when updating context in Hubspot

frontend/src/pages/Player/PlayerHook/PlayerHook.tsx, frontend/src/pages/Player/PlayerHook/PlayerState.ts, frontend/src/pages/Player/ResourcesContext/ResourcesContext.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ConsolePage/ConsolePage.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ErrorsPage/ErrorsPage.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/NetworkPage/NetworkPage.tsx, frontend/src/util/db.ts, frontend/src/util/preload.ts
IndexedDB caching has caused issues with stale data.
To allow caching all data and ensure that we never show incorrect data, return cached data first but always update with network data.
Local deploy.
No. IndexedDB version update not needed since data model has not changed.
Closes #3605
=> indexeddb should always make requests that update data

frontend/src/components/LinkButton/styles.css.ts, packages/ui/src/components/Button/styles.css.ts, packages/ui/src/components/ButtonIcon/styles.css.ts, packages/ui/src/components/SwitchButton/styles.css.ts
We've been adding styles with a `:focus` selector but these are having some undesirable side effects (see Linear issue linked below). It also results in losing the visual indicator of the active element in many of our interactive elements.
This PR restores the default styles for focusable elements which fixes the originally reported issue of confusing styles after closing a menu and restores the visual indicator to most of our interactive elements.
This video shows the changes in this PR first and then loads production and tabs through the page.
https://www.loom.com/share/fe0199d54754416fbbfbbf153974e22c
N/A
=> Fix focus styles on buttons

backend/kafka-queue/kafkaqueue.go
Turns out our explicit commit logic wasn't doing anything because `ReceiveMessage` was doing an implicit commit.
Switch to [FetchMessage](https://pkg.go.dev/github.com/segmentio/kafka-go#Reader.FetchMessage) to allow manual committing.
Local deploy.
No.
=> switch readmessage to fetchmessage

backend/clickhouse/logs.go, backend/main.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/components/Header/Header.tsx, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/LogsPage/LogsPage.tsx, frontend/src/routers/OrgRouter/ApplicationRouter.tsx
For the given data generated in #3606, this PR creates a stub page for showing the logs (`/${projectId}/logs`). This is only visible to Highlight admins.
Observe new log nav item:
Observe log data shown in a simple json viewer:
N/A
=> stub out page to load logs

.github/workflows/backend.yml, README.md, backend/public-graph/graph/resolver.go, backend/worker/worker.go, go.work.sum, sdk/highlight-go/go.mod, sdk/highlight-go/go.sum
Versioned sessions (with an `appVersion` set) were not having sourcemaps processed correctly
because GORM was not querying the version (always returned nil).
Local deploy with [runway error](https://app.highlight.io/1664/errors/ew641P6zDOUDqib1hOPLnstlarC7?page=1&query=and%7C%7Cerror_state%2Cis%2COPEN%7C%7Cerror-field_timestamp%2Cbetween_date%2C30%20days) being processed correctly.
No
=> fix error sourcemap processing

backend/clickhouse/logs.go, backend/kafka-queue/kafkaqueue.go, backend/kafka-queue/types.go, backend/main.go, backend/public-graph/graph/resolver.go, backend/public-graph/graph/schema.resolvers.go, backend/scripts/reset-kafka-offset/main.go, backend/worker/kafka_worker.go, backend/worker/worker.go
Log data should be written to clickhouse in batches per their recommendations, especially when log writes can be frequent.
Adds a new separate kafka queue used for batched messages (only logs for now). Workers consume
these messages until the batch size or batch timeout is hit, at which point they are processed and written to clickhouse
with the entire batch.
Local deploy observing creating and using the batched kafka queue.
No
=> [HIG-3749] add batched message processing for log ingestion

frontend/src/components/NewIssueModal/NewIssueModal.tsx, packages/ui/src/components/Form/Form.tsx
Cleans up some `any` in the `<Form.* />` components. 
Without this change, we weren't getting the underlying [ARIA kit form](https://ariakit.org/components/form) props. 
Before:
After:
N/A
=> fix any usage in form input props

backend/clickhouse/logs.go, backend/clickhouse/migrations/000002_rename_logs_table.down.sql, backend/clickhouse/migrations/000002_rename_logs_table.up.sql
See rollout plan of #4109.
Confirmed `logs_new` does not exist and `logs` does exist:
```
show tables;
=> 
name
--
logs
schema_migrations
```
Confirmed `logs` has data:
```sql
select count(*) from logs
=> 
count()
--
777
```
I also confirmed that we are reading/writing logs to the renamed table correctly. 
Per the rollout of #4109, I manually dropped `logs` on prod (`drop table logs;`). So when this rolls, out, this migration should run cleanly.
=> rename logs table

frontend/src/pages/ErrorsV2/ErrorStateSelect/ErrorStateSelect.tsx
Snoozing an error doesn't currently work because of a regression introduced in https://github.com/highlight/highlight/pull/3521/files#diff-1118372a92bc179eb5799ac9af7dfea83da9368881356f012fbf52736af7305bR65 which is resolved in this PR.
Resolves #4034 
N/A
=> Fix snoozing errors

packages/ui/src/components/Container/styles.css.ts
The fix for #4064 introduced a regression which prevents vertical scrolling on the errors page. This PR resolves that.
Resolves #4150
N/A
=> Fix vertical scroll on errors page

backend/go.mod, backend/go.sum, backend/otel/otel.go, docker/compose.dev.yml, sdk/highlight-go/otel.go
Updates the `highlight-go` sdk to report stacktrace, because otel does not report them by default.
=> ensure go errors report stacktrace

backend/go.mod, backend/go.sum, backend/otel/otel.go, backend/util/logging.go, sdk/highlight-go/otel.go, sdk/highlight-go/tracer.go
Adjust otel sdk settings to serialize go stacktraces.
Improve the otel ingest.
Improve golang graphql instrumentation to report stacktraces.
=> ensure go otel serializes stacktrace

backend/go.mod, backend/go.sum, backend/kafka-queue/types.go, backend/main.go, backend/model/model.go, backend/otel/otel.go, backend/public-graph/graph/resolver.go, backend/util/logging.go, sdk/highlight-go/go.mod, sdk/highlight-go/go.sum, sdk/highlight-go/log/log.go, sdk/highlight-go/log/logrus.go, sdk/highlight-go/otel.go, sdk/highlight-go/tracer.go, sdk/highlight-py/examples/app.py, sdk/highlight-py/highlight_io/sdk.py, sdk/highlight-py/poetry.lock, sdk/highlight-py/pyproject.toml
* Adds functionality to `highlight-go` SDK to instrument logrus
* Ingests OTLP logs to clickhouse.
* Fixes issues in ingest of error stacktraces with the golang SDK
* Fixes logs transmission of python SDK
Local deploy, using new logging and error ingest from our public/private graphs.
Will tag new version of `highlight-go` SDK
=> add otel logging ingest

backend/private-graph/graph/schema.resolvers.go, backend/worker/kafka_worker.go
Error instances were not reported in the right order because the order clause was sometimes omitted.
Local deploy with debug query output.
No
=> ensure error instances are shown in the right order

backend/otel/otel.go, backend/worker/kafka_worker.go, backend/worker/worker.go, sdk/highlight-py/examples/app.py, sdk/highlight-py/highlight_io/sdk.py, sdk/highlight-py/pyproject.toml
* Allow highlight python sdk to override OTLP endpoint.
* Batch messages from multiple partitions into a shared in-memory buffer.
* currently, each public-worker container runs 8 goroutines for the batched topic. each goroutine gets a set of subset of partitions assigned to it. as messages are consumed by the goroutines, we should aggregate the LogRows together across these partitions so that the batching can be more substantial. without this change, each goroutine had its own in-memory buffer which would not get many messages (and actually could lead to dropping messages because a goroutine would flush its partition's messages as the front of the topic, while in reality there may be other unflushed messages)
* Don't write log messages as an attribute.
Local deploy with debugger.
New …
=> improve kafka log batching and highlight-py sdk

backend/public-graph/graph/resolver.go, sdk/highlight-go/highlight.go
Ungate the backend console message processing so that all projects' frontend client logs are streamed through otel.
Local deploy.
Will monitor kafka queue backlogs / otel collector metrics.
=> enable frontend log streaming through otel for all projects

.github/workflows/turbo.yml, frontend/package.json, frontend/src/index.tsx, frontend/vite.config.ts
Ensure vite build does not put hash strings into the js output.
Use versioned sourcemaps for app.highlight.io
Preview
No
=> fix prod sourcemaps

frontend/src/components/CollapsibleSection/index.tsx, frontend/src/components/FullCommentList/FullCommentList.tsx, frontend/src/components/TextViewer/TextViewer.css.ts, frontend/src/components/TextViewer/index.tsx, frontend/src/pages/ErrorsV2/SearchPanel/SearchPanel.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ConsolePage/ConsolePage.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/DevToolsWindowV2.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ErrorsPage/ErrorsPage.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/NetworkPage/NetworkPage.tsx, frontend/src/pages/Player/components/EventStreamV2/EventStreamV2.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionsFeedV3.tsx, frontend/src/pages/Setup/CodeBlock/CodeBlock.tsx, frontend/src/style/common.css.ts
Instead of wrapping long lines in json previews, show a horizontal scrollbar. 
Closes https://github.com/highlight/highlight/issues/3909
local clicktest
go to any session with long metadata to see it in action
no
=> fix(#3909): switch to horizontal scrollbars for long json

frontend/src/pages/Error/components/ErrorComments/ErrorComments.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/DevToolsWindowV2.tsx, frontend/src/pages/Player/Toolbar/TimelineIndicators/TimelineBar/TimelineBar.tsx, frontend/src/pages/Player/Toolbar/TimelineIndicators/TimelineIndicatorsBarGraph/TimelineIndicatorsBarGraph.tsx, frontend/src/pages/Player/Toolbar/TimelineIndicators/TimelinePopover/TimelinePopover.tsx
Resolves #4143:
open the popover over the corresponding bar
change the popover to show the error body rather than the secure id
open the errors tab in dev tools
no
=> fix(#4143): error to session ux

frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ConsolePage/ConsolePage.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ErrorsPage/ErrorsPage.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/NetworkPage/NetworkPage.tsx, frontend/src/pages/Player/Toolbar/ToolbarControlBar/ToolbarControlBar.tsx
Resolves #4135. Makes sure dev tools do not come out of the loading state before the replayer and reloads network requests on session nav.
go to the sessions tab and check that the sessions are loading ok
no
=> fix(#4135): dev tools jankiness

backend/otel/otel.go, backend/otel/parse.go, backend/otel/parse_test.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/public-graph/graph/resolver.go, frontend/src/graph/generated/schemas.tsx
* Makes our otel errors ingest parse stack traces into a structured format that the frontend can render.
* Resolves a noisy log `PushMetricsImpl called without secureID` from session-less metrics (not yet supported).
New unit test, full stack deploy.
No.
=> make otel process stacktraces into structured format

README.md, backend/main.go, backend/otel/parse_test.go, backend/private-graph/graph/schema.resolvers.go, backend/vercel/vercel.go, frontend/src/pages/Setup/SetupPage.tsx, sdk/highlight-go/log/log.go
* Sets up new log drain handler on pub/vercel/v1/logs
* Adds [log drain creation](https://vercel.com/docs/concepts/observability/log-drains-overview/log-drains-reference) to the vercel integration setup workflow.
Local deploy testing the vercel log creation.
Tricky to test the log drain locally.
=> create vercel log drain from the integration

frontend/src/util/integrated.tsx
After the rewrite of routes, `project_id` [is undefined](https://github.com/highlight/highlight/blob/3921bc3ec1aff3500a1ef01281037fcef6e6cca6/frontend/src/routers/AppRouter/AppRouter.tsx#L123) at the point where we are calling useIntegrated. This PR fixes the useIntegrated hook by replacing useParams with useMatch which does not depend on the param defined inside `<Route .../>`.
Go to /sessions or /errors for any integrated project and check that the empty session card is correct.
e.g. https://frontend-pr-4244.onrender.com/1/sessions
should be (this PR):
now:
no
=> hotfix: replace useParams with useMatch for useIntegrated

backend/vercel/vercel.go
adds the `teamId` query string param which turns out is required for project-specific integration installations to
ensure that we use the [correct url](https://vercel.com/docs/rest-api#endpoints/log-drains/creates-a-configurable-log-drain) for creating a vercel log drain.
=> fix vercel log drain api url

backend/vercel/vercel.go, backend/worker/kafka_worker.go
* add extra vercel log drain setup logging
* reduce batch processing size for log ingest to limit write size
=> add vercel debug info and kafka log ingest sizes

frontend/src/pages/LogsPage/LogsPage.tsx
The upgrade for react-router #4203 fixes the issue I noted in #4128.
Confirmed that when we modify the input, it updates the query params correctly and triggers a re-render to persist the change in the input (previously, there wasn't a re-rendering happening).
N/A
=> Remove manual routing changes.

backend/clickhouse/logs.go, backend/clickhouse/seeds/main.go, backend/private-graph/gqlgen.yml, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/LogsPage/LogsPage.tsx
Currently, we throw an arbitrary limit on our logs query: https://github.com/highlight/highlight/blob/7a6090f5f5d54768aaddafb46fce52b678a5bf08/backend/clickhouse/logs.go#L54-L58
At some point, we'll be adjusting to add infinite scroll (#4211) but we'll still need to show the total count that a query matches. 
I pulled the script from #4173 to generate a lot of data. 
Confirmed the total count is present using the same formatting as the sessions view:
N/A
=> add total count to logs page

backend/migrations/cmd/backfill-session-missing-user-properties/main.go, backend/public-graph/graph/resolver.go
As discovered during our topic rewind due to opensearch running out of space, our
indexing of sessions in opensearch is not idempotent because it only happens if a session
does not exist in postgres.
Makes the opensearch session addition from `InitializeSession` always occur, even if the session exists in postgres.
Improves the backfill-session migration script for bulk processing and full reindexing of sessions in opensearch.
Local deploy.
No
=> make initializeSession opensearch indexing idempotent

frontend/package.json, frontend/src/index.tsx, frontend/src/pages/LogsPage/LogsPage.tsx, yarn.lock
See the revert of #4257. 
Basically, when we call `set*` with use-query-params, the updated value wasn't triggering a re-render. 
I discovered that the fix for this was two things:
* upgrading [use-query-params](https://github.com/pbeshai/use-query-params/tree/master/packages/use-query-params) to the next major version (see [migration plan](https://github.com/pbeshai/use-query-params/blob/master/packages/use-query-params/CHANGELOG.md#migrating-from-v1))
* correctly nesting `QueryParamProvider` under `BrowserRouter`
I undid the revert of #4257 and confirmed that updating the logs query correctly re-renders (triggers a new request to load logs). 
It seems like my bug occurs only when we are using a `set*` but most times we just pluck off the query value and then pipe it into something else. …
=> Fix query param rendering via use-query-params

frontend/src/pages/Player/Toolbar/DevToolsWindowV2/style.css.ts, packages/ui/src/components/Tabs/styles.css.ts
Removes the background color from tabs and cleans up unused styles.
Closes #4229.
go to the right panel and dev tools in the session view and make sure tabs look ok
no
=> fix(#4229): clean up tabs

frontend/src/pages/Player/Toolbar/TimelineIndicators/TimelinePopover/TimelinePopover.tsx, frontend/src/pages/ProjectSettings/ProjectSettings.tsx, frontend/src/routers/OrgRouter/ApplicationRouter.tsx
Resolves #4255.
At the moment going to project settings crashes the app:
https://app.highlight.io/1/settings/errors
Check out the preview: https://frontend-pr-4260.onrender.com/1/settings/errors
Go to project settings from the menu in the top left.
no
=> fix(#4255): routing for project settings

backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, backend/worker/worker.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/mutation.gql, frontend/src/pages/ErrorsV2/ErrorsV2.tsx
Track error group views and add hubspot instrumentation for reporting error group view counts.
Local deploy tracing whether a session view is reported.
No.
=> add sales observability for error monitoring

frontend/src/components/TableList/TableList.css.ts, packages/ui/src/components/Tag/styles.css.ts
Resolves #4214. 
Was:
Now:
1. Go to https://frontend-pr-4264.onrender.com/1/sessions/KIDpzdvEzDRkHYz2rpdG6SFod5Rm
2. Open the right panel
3. Check that the alignment is ok
no
=> fix(#4214): alignment in Tag and TableList

backend/public-graph/graph/resolver.go
- add a new noisy error to filter out - most of our current DB load is caused by this
- created https://github.com/highlight/highlight/issues/4281 to move this logic to a separate table
- built locally
- no
=> filter out a noisy error

frontend/src/pages/ErrorsV2/ErrorInstance/ErrorInstance.tsx
Fixes the "View all sessions for user" link on the errors page.
N/A
=> Fix view all sessions for users link on error page

frontend/src/pages/LogsPage/LogsPage.tsx, frontend/src/pages/LogsPage/SearchForm/SearchForm.tsx, packages/ui/src/components/DatePicker/PreviousDateRangePicker.stories.tsx, packages/ui/src/components/DatePicker/PreviousDateRangePicker.tsx
* Add a checkbox if range (or custom) is selected
* Add support for a min date
**Preset selected**
**Custom selected**
**Min date**
Observe that dates prior to `minDate` are greyed out and not selectable (the storybook example uses 90 days ago)
N/A
=> some datepicker additions

packages/ui/src/components/DatePicker/PreviousDateRangePicker.tsx
There's some extra padding when opening the calendar view of the datepicker. This is due to the padding of nesting inside a menu item:
https://github.com/highlight/highlight/blob/f2e0522c30be9fb644c06cb04fa5e43c8eec86e9/packages/ui/src/components/Menu/styles.css.ts#L20-L24
Before:
After:
N/A
=> remove extra padding on calendar select

frontend/src/pages/LogsPage/LogsPage.tsx, frontend/src/pages/LogsPage/LogsTable/LogsTable.tsx, frontend/src/pages/LogsPage/LogsTable/NoLogsFound.tsx
This PR creates an empty state when there are no logs found. Specifically when the query does not match anything. Note that this does not handle an onboarding situation whereby we have never received any logs (that'll be covered in #4213).
Fixes #4212
Observe empty state is horizontally and vertically centered:
I've also centered the loading spinner:
N/A
=> add empty state for when no logs are found

.github/workflows/docker.yml, backend/main.go, backend/opensearch/opensearch.go, backend/otel/otel.go, backend/public-graph/graph/resolver.go
Adds an enhanced health check for postgres, influx, redis, opensearch, and clickhouse.
Enhanced health check does not run for public graph since public graph only depends on kafka, and
we want to make sure public graph remains up even if other infra is down (ECS LB would not route traffic
to nodes that are not passing the health check).
Public graph health check validates kafka communication.
Local deploy.
Will monitor rollout. If health checks fail during rollout, ECS will not switch traffic over to the new containers.
=> add enhanced health check for non-public-graph runtimes

backend/otel/otel.go, examples/cloudflare-worker/package.json, examples/cloudflare-worker/src/index.ts, sdk/highlight-cloudflare/package.json, sdk/highlight-cloudflare/src/sdk.ts
Improves the cloudflare SDK with response recording support.
Fixes the `@highlight-run/cloudflare` package to actually publish a version to npmjs.
Local cloudflare testing using example.
No.
=> add cloudflare response recording support

frontend/src/pages/ErrorsV2/ErrorQueryBuilder/components/QueryBuilder/QueryBuilder.tsx, frontend/src/pages/Player/Toolbar/TimelineIndicators/TimelineIndicatorsBarGraph/TimelineIndicatorsBarGraph.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionFeedV3.css.ts, frontend/src/pages/Sessions/SessionsFeedV3/SessionQueryBuilder/components/QueryBuilder/QueryBuilder.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionQueryBuilder/components/SessionFeedConfigurationV2/SessionFeedConfigurationV2.tsx, frontend/src/util/dom.ts, packages/ui/src/components/Menu/Menu.tsx
Resolves #4234.
was:
now:
go to the session feed settings in the top left
no
=> fix(#4234): session feed settings

frontend/src/pages/Sessions/SessionsFeedV2/components/SessionFeedConfiguration/SessionFeedConfiguration.tsx
moment.day returns the day of the week (1 - 7), not the day of the month
old:
https://app.highlight.io/898/sessions/Mn8PwKIp8t3idNJ11QEjRXmVQ6y6?query=and%7C%7Ccustom_processed%2Cis%2Ctrue%7C%7Ccustom_created_at%2Cbetween_date%2C30%20days%7C%7Cuser_email%2Cis%2Crachel.bahl%40netlify.com%7C%7Ctrack_window%2Cis%2Csidekick
new
https://frontend-pr-4294.onrender.com/898/sessions/Mn8PwKIp8t3idNJ11QEjRXmVQ6y6?query=and%7C%7Ccustom_processed%2Cis%2Ctrue%7C%7Ccustom_created_at%2Cbetween_date%2C30%20days%7C%7Cuser_email%2Cis%2Crachel.bahl%40netlify.com%7C%7Ctrack_window%2Cis%2Csidekick
no
=> hotfix: session date in feed

frontend/src/pages/LogsPage/LogsPage.tsx
We need to add a spinner for the total log count added in #4253
Observe spinner while we are fetching the log count
N/A
=> add a spinner when fetching the total log count

backend/clickhouse/logs.go, backend/clickhouse/logs_test.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/LogsPage/LogsPage.tsx
We need to fetch all the possible facets (the keys of [LogAttributes](https://github.com/highlight/highlight/blob/bea44cc29d858c1d5267376fb601eda9bd48ae22/backend/clickhouse/migrations/000001_create_logs_table.up.sql#L12)) such that we can use this to build a really great UX to filter on.
Effectively, we need to get all keys over the last 30 days (the TTL of a log) with this query:
```sql
SELECT arrayJoin(LogAttributes.keys) as key, count() as cnt FROM logs
WHERE ProjectId = ${ProjectID}
AND Timestamp < now()
AND Timestamp >= (now() - toIntervalDay(30))
GROUP BY key
ORDER BY cnt DESC;
```
This orders the keys by popularity of how often they occur (see the unit test for an example).
The frontend receives this sorted array of `[{name, type}]` where `name` is the key name and `type` …
=> add backend endpoint to fetch log attributes keys

backend/private-graph/graph/schema.resolvers.go
Because an error instance's session may be excluded, ensure we prioritize showing error instances
with a processed session. When an error instance with an excluded session is loaded, do not render the session link
since the session will not be able to be loaded.
Local docker deploy.
No
=> ignore excluded sessions for error instances

.github/workflows/deploy.yml
- disabling this migration step to avoid DB blocking while we migrate our DB to another instance
- GORM automigrate would run a few `ALTER TABLE ALTER COLUMN` commands - this is fixed in newer versions of GORM, but there are some other issues happening in our code base with the newest GORM v1 release
- will keep monitoring prod
- no, will revert this once DB instance migration is complete
=> temporarily disable migration during deploy

frontend/src/pages/ErrorsV2/ErrorSourcePreview/ErrorSourcePreview.tsx, frontend/src/pages/ErrorsV2/ErrorStackTrace/ErrorStackTrace.css.ts, frontend/src/pages/ErrorsV2/ErrorStackTrace/ErrorStackTrace.tsx, sdk/highlight-go/otel.go
Tweaks display of error stack trace titles.
stops wrapping of long lines because 
limits on the length of file names
No
=> tweak frontend stacktrace display

backend/main.go, backend/otel/otel.go, backend/worker/kafka_worker.go, sdk/highlight-go/log/log.go, sdk/highlight-go/otel.go
Makes the otel data ingest mark a project as having their backend integration setup.
For otel data coming from the frontend (frontend console logs), the flag should not be set.
Local deploy.
No.
=> otel ingest should mark backend setup

backend/private-graph/graph/schema.resolvers.go
- `project_id` needs to be included in the join condition here to avoid returning invalid users
- tested locally
- no
=> filter project_id in top users query

backend/clickhouse/logs.go, backend/clickhouse/logs_test.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/schemas.tsx
When the user types into the log input and has a filter selected, we should provide possible values that might facilliate their search. This will work similar to datadog's search:
This is the backend endpoint. A follow up PR will handle wiring this up to the frontend.
Unit test added
N/A
=> add an endpoint to fetch values for a given key

backend/otel/otel.go, frontend/src/pages/ErrorsV2/ErrorInstance/ErrorInstance.tsx
If a stacktrace is empty on an error instance, omit it in the frontend.
Local deploy manipulating stacktrace to be `"null"` or `""`
No
=> omit empty error instance stacktrace

backend/private-graph/graph/schema.resolvers.go
- had some invalid data break prod because some queries cast this column to jsonb when reading
- tested different inputs to `json.Valid` in a Go sandbox, made sure this function worked locally
- no
=> add JSON validation for allowed_auto_join_email_origins

sdk/highlight-go/log/console_messages_parser.go, sdk/highlight-go/log/log.go
Column / Line number can come as int or string. Ensure they are parsed as an int.
Local deploy.
No
=> fix serialiazation issue for frontend log lines

sdk/highlight-cloudflare/package.json, sdk/highlight-next/package.json, sdk/highlight-node/package.json, sdk/highlight-react/package.json, sourcemap-uploader/package.json
Makes our packages using tsup consistently implement a `typegen` script that will be used by turborepo in the right order.
Local `yarn test:all`
No. Could bump versions, but this change does not actually affect the npmjs packaged files (just affects our CI build ordering)
=> ensure sdk types built first before frontend

.gitmodules
`.gitmodules` pointed to old repository url (referencing old org name) which currently 301s but may break in the future.
Local `git submodule init --update`; CI
No
=> update git submodule url

backend/clickhouse/logs.go, backend/clickhouse/logs_test.go
This PR solves two things:
* Fix our quoting logic that results in a panic with multiple filters (#4359)
* Changes the quote delimiter from single quote (`'`) to double quote (`"`). Per a conversation with @ccschmitz, the latter seems more logical to support (and matches the way datadog works).
Fixes #4359
I red/greened this with a unit test.
I also click tested the query from #4359 to validate there is no panic error anymore:
N/A
=> fix quoting logic for filters

backend/clickhouse/logs.go, backend/clickhouse/logs_test.go, backend/clickhouse/seeds/main.go, backend/go.mod, backend/go.sum
We need to expand flatted json when fetching logs.
Test setup
While I added nested json to the seeds script, it's probably easier to test via:
```sql
TRUNCATE logs;
```
make the following diff locally:
```diff
diff --git a/backend/clickhouse/seeds/main.go b/backend/clickhouse/seeds/main.go
index 9d552cea1..1525e618f 100644
--- a/backend/clickhouse/seeds/main.go
+++ b/backend/clickhouse/seeds/main.go
@@ -39,27 +39,7 @@ func makeRandomBody() string {
}
func makeRandLogAttributes() map[string]string {
-       randomKeys := [21]string{
-               "key1",
-               "key2",
-               "key3",
-               "key4",
-               "key5",
-               "key6",
-               "key7",
-               "key8",
-               "key9",
-               "key10",
- …
```
=> expand nested json in logs

frontend/src/pages/ErrorsV2/ErrorInstance/ErrorInstance.tsx
- Julianified design for errors w/o a session
- click tested locally, made sure errors with sessions are displayed properly
- no
=> #4310 disable session button and add callout when no session

backend/otel/otel.go, e2e/go/go.mod, sdk/highlight-cloudflare/package.json, sdk/highlight-cloudflare/src/sdk.ts, sdk/highlight-go/log/log.go, sdk/highlight-go/log/logrus.go, sdk/highlight-go/otel.go, sdk/highlight-next/package.json, sdk/highlight-node/package.json, sdk/highlight-node/src/client.ts, sdk/highlight-py/highlight_io/sdk.py, sdk/highlight-py/pyproject.toml
Standardizes highlight otel attribute names to be more consistent with otel conventions.
Local deploy running e2e examples of our sdks.
New SDK versions.
Ingest will support deprecated attribute names, favoring the new ones.
=> standardize highlight context variable attribute names

backend/clickhouse/logs.go, backend/clickhouse/logs_test.go
We can get an empty string when fetching key values. 
Example:
```sql
CREATE TABLE table_map (a Map(String, String)) ENGINE=Memory;
INSERT INTO table_map VALUES ({'foo':'bar'})
INSERT INTO table_map VALUES ({'baz':'buzz'})
```
```sql
SELECT a['foo'] as value, count() as cnt FROM table_map
GROUP BY value
ORDER BY cnt DESC
```
| value | count |
|-------|-------|
|       | 1     |
| bar   | 1     |
This is seems to be because of some weird clickhouse quirk whereby the `baz` row is saying I have nothing that matches the `a['foo']` column. We can filter it out with a `mapContains`
```
SELECT a['foo'] as value, count() as cnt FROM table_map
where mapContains(a, 'foo')
GROUP BY value
ORDER BY cnt DESC
```
| value | count |
|-------|-------|
| bar   | 1     |
Unit tests FTW
N/A
=> filter out empty strings when fetching values for a key

frontend/src/pages/Alerts/AlertConfigurationCard/AlertConfigurationCard.tsx
- if a user edited any of the other alert fields without editing the "emails to notify", the emails would be cleared
- click test locally
- no
=> initialize alert emails to what was already saved to prevent them from being cleared on save

frontend/src/components/CommandBar/CommandBar.tsx, frontend/src/components/CommandBar/context.ts
Jay's suggestions:
1. At least one option is always selected, which avoids the confusion about the behavior on `enter` press with no explicit selection.
2. Adds `enter` hint for the selected option.
cmd-k or /
no
=> hotfix: commandbar polish

frontend/src/pages/Player/styles.css.ts
Resolves #3997.
was
going to be
no
=> fix(#3997): container corners in session replay

backend/clickhouse/seeds/main.go, frontend/src/pages/LogsPage/LogsTable/LogBody.tsx, frontend/src/pages/LogsPage/LogsTable/LogDetails.css.ts, frontend/src/pages/LogsPage/LogsTable/LogDetails.tsx, frontend/src/pages/LogsPage/LogsTable/LogTimestamp.tsx, frontend/src/pages/LogsPage/LogsTable/LogsTable.css.ts, frontend/src/pages/LogsPage/LogsTable/LogsTable.tsx, frontend/src/pages/LogsPage/SearchForm/SearchForm.css.ts, frontend/src/pages/LogsPage/SearchForm/SearchForm.tsx, packages/ui/src/components/ButtonLink/ButtonLink.tsx, packages/ui/src/components/ButtonLink/styles.css.ts
* Some UI updates to better match what we have in Figma
* Adds a copy button to copy the raw log to your clipboard
* Adds a button to toggle all nested fields
* Adds some logic to collapse all rows when the search query changes
* Adds a `kind` prop to `ButtonLink` that allows creating button links that are gray instead of purple
* Fixes a display issue when logs have very long string values with no spaces
https://www.loom.com/share/a744874144484127845f78a4eab3d649
Local and PR preview click test
N/A
=> Polish for logs view

e2e/nextjs/next.config.js, e2e/nextjs/package.json, sdk/highlight-next/CHANGELOG.md, sdk/highlight-next/package.json, sdk/highlight-next/src/util/withHighlightConfig.test.ts, sdk/highlight-next/src/util/withHighlightConfig.ts, yarn.lock
Adds support for [generateBuildId](https://nextjs.org/docs/api-reference/next.config.js/configuring-the-build-id) which is how folks typically provide their app version to a next.js app. 
Local deploy of e2e next.js app with `generateBuildId` set in config.
`@highlight-run/next` version bump.
Closes #4418
=> add support for next.js generateBuildId

backend/private-graph/graph/resolver_test.go, backend/private-graph/graph/schema.resolvers.go, frontend/src/pages/AboutYou/AboutYouCard.tsx, frontend/src/pages/NewProject/NewProjectPage.tsx, frontend/src/util/db.ts
`AboutYou` page would get stuck on completion because the Admin query would be cached by indexeddb, and we were not awaiting the mutation to complete. Submitting the `AboutYou` page would not change the UI until the page was refreshed. This bug would only surface on production frontend builds.
Fixes a backend race condition with `Admin` row creation waiting for firebase data.
Local production deploy of frontend: `doppler run -- yarn vite build; doppler run -- yarn vite preview --port 3000`
`make debug` backend gdb tracing
Testing with new account creation.
No
=> fix about you forms getting stuck on completion

frontend/src/index.tsx, frontend/src/routers/OrgRouter/DefaultWorkspaceRouter.tsx
- use `useLocation` hook to rerender `AuthenticationRoleRouter` on page change
- remove `workspace_id` from the `DefaultWorkspaceRouter` match because the component is only used when there is no numeric workspace_id provided
- click test locally, went to a bunch of pages to make sure the top level `useLocation` wasn't causing any major issues
- no
=> Fix deep links for workspace-level pages

package.json, sdk/highlight-py/e2e/highlight_aws/lambda_function.py, sdk/highlight-py/e2e/highlight_azure/HttpTrigger/__init__.py, sdk/highlight-py/e2e/highlight_azure/requirements.txt, sdk/highlight-py/e2e/highlight_gcp/hello_http.py, sdk/highlight-py/highlight_io/integrations/aws.py, sdk/highlight-py/highlight_io/integrations/azure.py, sdk/highlight-py/highlight_io/integrations/django.py, sdk/highlight-py/highlight_io/integrations/gcp.py, sdk/highlight-py/highlight_io/integrations/serverless.py, sdk/highlight-py/highlight_io/sdk.py, sdk/highlight-py/poetry.lock, sdk/highlight-py/pyproject.toml, sdk/highlight-py/tests/test_aws.py, sdk/highlight-py/tests/test_gcp.py
Adds `gcp` and `aws` integrations for the Python SDK to support functions.
New unit tests.
Manual deploy of e2e functions.
New python sdk version.
=> add python sdk support for GCP Cloud Functions and AWS Lambda

frontend/package.json, frontend/src/pages/Accounts/Accounts.tsx, frontend/src/pages/Billing/Billing.tsx, frontend/src/pages/Billing/BillingPlanCard/BillingConfig.ts, frontend/src/pages/Billing/BillingPlanCard/BillingPlanCard.tsx, frontend/src/pages/Billing/BillingStatusCard/BillingStatusCard.tsx, yarn.lock
- upgrade to latest version of `dinero` for `toDecimal`
- adjust tooltip text based on retention period
- represent session + error overage prices as cents to avoid floating point math (crashes page for certain inputs because of an `assert` in the `dinero` constructor)
- no
=> billing page fixes

frontend/src/pages/Billing/BillingStatusCard/BillingStatusCard.tsx
- showing overage as 100x what it should be after the change to use cents - fix this
- click test locally
- no
=> billing page - fixup cents calc

docker/otel-collector.yaml
Since we're not using the `otel-contrib` image, the `groupby` processor is missing, so we remove it.
=> fix: removed groupbytrace otel processor

sdk/client/package.json, sdk/client/src/index.tsx, sdk/firstload/package.json, yarn.lock
Customers have reported finding collisions in the `fingerprint` session value. Our usage of fingerprint.js limits what heuristics it uses so there are likely collisions in the ids.
Switch to using the generated clientID as the fingerprint for consistency in our session search and frontend UI. 
On our backend, we expect the fingerprint as a string now that is hashed, so the change should be entirely compatible.
Local deploy.
New client version.
=> replace fingerprint with generated client id

backend/clickhouse/logs.go, backend/clickhouse/logs_test.go, backend/clickhouse/seeds/main.go, backend/go.mod, backend/go.sum, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/LogsPage/LogsTable/LogDetails.tsx
This PR adds support for filtering by `trace_id`, `span_id`, and `secure_session_id`. 
The naming of `"secure"_session_id` may be confusing (I could see an argument for calling this `session_id`). Jay and I chatted about this and we are opting to leave it as for now. People won't really be using this search directly (they'll only see it because they they were on a session page and clicked View logs which populated that filter). We can revisit this if it seems confusing.
Observe that values are only visible when a non-empty string:
Trace id filtering works:
Span id filtering works:
Secure session id filtering works:
=> add filtering for trace id, span id, and secure session id

backend/clickhouse/logs_test.go
This is a test PR to see if ClickHouse is getting confused with equal timestamps.
=> hotfix: tests for logs histogram

backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go, frontend/src/components/Header/Header.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/index.tsx, frontend/src/routers/OrgRouter/ApplicationRouter.tsx
Admin resolver no longer creates an admin, which may be necessary because the CreateAdmin mutation is not guaranteed to be called in some edge cases.
Local deploy.
No
=> fix admin creation

backend/clickhouse/logs.go, backend/clickhouse/logs_test.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/LogsPage/LogsPage.tsx, frontend/src/pages/LogsPage/SearchForm/SearchForm.tsx
Fetching values for keys takes too long. This is for two reasons:
* we are using an aggregation query `COUNT`
* we are not using a time range
This PR simplifies the query to fetch values to fix this issues. Per the linked issue, this dramatically speeds up the query.
Clicktested locally to confirm query still works.
We should monitor in prod to confirm this results in the queries passing.
=> add a date range when choosing log key values

frontend/src/pages/Setup/SetupPage.tsx, sdk/client/src/index.tsx, sdk/client/src/types/types.ts, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/index.tsx
Highlight does not record correctly in an iframe because of the cross-origin setting. Before this change,
when Highlight is added to an iframe with the intention to record just the iframe, we would assume that
the iframe was emitting events to the parent while there was no Highlight instance in the parent.
Since previously we would pass `recordCrossOriginIframes: true` to rrweb, the following logic in rrweb would never emit events in an iframe.
```ts
const inEmittingFrame = recordCrossOriginIframes
? window.parent === window
: true;
```
Buttons page iframe recording.
New highlight.run minor version bump.
=> fix recording in iframes without highlight in the parent window

frontend/src/pages/Player/Toolbar/DevToolsWindowV2/DevToolsWindowV2.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/utils.ts
Issue #4416 
-Improves network request filtering
-Shows count per request type
-Displays proper name in MenuButton for selected network request filter type
-**Note - doesn't implement multi-select, perhaps that can be split into a separate issue**
-Dev mode click test
-None
=> Issue #4416 - show count per network request type

backend/clickhouse/cursor.go, backend/clickhouse/cursor_test.go, backend/clickhouse/logs.go, backend/clickhouse/logs_test.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx
This PR extends #4319 to add backward pagination and support to permalink to log. A frontend PR will follow that wires up these changes.
This continues with the [Relay spec](https://relay.dev/graphql/connections.htm#sec-Backward-pagination-arguments) adding a `before` argument.
Similar to handling the `after` cursor logic:
```sql
WHERE Timestamp <= x
AND ( Timestamp < x OR UUID < y )
ORDER BY Timestamp DESC, UUID DESC
```
we need to invert the logic to handle going "backwards" ("backward" in flying quotes because it's going forward in time to get the newer logs)
```sql
WHERE Timestamp >= x
AND ( Timestamp > x OR UUID > y )
ORDER BY Timestamp ASC, UUID ASC # Note the flipped order here
```
If we simply returned this directly though, the result would not match the existing descending order, …
=> Handle backward pagination and permalinking logs (backend)

backend/clickhouse/logs.go, backend/clickhouse/logs_test.go
This PR ensures we persist a space when searching a log body.
Confirmed that searching with a space works.
Before:
After:
N/A
=> fix searching log body with a space

backend/clickhouse/logs.go, backend/clickhouse/logs_test.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, frontend/src/graph/generated/schemas.tsx, frontend/src/pages/LogsPage/SearchForm/SearchForm.tsx, frontend/src/pages/LogsPage/SearchForm/utils.test.ts, frontend/src/pages/LogsPage/SearchForm/utils.ts
To accompany #4509, this allows one to search for the log body via `message:value`. We'll use this once we wire up clicking on a log property to prefill the search (see https://github.com/highlight/highlight/issues/4471#issuecomment-1456516602) 
This _does not_ include `message` in the dropdown keys because it would just be noise at that point:
Confirmed direct search works:
Confirmed wildcard works:
N/A
=> add the ability to search body via message:value

frontend/src/components/CommandBar/context.ts
We've received customer feedback that they search for an email through commandbar using the 'identifier' filter, but not all identifiers are emails. 
no
=> hotfix: add email to commandbar filters

backend/main.go, sdk/highlight-go/highlight.go, sdk/highlight-go/log/console_messages_parser.go, sdk/highlight-go/log/console_messages_parser_test.go, sdk/highlight-go/log/log.go, sdk/highlight-go/log/logrus.go, sdk/highlight-go/log/util.go, sdk/highlight-go/otel.go
Enhances the go sdk with manual log functions that can be used without a logging library.
Local deploy.
Will release new highlight-go tag.
=> add manual log methods to highlight go sdk

frontend/src/pages/WorkspaceTabs/WorkspaceTabs.tsx
Fixes an issue where users we stuck in a redirect loop when visiting the root path for their workspace (`/w/:workspace_id`).
Local click test. Should be able to confirm in the PR preview as well.
N/A
=> Fix infinite workspace redirect

frontend/src/pages/LogsPage/LogsTable/LogsTable.tsx
Frontend polish from #4535
The permalinked log should expand open by default.
N/A
=> expand the permalinked log

frontend/src/pages/LogsPage/LogsPage.tsx, frontend/src/pages/LogsPage/LogsTable/LogsTable.tsx
Regression from #4535. It's more noticeable on prod where the initial logs request takes longer than development.
Fixes #4546
Confirmed on render preview that flashing doesn't occur.
N/A
=> fix empty state flashing

backend/alerts/alerts.go, backend/alerts/routing.go, backend/model/model.go, backend/public-graph/graph/resolver.go
Slack alerts should link to an error instance so that the session from which an alert triggers
is included as part of the URL and shows the relevant stacktrace. Otherwise, customers have
complained about the slack alert URLs leading them to error instances from old sessions or situations
where the stack trace is out of date.
Local deploy with alerts integrated.
No
=> update slack alerts to link to error instance

backend/lambda-functions/deleteSessions/handlers/handlers.go, backend/main.go, backend/migrations/cmd/add-has-comments-opensearch-field/main.go, backend/migrations/cmd/backfill-session-missing-user-properties/main.go, backend/migrations/cmd/influxdb-backfill-error-groups/main.go, backend/model/model.go, backend/opensearch/opensearch.go, backend/otel/otel.go, backend/retryables/retryables.go
Report opensearch indexing errors as postgres rows.
Local deploy.
No
=> report retryable opensearch errors to postgres for reprocessing

frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ErrorsPage/ErrorsPage.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/NetworkPage/NetworkPage.tsx
Issue #4556 
- For player console Network rows and Error rows:
- "Goto" button should only navigate to the correct timestamp, not open the right panel
- Dev mode click test
- https://www.loom.com/share/e3d006d50fa04832bc6ff4fab8300e25
- None
=> Aaron i4556

frontend/index.html
Adds hubspot tracking pixel for tracking google ads conversions.
Local frontend build passing.
No
=> add hubspot tracking pixel

backend/clickhouse/logs.go
When we paginate forward, the query time becomes exceptionally slow. The reason for this is because clickhouse isn't optimizing ordering. Adjusting our `ORDER BY` to match our schema fixes the issue:
https://github.com/highlight/highlight/blob/95b5df43da50ebeb8f7f4236544950e65d8be1e1/backend/clickhouse/migrations/000004_create_new_logs_table.up.sql#L26
Let's take a really simple query that trys to get the next set of logs before a given a timestamp.
```sql
SELECT *
FROM logs
WHERE (ProjectId = 1) AND (Timestamp >= '2023-03-10 20:39:09.801403533')
ORDER BY Timestamp DESC
LIMIT 10
```
This query takes an exceptionally long time to run:
`10 rows in set. Elapsed: 81.754 sec. Processed 170.75 million rows, 181.68 GB (2.09 million rows/s., 2.22 GB/s.)`
whereas if we run the exact same query, …
=> ensure we use identical ordering as the schema when we query

frontend/src/index.tsx
Make sure that the `getAdmin` query reruns when switching between project and workspace context.
Rerunning the firebase subscription if the context changes should be ok since the useEffect returns a cleanup callback.
Visiting `/w/1/upgrade-plan` locally after logging in/out would exhibit the `access denied` modal which is fixed with this change.
No.
=> fix billing details not loading when coming from non-workspace page

backend/clickhouse/logs.go
We are currently optimizing slow queries for things we know about it but It would be great to have insight on other slow queries we don't know about.
This PR adds tracing data for our read logs queries.
Will observe in datadog.
N/A
=> add tracing for querying clickhouse

backend/clickhouse/logs.go, backend/clickhouse/logs_test.go
When we search on the log body, we aren't utilizing the `tokenbf_v1` index (see #4575). This particular index basically takes a log body such as `log.Info("some message that we emit")` and splits it into tokens `["some", "message", "that", "we", "emit"])`.
In order to leverage it properly, we need to switch to actually use the `hasToken` function to see if one of those tokens contains our string. This does require us to split up the body string even further:
For example: searching for "some message that we emit" would construct this query:
```sql
SELECT Timestamp, Body
FROM 
logs 
WHERE 
ProjectId = 1 
AND Timestamp >= (now() - toIntervalDay(15))  
AND (hasToken(Body, 'some'))
AND (hasToken(Body, 'message'))
AND (hasToken(Body, 'that'))
AND (hasToken(Body, 'we'))
AND (hasToken(Body, …
```
=> speed up body searches by utilizing bloom filter index

backend/public-graph/graph/resolver.go
Some new projects are sending lots of sessions causing our own `BillingQuotaExceeded` error to cause high json match load on postgres.
Local backend build.
No
=> filter noisy highlight errors

backend/hubspot/hubspot.go
Retry hubspot contact creation to avoid (hopefully) transient 500 errors.
No
=> retry hubspot admin creation

frontend/src/pages/Sessions/EmptySessionsSearchParams.tsx
Live sessions should not be shown by default because they have a tendency to confuse highlight users.
Local frontend deploy.
No
=> exclude live sessions

sdk/client/src/types/client.ts, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/index.tsx
Ensures we don't initialize Mixpanel or Amplitude integrations when they are explicitly disabled. Also removes a Mixpanel warning which wasn't accurate and makes the tokens/keys optional in the integration objects optional so you don't need to specify them when trying to set `disabled: true`.
Could possibly change tracking behavior if projects were not configured correctly in the past (were passing the token/API key + `disabled`).
=> Don't allow integration setup when disabled

frontend/src/pages/LogsPage/LogsTable/LogTimestamp.tsx
Uses moment to format timestamps. Using the built-in javascript datetime formatting handles the hour at the start of the day weirdly (see #4605)
Confirmed this moment format starts at the zero hour.
N/A
=> fix invalid timestamp

backend/clickhouse/logs.go, backend/clickhouse/logs_test.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, frontend/src/graph/generated/schemas.tsx, frontend/src/pages/LogsPage/LogsTable/LogDetails.tsx, frontend/src/pages/LogsPage/LogsTable/LogLevel.tsx
Filtering by log level is sometimes broken because we haven't normalized it before writing to the db (something that will have a more robust fix in #4464).
To compensate for the discrepancy, in [#4555,](https://github.com/highlight/highlight/pull/4555/files#diff-44251d85d1baf341cd7313aaa7aa61bd8d4832267460557e8cbb6b215ba3b52fR373-R378) the frontend is lowercasing the level but this is something the backend should just be figuring out.
This PR ensures that the backend always sends the frontend lowercase log levels and that we always write it to lowercase before hitting the clickhouse db.
* Confirmed the backend is sending lowercase log levels to the frontend
* Confirmed we can filter by log level via the frontend
N/A
=> fix filtering by log level

.vscode/launch.json, backend/clickhouse/log_row.go, backend/clickhouse/log_row_test.go, backend/clickhouse/logs.go, backend/otel/otel.go
`log.severity` and `log.message` aren't being excluded from `LogAttributes`.
This PR fixes that. It also moves some data parsing logic down out of the OTEL code and into the logs code. This makes it easier to unit test and it sets up a better interface for building a log row.
Confirmed `log.severity` and `log.message`  aren't present in log attributes anymore.
N/A
=> skip writing log attributes if these are internal attributes

frontend/src/index.tsx, sdk/highlight-py/e2e/highlight_azure/HttpTrigger/function.json, sdk/highlight-py/e2e/highlight_azure/requirements.txt, sdk/highlight-py/highlight_io/integrations/aws.py, sdk/highlight-py/highlight_io/integrations/azure.py, sdk/highlight-py/highlight_io/integrations/gcp.py, sdk/highlight-py/highlight_io/integrations/serverless.py, sdk/highlight-py/pyproject.toml
Updates the highlight python sdk to ensure serverless wrapper signatures do not conflict with the serverless libraries.
Pytest, currently testing on azure.
https://highlightaztest.azurewebsites.net/api/httptrigger
Releasing new python sdk version 0.4.4
=> fix python serverless signature

sdk/highlight-py/highlight_io/sdk.py, sdk/highlight-py/pyproject.toml
To keep SDKs consistent, enable log recording by default in the Python SDK.
Pytests.
New version released.
=> enable logs recording by default

backend/worker/opensearch.go
- some sessions have many associated fields, if more than 2 of these are loaded at the same time, we'll hit the postgres 65535 parameter limit
- longer term, we could have a custom script for this instead, performance won't be great since it's making separate calls for each pair of sessions, but there won't usually be more than a few dozen per 30 minute run of the update-opensearch job
- made sure `update-opensearch` job still worked locally
- nope, will monitor for errors post-deployment
=> limit batch size for opensearch update job

sdk/highlight-apollo/package.json, sdk/highlight-nest/package.json, sdk/highlight-next/package.json, sdk/highlight-node/CHANGELOG.md, sdk/highlight-node/package.json, sdk/highlight-node/src/client.ts, sdk/highlight-node/src/handlers.ts, yarn.lock
* Make the expressjs error middleware synchronous to ensure other middleware runs serially.
* Adds a way to force flushing opentelemetry trace data from the nodejs sdk.
Usage of local SDK - https://github.com/Learn-Build-Teach/learn-build-teach-discord-bot/tree/add-highlight
New versions of SDK released.
=> add ability to flush nodejs sdk

.github/workflows/backend.yml, backend/clickhouse/log_row.go, backend/clickhouse/log_row_test.go, backend/otel/otel.go, backend/otel/otel_test.go, docker/compose.yml, frontend/src/pages/ErrorsV2/ErrorLogCursor/ErrorLogCursorRedirect.tsx, sdk/highlight-go/highlight.go, sdk/highlight-go/log/logrus.go, sdk/highlight-go/log/util.go, sdk/highlight-go/otel.go
OTEL error level logs should create error objects, so that our UI can successfully link logs to errors.
Local deploy.
No
=> ensure error logs create error objects

sdk/highlight-next/package.json, sourcemap-uploader/package.json, sourcemap-uploader/src/lib.ts, yarn.lock
* Move `eslint` and `typescript` from dependencies to devDependencies, since they shouldn't be necessary at runtime
* Remove `aws-sdk` dependency altogether since it isn't used anywhere anymore
* Remove unused `@types/*` dependencies
* Upgrade various dependencies
`yarn && yarn build` in the `sourcemap-uploader` directory
No
=> Move dependencies to devDependencies

frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/ErrorsV2/ErrorInstance/ErrorInstance.tsx, frontend/src/pages/ErrorsV2/ErrorLogCursor/ErrorLogCursorRedirect.tsx
Adjusts how the logs query is built on the errors page for finding related logs.
Uses a +- 5 minutes time window for related logs.
Ensures the link has a project in it in case the user belongs to more than one project. 
This also fixes loading glitchiness on the logs -> errors link.
https://www.loom.com/share/e97679360aaf4794967b6b03b6516fff
preview: https://frontend-pr-4665.onrender.com/sign_in
No
=> fix error to log url linking

backend/clickhouse/cursor_test.go, backend/clickhouse/logs.go, backend/clickhouse/logs_test.go, backend/clickhouse/migrations/000006_create_logs_new.down.sql, backend/clickhouse/migrations/000006_create_logs_new.up.sql
Our existing schema is hitting memory errors. From doing some analysis, it appears that using an `ORDER BY` (which we always do to sort logs in time descending order) isn't working very well with a DateTime64.
The original reasoning for using this precision was borrowed from the OTEL schema. But in reality, this nanosecond precision is overkill and using a `DateTime` (second precision) is adequate.
This PR creates a new table (`logs_new` but we can rename this later to `logs`) that has a simpler schema, namely:
* Timestamp changed from DateTime64 -> DateTime
* Removed all the codec stuff
* Removed `toUnixTimestamp` in the order by
* Removed `index_granularity` setting (we were using 8092 which is the default, if we remove it, clickhouse can adjust it with adaptive granularity if it makes …
=> switch timestamp precision on logs table

frontend/src/pages/LogsPage/utils.ts
See this screenshot:
The `:8` for seconds is confusing without a leading zero. It should be `:08`
Load with this URL: https://localhost:3000/1/logs?end_date=2023-03-23T03%3A32%3A08.738Z&start_date=2023-03-23T03%3A17%3A08.979Z
Confirmed the leading zero for seconds is present.
N/A
=> add leading zero to time

frontend/src/pages/ErrorsV2/ErrorInstance/ErrorInstance.tsx, frontend/src/pages/LogsPage/SearchForm/utils.ts, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/DevToolsWindowV2.tsx
[Figma](https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=40-3089&t=lrQbbI0AVltkH5CZ-0)
This adds a Related logs button to the session's devtools when the Console tab is selected.
Clicking on it loads the logs page when the secure session id filled in with a time range of (session.created_at + 1 day) to capture all the logs while also optimizing the clickhouse query. Setting a range is required so we don't use the default state of "Last 15 minutes". 
Verified that clicking Related logs loads the logs page correctly with the secure session id in the filter box.
N/A
=> add related logs to session devtools

backend/clickhouse/logs.go, backend/clickhouse/logs_test.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/LogsPage/SearchForm/SearchForm.tsx
Fetching log key queries is slow because we don't specify a time range (see #4652 and #4507). 
* Added unit test
* Verified log keys still loads via the frontend
A more robust solution would be #4662 but we'll look into that after our launch.
=> attach a time frame when fetching log keys

frontend/src/pages/LogsPage/LogsTable/LogDetails.css.ts, frontend/src/pages/LogsPage/LogsTable/LogDetails.tsx
Adds a `Related Session` button for logs that have a session id.
Updates the `Related Error` button design per figma.
https://www.loom.com/share/51ef1bcf3b8f412ea3a90fc09f138880
No
=> add related sessions button

backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go
- autocreated monitors are a bit overwhelming when visiting the alerts page for the first time
- charts function correctly with 0 related monitors
- tested locally by creating new project + visiting dashboard
- no
=> stop autocreating monitors in UpsertDashboard

backend/jobs/metric-monitor/metric-monitor.go, backend/public-graph/graph/resolver.go, backend/util/logging.go, backend/worker/worker.go
- there are a bunch of "expected" errors - now that error logs are creating Highlight error groups, this is causing us to build up a Kafka backlog
- these should be treated as log level WARN
- will monitor in prod after deployment, expecting backlog to resolve
- no
=> warn instead of err for expected errors

backend/clickhouse/cursor_test.go, backend/clickhouse/logs.go, backend/clickhouse/logs_test.go
This PR lowers the number of logs loaded from 100 -> 50. There's a couple reasons for this:
* Loading large amounts of data (which we see with `LogAttributes`) can cause clickhouse to slow down significantly (see https://github.com/ClickHouse/ClickHouse/issues/7187)
* If there is very few matching results (e.g. find me logs with a log body of "STRIPE_INTEGRATION_ERROR"), we want to terminate as early as possible
* Loading less data results in a smaller payload size.
* Realistically, only about ~20-25 logs fix on the the screen (dependent on screen size) given our UX. This reason is less important as the previous points but mostly mentioning that this change shouldn't break our UX.
Verified that logs still load and pagination works as expected.
N/A
=> lower log limit

backend/clickhouse/logs.go, backend/clickhouse/migrations/000007_drop_logs_old.down.sql, backend/clickhouse/migrations/000007_drop_logs_old.up.sql, backend/clickhouse/migrations/000008_rename_logs_table.down.sql, backend/clickhouse/migrations/000008_rename_logs_table.up.sql
This PR tears down the old logs table now that our data has been fully migrated to the new schema (see #4667) and renames the `logs_new` table to `logs`
* Validated `show tables;` only shows a `logs` table
* Validated the data of `logs_new` still exists, just in a table called `logs` now.
Per the query in #4667, this will free up 125 GB of data
=> teardown old logs table

backend/clickhouse/log_row.go, backend/clickhouse/log_row_test.go, backend/otel/otel.go
Error created from error logs should have the logattributes as the payload. 
For example, the following [error](https://app.highlight.io/1/errors/pkQAv9oKfgBVYBO99aZ0ocJ3qk1w/instances/162208765?page=1) has an associated [log](https://app.highlight.io/logs/MjAyMy0wMy0yM1QxNToxOTowMVosMjc5OTYzYzgtOGMzNS00NjBjLWJhYTctYjhhMmI1NmQ3MDlm) that has structured attributes that are not passed to the created error.
The PR also captures span attributes that were not being processed on logs and errors (for example, the go sdk can report attributes on a span with the `span.SetAttribute` method exposed via the opentelemetry span interface.
After the change, errors show useful tags that can help with debugging an error. In the above example, the `path` attribute is a custom tag on the log line that shows …
=> ensure errors created from a log pass structured metadata

backend/alerts/integrations/webhook/serializer.go, backend/alerts/integrations/webhook/webhook.go, backend/alerts/sessionalerts.go, backend/model/sessionalerts.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/mutation.gql, frontend/src/graph/operators/query.gql, frontend/src/pages/Alerts/AlertConfigurationCard/AlertConfigurationCard.tsx, frontend/src/pages/Alerts/EditMonitorPage.tsx, frontend/src/pages/Alerts/MonitorConfiguration/MonitorConfiguration.tsx, frontend/src/pages/Alerts/NewAlertPage.tsx, frontend/src/pages/Alerts/NewMonitorPage.tsx, package.json
Adds a frontend for viewing and editing webhook alerts.
Depends on merging #4678 
Local deploy.
https://www.loom.com/share/e2053fab48c74af58d73cd9fc0f41a22
No.
=> add frontend logic to retrieving and setting webhook configurations

backend/worker/kafka_worker.go, backend/worker/worker.go
Ensure batches message flushing happens based on the inner count of messages to avoid OOM
due to a large batch of OTLP messages coming in.
Local deploy.
Monitoring kafka backlog.
=> flush batched messages based on inner count

backend/otel/otel.go
There are logs with very large `LogAttributes` columns:
```sql
select * from logs where Body = 'otel span error got no session and no project' and Timestamp >= (now() - toIntervalDay(1))
```
This is causing issues when trying to return that data to the frontend (see [slack](https://highlightcorp.slack.com/archives/C04NUD29BT3/p1679955470606809?thread_ts=1679944459.103359&cid=C04NUD29BT3)).
=> remove logrow and requestjson from logging

backend/private-graph/graph/resolver.go, frontend/src/pages/Alerts/AlertConfigurationCard/AlertConfigurationCard.tsx, frontend/src/pages/Alerts/AlertSetupModal/AlertSetupModal.tsx, frontend/src/pages/Alerts/MonitorConfiguration/MonitorConfiguration.tsx, frontend/src/pages/ErrorsV2/ErrorFeedHistogram/ErrorFeedHistogram.tsx, frontend/src/pages/ErrorsV2/ErrorInstance/ErrorInstance.tsx, frontend/src/pages/ErrorsV2/ErrorQueryBuilder/components/QueryBuilder/QueryBuilder.tsx, frontend/src/pages/ErrorsV2/utils.ts, frontend/src/pages/Player/PlayerHook/PlayerHook.tsx, frontend/src/pages/Player/PlayerHook/utils/index.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionQueryBuilder/components/QueryBuilder/QueryBuilder.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionsFeedV3.tsx, frontend/src/util/preload.ts, frontend/src/util/time.ts
Tweaks local error group loading per some feedback.
* errors feed refresh icon does not refresh instances (only refreshes error group)
* error instance / user count not working correctly for new errors
* clicking show session from error opens session in weird state (does not move player to right time
* updates `channels to notify` -> `slack channels to notify` to be more specific
Local deploy.
Correct instances for new error.
No.
=> cleanup error loading

backend/clickhouse/log_row.go, backend/clickhouse/log_row_test.go, backend/otel/otel.go, sdk/highlight-go/otel.go
Removes `exception.` attributes from logs since they are bloating `LogAttributes` and are not useful. 
For error stacktraces, we parse and structure them anyway.
Adds a limit to tag values at 64K characters. 
This is a pretty high limit but prevents arbitrarily-large values from being sent.
No
=> exclude exception tags and limit log attributes

backend/migrations/cmd/influxdb-backfill-error-groups/main.go, backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/schemas.tsx
Ensure error instance counts are correct by falling back on opensearch queries / postgres data
when an error group metric is missing from influxdb.
Consolidates some types by using the `modelInputs.ErrorDistributionItem` consisntly.
Before
After
No
=> fallback to using opensearch for error group frequency queries

frontend/src/pages/ErrorsV2/ErrorInstance/ErrorInstance.tsx, frontend/src/pages/LogsPage/SearchForm/SearchForm.tsx
Clicking `Show Logs` from errors would populate the query string that would be replaced with the default value of the form.
Ensure that the search form only updates the query when there is an actual input.
https://www.loom.com/share/12625c23205348369aa2d745bf2a14e7
No
=> ensure logs query string is used when provided

frontend/package.json, frontend/src/pages/LogsPage/LogsTable/LogDetails.tsx, frontend/src/pages/LogsPage/SearchForm/SearchForm.tsx, frontend/src/pages/LogsPage/SearchForm/utils.test.ts, frontend/src/pages/LogsPage/SearchForm/utils.ts, frontend/src/pages/LogsPage/useGetLogs.ts
Updates the behavior for handling strings in logs queries.
* Does not strip/transform quotes on user input anymore. Instead, we perform a transformation before sending the query string to the server to convert everything to double quotes.
* Adds quotes around values that need it when being applied outside the search input (e.g. "Apply as filter" button or selecting an item in the dropdown list).
Local and PR preview click testing.
N/A
=> Fix handling of quotes in logs queries

backend/clickhouse/logs.go
Clickhouse has a feature called [PREWHERE](https://clickhouse.com/docs/en/sql-reference/statements/select/prewhere) which allows it to filter data efficiently.
Under the hood, Clickhouse does this automatically. 
See how it's doing it when we search for `SecureSessionId`:
```sql
EXPLAIN SYNTAX
SELECT
Timestamp,
UUID,
SeverityText,
Body,
LogAttributes,
TraceId,
SpanId,
SecureSessionId
FROM logs
WHERE (ProjectId = 1) AND (Timestamp <= now()) AND (Timestamp >= (now() - toIntervalHour(1))) AND (SecureSessionId = 'test')
ORDER BY Timestamp ASC
LIMIT 50
┌─explain────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ SELECT …
```
=> manually set PREWHERE when using log body searches

frontend/src/pages/LogsPage/LogsTable/NoLogsFound.tsx
Log search [docs](https://www.highlight.io/docs/general/product-features/logging/log-search) are now live. We should update the empty state to reflect that.
Fixes #4723
Visual test
N/A
=> add log search specification link to logs empty state

backend/otel/otel.go, frontend/src/index.tsx, sdk/client/src/index.tsx, sdk/client/src/listeners/first-load-listeners.tsx, sdk/client/src/types/types.ts, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/index.tsx
* stop creating error instances from error logs
* adds an opt-in way to disable reporting console logs as errors
Testing with new `reportConsoleErrors: false` setting.
Testing without the `reportConsoleErrors` (should default to true) continues to report errors.
New version of the `highlight.run` npm package. `reportConsoleErrors` will default to `true` for now.
=> stop creating errors for error logs

backend/pricing/pricing.go
- debugging an error "expected 4 prices, received 3", adding some more context to figure out exactly which key is not found
- tested `%#v` print format in go playground, will monitor these errors in prod after deploying
- no
=> output lookup keys for debugging missing key

backend/clickhouse/log_row.go, backend/clickhouse/log_row_test.go, backend/util/logging.go, sdk/highlight-go/log/util.go, sdk/highlight-go/middleware/fiber/middleware.go, sdk/highlight-go/tracer.go
Our graphql entrypoint `InterceptResponse` creates a span that passes a context to children with that span set.
Nested operations may set the span attributes affecting the parent span, as happens in the following log:  
In general, this standardizes the format of the source to be `frontend` or `backend`.
No.
=> ensure that backend spans set source correctly

frontend/src/pages/Billing/Billing.tsx
- Apollo was returning an old checkout URL, add the `no-cache` fetch policy since these urls expire
- will verify new URLs are generated in prod
- no
=> use no-cache when updating stripe subscription

packages/ui/src/components/DatePicker/PreviousDateRangePicker.test.tsx, packages/ui/src/components/DatePicker/PreviousDateRangePicker.tsx
The relative date time picker doesn't include hours or minutes which can make it hard to understand what the time range is. For example, linking from the sessions, only [looks back the last 4 hours](https://github.com/highlight/highlight/pull/4653/files#diff-79ba7ec6cb62b65929c3c8a0aabc7b5857d3bd339dd50e40382ebf8f61f7194aR105).
This PR adjusts the label when the relative time picker is closed, namely:
* adds hours and minutes to when the relative date time picker is closed
* removes the day of week.
Before:
After:
N/A
=> add more context to logs datetime picker when it is closed

frontend/src/util/integrated.tsx
The integration status gets stuck in pending/loading because we don't fetch it when we've already cached the status in localStorage.
We are making more requests now to the integration endpoint. We should circle back on this to eliminate the extra requests if we already know they are integrated.
=> [hotfix] Make sure we always fetch integration status on setup

backend/model/model.go, backend/pricing/pricing.go, backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver.go, backend/worker/worker.go
- `daily_error_counts` was overcounting - switch this to use a materialized view similar to the sessions count instead
- cleanup some now-unused code
- increase timeout to 30 mins per refresh
- tested errors count in billing query locally
- tested `make refresh-materialized-views`
- no
=> use materialized view for errors count

backend/clickhouse/log_row.go, backend/main.go, backend/otel/otel.go, backend/vercel/vercel.go, docs-content/sdk/go.md, e2e/go/fiber.go, e2e/go/go.mod, e2e/go/go.sum, highlight.io/components/QuickstartContent/backend/go/go-gqlgen.tsx, highlight.io/components/QuickstartContent/logging/go/fiber.tsx, sdk/highlight-go/middleware/chi/middleware.go, sdk/highlight-go/middleware/fiber/middleware.go, sdk/highlight-go/middleware/gin/middleware.go, sdk/highlight-go/middleware/gorillamux/middleware.go, sdk/highlight-go/middleware/util.go, sdk/highlight-go/tracer.go
Improve our highlight graphql `tracer` to allow logging all graphql operations. 
This is particularly handy until we have a better tracing product to allow folks to find
highlight frontend sessions where a particular network request (GraphQL operation) was
called by searching for it in the logs and then finding its session.
Fixes the go/fiber middleware to use the `c.Context()` which is more commonly 
available in customers' codebases rather than the `UserContext()`
Will deploy new version of the go package.
=> improve middleware to trace http request handling

backend/pricing/pricing.go, backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go
- our stripe integration was failing to update details for older plans (e.g. ones without unlimited members) because `|SixMonths` was being appended to the lookup key
- default to the `3 month` prices instead (which doesn't add anything extra to the lookup key)
- don't update the workspace's retention period after the billing period ends to preserve the null  value
- ran `make report-stripe-usage` locally
- need to set `workspace.retention_period` to null for grandfathered 6 month retention customers
=> fix STRIPE_INTEGRATION_ERROR for grandfathered-in plans

backend/clickhouse/logs.go, backend/clickhouse/logs_test.go
Log attribute searches are not escaped.
Added a unit test to confirm we don't error.
N/A
=> escape log attribute searches

frontend/src/pages/LogsPage/LogsTable/LogsTable.tsx
In #4738 we added an error state for logs. After looking at this with a real error, we decided that we shouldn't actually show the raw message of the error and should just show a generic message.
N/A
=> remove actual error message from logs error state

docker/compose.yml
Currently fails to deploy with the docker compose file on versions greater than v2.17, see [this](https://github.com/docker/compose/issues/10407#issuecomment-1484787932)
=> fix yaml merges

docs-content/getting-started/3_client-sdk/7_replay-configuration/tracking-events.md
Typo linking to alerts in the tracking docs.
CI building the highlight.io preview.
No
=> Typo linking to alerts

highlight.io/components/Docs/Docs.module.scss
Added `cursor: pointer` to the docs link icon
=> Added cursor:pointer to docs link icon

.github/workflows/docker.yml, docker/frontend.Dockerfile
We are hitting the following error in our docker builds on main:
```sh
#50 [public.ecr.aws/k9o6n7l8/highlight-frontend frontend-base 28/42] RUN yarn
#50 0.787 ➤ YN0000: ┌ Project validation
#50 0.787 ➤ YN0057: │ @highlight-run/frontend: Resolutions field will be ignored
#50 0.788 ➤ YN0057: │ @highlight-run/client: Resolutions field will be ignored
#50 0.788 ➤ YN0000: └ Completed
#50 0.788 ➤ YN0000: ┌ Resolution step
#50 1.439 ➤ YN0001: │ Error: highlight.io@workspace:*: Workspace not found (highlight.io@workspace:*)
```
The problem is that we don't copy over our `highlight.io` directory in our `frontend.Dockerfile`.
Set the workflow step to run and took it from [red](https://github.com/highlight/highlight/actions/runs/4598192564/jobs/8121903507?pr=4815) to [green (still failing because an …
=> [hotfix] highlight.io build error

docs-content/general/4_company/open-source/contributing/4_landing-site.md, highlight.io/package.json
This PR runs the docs on port 4000 (it currently defaults to 3000). This avoid conflicts with the main app.
`yarn dev:frontend` successfully runs
N/A
=> use port 4000 for docs to avoid a conflict with the main app

highlight.io/next.config.js
We are seeing some issues loading images on our setup pages. The error is CORS related.
This PR sets a header to allow cross origin requests for our images in `public/images`.
Confirmed the header was set when inspecting an image loaded locally.
Should just monitor to ensure images are being loaded as expected once this goes out to prod.
=> [hotfix] Fix images not loading in setup docs from app

backend/clickhouse/logs.go, backend/clickhouse/logs_test.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/LogsPage/LogsHistogram/LogsHistogram.tsx, frontend/src/pages/LogsPage/useGetLogs.ts
Currently, our logs endpoint defaults to sorting logs in descending order. This PR adds backend support to sort logs in ascending order. A follow up PR will actually leverage this such that we can replace the session viewer logs (which expects ascending order).
I manually modified the logs query to use ascending order
```diff
diff --git a/frontend/src/pages/LogsPage/useGetLogs.ts b/frontend/src/pages/LogsPage/useGetLogs.ts
index 5bb453596..1c3e84745 100644
--- a/frontend/src/pages/LogsPage/useGetLogs.ts
+++ b/frontend/src/pages/LogsPage/useGetLogs.ts
@@ -53,7 +53,7 @@ export const useGetLogs = ({
variables: {
project_id: project_id!,
at: logCursor,
-				direction: Types.LogDirection.Desc,
+				direction: Types.LogDirection.Asc,
params: {
query: serverQuery,
date_range: {
```
and confirmed …
=> Support sorting logs in ascending order

highlight.io/utils/urls.ts
Reusing images from highlight.io in app.highlight.io results in a 308 redirect error:
We observed that manually changing the URL to use www fixes that redirect error.
This is somewhat tricky to test. We're operating off of a hunch. If this does not work, we will just move the images over.
N/A
=> add www to site images to ensure we do not redirect

backend/clickhouse/cursor.go, backend/clickhouse/cursor_test.go, backend/clickhouse/log_row.go, backend/clickhouse/log_row_test.go, backend/clickhouse/logs_test.go, backend/clickhouse/seeds/main.go, backend/otel/otel.go, frontend/src/pages/ErrorsV2/ErrorInstance/ErrorInstance.tsx, frontend/src/pages/ErrorsV2/ErrorsV2.tsx, frontend/src/pages/LogsPage/LogsTable/LogDetails.tsx, frontend/src/pages/Player/PlayerHook/utils/index.tsx, frontend/src/pages/Player/PlayerPage.tsx
Addresses linking logic between errors and logs.
* makes error -> `related session` button use a copyable link that closes left panel while populating error details
* makes logs -> `related session` button use a copyable link that closes left panel
* makes logs -> `related error` button use a copyable link that closes left panel
Fixes issue in clickhouse timestamp rounding after #4667 that broke logs -> errors linking
```
returned by clickhouse
2023-04-03 23:15:46 +0000
MjAyMy0wNC0wM1QyMzoxNTo0NlosODVmM2EwYTAtYjFhMS00ZWJiLWIxMjctODRmZTAxNjdmYTBk
in otel
2023-04-03 23:32:12.547854882 +0000
MjAyMy0wNC0wM1QyMzozMjoxMi41NDc4NTQ4ODJaLDc5MDFmMGM2LTYwMmYtNDk1NS05ZTZmLTYwYTQyODQ3NmI0NQ==
after fix in otel
2023-04-03 23:37:51 +0000
MjAyMy0wNC0wM1QyMzozNzo1MVosY2M3ODlkOTMtN2Q4ZS00MTJkLTliMTgtZjM2ZDZ …
```
=> use link for related session error link

backend/clickhouse/log_row.go, backend/clickhouse/log_row_test.go, backend/clickhouse/logs_test.go, backend/otel/otel.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, frontend/src/graph/generated/schemas.tsx, sdk/highlight-go/log/util.go, sdk/highlight-go/otel.go
In preparation for #4779, we need a GraphQL enum to identify the log source (because Go types aren't usable on the frontend without a of work).
Additionally, this PR fixes a bug with the `IsBackend` function that wasn't correctly identifying backend logs correctly.
* Tests added
* Code should compile
N/A
=> use graphql enum for identifying log source

frontend/src/util/time.ts
We are getting this moment deprecation warning on the session page:
This is pretty noisy especially when it shows up in the session console viewer ([example](https://app.highlight.io/1/sessions/1vlsA5jzUoyLvuBU1mEn5O2RdJzn)).
This has been happening for some time now and it appears to be because we are feeding moment a non standard time format. Hence it falls back to using `new Date` (see [here](https://stackoverflow.com/a/23376374) for more context).
The code in question is simply trying to get the floor time of the nearest minute and moment has a built-in function to do that while still maintaining proper formatting.
Observed no deprecation warning.
N/A
=> fix moment deprecation warning

.github/workflows/docker.yml, docker/start-infra.sh
Make the check for migration success more strict so that it does not match irrelevant lines.
```bash
2023-04-06T04:19:40.4627731Z + grep -i 'error ' /tmp/highlightSetup.log
2023-04-06T04:19:40.4627833Z + grep -v lambda
2023-04-06T04:19:40.4628053Z go: downloading github.com/hashicorp/go-multierror v1.1.1
```
Improving the GitHub Action output as well to make it easier to triage the test.
Running in CI.
Testing the bad-path locally:
No
=> fix ci check for opensearch migration

frontend/src/components/Header/Header.tsx, frontend/src/pages/Setup/SetupRouter/SetupRouter.tsx, frontend/src/routers/ProjectRouter/ApplicationRouter.tsx, frontend/src/routers/ProjectRouter/ProjectRouter.tsx
Reverts highlight/highlight#4841
This is causing the page to randomly refresh every 2 seconds. We have an [intercom](https://highlightcorp.slack.com/archives/C01EQU6G18R/p1680788184803689) and I was able to reproduce this locally.
Not sure what the actual root issue is but we can figure that after the revert is out.
=> Revert "[hotfix] Only query integration data on projects"

backend/main.go, backend/util/logging.go, docs-content/sdk/go.md, highlight.io/components/QuickstartContent/backend/go/go-gqlgen.tsx, sdk/highlight-go/tracer.go
Fixes an issue with the gqlgen graphql server middleware provided by the highlight go sdk that would
cause a panic on graphql server errors.
Improves the backend panic recovery utility to use the native gqlgen error object.
Hitting the backend with an invalid graphql request no longer causes a panic:
Hitting the backend with a graphql request that actually panics shows a stacktrace:
Docs
Will tag a new go sdk version.
=> ensure tracer does not panic on graphql errors

backend/private-graph/graph/schema.resolvers.go
Change backend integration checks from querying `.First` to `.Limit(1).Find` so that SQL queries are faster.
```
-- old query
SELECT * FROM "error_groups" WHERE project_id = 1 ORDER BY "error_groups"."id" LIMIT 1
Limit  (cost=0.56..508.62 rows=1 width=1580) (actual time=33636.120..33636.120 rows=1 loops=1)
->  Index Scan using error_groups_pkey on error_groups  (cost=0.56..6014852.53 rows=11839 width=1580) (actual time=33636.119..33636.119 rows=1 loops=1)
Filter: (project_id = 1344)
Rows Removed by Filter: 34845309
Planning Time: 0.087 ms
Execution Time: 33636.140 ms
-- new query
SELECT * FROM "error_groups" WHERE project_id = 1 LIMIT 1
Limit  (cost=0.44..1.35 rows=1 width=1580) (actual time=0.049..0.049 rows=1 loops=1)
->  Index Scan using idx_error_groups_project_id on error_groups …
```
=> update sql queries for backend integration checks

frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ConsolePage/ConsolePage.tsx
The logic to autoscroll console messages uses a "guess" based off the session's current time. This is fine for when the player is actually playing but it doesn't make sense to use this guessing when the player is paused as it can guess the wrong thing (see #4843).
* Pause the player
* Click a console message
* Observe that the selection is what the user chose.
N/A
=> only autoset selected console message if the player is actually playing

.github/workflows/deploy.yml
Pin the github action version to make sure we do not pick up breaking changes, such as the AWS policy requirements.
CI, running this in non-main deploy: https://github.com/highlight/highlight/actions/runs/4615047524/jobs/8158572791
No
=> pin lambda-action version

e2e/nestjs/src/main.ts, highlight.io/components/QuickstartContent/backend/js/nestjs.tsx, sdk/highlight-nest/CHANGELOG.md, sdk/highlight-nest/package.json, sdk/highlight-nest/src/index.ts, yarn.lock
The nestjs `HighlightErrorFilter` would alter exceptions raised by applications.
This meant that exceptions that should return a body with a 400 exception would
be replaced by a 500 response coming from highlight.
The `NestInterceptor` interface allows us to observe exceptions raised by api handlers
without altering the response. This is a better fit for the highlight nestjs sdk to record errors. 
example usage
New nestjs sdk version published.
=> replace nestjs error filter with an interceptor

backend/clickhouse/cursor_test.go, backend/clickhouse/log_row.go, backend/clickhouse/log_row_test.go, backend/clickhouse/logs_test.go, backend/clickhouse/seeds/main.go, backend/otel/otel.go
We have a lot of data normalization when using the log row constructor (`NewLogRow`) and it's options (e.g. `WithSeverityText`). But some code calls the struct (`LogRow`) directly (specifically the tests) and that makes our code more brittle. 
Hence, this PR is doing a couple things:
* ensuring that all log rows are created with `NewLogRow`
* adjusted the constructor to require a timestamp and a project id (these are the bare minimum requirements for a log, everything else is optional and should use the `With*` functions)
* Got rid of `LogRowPrimaryAttrs` in favor of more `With*` functions (e.g. `WithTraceID`)
* Since timestamp is required, I got rid of `WithTimestamp` (the logic of truncating to the second is still present)
* Since project id is required, I got rid of …
=> use log row constructor everywhere

frontend/src/pages/ErrorsV2/ErrorSourcePreview/ErrorSourcePreview.tsx, frontend/src/pages/Setup/CodeBlock/CodeBlock.tsx
_This is part of a [series](https://github.com/highlight/highlight/pull/4813) [of](https://github.com/highlight/highlight/pull/4848) PRs being spun off from [my WIP branch](https://github.com/lewisl9029/highlight/pull/2) to get the Highlight web app ready for [Reflame](https://reflame.app/). Hopefully this makes things a bit easier to review, test, and merge. 🙂_ 
I ran into this specific [esbuild issue](https://github.com/evanw/esbuild/issues/1836) when preping the dependencies bundle for the [Highlight app](https://highlight-test-lewisl.reflame.dev/~r/start-preview/?mode=production&userId=01FQZZ7XJFDA799Z1Z9DRCFXWA&variantId=01GSY56NZ2GP8KAA4Y26A1RT6E&variantName=git%7Enew-reflame-app-1&resourceIdHtml=YvIo8Nr9gSIBHlECxeibDghiBAU) in [Reflame](https://reflame.app/). And my workaround was …
=> Import from specific entry points in react-syntax-highlighter

.github/workflows/deploy.yml, backend/jobs/log-alerts/log-alerts.go, deploy/log-alerts-task.json
- task definitions / service were manually set up in ECS console, make it part of the deployment
- use `errgroup` to prevent log alert watcher from exiting
- tested `make start-log-alerts-watch` locally
- nope
=> add config files for log-alerts service deployment

frontend/.eslintrc, frontend/src/components/Breadcrumb/Breadcrumb.tsx, frontend/src/components/FieldsBox/FieldsBox.tsx, frontend/src/components/KeyboardShortcutsEducation/KeyboardShortcutsEducation.tsx, frontend/src/pages/Alerts/AlertConfigurationCard/AlertConfigurationCard.tsx, frontend/src/pages/Alerts/LogAlert/LogAlertPage.tsx, frontend/src/pages/ErrorsV2/ErrorsV2.tsx, frontend/src/pages/Player/PlayerHook/utils/index.tsx, frontend/src/pages/Setup/SetupPage.tsx, frontend/src/util/react-router/useParams.tsx
_This is part of a [series](https://github.com/highlight/highlight/pull/4813) of PRs being spun off from [my WIP branch](https://github.com/lewisl9029/highlight/pull/2) to get the Highlight web app ready for [Reflame](https://reflame.app/). Hopefully this makes things a bit easier to review, test, and merge. 🙂_ 
There were several places in the frontend codebase where we were importing from `react-router`, a transitive dependency, instead of `react-router-dom`, a direct dependency.
This is often referred to as a phantom dependency, and can cause a number of issues, both in theory and practice:
- We have a rule against importing `useParams` from `react-router-dom`, but that does nothing to protect against importing `useParams` from `react-router`. In fact, this was something I [had to …
=> Import from react-router-dom instead of react-router

frontend/package.json, frontend/src/pages/Auth/AuthRouter.tsx, frontend/src/pages/Auth/MultiFactor.tsx, frontend/src/pages/Auth/SignIn.tsx, frontend/src/pages/Auth/SignUp.tsx, frontend/src/pages/UserSettings/Auth/Auth.tsx, frontend/src/routers/ProjectRouter/ProjectRouter.tsx, frontend/src/util/auth.tsx, frontend/src/util/graph.tsx, yarn.lock
_This is part of a [series](https://github.com/highlight/highlight/pull/4813) [of](https://github.com/highlight/highlight/pull/4848) [PRs](https://github.com/highlight/highlight/pull/4849) [being](https://github.com/highlight/highlight/pull/4851) spun off from [my WIP branch](https://github.com/lewisl9029/highlight/pull/2) to get the Highlight web app ready for [Reflame](https://reflame.app/). Hopefully this makes things a bit easier to review, test, and merge. 🙂_ 
We were on v8 of the firebase SDK before, which had a whole bunch of issues when I tried to get it running on the [Highlight app](https://highlight-test-lewisl.reflame.dev/~r/start-preview/?mode=production&userId=01FQZZ7XJFDA799Z1Z9DRCFXWA&variantId=01GSY56NZ2GP8KAA4Y26A1RT6E&variantName=git%7Enew-reflame-app-1&resourceIdHtml=Yv …
=> Upgrade firebase to v9 with compat layer

backend/clickhouse/logs.go, backend/clickhouse/logs_test.go, docs-content/general/6_product-features/4_logging/log-search.md
This PR adds support for doing an implicit OR on attribute when the attribute is included more than once (e.g. `level:info level:warn`)
Docs have been added for this behavior:
Verified it works `level` (uses the `SeverityText` column)
Verified it works on `span_id` (uses the `SpanId` column)
Verified it works on an arbitrary key (which uses the `LogAttributes` map column)
This should also work for `secure_session_id`, `trace_id`, `source`, and `service_name` (confirmed via tests).
N/A
=> add support for implicit OR on duplicate attribute keys

backend/clickhouse/logs.go, backend/clickhouse/logs_test.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql
This PR creates a dedicated endpoint for session logs. Unlike the log viewer that has to handle pagination, session logs are more well scoped. Specifically they:
* have a `secure_session_id` to filter on
* are [confined to a 4 hour window ](https://github.com/highlight/highlight/blob/et/session-logs-endpoint/frontend/src/pages/LogsPage/SearchForm/utils.ts#L126-L127)
Because it's more well scoped, it can avoid limitations of dealing with pagination (very unpredictable with virtualized lists).
Additionally, session logs do not need `LogAttributes` which is a very heavy column. A previous [observation](https://gist.github.com/et/bd25c44fd04b64bd76a0e35853e8cb3b) has noticed that omitting this column speeds up queries.
Using a [30 minute …
=> Create dedicated endpoint for loading session logs

.vscode/settings.json
Adds `.next` files to our ignored vscode settings.
run a search in vscode.
n/a
=> Add `.next` to vscode ignore

highlight.io/components/Home/CustomerReviewTrack.tsx, highlight.io/pages/docs/[[...doc]].tsx, highlight.io/pages/for/[slug].tsx, highlight.io/pages/index.tsx
Fix intersection observer usage on mobile. Inspired by: https://stackoverflow.com/questions/62084306/intersectionobserver-not-working-in-safari-or-ios
Click test.
n/a
=> update intersection observer usage

highlight.io/components/Home/CustomerReviewTrack.tsx, highlight.io/pages/for/[slug].tsx, highlight.io/pages/index.tsx
Removes `root` from intersectionObserver calls because it is either:
- redundant
- problematic (causes issues)
clicktest
n/a
=> Remove root from `root` from intersection observer calls

sdk/firstload/rollup.config.js, sdk/firstload/src/index.tsx
_This is part of a [series](https://github.com/highlight/highlight/pull/4813) [of](https://github.com/highlight/highlight/pull/4848) [PRs](https://github.com/highlight/highlight/pull/4849) being spun off from [my WIP branch](https://github.com/lewisl9029/highlight/pull/2) to get the Highlight web app ready for [Reflame](https://reflame.app/). Hopefully this makes things a bit easier to review, test, and merge. 🙂_ 
The sdk/firstload package currently imports from `@highlight-run/client` using relative paths that point outside the package root. I read your [blog post on this](https://www.highlight.io/blog/publishing-private-pnpm-monorepo) and was able to get a good understanding of the motivations, but it was breaking the app in Reflame (where individual libraries are much more tightly …
=> Resolve @highlight-run/client without relative paths

.vscode/settings.json, highlight.io/components/Home/FeatureCarousel/CarouselCard.tsx, highlight.io/components/Home/FeatureCarousel/FeatureCarousel.tsx
Adds rendering of the `link` property for the self-host section of the carousel.
CI / Clicktest
n/a
=> Selfhost page is missing the `link` property

backend/event-parse/parse.go, backend/event-parse/parse_test.go, backend/event-parse/sample-events/dom-with-scripts.json, backend/public-graph/graph/resolver.go
Adds an additional guard rail to our events ingest to ensure javascript injection is not possible.
For more details, see [slack](https://highlightcorp.slack.com/archives/C0524MRA4NA/p1680904810669179).
Adds a new unit test for parsing events.
Validated that sessions are recorded correctly locally.
Validated that the existing issue is fixed (javascript is removed server-side).
Will monitor rollout to ensure sessions recorded correctly.
=> remove javascript from session events

frontend/src/components/CollapsibleSection/index.tsx, frontend/src/components/FullCommentList/FullCommentList.tsx, frontend/src/components/TextViewer/index.tsx, frontend/src/pages/ErrorsV2/SearchPanel/SearchPanel.tsx, frontend/src/pages/LogsPage/SearchForm/SearchForm.css.ts, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ConsolePage/ConsolePage.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/DevToolsWindowV2.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ErrorsPage/ErrorsPage.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/NetworkPage/NetworkPage.tsx, frontend/src/pages/Player/components/EventStreamV2/EventStreamV2.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionsFeedV3.tsx, frontend/tsconfig.json
_This is part of a [series](https://github.com/highlight/highlight/pull/4813) [of](https://github.com/highlight/highlight/pull/4848) [PRs](https://github.com/highlight/highlight/pull/4849) [being](https://github.com/highlight/highlight/pull/4851) [spun](https://github.com/highlight/highlight/pull/4852) off from [my WIP branch](https://github.com/lewisl9029/highlight/pull/2) to get the Highlight web app ready for [Reflame](https://reflame.app/). Hopefully this makes things a bit easier to review, test, and merge. 🙂_ 
Previously we had a bunch of places where we imported `/src/style/common.css` using the identifier `style/common.css`. `style/*` was not setup as an alias in tsconfig.json, but this seem to have worked anyways (I think it might be a quirk of the …
=> Add root alias, use for style/common.css import

backend/util/tracer.go, sdk/highlight-go/highlight_test.go, sdk/highlight-go/tracer.go
`graphql.GetOperationContext` panics when there is no operation context.
When a graphql input validation error happens (eg. when someone sends us a request with
an invalid schema), the graphql input parsing layer throws an error leading to the operation context
being omitted. The result is a panic when we try and get the operation context.
Wrapping the operation with a check for the context fixes the panic and correctly responds
to the user with the error and expected 422 http code.
Local postman sending invalid requests.
Before
After
Will publish new sdk version.
=> fix tracer panics on graphql parsing errors

backend/private-graph/graph/schema.resolvers.go, backend/vercel/vercel.go, backend/vercel/vercel_test.go, docs-content/getting-started/backend-logging/6_hosting/index.md, docs-content/getting-started/backend-logging/6_hosting/vercel.md, highlight.io/components/QuickstartContent/QuickstartContent.tsx, highlight.io/components/QuickstartContent/logging/hosting/vercel.tsx
Ensure the log drain is correctly created with sources to ensure vercel will use it.
Ensure that only one log drain is created for all desired projects.
Firing request from the test.
After accessing highlight.io
New unit test.
Adding  documentation.
=> fix vercel log drain integration

backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver.go, backend/public-graph/graph/resolver_test.go, docs-content/general/6_product-features/2_error-monitoring/ignoring-errors.md, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/mutation.gql, frontend/src/graph/operators/query.gql, frontend/src/pages/ProjectSettings/ErrorFiltersForm/ErrorFiltersForm.module.scss, frontend/src/pages/ProjectSettings/ErrorFiltersForm/ErrorFiltersForm.module.scss.d.ts, frontend/src/pages/ProjectSettings/ErrorFiltersForm/ErrorFiltersForm.tsx, frontend/src/pages/ProjectSettings/ErrorSettingsForm/ErrorSettingsForm.tsx, frontend/src/pages/ProjectSettings/FilterExtensionForm/FilterExtensionForm.tsx, frontend/src/pages/ProjectSettings/ProjectSettings.tsx
Based on https://github.com/highlight/highlight/pull/4631
Addresses issue #4457 
Added `error_filters` to `projects` table and cloned front-end for `error_json_paths`.
Confirmed successful save.
https://user-images.githubusercontent.com/878947/225923680-8fa075d7-b41f-4bcf-a3eb-943d7f3f4870.mp4
The back-end error filtering is harder to test. I added a `panic("test message")` into the front-end error handling code and got it to register against an `error_filter` in the back-end handling code.
No need to backfill data. Migration should be automatic.
=> Ignore error groups by regex

frontend/src/pages/Sessions/EmptySessionsSearchParams.tsx
In [EmptySessionsSearchParams.tsx](https://github.com/highlight/highlight/blob/eadc0963613dd70110121d728331ae86a93cd6c3/frontend/src/pages/Sessions/EmptySessionsSearchParams.tsx#L23), we have this set as the default query: ``{\"isAnd\":true,\"rules\":[[\"custom_processed\",\"is\",\"true\"]]}``
The backslashes end up causing this exception in my Reflame deploy because they end up as literal slashes due to the template string already escaping double quotes:
Removing the backslashes seems to fix this.
Tested in a Reflame deploy.
None I can think of.
=> Fix empty state query slashes causing parse error

backend/kafka-queue/types.go, backend/public-graph/graph/generated/generated.go, backend/public-graph/graph/resolver.go, backend/public-graph/graph/schema.graphqls, backend/public-graph/graph/schema.resolvers.go, frontend/src/index.tsx, sdk/client/src/graph/generated/operations.ts, sdk/client/src/graph/generated/schemas.ts, sdk/client/src/graph/operators/mutation.gql, sdk/client/src/index.tsx, sdk/client/src/listeners/first-load-listeners.tsx, sdk/client/src/types/types.ts, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/index.tsx, yarn.lock
Recently, we released a new flag to the frontend `H.init` to disable `console.error(...)` calls from being reported as Highlight Errors. This was done because frontend errors are still reported as error logs and are often noisy (not a real application-breaking error like a `window.onerror`, etc).
This PR switches `reportConsoleErrors` off by default to make this the default behavior for new SDK versions >= 5.5.0.
Adds a `disableSessionRecording` setting that allows using the javascript client without recording session data.
Disabling the flag locally and ensuring that frontend `console.error` calls are not reported as Highlight errors.
Error reporting by the sessionless client.
New `highlight.run` version 5.5.0
=> disable reportConsoleErrors by default

.vscode/settings.json, frontend/src/pages/LogsPage/SearchForm/utils.ts, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ConsolePage/ConsolePage.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ConsolePage/style.css.ts, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/DevToolsWindowV2.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/NetworkPage/NetworkPage.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/utils.ts, frontend/src/util/preload.ts, packages/ui/src/components/MenuButton/MenuButton.tsx, packages/ui/src/css/theme.css.ts
This PR's main purpose is to change the session logs source from S3 to Clickhouse (dedicated backend endpoint added in #4883). Additionally, we now have the ability to see Backend logs in the session logs viewer.
We are also making several UX change. See [figma](https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=4451-205639&t=dnCWY9epGQJQ8INj-11) but also below for a detailed before/after.
Fixes #4779
**Note: we don't have a component for multi-select (#4816) so the filters use the existing menu button component which only permits single select**
Adjust the level filter to remove all colors and use the normalized log levels from clickhouse:
https://github.com/highlight/highlight/blob/83da5535aa0bca9239bd316a91c2f402e4f3f824/backend/private-graph/graph/schema.graphqls# …
=> Fetch session logs via clickhouse

backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go
- this method is only called from other resolvers that are already doing their own auth checks
- this broke making a session public
- made a session public locally, validated I was able to view it incognito
- no
=> public sessions fixup - remove auth check for retention period

backend/alerts/alerts.go, backend/alerts/integrations/discord/messages.go, backend/alerts/integrations/integrations.go, backend/alerts/routing.go, backend/jobs/log-alerts/log-alerts.go, backend/model/model.go, frontend/src/components/Select/Select.tsx, frontend/src/index.tsx, frontend/src/pages/Alerts/LogAlert/LogAlertPage.tsx, frontend/src/pages/LogsPage/LogsHistogram/LogsHistogram.tsx, frontend/src/pages/LogsPage/SearchForm/SearchForm.tsx
- url in the email/slack/discord alerts links to the logs page
- add `create alert` button to logs page
- log alert page uses the same query params as the logs page
- fix bug where selecting slack / discord channels was broken
- use spinner loading state for logs histogram
- click test locally
- no
=> #4880 log alerts polish

sdk/firstload/src/environments/electron.ts
Ensure that electron app closing forwards an event to the renderer thread so that
the highlight client can issue a `navigator.sendBeacon` payload.
Local deploy of an electron sample app.
The local backend received a beacon event with remaining rrweb events as soon as the electron window was closed.
Will follow up on improving docs in #4947 
Will add an e2e test for electron and event listeners in #4588
Will publish a new version of the highlight.run client in another PR.
=> forward electron close events to highlight client

highlight.io/components/QuickstartContent/frontend/sveltekit.tsx
Adds tracingOrigins to Sveltekit docs. Called out by our dear friend James Q Quick.
clicktest
n/a
=> Adds `tracingOrigins` to Sveltekit docs

frontend/src/components/Select/Select.tsx, frontend/src/pages/Alerts/LogAlert/LogAlertPage.tsx
- add label to our `Select` component so we can filter on it with `optionFilterProp`
- Slack / Discord channel filtering wasn't working otherwise
- no
=> select filter on label prop

backend/lambda-functions/deleteSessions/handlers/handlers.go
- need to use `db.Exec` instead of `db.Raw` to delete from postgres
- will validate post-release
- no
=> use db.Exec in lambda delete job

sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/rollup.config.js, sdk/firstload/src/index.tsx
Reverts highlight/highlight#4851
The changes to firstload -> client imports break types checking in packages using highlight.run after #4851
```
[1] 11:03:22 AM - Found 1 error. Watching for file changes.
[2] node_modules/highlight.run/dist/firstload/src/index.d.ts(1,65): error TS2307: Cannot find module '@highlight-run/client/src/types/types' or its corresponding type declarations.
[2] wait-on http://127.0.0.1:3000 && tsc -p electron && electron . exited with code 1
```
Looks like that's because our npm.js package packages the typescript definitions with their imports from the client package, which is not a public package.
```
~/w/react-typescript-electron-sample-with-create-react-app-and-electron-builder   master ±  cat node_modules/highlight.run/dist/firstload/src/index.d.ts
import …
```
=> Revert "Resolve @highlight-run/client without relative paths"

turbo.json
Because rrweb `typegen` commands also output js, we need to make sure they are cached from the step.
Otherwise, a build where the `typegen` output is retrieved from cache fails as follows:
Local build with cache.
No
=> fix build failures due to incorrect turbo cache setting

sdk/highlight-next/package.json, sdk/highlight-node/package.json, yarn.lock
Loosen dependencies for @highlight-run/node and @highlight-run/next.
* Set a peer dependency on next 12 as our sdk is compatible with it.
* Loosen node graphql dependency to allow lower version that our SDK is compatible with.
Local nextjs 12 app
New versions of node and next sdks published.
=> soften nextjs sdk dependencies

docs-content/getting-started/1_overview.md, docs-content/getting-started/4_backend-sdk/js/nextjs.md, docs-content/getting-started/fullstack-frameworks/next-js/1_overview.md, docs-content/getting-started/fullstack-frameworks/next-js/env-variables.md, docs-content/sdk/client.md, docs-content/sdk/go.md, docs-content/sdk/nextjs.md, docs-content/sdk/nodejs.md, docs-content/sdk/python.md, highlight.io/components/QuickstartContent/frontend/next.tsx, highlight.io/components/QuickstartContent/frontend/shared-snippets.tsx
- Adds `useEffect` to the identify example + clarification on why that's preferred (resolves #4927)
- Adds proper links to getting started guides in the sdk docs (resolves #4928)
- Updates the ErrorBoundary NextJS instructions to reflect `create-next-app`'s `_app` structure (resolves #4926)
- Use the `siteUrl` macro in the `next.tsx` file (resolves #4925) - cc @ccschmitz to take a look at.
- Consolidate Next.js Docs (resolves #4961)
- Gets rid of `docs-content/getting-started/4_backend-sdk/js/nextjs.md`
- Adds `next13Snippet` and `nextBackendSnippet` to `next.tsx`
Clicktest. For those that review, would be nice if you spun it up locally (or looked at the preview) to confirm everything looks good.
no
=> Nextjs Docs Change

sdk/firstload/package.json, sdk/firstload/rollup.config.js, sdk/firstload/scripts/replace-client-imports.mjs, sdk/firstload/src/index.tsx, sdk/firstload/src/integrations/amplitude.ts, sdk/firstload/src/integrations/mixpanel.ts, sdk/firstload/src/integrations/segment.ts, sdk/firstload/src/listeners/fetch/index.ts, yarn.lock
This is another attempt at https://github.com/highlight/highlight/pull/4851, which had to be [reverted](https://github.com/highlight/highlight/pull/4950) because it broke type declarations. 😞 
TypeScript isn't planning to officially support import path rewriting in declarations (see https://github.com/microsoft/TypeScript/issues/31643#issuecomment-496995677), so to fully support arbitrary path remappings (like the ones to `@highlight-run/client`), the most promising solution I could find involved a combination of [ttypescript](https://github.com/cevek/ttypescript), [ts-transform-paths](https://github.com/zerkalica/zerollup/tree/master/packages/ts-transform-paths), and [rollup-plugin-typescript2](https://github.com/ezolenko/rollup-plugin-typescript2).
However in our case, we're only …
=> Resolving highlight client from firstload - attempt 2

docs-content/general/7_integrations/vercel-integration.md, highlight.io/components/QuickstartContent/logging/hosting/vercel.tsx
Adds vercel log drain docs to the integrations page. 
clicktest
n/a
=> Add vercel log drain docs

frontend/src/pages/Player/Toolbar/DevToolsWindowV2/DevToolsWindowV2.tsx
By default, when we load the session console logs, we autoselect Frontend only (see #4833). However, when we are linked from the log viewer, we should select "All" such that if a `source:backend` log was linked, it can be autoselected.
Fixes #4833
Click tested to confirm that a `source:backend` log with a linked session correctly is autoselected when clicking "Related Session" on the log line.
N/A
=> ensure backend logs are autoselected when linked from logs -> session

.github/workflows/turbo.yml, sdk/client/package.json, sdk/client/src/listeners/web-vitals-listener/web-vitals-listener.tsx, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, yarn.lock
Switch to using an npm package for web vitals measurement. This bundles the web vitals logic into client
which is loaded asynchronously, and prevents Highlight from needing to fetch another file that would otherwise
often be blocked by ad-blockers.
new session
no web vitals download but client has the npmjs library
Will publish new highlight.run package.
=> bundle web vitals listener into client

docs-content/getting-started/backend-logging/3_python/1_overview.md, frontend/src/pages/Setup/SetupDocs.tsx, highlight.io/components/QuickstartContent/backend/js/apollo.tsx, highlight.io/components/QuickstartContent/backend/js/cloudflare.tsx, highlight.io/components/QuickstartContent/backend/js/express.tsx, highlight.io/components/QuickstartContent/backend/js/firebase.tsx, highlight.io/components/QuickstartContent/backend/js/nestjs.tsx, highlight.io/components/QuickstartContent/backend/js/shared-snippets.tsx, highlight.io/components/QuickstartContent/backend/js/trpc.tsx, highlight.io/components/QuickstartContent/backend/python/aws.tsx, highlight.io/components/QuickstartContent/backend/python/azure.tsx, highlight.io/components/QuickstartContent/backend/python/django.tsx, highlight.io/components/QuickstartContent/backend/python/fastapi.tsx, highlight.io/components/QuickstartContent/backend/python/flask.tsx, highlight.io/components/QuickstartContent/backend/python/gcp.tsx, highlight.io/components/QuickstartContent/backend/python/other.tsx, highlight.io/components/QuickstartContent/logging/go/fiber.tsx, highlight.io/components/QuickstartContent/logging/go/other.tsx, highlight.io/components/QuickstartContent/logging/js/nestjs.tsx, highlight.io/components/QuickstartContent/logging/python/other.tsx, highlight.io/components/QuickstartContent/logging/shared-snippets.tsx
- link to the python logging getting started docs was broken from the overview page
- backend `highlight_io.H` initialization had hardcoded `"1"` as the project id
- use bracketed `<YOUR_PROJECT_ID>` everywhere
- `replaceAll` for code snippets w/ project id listed more than once
- no
=> DX test - getting started docs fixes

docs-content/general/4_company/product-philosphy.md, highlight.io/pages/docs/[[...doc]].tsx
Adds a section to our `company` docs about our product philsophy. 
I read it.
no.
=> Adds 'product philsophy' docs

docs-content/sdk/java.md
I've made some changes to the Java docs that should make it easier to locate the required dependencies.
Locally
No
=> Added mavenrepository links for java docs

frontend/src/components/ErrorState/ErrorState.module.scss, frontend/src/components/ErrorState/ErrorState.module.scss.d.ts, frontend/src/components/ErrorState/ErrorState.tsx
Converts the ErrorState component from a clickable span to `<details><summary/></details>` [elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details), which handles showing and hiding detailed information natively.
Tested with auth error. Validated in Chrome, Firefox, Safari.
nope.
=> Convert errorBody display to details and summary

backend/kafka-queue/kafkaqueue.go, backend/main.go
Per [this guide](https://betterprogramming.pub/kafka-acks-explained-c0515b3b707e), switch to single-broker ack for writes
to make sure we are not blocked from writing messages when a broker is out-of-sync.
Since we have `min.insync.replicas=3` on our prod partition, this means that the previous `all` setting
would block until all 3 brokers have received messages. 
Adding a health check log to make sure it is obvious when health checks fail.
Local deploy.
Will monitor rollout.
=> switch to single-broker ack

frontend/src/pages/ErrorsV2/ErrorQueryBuilder/components/QueryBuilder/QueryBuilder.tsx
When reloading the sessions page and the URL is populated with a session query, 
the query params carry over to the error feed, breaking the query for errors.
This was caused by the differing error feed logic of triggering the `setSearchParams` update
on `segmentsLoading` change.
By making this consistent with the error feed, we get the right behavior on the errors feed.
Before: https://www.loom.com/share/af6cc98433214fdc9b73988da19f19c7
After: https://www.loom.com/share/5e9973ba3841426a97fe4a426216c686
No
=> stop session feed query carryover on error feed

frontend/src/util/db.ts
Our indexeddb caching strategy always updates the cache, but certain code that uses `window.open` or
`navigate` will switch the page before the cache gets to update. As a result, the cache is never updated
and can result in invalid behavior (ie. invalid stripe urls opened).
Adds a consistent way to exclude graphql queries from the apollo indexeddb cache.
Issue was originally reported by a customer.
Before:
After:
No.
=> avoid caching billing data in indexeddb

frontend/src/pages/LogsPage/LogsHistogram/LogsHistogram.tsx
- if the max bucket had less than 5 items, the histogram appeared as if it had 5
- this will show N+1 ticks (including a 0 tick) if N < 5
- no
=> fix log alert y axis ticks when max bucket size < 5

backend/phonehome/phonehome.go, docs-content/general/4_company/open-source/hosting/telemetry.md
Update the telemetry metrics to include `doppler-config` so that we can differentiate
our cloud hosted deployments from on-prem ones.
Will release new docker images.
=> update phonehome telemetry metrics

highlight.io/components/common/Navbar/ResourceDropdown.tsx
Added a link to our roadmap in the resource dropdown located in the navbar. Also replaced the blog link, which is redundant, with a link to our competitor pages docs page.
=> Update resource dropdown

highlight.io/pages/for/[slug].tsx
The first "Docs" CTA on the framework page linked to the generic docs site, instead of the purpose-built guide for the selected framework. This change simply uses the link provided for all the other docs CTAs.
Click the first CTA, see it take you to the `product.docsLink`
nope
=> Consistent docs link

frontend/src/pages/LogsPage/LogsTable/LogsTable.tsx
Fixes issues with overmatching and highlighting attributes that aren't actually relevant to the logic for the logs being shown.
N/A
=> Fix overmatching for attribute and body filters

frontend/src/pages/ErrorsV2/ErrorBody/components/ErrorOccurenceDate/index.tsx, packages/ui/src/components/Text/Text.tsx
This text could overflow in ugly ways. It's not common, but it shouldn't be breaking out of its containing box.
=> Wrapping text in the Errors header

highlight.io/components/Docs/Docs.module.scss, highlight.io/pages/docs/[[...doc]].tsx
Adjust the table styles based on the design document.
=> Tweak doc tables style

packages/ui/src/components/Form/styles.css.ts
According to [Vanilla Extract docs](https://vanilla-extract.style/documentation/styling/#complex-selectors), complex rules need to be nested under the `selectors` key. Looks like we had a spot that wasn't doing this, which was detected as a syntax error in the generated CSS on Reflame's side, and a warning in Vite's build output:
This was ending up in the final CSS output apparently (screenshot from prod):
Not valid syntax outside of browsers with draft CSS nesting support, though support is actually getting [surprisingly good](https://caniuse.com/css-nesting) for a draft, which might be why we haven't seen this in prod yet.
Here's the output in the generated CSS after the change:
=> Fix unnested complex selector resulting in invalid css output

frontend/src/public.css
A quick fix to #5088, where I missed one of font urls in public.css.
=> Fix missed relative font url in public.css

highlight.io/components/Blog/Blog.module.scss, highlight.io/components/Blog/Blog.module.scss.d.ts, highlight.io/pages/blog/[slug].tsx, highlight.io/pages/docs/[[...doc]].tsx
Adds a border to all images in docs and blog pages. Closes #5108
=> Add border to docs and blog images

backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go
We've [had reports](https://highlightcorp.slack.com/archives/C04NQ25RV8B/p1681759896782209) that there are error groups with many error instances that do not load.
This would happen because an error group would have so many error fields that doing a 
subquery preload would result in a very large query [failing to run.](https://app.highlight.io/1/errors/RXZgbXsi1IwTqjrKsoMIVJC7mtGh/instances)
Running the production SQL query that would be generated from https://app.highlight.io/1703/errors/dUWwT2haf38sBAGXywNV1WzzvmGn?page=1
without the `error_fields` subquery would work correctly.
Everything else in error groups loads correctly.
https://www.loom.com/share/fb5b1e6ec8514871aed1329d0e51e3e2
No.
=> avoid preloading unnecessary error group fields

.gitattributes, backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/schema.resolvers.go
GitHub hides our `schema.resolvers.go` file because gqlgen injects this comment:
https://github.com/highlight/highlight/blob/09b461b6c56809d4233ea651b9d5c8f29fb99aea/backend/public-graph/graph/schema.resolvers.go#L1-L6
But we have lots of non-generated code in these files. See this recent [PR](https://github.com/highlight/highlight/pull/5116/files) change and that `backend/private-graph/graph/schema.resolvers.go` is hidden yet there are actual non generated code changes in there.  
See the files changes for this PR output and observe that `schema.resolvers.go` changes are not hidden by default.
N/A
=> mark schema.resolvers.go as not generated

frontend/src/pages/ErrorsV2/ErrorInstance/ErrorInstance.tsx
Don't expand custom properties on single error view. Prevents this issue (very long custom properties):
Visual test.
n/a
=> Don't expand custom properties on single error view

frontend/src/components/CommandBar/CommandBar.tsx, frontend/src/components/CommandBar/context.tsx, frontend/src/components/CommandBar/utils.ts
Command bar inputs should trim leading/trailing whitespace 
in case someone copy-pastes an email or other search query with whitespace.
https://www.loom.com/share/acffcc8bfa784402b5b0edc0b1bf1b5d
No
=> trim command bar whitespace

frontend/src/index.tsx, frontend/src/pages/OAuthApproval/OAuthApprovalPage.tsx, sourcemap-uploader/package.json, sourcemap-uploader/src/lib.ts
Updates the frontend to use pri.highlight.io since the frontend is hosted on app.highlight.io.
While everything has been working so far on app.highlight.io using pri.highlight.run, today we
discovered that the `/assets` feature is broken as loading the authenticated resources
requires the project token cookie, set by a backend request on `.highlight.io`. This cookie
is not sent to requests to pri.highlight.run since the domain does not match.
I've already made the necessary AWS LB and DNS changes to set up pri.highlight.io.
This change cleans up other code references to pri.highlight.run to point to the new domain.
Local depoy of the frontend with the `REACT_APP_PRIVATE_GRAPH_URI` set to pri.highlight.io runs into CORS issues but has valid SSL
Will update REACT_APP_PRIVATE_GRAPH_URI in …
=> update pri.highlight.run -> pri.highlight.io

.github/workflows/turbo.yml, docs-content/getting-started/3_client-sdk/7_replay-configuration/react-error-boundary.md, e2e/nextjs/src/components/ErrorBoundaryButton.tsx, frontend/src/index.tsx, highlight.io/components/Home/SnippetTab/SnippetTab.tsx, highlight.io/components/QuickstartContent/frontend/next.tsx, highlight.io/components/QuickstartContent/frontend/react.tsx, packages/component-preview/src/ErrorBoundary.stories.tsx, sdk/highlight-react/package.json, sdk/highlight-react/src/components/ErrorBoundary.tsx
* Disables error reporting to highlight by the error boundary when highlight is present because highlight will be catching the same error via the `window.onerror` listener, resulting in duplicate errors. ie. 
* Changes the ErrorHandler props to default to `showDialog` and add an optional `noShowDialog` as we've heard from customers that the props are un-intuitive (the dialog is the whole point of the error boundary to begin with).
buttons page
only one error recorded
The `showDialog` is kept to keep this change non-breaking. Since we just released the major version 3.x today, thinking we can still sneak this in as 3.0.1 though the behavior of the dialog has changed.
=> avoid duplicate errors from error boundary and show dialog by default

backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver.go, backend/worker/worker.go, frontend/src/graph/generated/schemas.tsx
_This is some initial set up work to make #4980 easier._
This PR moves the excluded users logic from the worker process session up to ProcessPayload. 
The previous logic worked like this:
* `InitializeSession` (excluded = true)
* `ProcessPayload` (excluded = false)
* Session is visible in the feed
* Session finishes
* Process session kicks off
* `isSessionUserExcluded = true` and the session is marked as `excluded = false` and removed from the feed
Now the logic works like this:
The previous logic worked like this:
* `InitializeSession` (excluded = true)
* `ProcessPayload` (excluded = false **unless `isSessionUserExcluded = true`**)
* Session is **not** visible in the feed
* Session finishes
* Process session kicks off
* Confirmed that using the [excluded users …
=> Move excluded users up to ProcessPayload to avoid disappearing sessions

backend/lambda-functions/deleteSessions/deleteSessionBatchFromOpenSearch/main.go, backend/lambda-functions/deleteSessions/deleteSessionBatchFromPostgres/main.go, backend/lambda-functions/deleteSessions/deleteSessionBatchFromS3/main.go, backend/lambda-functions/deleteSessions/getSessionIdsByQuery/main.go, backend/lambda-functions/deleteSessions/handlers/handlers.go, backend/lambda-functions/deleteSessions/main.go, backend/lambda-functions/deleteSessions/sendEmail/main.go
- the delete from `session_fields` query is timing out even when there are no records left to delete
- this new form of the query selecting from the `delete_sessions_tasks` table completes in `.093s` right now (for 0 rows to delete)
- ran query against prod
- no
=> join on delete_sessions_tasks table in delete sessions / fields queries

backend/event-parse/parse.go
Increase the stored asset size to 10GB for the persistent-assets feature.
This feature is gated for a few projects so this would have no broad impact.
We can reduce this once we have a sense of the distribution of file sizes of assets saved.
CI - feature is gated.
No
=> increase asset storage limit

sdk/highlight-go/log/logrus.go, sdk/highlight-go/tracer.go
Fixes duplicate errors recorded by the go graphql SDK.
* Errors were recorded any time a `logrus.WithError(err)...` print statement was made. This is incorrect behavior - we should report the error as an attribute of the log, but never create error objects from the log statement.
* The graphql tracer would record two errors for the same request - once from `InterceptField` (the right place that has access to the stacktrace of the error) and once from `InterceptResponse` (an aggregate of the errors that do not have the source stacktraces).
* Checking the types of stacktraces present in go errors reported to highlight.
*Only two errors now reported in a clean local deploy
Will tag a new version of the Go SDK.
=> fix go graphql sdk recording duplicate errrors

frontend/src/pages/Player/Toolbar/TimelineIndicators/TimelineIndicatorsBarGraph/TimelineIndicatorsBarGraph.tsx
Fixes the issue with the timeline being collapsed on the initial render as shown in this Loom.
https://www.loom.com/share/3feb73fa6a9e4f47ac1e315ef9d655ed
Local click test. Can also test in the PR preview.
N/A
=> Fix timeline being collapsed on initial render

.github/workflows/e2e.yml, .github/workflows/python.yml, .github/workflows/turbo.yml, frontend/src/index.tsx, sdk/highlight-react/package.json, sdk/highlight-react/src/components/ErrorBoundary.tsx
Revert the error boundary change to keep reporting caught errors.
Duplicate errors were previously encountered because the legacy SDK was used that reported `console.error` exceptions.
Cleans up the reported exception name to remove extraneous text in the title.
Defaults to refreshing the page when `cancel` or `submit` is pressed as per customer suggestion.
Turns out when I thought that React was causing the `window.onerror` events, it was actually a chrome extension.
As seen from that `PushPayload` contents, now there is only one real error sent in a production environment.
New react sdk version.
Instructions to customers with duplicate issues: upgrade to `highlight.run@>=6.0.0` and `@highlight-run/react@>=3.1.1`
=> revert error boundary error reporting change

backend/hubspot/hubspot.go, backend/kafka-queue/kafkaqueue.go, backend/kafka-queue/types.go, backend/main.go, backend/migrations/cmd/backfill-hubspot/main.go, backend/private-graph/graph/resolver.go, backend/private-graph/graph/resolver_test.go, backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver.go, backend/redis/utils.go, backend/util/random.go, backend/worker/worker.go
Adds hubspot backend contact and company creation.
Uses kafka to queue contact and company creation messages to ensure they are not lost
if the private graph restarts while polling hubspot.
Polls hubspot every 5 seconds for up to a minute to wait for the contact or company to be created,
then creates the object as a fallback.
Local deploy with hubspot api key, with a debugger in the codepath.
Will monitor hubspot account creation.
=> readd delayed hubspot contact and company creation

frontend/src/pages/ErrorsV2/ErrorInstance/ErrorInstance.tsx, packages/ui/src/components/Button/Button.tsx, packages/ui/src/components/Button/styles.css.ts
Fixes an issue with the older/newer error instance buttons not having their text vertically centered. Since no buttons were using the `display` prop anymore I decided to clean that up as well.
| --- | --- |
| Before | After |
| --- | --- |
| <img width="258" alt="Screenshot 2023-05-02 at 12 29 12 PM" src="https://user-images.githubusercontent.com/308182/235740366-40001ca3-3a33-4e96-907f-5d428c156cbf.png"> | <img width="394" alt="Screenshot 2023-05-02 at 12 27 48 PM" src="https://user-images.githubusercontent.com/308182/235740415-6ac87eff-6526-4f2a-99ec-4dda3aa24bdd.png"> |
| --- | --- |
N/A
=> Fix alignment on older/newer error instance links

backend/model/model.go
Removes unused session table indexes.
Figuring out what indexes are unused via
```sql
select *
from pg_stat_all_indexes
where schemaname <> 'pg_catalog'
and relname = 'sessions'
order by idx_scan desc;
```
Should fix https://github.com/highlight/highlight/actions/runs/4885635564/jobs/8720972044 (caused by automigration trying to add manually-deleted indexes).
=> remove unnecessary session table indexes

backend/event-parse/parse.go, backend/event-parse/parse_test.go, backend/event-parse/sample-events/input.json, backend/event-parse/sample-events/output.json, backend/go.mod, backend/go.sum, backend/public-graph/graph/resolver.go, backend/worker/worker.go
Deduplicate asset retrieval when certain query string parameters differ that do not affect the contents of the asset.
Parallelize fetching of assets to help with improving `PushPayload` performance.
New functional test.
Assets correctly hashed and saved (1.mp4 and 2.mp4 were ones i renamed)
No
=> speed up asset fetching

.github/workflows/e2e.yml, .github/workflows/go-sdk.yml, backend/.golangci.yml, backend/alerts/integrations/discord/discord.go, backend/go.mod, backend/kafka-queue/kafkaqueue_test.go, backend/main.go, backend/private-graph/graph/schema.resolvers.go, backend/worker/worker.go, e2e/go/go.mod, go.work, highlight.io/components/QuickstartContent/self-host/shared-snippets.tsx, sdk/highlight-go/.golangci.yaml, sdk/highlight-go/go.mod
If you're seeing this PR linked from somewhere else, you'll need to upgrade Go to [v1.20](https://go.dev/blog/go1.20).
`brew install go@1.20`
https://go.dev/dl
This PR upgrades us to Go 1.20 ([release notes](https://go.dev/blog/go1.20)). The reasoning behind the upgrade is obviously to be on the latest and greatest but also to help prove we don't need the [deprecated github.com/pkg/errors](https://github.com/pkg/errors/issues/245) library. Specifically, Go 1.20 has a built-in [`errors.Join`](https://pkg.go.dev/errors#example-Join) function that does what the [`errors.Wrap`](https://github.com/pkg/errors#adding-context-to-an-error) function was doing.
As we have discussed over slack, Go error wrapping is unnecessary assuming there's an associated stack trace. Long term, I still plan on …
=> upgrade to go 1.20

backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/ErrorsV2/ErrorInstance/ErrorInstance.tsx, frontend/src/pages/ErrorsV2/ErrorInstance/ShowSessionButton.tsx, frontend/src/pages/ErrorsV2/ErrorStackTrace/ErrorStackTrace.tsx, packages/ui/src/components/Tooltip/Tooltip.tsx
#3576 attempted to fetch the first error instance with a non-live session (`processed=true`). The reasoning behind this was the devtools in for livemode aren't great (#4965). Additionally, #4269 tried to avoid error instances tied to excluded sessions.
The problem with these approaches is that the error group's last instance timestamp doesn't match one these selected. Here's a visual:
This PR removes the backend logic and relies more on frontend UX to inform the user if there is an issue. 
If the session is excluded, we disable the "Show session" button and use a callout:
If the session is live, we provide a tooltip to warn them about dev tools:
Will confirm with the customer that reported this that this fixes their issue.
=> remove logic to fetch error instance that is not live

frontend/src/pages/Player/Toolbar/DevToolsWindowV2/DevToolsWindowV2.tsx, packages/ui/src/components/Tabs/Tabs.tsx
Adds a "handle" to the draggable area of the dev tools. This has been a source of confusion for many as they didn't realize you could resize the dev tools.
https://www.loom.com/share/843eb726fff140b59b0d44783bdeb074
N/A
=> Add a draggable handle to resize devtools

backend/otel/otel.go, backend/otel/otel_test.go
Noticed that setup events `where type = 'error'` haven't been created since April 5th, which led me to believe that https://github.com/highlight/highlight/pull/4839 might have changed some logic preventing these from being created. Turns out `err.Type` would never be equal to `modelInputs.LogSourceBackend.String()` (`"backend"`).
Thanks to @et for jumping on a call to help troubleshoot this one.
Will check prod DB to ensure setup events are being created as expected after this goes out.
=> Fix logic for creating error setup events

backend/lambda-functions/deleteSessions/deleteSessionBatchFromOpenSearch/main.go, backend/lambda-functions/deleteSessions/deleteSessionBatchFromPostgres/main.go, backend/lambda-functions/deleteSessions/deleteSessionBatchFromS3/main.go, backend/lambda-functions/deleteSessions/getSessionIdsByQuery/main.go, backend/lambda-functions/deleteSessions/main.go, backend/lambda-functions/deleteSessions/sendEmail/main.go, backend/main.go, backend/private-graph/graph/resolver.go, docs-content/sdk/go.md, e2e/go/fiber.go, highlight.io/components/QuickstartContent/backend/go/go-gqlgen.tsx, highlight.io/components/QuickstartContent/backend/go/shared-snippets.tsx
This PR removes all aliasing of the `highlight` Go SDK package in our docs and our code. The motivation for this is described in #5269
* Build passes
* Visual test on docs
N/A
=> unalias highlight package in Go code and docs

backend/public-graph/graph/resolver.go
We want to optimize the error grouping SQL. Before we do this, we want to capture more information as to how long it takes (e.g. give us the p99 in addition to the [AWS average](https://us-east-2.console.aws.amazon.com/rds/home?region=us-east-2#performance-insights-v20206:/resourceId/db-5ESFOLISXAYURFEQRLL3CX3SSY/resourceName/database-2-aurora/startTime/1683656528137/endTime/1683660128137/presetKey/1h/presetAmount/1/presetUnit/hour)):
This uses Datadog under the hood to measure. I wanted to use our own metrics but discovered a bug with how we record backend only metrics (see #5258).
N/A
=> add a datadog metric to record error grouping sql

backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/public-graph/graph/resolver.go, backend/worker/worker.go, frontend/src/graph/generated/schemas.tsx
This PR tracks why a session was excluded (see #5231 for reasons why a session could be excluded). We log this information but we don't persist it to the db. Hence, it's not possible for us to tell the end user why I session was excluded. With this change, we'll have the information available and can present it as such. 
Note: this is just the backend changes to record the excluded reason. A follow up PR will tidy up the [frontend code](https://github.com/highlight/highlight/pull/5223/files#diff-c740ecb3d6dc5071064893b4a639d723ff746a049d50e3dde47fe24b59ccd49aR531-R545). 
Tested [various exclusion reasons](https://github.com/highlight/highlight/issues/5231). Ensured that `excluded_reason` is set when `excluded=true`
N/A
=> track why a session was excluded

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/public-graph/graph/resolver.go
As reported in [Intercom](https://app.intercom.com/a/inbox/gm6369ty/inbox/admin/5462337/conversation/41260?view=List), our all sessions were excluded after #5252.
This corrects the exclusion logic and adds a better reason for the default exclusion from `InitializeSession`
Local deploy recording sessions
Monitoring session processing rates. To reprocess existing sessions, will manually reset `processed` flag.
=> fix exclusion logic

backend/event-parse/parse.go, e2e/nextjs/next.config.js, e2e/nextjs/src/components/ErrorBoundaryButton.tsx
closes #5182 
Relative stylesheet paths were persisting in the session viewer, leading to a lot of 404'ed requests to `app.highlight.io/some-font.ttf`
I reproduced the issue locally.
Nope.
=> Replacing relative paths in stylesheets

docs-content/general/6_product-features/1_session-replay/canvas-iframe.md, docs-content/getting-started/3_client-sdk/7_replay-configuration/canvas.md
This adds a short loom video to our canvas recording docs. 
Click test + watched the video.
n/a
=> Add a video to canvas recording docs.

.gitattributes, backend/event-parse/parse.go, backend/event-parse/parse_test.go, backend/migrations/cmd/unexclude-sessions-opensearch/main.go, backend/public-graph/graph/resolver.go, backend/redis/utils.go, frontend/src/pages/Buttons/CanvasV2.tsx
Fix logic that would incorrectly fail to inline media assets. 
For urls that were truncated ie. `https://foo.com/example?key=value&signature=bar -> https://foo.com/example?key=value`
the replacement would search for the truncated string, which would not exist.
The http request would also be made to the second string, which would return a 403.
Recording a session locally from the customer whose assets were not inlined
No
=> fix incorrect asset requests

docs-content/getting-started/fullstack-frameworks/next-js/1_overview.md, docs-content/sdk/nextjs.md
Addresses #4057
We've added some comments to the `withHighlightConfig` docs. 
In short, `withHighlightConfig` returns a promise, which is supported for Next v12.1.0 and greater. This breaks old Next apps as well as Next config generator functions that haven't learned to accept a promise as their argument. `next-pwa` is the offender in this case.
Spun up the docs.
Nope
=> withHighlightConfig doc improvement

highlight.io/pages/docs/[[...doc]].tsx
The doc parser was only rendering complex unordered list items. Simple, text-only `<li>` elements under a `<ul>` were being skipped entirely.
I got it fixed 👇 
I worked on the Changelog 18 page: https://www.highlight.io/docs/general/changelog/changelog-18
Nope!
=> Repairing doc parser's UL handling.

.reflame.config.jsonc, backend/public-graph/graph/resolver.go, frontend/src/graph/generated/schemas.tsx, frontend/src/pages/Player/PlayerHook/PlayerHook.tsx, frontend/src/pages/Player/PlayerHook/PlayerState.ts
For some projects, we need to inject styles when we are replaying to ensure the replay looks correct.
Ensure we do this after applying rrweb mutations to make sure the styles are rendered correctly.
Enables media asset inlining for this project.
before
after
https://frontend-pr-5292.onrender.com/1031/sessions/6MvXaWNjUZ9RW6wuANX4QCKYZ79h
https://frontend-pr-5292.onrender.com/1031/sessions/7S4SqSsK5nNRmrqNf7ObE8rMJGFD
No
=> update mui injection logic for synder

docs-content/getting-started/3_client-sdk/7_replay-configuration/recording-network-requests-and-responses.md, sdk/client/src/listeners/first-load-listeners.tsx, sdk/client/src/listeners/network-listener/network-listener.ts, sdk/client/src/listeners/network-listener/utils/fetch-listener.ts, sdk/client/src/listeners/network-listener/utils/xhr-listener.ts, sdk/client/src/types/client.ts, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json
Add option to specify specific keys in the request/response body to redact and to record all others by default.
Not tested
=> Add option to redact specific request/response body keys

frontend/src/graph/generated/schemas.tsx, frontend/src/pages/Player/ResourcesContext/ResourcesContext.tsx, frontend/src/util/preload.ts
Consolidate network resource size logic from #5264 between all places that we fetch network resources.
This ensures that viewing an error instance that will preload the session does not fetch a large network resource file.
[preview](https://preview.highlight.io/5403/errors/j5pxbefr4utB8uHe5y8RANfHf3BA) of error with large session j5pxbefr4utB8uHe5y8RANfHf3BA that would crash on loading network resources.
No
=> ensure errors page does not load large session resources

backend/event-parse/parse.go, backend/event-parse/parse_test.go, backend/event-parse/sample-events/input.json, backend/event-parse/sample-events/output.json, frontend/src/components/Header/Header.tsx
Asset ingestion logic would store non-ok http responses.
Updates the header to only show the `data is not recorded` warning for non-paying (non-overage) customers.
N/A
No
=> ensure we do not store invalid assets

highlight.io/components/Home/CalendlyPopover.tsx, highlight.io/pages/demo-confirmation.tsx
Add a `/demo-confirmation` page and redirect to it when scheduling a demo through Calendly. closes #5280
=> Add "Thank you" page on demo confirmation

backend/model/model.go, backend/opensearch/opensearch.go, backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver.go, backend/worker/opensearch.go
In the flow to create or update an error group, we have some logic that attaches the stacktrace's top frame's filename to the opensearch document (see #2091 for when this was added). Per a chat with @mayberryzane, this is from a time when we showed the filename in the error feed. We no longer do this and therefore:
* have no need to include the filename
* can reduce an unnecessary update
Confirmed error feed indexing still works as expected.
N/A
=> remove useless opensearch update

sdk/firstload/.npmignore, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts, sdk/firstload/vite.config.ts
As mentioned in https://github.com/highlight/highlight/pull/5282#issuecomment-1549450686, our highlight.run release
was not setting a `browser` key resulting in `unpkg` and `cdn.jsdelivr.net` using the `main` file, which is now an ESM build.
Adds the `browser` key to ship the `<script>` tag umd file.
https://www.jsdelivr.com/documentation#id-configuring-a-default-file-in-packagejson
Updates some other highlight.run package metadata.
Local deploy using `<script src="http://localhost:5173/dist/index.umd.cjs></script>`
https://www.loom.com/share/98a9863ada1143b197f3201bf6ad4400
New patch version of highlight.run released.
=> add highlight.run browser key for cdn distribution

backend/main.go, backend/opensearch/opensearch.go, backend/public-graph/graph/resolver.go, backend/worker/opensearch.go
#5301 had an unintended regression because `IndexSynchronous` does not handle parent/child relationships like `Index` does. 
As a result, error instances were not being attached to their error group in opensearch (postgres is fine) and therefore were not showing up in the error feed because they didn't have `join_type` defined on their document:
This PR adjusts the code so those two functions use the same logic for building up the openseach index request.
Validated that new error groups have `join_type` set 
and that they show up in the error feed
N/A
=> fix attaching error object to error group in opensearch

sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts, sdk/firstload/vite.config.ts
Main exported object is `H`, not `highlight`.
=> fix umd named object

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, backend/storage/storage.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/Player/PlayerHook/PlayerHook.tsx, frontend/src/pages/Player/PlayerHook/PlayerState.ts, frontend/src/pages/Player/ResourcesContext/ResourcesContext.tsx, frontend/src/pages/Player/TimelineIndicatorsContext/TimelineIndicatorsContext.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/NetworkPage/NetworkPage.tsx, frontend/src/util/preload.ts
Timeline indicator events were loaded from the backend where the backend would download the file from S3.
Instead, pass the S3 signed url to the frontend as we do for resources and the events data
so that the frontend could asynchronously load the timeline without blocking the rest of the loading, and
to make sure the cloudfront download could happen faster and be cached by the browser.
Local fetch and render of large session VbEEeAuUMnOqTefUNruC7Dhd3Yb0
No
=> load timeline indicator events on frontend from s3

sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts, sdk/firstload/vite.config.ts
unpkg will use `application/node` when the file extension is `.umd.cjs`
new highlight.run patch
=> use consistent js extension for highlight.run

.reflame.config.jsonc
This PR regenerates the reflame config with `REACT_APP_AUTH_MODE` now being set in Doppler (previously it wasn't set to anything).
See: https://highlightcorp.slack.com/archives/C04DVJJ0ZJ6/p1684262049954269
=> Fix reflame vars

backend/public-graph/graph/resolver.go
- there are sessions for ignored users not getting flagged as excluded: 
`select * from sessions where excluded_reason = 'IgnoredUser' and not excluded limit 1`
- it seems like this is affecting sessions where a payload is ingested before the session is identified
- was able to repro by logging out, starting a new session, and logging in as an ignored user
- followed steps above before and after change
- no, but we can probably backfill the excluded flag for these sessions. looking into how many are affected
=> fix issue where identify after payload isn't excluded

frontend/src/components/Header/Header.tsx, frontend/src/pages/Billing/utils/utils.ts, frontend/src/pages/ErrorsV2/SearchPanel/SearchPanel.tsx, frontend/src/pages/LogsPage/LogsPage.tsx, frontend/src/pages/LogsPage/OverageCard/OverageCard.tsx, frontend/src/pages/Sessions/SessionsFeedV3/OverageCard/OverageCard.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionsFeedV3.tsx
- per https://github.com/highlight/highlight/issues/5195, adds overage cards to make it clearer to the user when they have sessions/logs/errors that are no longer being recorded due to exceeding their billing limits
- local clicktest
- dependent on `zane/billing_page_v2` branch, will merge into that branch or merge into main after that is deployed
=> #5195 add overage cards to sessions/errors/logs feeds

highlight.io/pages/docs/[[...doc]].tsx
When clicking a link that leads to an index doc page, it redirects to it's first non-index page. This used to make it impossible to go back in browser history. fix #4960
=> Fix breadcrumbs in docs trapping your history

sdk/client/vite.config.ts, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts, sdk/highlight-next/package.json, sdk/highlight-node/package.json
It looks like our `highlight-run/client` sourcemaps references are causing some weird, 404ed queries in client applications.
https://discord.com/channels/1026884757667188757/1026884757667188763/1108885210277347389
=> Supress @highlight-run/client sourcemaps

.vscode/settings.json
=> Repairing wordwrap settings for VSCode

sdk/client/vite.config.ts, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts, sdk/firstload/vite.config.ts
Certain environments have a problem with the `modules` target that vite uses by default.
Bundle to `ES6` for best compatibility.
Local client preview.
No
=> use es6 build compatibility

backend/private-graph/graph/schema.resolvers.go
- overage cards were showing if exceeding the free tier limits but on the free trial
- tested the `GetBillingDetailsForProject` query locally with null, past, and future `trial_end_date`
- no
=> fix overage cards when on free trial

backend/hubspot/hubspot.go
We are adding links to hex dashboards manually to Hubspot companies, but the link is in a consistent format and can be assigned automatically.
Will click test after this change goes outl.
Confirm property gets set as expected.
=> Set hex dashboard link on Hubspot companies

frontend/.eslintrc
This reverts commit bc887cbadf4143734cf93f7fdfc5cf551490896a.
This broke the build since `yarn lint` didn't run on that PR. 
See broken build on a different PR:
https://github.com/highlight/highlight/actions/runs/5047812453/jobs/9055181704?pr=5127
=> Revert "ban imports from @icons (#5389)"

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/mutation.gql, frontend/src/graph/operators/query.gql, frontend/src/pages/ProjectSettings/ErrorFiltersForm/ErrorFiltersForm.tsx, frontend/src/pages/ProjectSettings/ErrorSettingsForm/ErrorSettingsForm.tsx, frontend/src/pages/ProjectSettings/ExcludedUsersForm/ExcludedUsersForm.tsx, frontend/src/pages/ProjectSettings/FilterExtensionForm/FilterExtensionForm.tsx, frontend/src/pages/ProjectSettings/FilterSessionsWithoutErrorForm/FilterSessionsWithoutErrorForm.tsx, frontend/src/pages/ProjectSettings/NetworkRecordingForm/NetworkRecordingForm.tsx, frontend/src/pages/ProjectSettings/ProjectSettings.tsx, frontend/src/pages/ProjectSettings/ProjectSettingsContext/ProjectSettingsContext.tsx, frontend/src/pages/ProjectSettings/RageClicksForm/RageClicksForm.tsx
Figma for the new settings show that project settings are saved using a single button. This PR adds that endpoint, and changed much of the logic in the project settings to use the new context that manages settings. 
Discussion in Slack about it: https://highlightcorp.slack.com/archives/C01FJL7V630/p1683905993153839
=> Endpoint that saves all settings

frontend/src/pages/Player/PlayerHook/PlayerHook.tsx
Sessions that are live but have been processed can have inactivity intervals.
We should skip them to make live sessions work more like non-live ones.
[preview](https://frontend-pr-5359.onrender.com/1/sessions/jV2IeabUfdcacjr1XRnVdXMQy0D3?page=1&query=and%7C%7Ccustom_processed%2Cis%2Ctrue%7C%7Ccustom_created_at%2Cbetween_date%2C2023-04-17T17%3A20%3A25.774Z_2023-05-17T17%3A20%3A25.774Z)
https://www.loom.com/share/5c94b3e044ca4be893dabd1cb13323b3
No
=> skip inactivity periods for live sessions

docs-content/getting-started/fullstack-frameworks/next-js.md, e2e/nextjs/instrumentation.ts, e2e/nextjs/middleware.ts, e2e/nextjs/next.config.mjs, e2e/nextjs/tsconfig.json
DragonZSG discovered a problem with `middleware.ts` and `instrumentation.ts` on [this Discord thread](https://discord.com/channels/1026884757667188757/1109236631665385473/1109236631665385473)
I was able to reproduce and found this error:
```
An error occurred while loading instrumentation hook: (0 , _highlight_run_next__WEBPACK_IMPORTED_MODULE_1__.registerHighlight) is not a function
```
I was able to resolve the issue with a dynamic import in `instrumentation.ts`, because it appeared that `middleware.ts` was attempting to import Node.js-only code in a non-Node.js environment.
I've updated the docs.
I created a `middleware.ts` file at the root of `e2e/nextjs` and reproduced the error.
Subsequent changes to `instrumentation.ts` resolved the issue
Nope
=> Supporting Next.js middleware

backend/public-graph/graph/resolver.go, frontend/src/pages/Buttons/Buttons.tsx
Adds an example to the buttons page to ensure that we can correctly inline a style image asset.
Customer has a div that uses a `style` attribute with a `backgroundImage("url(...)"` syntax.
Adding a sample div of that type to our hidden buttons page for internal testing.
No
=> enable asset storage for another customer

backend/private-graph/graph/schema.resolvers.go, backend/redis/utils.go
Cleans up some outdated logic for fetching network request data from storage and Postgres and adds logic for reading from Redis. This is only hit when a session has not been processed (`resources_url == nil`).
https://www.loom.com/share/5557d98fa45c456ea306fc333e1173ef
Also started working on some notes about how data is fetched for session replay: https://www.notion.so/runhighlight/Live-Mode-Notes-53677c96bd9d4280a6e2164898da99df?pvs=4
Will monitor `Resources` resolver and click test once things are live in production.
=> Load resources from Redis for unprocessed sessions

backend/migrations/cmd/delete-behave-health-sessions/main.go, backend/model/model.go, backend/payload/payload.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver.go, backend/redis/utils.go, backend/storage/storage.go, backend/worker/worker.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/index.tsx, scripts/remove_uncompressed.py, scripts/test_remove_uncompressed.py
This PR cleans up writing (and reading) console messages from redis. We now write/read this data from clickhouse (#4833)
Note: `messages_url` endpoint already cleaned up in #5336
Confirmed no errors with a new session and that the console messages still read/write from clickhouse.
N/A
=> remove writing session console messages to redis

backend/public-graph/graph/resolver.go
- resource is "within billing quota" if its cost is less than the max cost, comparison should be flipped here
- mocked data locally
- no
=> fix billing quota check

frontend/src/pages/Player/PlayerPage.tsx
Some sessions are failing to load when the initial rrweb events do not render a valid DOM.
Keep trying to scale the replayed in that case until the player loads successfully.
Example session: MG8O8w949UjPn1AiYAkaBJBzpbal
[Before](https://app.highlight.io/1/sessions/MG8O8w949UjPn1AiYAkaBJBzpbal)
[After](https://frontend-pr-5421.onrender.com/1/sessions/MG8O8w949UjPn1AiYAkaBJBzpbal)
No
=> fix sessions that fail to load

backend/private-graph/graph/resolver.go, frontend/src/util/db.ts
Operation name had the wrong case in the indexeddb cache exclusion policy.
Also stops emitting github integration errors as they are not actual errors.
cache now bypassed for the payment settings page
different stripe urls loaded
No
=> fix billing details caching stripe url

.github/workflows/python.yml, e2e/python/.gitignore, e2e/python/pyproject.toml, sdk/highlight-py/poetry.lock, sdk/highlight-py/pyproject.toml
Received a report of issues with our SDK
```
Could not find a version that matches opentelemetry-proto<2.0.0,==1.16.0,==1.18.0,>=1.16.0 (from highlight-io==0.4.8->talo-python-shared-lib (pyproject.toml))
Tried: 1.0.0, 1.0.0, 1.1.0, 1.1.0, 1.2.0, 1.2.0, 1.3.0, 1.3.0, 1.4.0, 1.4.0, 1.4.1, 1.4.1, 1.5.0, 1.5.0, 1.6.0, 1.6.0, 1.6.1, 1.6.1, 1.6.2, 1.6.2, 1.7.0, 1.7.1, 1.7.1, 1.8.0, 1.8.0, 1.9.0, 1.9.0, 1.9.1, 1.9.1, 1.10.0, 1.10.0, 1.11.0, 1.11.0, 1.11.1, 1.11.1, 1.12.0, 1.12.0, 1.13.0, 1.13.0, 1.14.0, 1.14.0, 1.15.0, 1.15.0, 1.16.0, 1.16.0, 1.17.0, 1.17.0, 1.18.0, 1.18.0
Skipped pre-versions: 0.9b0, 0.9b0, 0.10b0, 0.10b0, 0.11b0, 0.11b0, 0.12b0, 0.12b0, 0.13b0, 0.13b0, 0.14b0, 0.14b0, 0.15b0, 0.15b0, 0.16b0, 0.16b0, 0.16b1, 0.16b1, 0.17b0, 0.17b0, 1.0.0rc1, 1.0.0rc1, 1.12.0rc1, 1.12.0rc1, …
```
=> update python sdk dependencies

backend/model/model.go
Remove some indexes set in `model.go` that are not used, as per
```sql
select pg_size_pretty(pg_relation_size(i.indexrelid)) AS index_size, *
from pg_stat_all_indexes psai
LEFT JOIN pg_index i ON i.indexrelid = psai.indexrelid
where schemaname = 'public'
and idx_scan < 1
order by pg_relation_size(i.indexrelid) desc, idx_scan desc, relname;
```
Checking that these indexes have 0 bytes scanned.
Will monitor the migration step in the aws deploy.
=> cleanup unused gorm indexes

backend/store/error_groups.go
When we autoresolve error groups, the status isn't getting updated in opensearch correctly. 
Per this [comment](https://github.com/highlight/highlight/pull/5354#discussion_r1201385154), we switched to updating async to limit writes to opensearch. However, the async flavor doesn't seem to propogate the update. My suspicion is that we don't explicitly refresh in this flow (#3550). I filed #5457 to look into this more.
Regardless, because `updateErrorGroupState` is called by non-worker code (e.g. updating the status in the app), we need this to be a sync operation so there isn't a delay.
Ran the autoresolver locally with a "stale" error group (see #5354) and confirmed that both postgres and opensearch have updated "RESOLVED" states.
We should monitor opensearch after running the autoresolver …
=> use UpdateSynchronous when updating an error group state

backend/clickhouse/log_row.go, docs-content/getting-started/backend-logging/2_js/1_overview.md, docs-content/getting-started/backend-logging/2_js/cloudflare.md, e2e/cloudflare-worker/package.json, e2e/cloudflare-worker/src/index.ts, e2e/cloudflare-worker/tsconfig.json, highlight.io/components/QuickstartContent/QuickstartContent.tsx, highlight.io/components/QuickstartContent/backend/js/cloudflare.tsx, highlight.io/components/QuickstartContent/logging/js/cloudflare.tsx, highlight.io/components/QuickstartContent/shared-snippets.tsx, sdk/highlight-cloudflare/package.json, sdk/highlight-cloudflare/src/sdk.ts, sdk/highlight-cloudflare/tsconfig.json, yarn.lock
Updates the interface for `H` in cloudflare workers to add a separate `H.init` to allow starting logging.
Adds a `setAttributes()` method to the cloudflare SDK to set global attributes.
Allows sending cloudflare logs with attributes per console method.
Fixes ingesting opentelemetry logs with nested attribute maps.
https://discord.com/channels/1026884757667188757/1111459644053921822
v1
v2
https://www.loom.com/share/ed41b7c6b5924dec920c9397d849987e
New docs:
1. [cloudflare error monitoring](https://highlight-landing-git-vadim-cloudflare-sdk-321afb-highlight-run.vercel.app/docs/getting-started/backend-sdk/js/cloudflare)
2. [cloudflare logging](https://highlight-landing-git-vadim-cloudflare-sdk-321afb-highlight-run.vercel.app/docs/getting-started/backend-logging/js/cloudflare)
New major …
=> improve cloudflare sdk interface for logging

frontend/.eslintrc, frontend/src/pages/WorkspaceTeam/WorkspaceTeam.tsx
This broke Reflame builds because trailing slashes are treated as folder specifiers in import maps, so can't be mapped to the /index.ts module.
This PR fixes the 1 instance we have and adds a restricted import pattern to prevent this from happening again.
In the future we might be able to perform some lightweight import rewriting to normalize these automatically, or at least give more context in the error message and provide an autofix suggestion.
[Reflame preview](https://preview.highlight.io/~r/start-preview/?variantId=01H1D65PJSW4EMHEJBRAHGNAE1&region=sjc&variantData=%7B%22type%22%3A%22branch%22%2C%22branch%22%3A%22prevent-import-with-trailing-slash%22%2C%22forkSpecifier%22%3A%22lewisl9029%2Fhighlight%22%2C%22githubOwnerName%22%3A%22highlight%22%2C%22githubRepositoryName%22%3A%22highlig …
=> Prevent import with trailing slash

backend/worker/kafka_worker.go
Only create `logs` setup events for backend logs.
Will monitor setup event creation in prod.
=> Only create setup events for backend logs

frontend/src/pages/LogsPage/LogsTable/LogDetails.tsx, frontend/src/pages/LogsPage/useGetLogs.ts
There's an interesting bug whereby we can't scroll when changing the `query`. To reproduce:
* Visit the logs page and set the time frame to something small (Last 15 minutes is sufficient for local, you may need something smaller for prod)
* You should have more than one page of logs
* Set the query to: `level:trace`
* Keep scrolling until you hit the end of all trace logs
* Clear the query
* Observe that you cannot scroll past the first page of logs
The reason this was happening was because I initially configured the lazy query in #4535 to apply the variables at the instantiation of the lazy query, not when I actually call the query (`getLogs()`). This is a gotcha with apollo (see [#5912](https://github.com/apollographql/apollo-client/issues/5912)). 
The reason why we even use a lazy …
=> fix incorrect usage of lazy query

backend/worker/kafka_worker.go
Seeing a bunch of these errors locally:
I thought this might have been a regression from #5465 but it looks like the behavior was always broken?
I debugged locally to confirm I was only marking setup events for projectId=1 locally.
=> reference the projectId, not the range index

backend/worker/autoresolver.go, backend/worker/autoresolver_test.go
The previous query would overmatch since it was not considering whether there were error objects that were recently created.
Before:
```sql
SELECT DISTINCT (error_groups.id), error_groups.project_id
FROM
"error_groups"
INNER JOIN error_objects ON error_groups.id = error_objects.error_group_id
WHERE error_groups.state = 'OPEN'
AND error_groups.project_id = 1
AND error_objects.created_at < '2023-04-30 11:54:57.589'
```
After:
```sql
SELECT DISTINCT (error_groups.id), error_groups.project_id
FROM
"error_groups"
WHERE
"error_groups"."project_id" = 1
AND "error_groups"."state" = 'OPEN'
AND id NOT IN(
SELECT
"error_group_id" FROM "error_objects"
WHERE
created_at >= '2023-04-30 11:54:57.589')
```
Added a regression test.
N/A
=> Fix autoresolve query

.github/workflows/e2e.yml
Use the BuildJet Cache when using the BuildJet runners
For more details on how to migrate → https://buildjet.com/for-github-actions/docs/guides/migrating-to-buildjet-cache
=> Use BuildJet Cache instead of GitHub Cache on BuildJet Runners

sdk/highlight-next/bin/clean-highlight-init.sh
Updates the next build pipeline to work on all platforms by switching the `sed` command to `printf`. 
`sed` on mac would error with `sed: 1: "dist/HighlightInit.js": extra characters at the end of d command` despite working on linux.
The build step is necessary because the bundle must be marked with `"use client"` to make sure next.js does not
try to use the highlight component in server-side rendered code.
=> update next build clean script to be platform agnostic

backend/email/email.go
Issue: https://github.com/highlight/highlight/issues/5481
Update our emails to send from the `notifications@notify.highlight.io` address. Added the appropriate CNAME files to Google Domains to verify domain in [Sendgrid](https://app.sendgrid.com/settings/sender_auth).
1. Go to the team settings page (`/w/1/team`)
2. Invite yourself
N/A
=> Update email domain sender

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, backend/store/project_filter_settings.go, backend/store/project_filter_settings_test.go, backend/worker/autoresolver_test.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/mutation.gql, frontend/src/graph/operators/query.gql
This PR cleans up some unused endpoints that is no longer needed since we created a consolidated endpoint to save all project settings (#5387).
* Confirmed that updating project settings (that exist on the project_filter_settings table) correctly update
* Added tests
N/A
=> clean up unused project filter settings endpoints

.github/workflows/go-sdk.yml
As with #5519, pin the golangci-lint version for the Go SDK test.
CI
No
=> pin golangci-lint version in go sdk test

frontend/src/pages/Billing/BillingPageV2.tsx, frontend/src/pages/Billing/UpdatePlanPage.tsx
- adds tooltip to explain billing limit for #5455 
- update minimum spend copy #5447 
- no
=> update copy on billing page

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/worker/worker.go
Noticed this [comment](https://github.com/highlight/highlight/issues/5471#issuecomment-1568563563) and while looking at all the places where we exclude a session, I noticed this piece of code that excludes sessions when there are no timeline indicator events. I've added tracking to determine if this is a reason we exclude a session (see #5252).
I don't think this PR solves this comment linked but it may help with understanding why this query returns non-zero results:
```sql
SELECT
created_at,
excluded,
excluded_reason
FROM
sessions
WHERE
excluded = TRUE
AND excluded_reason IS NULL
ORDER BY
created_at DESC
LIMIT 100
```
=> add additional debugging information on when there are no timeline indicator events

backend/opensearch/opensearch.go
Synchronous updates to opensearch should be an all or nothing operation in terms of their success/failure. If they fail through our kafka flow, we should rely on kakfa to retry instead of the Retryable workflow (which is only for async updates to opensearch). This keeps the logic consistent with how we do synchronous index operations (see [slack](https://highlightcorp.slack.com/archives/C02CJANPHQS/p1685733121119179?thread_ts=1685660764.377189&cid=C02CJANPHQS)).
N/A
=> skip retryable flow for updating opensearch synchronously

backend/opensearch/opensearch.go
Since switching to sync updates to opensearch (#5524), we are getting some conflict updates:
See this stackoverflow: https://stackoverflow.com/questions/36188917/how-to-fix-elasticsearch-conflicts-on-the-same-key-when-two-process-writing-at-t
These are fine since kafka will retry, however it's a lot of noise.
Per looking at the source, it looks like the async update had RetryOnConflict set. This PR ports that behavior to the sync update.
We should monitor to confirm this cools off these logs:
https://app.highlight.io/1/logs?query=error%20updating%20session%20in%20opensearch%20level%3Aerror%20code.filepath%3A%2Fbuild%2Fbackend%2Fpublic-graph%2Fgraph%2Fresolver.go
=> retry sync updates to opensearch in case of conflict

backend/worker/autoresolver.go, backend/worker/autoresolver_test.go
The autoresolver query to find stale errors is taking too long
This PR optimizes the autoresolve query to use `NOT EXISTS` instead of `NOT IN` and includes the project_id in the subquery
Tests pass
N/A
=> optimize autoresolver query

sdk/highlight-ruby/highlight/lib/highlight.rb
Presently, the ruby SDK does not support specifying custom attributes on log messages.
This PR adds basic support for passing these custom attributes through to highlight.
This change should be backwards compatible with the existing SDK version
Right now, it's possible to configure this with some ruby magic and an initializer in a rails app, but this is far some ideal and brittle to breaking whenever the SDK makes minor changes:
```
Rails.application.reloader.to_prepare do
Highlight::H.class_eval do
def record_log(session_id, request_id, level, message, attrs = {})
caller_info = caller[0].split(":", 3)
function = caller_info[2]
if function
function.delete_prefix!("in `")
function.delete_suffix!("\"")
end
@tracer.in_span("highlight-ctx", attributes: { …
```
=> Allow attribute passing into H#record_log

backend/private-graph/graph/schema.resolvers.go
Similar to #5524, this makes all private graph requests that update opensearch to be synchronous
Confirmed that an update to opensearch via private graph (e.g. marking an error group as viewed) updates as expected.
Will monitor the same as #5524. Private graph traffic is a lot more negligible than public graph so I don't expect this to have any impact.
=> make all updates to opensearch via private graph synchronous

backend/private-graph/graph/schema.resolvers.go, frontend/src/pages/ErrorsV2/ErrorQueryBuilder/components/QueryBuilder/QueryBuilder.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionQueryBuilder/components/QueryBuilder/QueryBuilder.tsx
- fix issue where updating an existing segment was failing the "name already exists" validation
- preventdefault on dropdown click to avoid menu popping up for a split second
- remove buttons and interactive features from "readonly" state
- working on changes for relative date range (e.g. "last 7 days") in separate PR
- no
=> #4265 misc segment fixes

.gitattributes
So users won't get a useless diff, instead would be prompted to accept either version wholesale, and then regenerate using `yarn reflame-build`.
=> Treat Reflame generated files as binary

backend/public-graph/graph/resolver.go, backend/public-graph/graph/resolver_test.go
If an ignored error reoccurs, it is reopening instead of staying ignored. This PR fixes that and ensures the opensearch data is the same as postgres.
Relates to #5511
Tests added.
Manual test:
* Resolved errors reopen if they reoccur
* Ignored errors stay ignore if they reoccur
N/A
=> ensure ignored errors stay ignored

.gitattributes, frontend/scripts/build-css-bundle.mjs, frontend/src/__generated/index.css
This PR reverts back to outputting non-minified generated css for Reflame, in hopes that it could minimize frequency of merge conflicts in the generated file. 
Previously we had to start minifying because vanilla-extract's esbuild plugin outputted comments that depend on absolute path, so would differ between CI and local machines. In this PR we work around that by manually stripping out those comments with a regex.
Also reverts #5551, since treating the file as binary actually does the opposite of what we want (minimize frequency of merge conflicts), since no automatic conflict resolution could ever occur with binary files.
Styles in latest Reflame deployment looks fine. Should be good to go if the Reflame generated files check passes in CI. Edit: looks like we're good to go!
=> Stop minifying generated css again

backend/migrations/cmd/unexclude-sessions-opensearch/main.go, backend/opensearch/opensearch.go, backend/worker/worker.go
Per #5457, async updates to opensearch are unreliable. Per #5511, we are migrating all async updates to be synchronous. Hence, this PR simply removes the async update functionality.
* Confirmed opensearch updates that are processed via the worker (e.g. processing a session) still work as expected.
Will monitor the [prod cluster](https://us-east-2.console.aws.amazon.com/aos/home?region=us-east-2#opensearch/domains/highlight-search-prod-v2?tabId=clusterHealth).
=> deprecate async updates to opensearch

backend/model/model.go, backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go
This PR adds some auth checks to error object endpoints
On the main branch:
Copy one of the queries as curl and paste it into Postman
In Postman, uncheck the `token` param and observe that the request goes through:
On this branch:
Perform the same request and observe the request is rejected
If you check the `token` param, the request should go through:
N/A
=> add auth checks to error object endpoints

sourcemap-uploader/package.json, sourcemap-uploader/src/index.ts, sourcemap-uploader/src/lib.ts
Check that `.js.map` files are present when running the sourcemap uploader
to make sure a customer is generating sourcemaps in the first place when using the script.
Fixes an issue where `--path` was a required argument.
with `.js.map` files
without `.js.map` files but with other files there
New sourcemap uploader version.
=> make sourcemap-uploader validate sourcemaps exist

docs-content/getting-started/3_client-sdk/7_replay-configuration/iframes.md, docs-content/sdk/client.md, sdk/client/src/index.tsx, sdk/client/src/types/iframe.ts, sdk/client/src/types/types.ts, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts, sdk/firstload/src/index.tsx
Improves the experience of using highlight with a cross-origin iframe setup by removing the
`isCrossOriginIframe` option (now automatically inferred) and by making the `H.init` setup more robust to the order in which it is called.
Before this change, `H.init` had to be called first in the parent window and then in the cross-origin iframe
to make sure the iframe would be recorded. This change adds window message listeners to the parent
and iframe to allow them to communicate about the rrweb initialization state to allow the iframe to wait
for the parent window to set up rrweb.
https://www.loom.com/share/7727bf44b7e2418db9d8f9dc8238d220
New minor version 7.1.0
https://highlightcorp.slack.com/archives/C01JFQ77WTX/p1685063049376099
=> improve experience of recording cross-origin iframes

backend/opensearch/opensearch.go, backend/public-graph/graph/resolver.go
Still seeing the opensearch updates here taking up >50% of the ProcessPayload time in most cases. 
Ruling out the postgres part of the trace because the postgres load doesn't look bad. 
Local session recording and showing in the feed correctly.
Monitoring kafka message consumption.
=> make PushPayload processing use async opensearch updates

.prettierrc, .reflame.config.jsonc, .vscode/settings.json
A small quality of life change to make prettier format the reflame config with trailing commas (using [this](https://github.com/prettier/prettier/issues/5708#issuecomment-491610261) trick), and make vscode not show warnings for those trailing commas. (I'll probably start adding these to new apps by default soon)
It's possible to apply this to things like tsconfig and all the vscode configs as well, though I didn't do that here since they were added to prettier ignore previously.
=> Better support for trailing commas in reflame config

backend/integrations/integrations_test.go, backend/private-graph/graph/resolver_test.go, backend/public-graph/graph/resolver_test.go, backend/store/error_groups_test.go, backend/store/project_filter_settings_test.go, backend/util/tests.go, backend/worker/autoresolver_test.go
We have a util we use in tests to clean the postgres test db between test runs. It currently has a requirement to pass in the test name which is really unnecessary given we can derive that off of the `*testing.T` param.
Build passes
N/A
=> simplify db test util

frontend/src/__generated/index.css, frontend/src/pages/ErrorsV2/ErrorBody/ErrorBody.tsx, frontend/src/pages/ErrorsV2/ErrorBody/components/ErrorBodyText/index.tsx, frontend/src/pages/ErrorsV2/ErrorInstance/ErrorInstance.tsx, frontend/src/pages/Player/RightPlayerPanel/components/ErrorDetails/ErrorDetails.tsx
This PR moves the error body (internally called `event`) down from the error group level to the error instance (internally called `error_object`) level. The reason for doing this is that the error group's body is set to whatever the latest error instance body is. However, error instances with different error bodies can be grouped together (e.g. same stacktrace but different error bodies due to using [variable interpolation](https://github.com/highlight/highlight/pull/5310)).
See [figma](https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=8467-347211&t=iCRRrIXANlJHENtH-0).
* Find an error group with different error instance bodies.
* Traverse the error instances and observe the different error bodies.
Confirmed via …
=> move error body down to the instance level

frontend/src/pages/ErrorsV2/ErrorTitle/ErrorTitle.tsx
We never pass an `errorObject` into this component. No need to support that flow if it's unused.
Build passes.
N/A
=> simplify props to <ErrorTitle /> component

backend/opensearch/opensearch.go, backend/public-graph/graph/resolver.go
This reverts commit e99449e630fc8b498adadb752489f352d8b937ba but adds a dd trace to the opensearch update.
=> Revert "make PushPayload processing use async opensearch updates (#5568)"

backend/private-graph/graph/resolver.go, backend/private-graph/graph/resolver_test.go, backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver.go, frontend/src/util/log.ts, frontend/src/util/preload.ts, sdk/highlight-go/tracer.go
Fixes resolver logic that's causing nil pointers in our frontend.
Removes noisy frontend errors that are reported from the preload code.
Closes #5556
Closes #5590
New unit tests.
Testing the relevant graphql operations locally.
No
=> fix nil pointer references and remove noisy frontend errors

frontend/src/pages/Auth/SignIn.tsx, frontend/src/pages/Auth/SignUp.tsx, frontend/src/util/auth.tsx
Allow users to authenticate with their Github accounts
Other none code changes:
- Added Github as an Authentication app to Firebase
- Added a redirect_url to out Github app
- Updated asks from users to give us "Read email" privileges from their Github account
https://www.loom.com/share/39f9c7b794cc46dfb5ad82d54264f561
**Some gotchas**
- Make sure to delete your admin record from psql
- Make sure to delete your user from Firebase Authentication (used my personal email to avoid deleting admin account)
**Sign up**
1. Confirm you can sign up with email and password
2. Confirm you can sign up with Google
3. Confirm you can sign up with Github
**Sign in**
1. Confirm you can sign in with email and password
2. Confirm you can sign up with Google
3. Confirm you can sign up with Github
N/A
=> Add Github as a more developer friendly authentication flow

backend/model/model.go
See [slack](https://highlightcorp.slack.com/archives/C02N2AZS8BV/p1686325059574279). 
This setting should be opt-in, not opt-out (see original [ticket](https://github.com/highlight/highlight/issues/4744)).
Confirmed that this setting is disabled for a new project.
I've already ran `ALTER TABLE projects ALTER COLUMN filter_chrome_extension SET DEFAULT false;` on prod
=> Fix column default for Project.FilterChromeExtension

README.md
Found using a new linter as part of mega-linter, see [failing build](https://github.com/highlight/highlight/actions/runs/5258960794/jobs/9503888068)
Viewed readme
N/A
=> fix broken/dead links in README

backend/public-graph/graph/resolver.go
- new session alert code was being triggered on every push payload for non-excluded sessions even though they would only be sent once (some logic checks the DB to make sure they aren't sent more than once)
- >30% of CPU was spent in `SendSessionInitAlert` according to datadog, most of this for preloading session fields to get the visited url
- only trigger the code when transitioning from excluded to not (may happen a couple times during session processing but should be way less frequent)
- will monitor prod after deploying
- no
=> only send new session alerts when transitioning from excluded to not excluded

backend/pricing/pricing.go
- union the materialized view results with the count of sessions / errors after the materialized view was last updated (>= the latest date from the materialized view)
- added relevant indexes:
```
CREATE INDEX idx_error_objects_project_id_created_at ON public.error_objects USING btree (project_id, created_at)
CREATE INDEX idx_recent_sessions_billing ON public.sessions USING btree (project_id, created_at) WHERE ((excluded <> true) AND ((active_length >= 1000) OR ((active_length IS NULL) AND (length >= 1000))) AND (processed = true))
```
- slightly worse performance against the prod db (~.2s vs .06s for a larger project), difference will be more noticeable on ECS due to colocation so will monitor prod after deploying
- tested query in prod to make sure results were reasonable, click tested …
=> real time billing meters for sessions/errors

sdk/highlight-ruby/highlight/README.md
Tiny update, just noticed this looking over the SDK implementation. `highlight_io` is the correct gem to mention here
=> Fix gem name usage in README.md

backend/model/model.go, backend/pricing/pricing.go
- billing meter was including sessions outside billing quota after the materialized view's end date, remove those
- add filter to the materialized view definition in code (was already included in prod)
- currently adding another index in prod to include `within_billing_quota`
- click tested locallly
- no
=> remove sessions outside billing quota from meter

README.md
Removes the emoji in the "Contributors" title on the readme because the link was otherwise broken. Also keeping it this way for consistency.
=> Remove Emoji in Contributors Title

backend/vercel/vercel.go
- patching a Vercel environment variable will fail if it's already been defined (since the Highlight integration does not own it)
-  show the user a message indicating which variable is causing the issue so they can fix it
- no
=> better error messaging for Vercel env var patch error

frontend/src/__generated/index.css, packages/ui/src/components/Container/styles.css.ts
https://github.com/highlight/highlight/issues/5666
The popover on the errors page is appearing under the error content. This is due to the container's css sets the [container type](https://developer.mozilla.org/en-US/docs/Web/CSS/container-type) to `inline-size` which seems to ignore other component's `z-index`. Update the container's type to `normal`
1. Visit the errors page
2. Click an error
3. Click the `...` by the filters
<details><summary>Other uses of container</summary>
</details>
No
=> Fix popover transparency issues

frontend/src/index.tsx, frontend/src/util/log.ts
Per our eng retro, we should not have verbose client logs in our frontend by default.
Adds a local storage variable that can be used to enable verbose logs for player debugging.
No
=> disable client verbose logging by default

frontend/src/__generated/index.css, packages/ui/src/components/MultiSelectButton/styles.css.ts
Add a hover state to the multi select to make it clear that it is clickable.
1. View a session and hover over the "Type" and "Status" multi filters
https://github.com/highlight/highlight/assets/17744174/84689c9a-0f9d-4b6b-a2d9-c267427e2700
N/A
=> Add hover state of devtools multi selects

sdk/client/src/index.tsx, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts
Extends the maximum session length to 12 hours for a given project that needs longer sessions.
New patch version of the client.
=> extend session length for a given project

.github/workflows/turbo.yml, render/src/render.ts
Session render lambda was not published as part of CI.
CI with temp commit.
https://github.com/highlight/highlight/actions/runs/5337247107/jobs/9673025799
No
=> add session rendering lambda to CI

backend/clickhouse/logs.go
- avg() in clickhouse returns `NaN` when the input set is empty, not sure how to coalesce it correctly in SQL
- currently results in an error for projects with no logs recorded in the past 7 days
- tested locally w/ mocked input
- no
=> fix logs avg calc when no logs

highlight.io/components/Blog/Blog.module.scss, highlight.io/components/Blog/BlogPost/BlogPost.tsx, highlight.io/components/Blog/SuggestedBlogPost/SuggestedBlogPost.tsx, highlight.io/pages/blog/[slug].tsx
See [attached issue](https://github.com/highlight/highlight/issues/5265).
If a post does not have an image, then it defaults to the OG image which is currently used for previews.
Fixed Suggested Post:
Secondly, images don't scale infinitely depending on post title length anymore.
Before:
After:
=> Suggested blog posts sometimes do not have images

backend/model/model.go, backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver.go
We are not respecting the frequency setting set on alerts. This is due to a reference to a table that is no longer used, `AlertEvents`. Update the references to this table to use the respective table based on the type of event.
Click test:
1) Create a new error alert
a) set it to send to #chris-errors-test
b) Set the Alert Frequency to 5 minutes
2) Navigate to the buttons page (`/1/buttons`)
3) Clock on "Throw an Error" button
4) Click on "Throw an Error" again
5) Click on "Throw a randomized Error"
6) Wait 5 minutes
7) Click on "Throw an Error" again
N/A
=> Remove references to alert_events

render/src/ffmpeg.ts, render/src/render.ts
Because of how the frames were indexed, ffmpeg would generate the gif with frames in a random order.
https://highlight-session-render.s3.us-east-2.amazonaws.com/1/245336777.gif
Lambda will auto-depoy.
=> ensure session screenshot lambda generates gifs with frames in the correct order

sdk/highlight-py/e2e/highlight_azure/HttpTrigger/__init__.py, sdk/highlight-py/e2e/highlight_script/main.py, sdk/highlight-py/highlight_io/sdk.py, sdk/highlight-py/pyproject.toml, sdk/highlight-py/tests/test_aws.py, sdk/highlight-py/tests/test_azure.py, sdk/highlight-py/tests/test_gcp.py, sdk/highlight-py/tests/test_sdk.py
Ensure that logs emitted in a python app instrumented with the highlight SDK
outside of the context of a opentelemetry span are ingested. This allows using
highlight in an app without the `with H.trace():` contextmanager for the logging use-case.
New e2e that prints a log outside of a trace
trace-based spans still work
new unit test
New version of the python SDK published.
=> support ingesting logs without a span

.github/workflows/turbo.yml, docs-content/getting-started/4_backend-sdk/js/aws-lambda.md, docs-content/getting-started/4_backend-sdk/python/aws-lambda.md, highlight.io/components/QuickstartContent/QuickstartContent.tsx, highlight.io/components/QuickstartContent/backend/js/aws-lambda.tsx, package.json, render/package.json, render/src/index.ts, sdk/highlight-node/CHANGELOG.md, sdk/highlight-node/package.json, sdk/highlight-node/src/client.ts, sdk/highlight-node/src/handlers.ts, sdk/highlight-node/src/sdk.ts, yarn.lock
Adds a `Handlers.serverlessFunction` wrapper to the `@highlight-run/node` SDK for
capturing errors raised in AWS Lambda functions written in node.js
Closes #5625
Adding the new wrapper to the session-screenshot lambda written in node.js.
New minor version of `@highlight-run/node` released.
=> add a node.js error handler for aws lambda

.github/workflows/docker.yml, docker/compose.hobby.yml, docker/frontend-entrypoint.py, docker/frontend.Dockerfile, frontend/src/constants.ts, frontend/src/index.tsx, frontend/src/routers/ProjectRouter/ProjectRouter.tsx, frontend/src/util/graph.tsx, frontend/src/util/window.ts, frontend/vite.config.ts
Docker image was not correctly replacing the backend endpoint from the frontend 
when the endpoint is a numeric ip addresses.
Changes the build process to use a python script to make this easier to test.
Closes #5245
Testing deploy on EC2 instance.
https://www.loom.com/share/750c244a37384e2dbff42fc210f0090b
Will deploy a new docker image.
=> fix hobby docker image backend domain routing

docs-content/general/4_company/open-source/contributing/code-spaces.md, docs-content/general/7_integrations/clickup-integration.md, highlight.io/components/Docs/Docs.module.scss, highlight.io/components/MDXRemote/MarkdownList.tsx
Some of the markdown bullet points in Docs were styled incorrectly. Newlines would not be indented properly.
Before:
After:
=> Modified bullet styling for docs

frontend/src/pages/LogsPage/LogsTable/LogsTable.tsx
While working on a different table that uses react-table, I noticed that we can now make our react-table usages more typesafe (see #4142) and the utility in #4185
Confirmed keys work with typeahead:
Confirmed that keys are typesafe:
N/A
=> use strongly typed logs table

docs-content/general/changelog/changelog-19.md, docs-content/general/changelog/changelog-20.md, highlight.io/components/Blog/Blog.module.scss, highlight.io/components/Comments/CommentsBox.tsx, highlight.io/components/MDXRemote/EmbeddedVideo.tsx, highlight.io/components/MDXRemote/index.ts, highlight.io/pages/docs/[[...doc]].tsx
Videos in our docs were smaller than expected and looked weird without a border. Added a new EmbeddedVideo component that can be used in the docs that styles videos correctly.
Also went ahead and made the image borders in the blog pages consistent.
Checked embedded videos on all screen sizes
https://highlight-landing-pmnr4h2v7-highlight-run.vercel.app/docs/general/changelog/changelog-20
https://highlight-landing-pmnr4h2v7-highlight-run.vercel.app/blog/launch-week-1-day-5
=> added EmbeddedVideo component for docs

docker/compose.hobby.yml, frontend/src/util/db.ts
On Safari, we don't have access to reading how much memory indexeddb is occupying.
This means we cannot clean up if we are getting close to memory usage limits.
Disable indexeddb altogether in this case to avoid https://app.highlight.io/1/errors/4E8fIhngcFgOOeWpkmG0A6Aq7bee
* Fixes backend env vars for the hobby deployment needed by the backend
Reflame preview
No
=> disable indexeddb when there is no way to read memory usage

packages/ui/src/components/DatePicker/PreviousDateRangePicker.tsx
This PR is the first pass for issue #5693 
This PR enhances the control bar functionality by addressing the issue of text overflow when selecting date and time for large date ranges.
Here's a video of how it works now:
https://github.com/highlight/highlight/assets/94234459/3616af33-673d-47a4-b842-241bed4ebdf6
=> chore: fix the text overflow on DateInput

frontend/src/pages/Dashboards/pages/DashboardsHomePage/DashboardsHomePage.tsx
Fixes a broken link on the dashboards page. In prod, if you click the "View" button on a dashboard card it won't open and will cause the page to get in a weird state.
This PR makes the URL absolute and links to the correct project which fixes the issue.
N/A
=> Fix dashboard link

backend/private-graph/graph/resolver.go, backend/worker/worker.go
- fixes #5760
- when subscribing to a plan, clear the `TrialEndDate` to prevent ingesting extra sessions
- check billing quota again during session processing (since live sessions don't count toward the limit)
- no
=> reset trial on billing update, check quota during processing

frontend/src/__generated/index.css, frontend/src/routers/AppRouter/AppRouter.tsx, frontend/src/routers/ProjectRouter/ProjectRouter.tsx
- workspace level pages were breaking because of some code I added to the command bar to access the search context (the command bar is accessible outside of just the project-level pages)
- click tested locally, tested other non-project-router pages (workspace settings, login, etc) to make sure they weren't crashing
- need to turn on render autodeploys after this is merged
=> move error/search context up so it's accessible from workspace / other pages

backend/pricing/pricing.go, backend/public-graph/graph/resolver.go, backend/public-graph/graph/resolver_test.go
- customers committed to a monthly spend pay a different price - this fixes billing limit calculations for sessions
- unit test
- no
=> use special pricing for non-usage based plans

backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go
This PR makes all authorization errors (i.e. you're logged in but you don't have access to this resource) return a constant error message. Additionally, I removed all error wrapping for this scenario. Taking this approach will allow all these auth errors to be grouped together since we match if the error message is identical ([docs](https://www.highlight.io/docs/general/product-features/error-monitoring/grouping-errors)). 
If we didn't have error message matching, we could also fallback to [filtering](https://www.highlight.io/docs/general/product-features/error-monitoring/ignoring-errors#ignore-errors-by-regex-on-the-error-body) by error message.
Checked the graphql errors response when there is an auth issue:
Will monitor after rolling out. Assuming this groups as expected, we should …
=> constantize authorization errors

frontend/src/pages/Alerts/AlertConfigurationCard/AlertConfigurationCard.tsx
We want to allow non-Highlight admins to receive alerts. This can be helpful if someone wants to send alerts via email to an external service, like Opsgenie, as requested in #5732.
This PR adds some custom logic + styles to the emails input on the alert page allowing a user to enter a custom email address to receive email updates.
https://www.loom.com/share/9c0e69540fc84943addbe3121cae7cfa
I did not verify that the alerts were being sent locally because I wasn't sure how to trigger alert emails in local dev.
=> Allow non-admin emails to receive alerts

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/stacktraces/enhancer.go, backend/stacktraces/enhancer_test.go, frontend/src/graph/generated/schemas.tsx, frontend/src/pages/ErrorsV2/SourcemapErrorDetails/SourcemapErrorDetails.tsx, sdk/client/src/graph/generated/operations.ts, sdk/client/src/graph/generated/schemas.ts, turbo.json
Some stacktraces included a sourcemap URL that would cause a panic.
Fixes the panic and adds logging to make sure we can pinpoint what invalid sourcemap URL is provided.
Ingesting valid errors correctly.
Ingesting a fake sourcemap error of this type into the frontend.
Will monitor new log.
=> fix panic in stacktrace parsing code

e2e/go/fiber.go, sdk/client/src/utils/graph.ts, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts
Increases the backoff on client graphql retries to make sure we do not
send many requests to our public graph when there is an interruption.
Fixes issue in the web worker retry logic to avoid using window.localStorage which is not accessible.
Local deploy verifying that a fake backend error would throttle frontend requests correctly.
Adding a test 75% PushPayload failure rate to the backend:
New version of highlight.run client released.
=> throttle client retries to avoid PushPayload storm on kafka errors

backend/lambda/lambda.go, frontend/src/__generated/index.css, frontend/src/__generated/ve/pages/Player/RightPlayerPanel/components/SessionInsights/SessionInsights.css.js, frontend/src/pages/Player/RightPlayerPanel/components/SessionInsights/SessionInsights.css.ts, frontend/src/pages/Player/RightPlayerPanel/components/SessionInsights/SessionInsights.tsx, packages/ai/src/prompts.ts
Added button to trigger session insights as specified in https://github.com/highlight/highlight/issues/5687
Also fixed the backend insights retry function when local server is unavailable.
=> Add explicit button for session summary

backend/hubspot/hubspot.go, backend/hubspot/merge.go
Add company doppelganger API automation for merging duplicate companies.
This reverse engineers the [duplicates page](https://app.hubspot.com/duplicates/20473940/companies) in hubspot 
and automates the merging workflow.
Validating manually that the companies logged for merging are correct.
Now that #5728 is merged, will run this one-off to remove duplicate hubspot companies.
=> add automation for merging duplicate hubspot companies

experiments/chrome-extension/README.md, sdk/client/src/index.tsx, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts, sdk/firstload/src/index.tsx
Our client would set `window.Highlight` so that firstload could reference the class.
However, this would replace the native `window.Highlight` [class ](https://developer.mozilla.org/en-US/docs/Web/API/Highlight)defined by browsers.
This change renamed `window.Highlight` to `window.HighlightIO` to avoid this problem.
Render / reflame preview.
No
=> avoid overwriting native `window.Highlight` class

.reflame.config.jsonc
Turns out the crash was due to the reflame build resolving to a buggy antd version that doesn't properly handle objects as values (used in the Discord select, couldn't repro before because I didn't have Discord integration enabled).
Fixed by adding a version override to the latest antd v4.
Navigated to an alert with a discord channel set up in a [Reflame preview](https://preview.highlight.io/?%7Er_preview=%7B%22action%22%3A%22start%22%2C%22variantId%22%3A%2201H470H2MBBDRDQD4HT68MK2VJ%22%2C%22region%22%3A%22sjc%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22fix-alert-config-crash%5C%22%2C%5C%22forkSpecifier%5C%22%3A%5C%22lewisl9029%2Fhighlight%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A% …
=> Fix crash in alert details page

backend/stacktraces/enhancer_test.go, sdk/client/src/listeners/console-listener.tsx, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts
Our console error listener would drop the first frame of errors even when they were caught with a full stack trace.
It seems like this was an error when sharing the logic with the other console listeners that need to drop
the first frame of the stack trace because it is produced from the console listener itself (keeping that top frame
would be redundant).
Issue originally reported by a customer.
https://highlightcorp.slack.com/archives/C04NQ25RV8B/p1687896259977009
Local deploy triggering a frontend error.
before
after
New patch version of the SDK released.
=> ensure first frame of console.error is not dropped

backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go
Similar to #5781 but for authentication errors (you're not logged in).
* Copied a GQL request into Postman and removed the `token` attribute
* Observed 401 error in Highlight
=> constantize authentication errors

backend/errorgroups/filtering.go, backend/errorgroups/filtering_test.go, backend/model/model.go, docs-content/general/6_product-features/2_error-monitoring/ignoring-errors.md, frontend/src/pages/ProjectSettings/FilterExtensionForm/FilterExtensionForm.tsx
This PR filters out Firefox extension errors. See #5610
Rather than creating a new setting for this, we decided to overload the existing setting for filtering Chrome extension errors and now we filter for all browser errors.
This sets us up for adding additional functionality (like filtering for Safari extension errors).
Unfortunately, I still have not been able to replicate this behavior, but I did find an example of the error on prod (see #5606) and I wrote a unit test around it.
I've tracked #5811 to handle renaming the db column.
=> filter out firefox extension errors

frontend/src/pages/ErrorsV2/ErrorInstance/PreviousNextInstance.tsx
See https://github.com/highlight/highlight/pull/5774#pullrequestreview-1505733636
This PR reverses the order for the arrows to traverse error instances.
Confirmed the following:
* Down arrow means "go to the next older instance"
* Up arrow means "go to the next newer instance"
* Up arrow is disabled when on the latest instance
* Down arrow is disabled when on the oldest instance
N/A
=> reverse arrows order when traversing error instances

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/store/error_groups.go, backend/store/error_groups_test.go, frontend/src/graph/generated/schemas.tsx
While wiring up the frontend for the error instances listview (#5599), I noticed two issues with how the backend returns the data.
* Session must be optional (e.g. backed only error). Was getting an apollo error when this wasn't provided.
* Instances should be rendered in descending order (that way we get the latest instance at the top)
* Traversing backward `before != nil` doesn't maintain the expected order (see inline code comment)
Unit tests added
N/A
=> fix issues with error instances listview

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql
- pass a `sort_field` to the sessions_opensearch resolver, will be used to sort by "normalness" for interesting sessions
- splitting up frontend and backend so search will not break if frontend is deployed sooner
- tested in postman w/ existing query, new query with empty sort_field, 
- click tested
- no, will make the field non-optional in future PR with the UI changes to pass a sort_field
=> add sort_field to sessions_opensearch query

backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/components/ToggleRow/ToggleRow.tsx, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/mutation.gql, frontend/src/graph/operators/query.gql, frontend/src/hooks/useIsSettingsPath.ts, frontend/src/pages/EmailOptOut/EmailOptOut.tsx, frontend/src/pages/HaroldAISettings/HaroldAISettings.tsx, frontend/src/pages/SettingsRouter/SettingsRouter.tsx
First part of https://github.com/highlight/highlight/issues/5717
Add the Harold AI settings page, and a new setting to turn on emails for session insight digests
Set up the emailOptOut data model to handle specific projects
This should allow for users to turn on/off our new ai features, will have another PR addressing more advanced functionality shown in the designs
TODO: 
- Implement opting out for specific projects on the ui and backend (v2)
- Show the number of times a user calls the AI features on the Harold page.  (v2)
- this can be added once we add the ai output caching functionality
- Button leading to the docs page to learn more about AI
- Will add once the docs page is up
- Toggled the digests settings and check that it persists
- Toggled Harold settings and check it persists …
=> Added pages for new AI settings

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/store/error_groups.go, backend/store/error_groups_test.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql
This PR attaches the error group secure id when fetching a list of error objects. This is useful at the time we render the error instances table (not available yet) when linking out:
https://github.com/highlight/highlight/blob/b35d9614871ed9a498eba365e71ebad0e98ab05e/frontend/src/pages/ErrorsV2/ErrorInstances/ErrorInstancesTable.tsx#L80-L84
and not having to deal with conditional logic. 
Unit tests
N/A
=> attach error group secure id to error objects request

.reflame.config.jsonc
Looks like we were overriding to a version of antd that was different than the one in our lockfile, which caused some subtle CSS differences between Reflame and production that affected tab layout.
Using the version in the lockfile fixes this.
Checked Errors page in Reflame previews.
Before:
After:
=> Use matching version of antd

backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go
Auth errors should be grouped together (see #5781). We can't group them if we use error wrapping. This PR removes some error wrapping at some auth flows.
Fixes #5817, #5816
See deployment considerations for testing this.
This type of [error](https://app.highlight.io/1/errors/kZ35faADwk3q0K8s6geCkFxG53ux?page=1&query=and%7C%7Cerror_state%2Cis%2COPEN%7C%7Cerror-field_timestamp%2Cbetween_date%2C2023-06-05T19%3A48%3A52.509Z_2023-07-05T19%3A48%3A52.509Z) should no longer occur.
=> remove error wrapping for auth errors

backend/public-graph/graph/resolver.go
- a gorm `Create` with a `Returning` clause was not associating the returned ids with the correct records. e.g. if we attempted to create 10 records but only 5 were inserted, the new ids would be set on the first 5 records regardless of which ones were actually inserted
- instead of relying on the `Returning` clause, get the count of rows updated and sort the results of the second query by id to get the latest N rows
- set a watchpoint and confirmed via debugging
- will use the `init-opensearch` Make command to reindex the OpenSearch fields index
=> fix OpenSearch indexing when appending both new and old fields in same request

backend/lambda/lambda.go, frontend/src/pages/Player/RightPlayerPanel/components/SessionInsights/SessionInsights.tsx
https://github.com/highlight/highlight/issues/5775
The lambda often returns 500 and 503s, not sure if it's something to do with OpenAI's API being unreliable/inconsistent or the API Gateway timing out. Either way, the backend will now retry up to 5 times on error
=> Retry session insight lambda request on 500 errors

sdk/client/src/index.tsx, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts
- in `addProperties`, remove any properties that throw an error when calling `structuredClone`
- these would previously cause the entire `addProperties` call to fail
- we could consider making this check stronger (e.g. only allow `string | boolean | number`) as the `H.track` method signature enforces this already
- tested by calling `H.track` with invalid properties in prod vs locally
- no
=> addProperties - skip properties that cannot be serialized

frontend/src/index.tsx, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts, sdk/firstload/src/index.tsx, sdk/firstload/src/integrations/mixpanel.ts
When the mixpanel integration is enabled, forward the `H.identify` metadata to mixpanel
using the `mixpanel.people` [api](https://github.com/mixpanel/mixpanel-js/blob/master/doc/readme.io/javascript-full-api-reference.md#mixpanelpeople).
This change also send an `identify` event to mixpanel when `H.identify` is called.
If an `email` key is provided to the metadata, that value is used instead of the `identifier` to mimic
the `H.identify` behavior in the highlight app.
Enabling mixpanel integration in a local deploy.
New version `7.3.6`.
=> track identify metadata in mixpanel

docs-content/getting-started/fullstack-frameworks/next-js.md
I'll update the video title to "Next.js + Highlight Walkthrough"
=> Embedding YT vid into Next.js Walkthrough

backend/private-graph/graph/resolver.go
See #3497. Now [requested by another customer](https://discord.com/channels/1026884757667188757/1126738180553593026).
Allow Alerts / Comments to message private / DM conversations that the Highlight bot is added to in Slack.
Since the Bot has to be explicitly added in Slack by the members of the private channel, it wouldn't bypass slack's access controls. 
A channel name could only be shown to all highlight users if the bot is erroneously added to a slack channel.
Local deploy shows private channel that bot was added to.
No.
=> support private channel slack integration

docs-content/getting-started/4_backend-sdk/js/1_overview.md
The next js link is broken from this page
https://www.highlight.io/docs/getting-started/backend-sdk/js/overview
Verified link works locally with `npm run dev`
=> Fix nextjs link

backend/hubspot/hubspot.go, backend/kafka-queue/types.go, backend/worker/worker.go
Hubspot contact <-> company associations would not be created by our backend
because we would lose track of the contact / company hubspot IDs.
We would also have a race condition where the order of the two creations affected whether
an association would be created. This change makes that more robust and adds locking to make sure
there are no other races where two workers could try to create a duplicate contact / company.
Local testing: https://www.loom.com/share/87789a42e959446b9d88e03c7fafe9ed
Earlier testing: https://www.loom.com/share/2ca2439d433e46e298b18fe4cbeda8a6
No
=> ensure hubspot contacts and companies are associated

backend/public-graph/graph/resolver.go
- `sessionObj.ExcludedReason != reason` was doing a pointer comparison and always returning true if both were non nil
- debugged locally
- no
=> fix exclusion reason updated too frequently

frontend/src/__generated/index.css, frontend/src/pages/ErrorsV2/ErrorInstance/RelatedLogs.tsx, frontend/src/pages/ErrorsV2/ErrorInstance/RelatedSession.tsx
Use proper links for Related session / Related logs on the error instance view so these elements can be used as native links. For example, they can be cmd+clicked or have a right click context menu.
Verified these are links as expected:
=> use proper links for Related Logs / Related Session

backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go
See [error](https://app.highlight.io/1/errors/0DEF02alRmqVT5dUvuQF2nm76L18?page=1&query=and%7C%7Cerror_state%2Cis%2COPEN%7C%7Cerror-field_timestamp%2Cbetween_date%2C2023-06-11T18%3A34%3A57.039Z_2023-07-11T18%3A34%3A57.039Z) in Highlight.
Similar to #5854, this PR normalizes more auth errors so they can be grouped better.
Auth error should be grouped.
N/A
=> normalize more auth errors

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/store/error_groups.go, backend/store/error_groups_test.go, frontend/src/__generated/index.css, frontend/src/__generated/ve/pages/ErrorsV2/ErrorInstances/ErrorInstances.css.js, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/ErrorsV2/ErrorInstance/ErrorInstance.tsx, frontend/src/pages/ErrorsV2/ErrorInstance/SeeAllInstances.tsx, frontend/src/pages/ErrorsV2/ErrorInstances/ErrorInstances.css.ts, frontend/src/pages/ErrorsV2/ErrorInstances/ErrorInstances.tsx, frontend/src/pages/ErrorsV2/ErrorInstances/ErrorInstancesTable.tsx, frontend/src/pages/ErrorsV2/ErrorInstances/NoErrorInstancesFound.tsx, frontend/src/pages/ErrorsV2/ErrorTabContent/ErrorTabContent.tsx
This PR adds an error instances table for easier navigation (see [figma](https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=9059-234557&mode=dev)) along with the ability to search by email.
The table contains:
* error instance message (required)
* error instance created data (required)
* version (available if `session.appVersion` present)
* email (available if `session.userProperties.email` present)
The API uses the relay cursor spec and was already wired up in #5557.
Fixes #5599
https://www.loom.com/share/37351d0ef71c4089b5363bfeb19459e6
I am still trying to get the backfill from #5837 to finish hence this is guarded to only be visible to Highlight admins.
=> error instances table

backend/private-graph/graph/schema.resolvers.go
These endpoints should be returning proper errors otherwise there will be a graphql schema issue:
Incorrect:
Correct:
Related to #5818
There may be other graphql schema errors but this should get some of them.
N/A
=> return a proper err instead of getting a graphql error

frontend/package.json, frontend/src/index.tsx, yarn.lock
Reverts #4316. We were only using sentry for testing but aren't using it anymore.
Frontend loads as expected and no network requests to sentry.
N/A
=> remove sentry tracking

backend/private-graph/graph/schema.resolvers.go, frontend/src/pages/Player/PlayerHook/PlayerHook.tsx
* fixes undefined access to chunk_index when a chunk does not exist
* ensure error instance query returns nil instead of 0 for next/previous ids when they do not exist
No
=> cleanup some errors

highlight.io/components/Docs/HighlightCodeBlock/HighlightCodeBlock.tsx, highlight.io/components/MDXRemote/QuickStart.tsx, highlight.io/components/QuickstartContent/QuickstartContent.tsx, highlight.io/components/QuickstartContent/self-host/self-host.tsx, highlight.io/components/QuickstartContent/self-host/shared-snippets.tsx
As mentioned in #5828, our hobby deploy would not work for EC2 / remote-server deploys because
the frontend did not route correctly to the remote backend.
Confirmed that setting these env. vars solved the issue for this customer.
[Docs preview](https://highlight-landing-k9ikag77h-highlight-run.vercel.app/docs/getting-started/self-host/self-hosted-hobby-guide).
No
=> update docs for hobby networking

frontend/package.json, frontend/src/pages/ErrorsV2/ErrorStackTrace/ErrorStackTrace.tsx, yarn.lock
3.1.2 seems to have a broken build that references jsx without importing react: https://github.com/FezVrasta/react-resize-aware/issues/58
Pinning to the current version in the lockfile so there's no room for deviation in Reflame deploys.
=> Pin react-resize-aware to 3.1.0

backend/model/model.go
- fixes https://github.com/highlight/highlight/issues/4265
- don't count sessions not `within_billing_quota` in the meter
- tested locally, altered mv in prod already
- no, already deployed manually
=> ignore billing quota exceeded in session count

backend/public-graph/graph/resolver.go
- if a session was being excluded for an ignored user, its excluded flag / reason was updated in postgres but not updated in opensearch
- these sessions would keep showing as live since excluded sessions are skipped by the session processing worker
- local click test
- no
=> update excluded / excluded reason in opensearch w/ sql update

frontend/src/pages/ErrorsV2/ErrorFeedCard/ErrorFeedCard.tsx, frontend/src/pages/Player/RightPlayerPanel/components/NetworkResourcePanel/NetworkResourcePanel.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/NetworkPage/NetworkPage.tsx
Adds an Errors tab to the network request detail panel which shows a list of errors associated with the request.
N/A
=> Add errors tab to network request details panel

backend/hubspot/hubspot.go, backend/integrations/integrations.go, backend/jobs/log-alerts/log-alerts.go, backend/jobs/metric-monitor/metric-monitor.go, backend/oauth/oauth.go, backend/pricing/pricing.go, backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver.go, backend/public-graph/graph/resolver_test.go, backend/store/error_groups.go, backend/store/projects.go, backend/store/sessions.go, backend/worker/worker.go, backend/zapier/hook_store.go, backend/zapier/zapier.go
GORM's `Take` is essentially a `Limit(1).Find()` for one item, where if no item is found, an error is returned.
In most places, this makes more sense than our use of `First()` because we do not actually care about the ordering.
`First()` always adds a `ORDER BY` clause on the primary key, causing us to miss indexes in some situations
(we've had to manually bypass this for querying sessions by secure id). This cleans up the code and
makes it consistent for faster loading of error groups. 
Testing locally. https://www.loom.com/share/faaf23aafa5049fdb63aa08f06ef50e4
before
```sql
SELECT *
FROM "error_groups"
WHERE "error_groups"."secure_id" = 'O5am2YlVI3A6Cj8V9sUIgzDxTjkl'
ORDER BY "error_groups"."id"
LIMIT 1;
```
after
```sql
SELECT * 
FROM "error_groups" 
WHERE "error_groups"."secure_id" = …
```
=> replace first with take

.github/workflows/turbo.yml
- don't publish versions of the client bundle in PRs
- this causes 2 issues otherwise:
- earlier versions of the bundle can be cached in Cloudfront
- later PRs can overwrite published versions with old code
- will monitor change in Prod after deployment to ensure `Publish client bundle` is skipped
- no
=> don't publish client in non-main

.github/workflows/turbo.yml, highlight.io/components/MDXRemote/MarkdownList.tsx
Based on [slack thread](https://highlightcorp.slack.com/archives/C02N2AZS8BV/p1689260173138899), we've seen 
a number of errors for our project in highlight having an invalid stack trace when enhanced. The root cause
seems to be that our sourcemap uploader uploads the `.js` and `.map` files from the github actions build,
but the app is hosted from a different build done by render.com. Since the code differs in the inlined environment,
the sourcemap lines/columns do not match up resulting in incorrect stack traces.
Diffing the s3 sourcemap-uploaded index.js file against the prod app.highlight.run index.js
and comparing that to a local build with these changes.
No, will monitor future sourcemaps on errors in our project.
=> build frontend to be more similar to render

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/store/error_groups.go, backend/store/error_groups_test.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/ErrorsV2/ErrorInstances/ErrorInstancesTable.tsx
This PR uses the session's fingerprint as another fallback if email isn't available in the error instances listview.
Before:
After:
N/A
=> use fingerprint as fallback in the error instances view

frontend/src/pages/ErrorsV2/ErrorInstance/ErrorInstance.tsx
Moves Harold above the fold on the error instance view. Previously below User Details, now below the Instance Error Body.
[Slack request](https://highlightcorp.slack.com/archives/C01FJL7V630/p1689147405946569)
Before:
After:
N/A
=> move harold AI above the fold

backend/public-graph/graph/resolver.go
- even though the type definitions disallow it, `H.track` can be passed a string as the payload argument, which will then be expanded into an object with numeric fields and single character values
- tested `H.track` locally to confirm that:
1. a string payload argument was not saved as a field
2. for an object with numeric and non-numeric keys, the numeric ones are discarded
- after this is deployed, will:
1. run a sql script to delete the existing `session_fields` rows for fields with numeric names
2. reindex all sessions in opensearch
=> skip properties if the key is just a number

backend/private-graph/graph/resolver.go, backend/private-graph/graph/resolver_test.go
Recent auth changes mean that our session query would return an auth error even if the session is public.
Adds a check for sessions and errors to make sure both work for public sessions.
Viewing a public session locally.
Viewing a public error locally.
No
=> fix unlisted public session access

docs-content/getting-started/fullstack-frameworks/next-js.md, e2e/nextjs/README.md, e2e/nextjs/pages/_app.tsx, e2e/nextjs/src/app/layout.tsx
Wanted to clean up the next.js docs to make it a bit more concise, as it is the main
entrypoint for folks getting set up on next.js. We want to make it as bare-bones as possible
to avoid confusing folks (as is, there are three steps to instrumenting in the client, api fns, and serverless,
and it can get overwhelming where to start as an end user). Also, the warning about limitations
seemed a bit strong and discouraging, so I've refactored it to be in the relevant sections.
@deltaepsilon appreciate the work you did to build these docs. if there is anything you disagree with and think 
we should preserve, please comment!
[Vercel preview](https://highlight-landing-git-vadim-cleanup-nextjs-docs-highlight-run.vercel.app/docs/getting-started/fullstack-frameworks/next-js).
No
=> cleanup nextjs docs

frontend/src/pages/ErrorsV2/ErrorInstances/ErrorInstances.tsx, frontend/src/pages/ErrorsV2/ErrorInstances/ErrorInstancesTable.tsx
The error instances listview jumps when we are loading the page. This PR sets a min height on the listview to prevent the jumping. I tried figuring out a different solution that doesn't require a fixed value like this but nothing really seemed to do the job.
There is now a stable height on the loading and table view.
N/A
=> prevent jumping in viewport in the listview

frontend/src/pages/ErrorsV2/ErrorStackTrace/ErrorStackTrace.tsx
Just shipped an update to our exports detection for several common minified UMD module patterns. This means we should see errors like `module does not have named export` and `minified react error #130`(often caused by the entire module namespace being dumped into the default export, causing us to use an object as a jsx component instead of an actual component) much less often.
It also means we can remove the workaround we had in place for `react-collapsible` which uses a minified umd module format that will now get properly transformed into proper esm with named exports.
Click into error details page using react-collapsible, no longer crashes.
=> Revert workaround for minified umd package

.github/workflows/turbo.yml
Forks (#5950) are unable to run turborepo build because the doppler credentials are not accessible.
In forks, run the build without doppler (doesn't affect the frontend sourcemaps since they would not be uploaded in a fork)
CI
No
=> run js build in forks without doppler

frontend/src/pages/ErrorsV2/ErrorInstance/RelatedLogs.tsx, frontend/src/pages/ErrorsV2/ErrorInstance/RelatedSession.tsx, frontend/src/pages/ErrorsV2/ErrorInstance/SeeAllInstances.tsx
* Make Related Session/Logs more prominent
* Have "See all instances" use a tag instead of a button
Before:
After:
N/A
=> design feedback on error instance view

docs-content/getting-started/3_client-sdk/7_replay-configuration/recording-web-socket-events.md
Create documentation on how to enable and disable WebSocket recording.
View docs
https://highlight-landing-55rvsa4ib-highlight-run.vercel.app/docs/getting-started/client-sdk/replay-configuration/recording-web-socket-events
N/A
=> Create WebSocket recording documentation

frontend/src/components/Header/Header.tsx, highlight.io/components/common/Navbar/Navbar.module.scss, highlight.io/components/common/Navbar/Navbar.module.scss.d.ts, highlight.io/components/common/Navbar/Navbar.tsx
- launch week banners w/ dynamic link and text depending on day
- no
=> Add launch week banner to app and landing page

render/src/index.ts, render/src/render.ts
- screenshot lambda was failing because the events payload had a template expression in it
- escape backticks and dollar signs to prevent these issues
- added problem session to the tests - it failed before and succeeded after this change
- no
=> escape backtick and dollar signs in events string

frontend/src/components/Header/Header.tsx, highlight.io/components/common/Navbar/Navbar.tsx
- simplify launch week banner copy
- local click test
- no
=> edit launch week banner copy

frontend/src/pages/Player/Toolbar/DevToolsWindowV2/NetworkPage/NetworkPage.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/utils.ts
Fixes an issue where you couldn't access the `Network` tab in the dev tools when an `errorId` param was present in the URL. This triggered [a `useEffect` callback](https://github.com/highlight/highlight/blob/521c12ab2cede7c3d76ff8e54ca7e4bc9d16c90c/frontend/src/pages/Player/Toolbar/DevToolsWindowV2/NetworkPage/NetworkPage.tsx#L225-L230) which would set the active tab back to `Errors`.
Digging into this more, I realized this logic is just trying to select the error based on the `errorId` param on page load, but we also [handle that in `useSetPlayerTimestampFromSearchParam`](https://github.com/highlight/highlight/blob/521c12ab2cede7c3d76ff8e54ca7e4bc9d16c90c/frontend/src/pages/Player/PlayerHook/utils/index.tsx#L236-L267) so I was able to delete that callback entirely.
I click tested locally …
=> Fix broken network tab in session dev tools

packages/react-email-templates/package.json, packages/react-email-templates/tsup.config.ts
- lambda was exiting with an error about `require` being used, I think one of the dependencies doesn't support ESM? CJS build works successfully
- deployed lambda and tested
- no
=> use cjs build for email render

backend/lambda-functions/sessionInsights/handlers/handlers.go, backend/lambda-functions/sessionInsights/utils/utils.go, packages/react-email-templates/emails/session-insights.tsx, render/src/render.ts
- select distinct on fingerprint so we don't get multiple sessions for the same user
- use the middle chunk index for the screenshot (using chunk 0 / ts 0 often shows a loading state, not super aesthetic)
- email style fixes
- remove the 8px border from the screenshots
- deployed lambdas and tested
- no
=> email style fixes, get middle chunk for screenshot

render/package.json, render/src/activity.ts, render/tsup.config.ts
- given an events count array (e.g. "[1, 3, 6, 3, 2, 2, ...]"), return a base64 png for the activity graph, to be included in the email
- uses puppeteer to screenshot the SVG and save as a PNG, so I've included it in the `render` package and created a new lambda in AWS - the entry point for the lambda is `activity.handler`
- tested locally and viewed the output png:
- will add this to the session insights digest email, there's a placeholder rn
=> activity graph lambda

.github/workflows/backend.yml, backend/event-parse/parse.go, backend/hubspot/hubspot.go, backend/main.go, backend/private-graph/graph/resolver.go, backend/private-graph/graph/resolver_test.go, backend/public-graph/graph/resolver_test.go, backend/redis/utils.go, backend/store/error_groups.go, backend/store/main_test.go, backend/store/sessions.go, backend/store/sessions_test.go, backend/store/store.go, backend/worker/autoresolver_test.go, frontend/src/pages/Player/PlayerHook/PlayerHook.tsx, frontend/src/pages/Player/PlayerHook/PlayerState.ts, highlight.io/pages/_app.tsx
Improve performance of loading sessions.
On the frontend:
* parallelizes graphql operations responsible for loading parts of the session.
On the backend:
* improves performance of the backend queries loading parts of the session by avoiding concurrent session queries.
* ie. `GetSessionPayload` queries `errors` `rage_clicks` and `session_comments`, all of which make a db query to the `session`.
* this PR introduces a redis + LRU in-memory caching layer to the query so that multiple follow-up queries can reuse the database query result. 
Fixes a bug with hubspot that failed to create contacts because the redis locking logic would error on timeouts.
Local deploy and reflame preview for frontend.
Inspecting load times for `GetSessionPayload` (among other graphql operations responsible for …
=> improve performance of session loading

backend/store/error_groups.go, backend/store/error_groups_test.go, frontend/src/pages/ErrorsV2/ErrorInstances/ErrorInstances.tsx, frontend/src/pages/ErrorsV2/ErrorInstances/ErrorInstancesTable.tsx
Adjusts the logic for searching an error instance's email to use a case insensitive, wildcard search. 
This also highlights what part of the email matched.
_Note: this makes the query slower since it won't utilize an index but we opted for usability over performance ([slack](https://highlightcorp.slack.com/archives/C02N2AZS8BV/p1689273119805889?thread_ts=1689185062.220409&cid=C02N2AZS8BV))._
https://www.loom.com/share/3a22bac77fc6480c8ac5c3dc163d28b3
N/A
=> wildcard searching for email in error instances view

frontend/src/pages/ErrorsV2/ErrorInstance/ErrorInstance.tsx
This PR simplifies the loading state for loading the error instance data. I also added an error state if we fail to load the data (previously we just returned `null`).
Before:
After:
Error state
N/A
=> simplify loading state for the error instance page

frontend/src/pages/ErrorsV2/ErrorInstance/AiErrorSuggestion.tsx, frontend/src/pages/Player/RightPlayerPanel/components/SessionInsights/SessionInsights.tsx
Fixed issues mentioned here:
https://www.loom.com/share/c9c25313814548ee9f0cd312c478c8d8
Main issues I ran into involve LazyQuery, where after running LazyQuery once it behaves like useQuery. When the variables change it automatically refreshes. Added a state to check if the current error is the same error as the one AI Suggestions are requested for. 
Fixes https://github.com/highlight/highlight/issues/5947
=> Handle state switching for AI Suggestions

packages/react-email-templates/emails/session-insights.tsx, render/src/activity.ts
- remove the outer borders from each session in the template and use horizontal dividers instead
- add some properties to prevent outlook from expanding the table past its 400px width
- deployed and verified on outlook and other browsers
- no
=> fix session insights formatting for outlook

.github/workflows/e2e.yml
Runs Cypress against a static frontend build. Cypress is [notoriously slow loading assets from Vite](https://github.com/cypress-io/cypress/issues/22968) so we want to try running them against a static build so we only need to load a single file. We are hoping this drastically speeds up E2E test times.
**Before**
**After**
Running `yarn cy:run:chrome` locally and the CI step passing ✅
N/A
=> Run Cypress tests on a static frontend build

backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/components/Header/Header.module.css, frontend/src/components/Header/Header.tsx, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql
Show the maintenance banner based on a window stored in Postgres, so that
we can dynamically set the maintenance window without having to push code.
No
=> add a dynamic maintenance banner

.github/workflows/backend.yml, backend/errorgroups/embeddings.go, backend/model/model.go, backend/public-graph/graph/resolver.go, backend/store/error_groups.go, docker/compose.yml
* Sets up our postgres with [pgvector](https://github.com/pgvector/pgvector#docker) to store embeddings. In production, this will use the pgvector extension [available in aurora](https://aws.amazon.com/about-aws/whats-new/2023/07/amazon-aurora-postgresql-pgvector-vector-storage-similarity-search).
* Adds openai embeddings queries using the `AdaEmbeddingV2` model for each error object (gated for project 1).
* The embedding is generated based on the title and the stack trace of the error object.
* Stores embeddings for our project in batches.
Local deploy writing embeddings correctly.
Testing querying error groups locally. For example, the following query is trying to find error instances most similar to the one with title `"Uncaught Error: random error! 0.1871015092135686"`
```
with …
```
=> store error object embeddings

backend/clickhouse/logs.go, backend/queryparser/queryparser.go, backend/queryparser/queryparser_test.go, backend/store/error_groups.go
This PR extracts out the query parsing logic from logs. The intention here is that the syntax can be re-used easily without being tied to a specific table or database.
Furthermore, it becomes incredibly easier to write additional unit tests without a clickhouse dependency (see `queryparser_test.go`).
This was already heavily tested in `logs_test.go`. I added additional tests for sanity.
Confirmed searching for logs and error instances works as expected
N/A
=> Extract query parsing logic out of logs

sdk/highlight-next/package.json, sdk/highlight-node/package.json, sdk/highlight-node/src/client.ts
Capture possible otel `.forceFlush()` exceptions to avoid a `window.onunhandledrejection` error on timeouts.
See [discord](https://discord.com/channels/1026884757667188757/1124636931200929892) for context.
`yarn build:sdk`
New next/node package versions.
=> capture warning from otel flush

frontend/src/util/db.ts
Some users are running into issues with IndexedDb that may be caused by browser settings or limited storage. Add a killswitch that will not crash the app when IndexedDB fails to complete an action.
Error: https://app.highlight.io/1/errors/eN8JNCVob09aKNV1cSrtrqwcn0JJ?page=1&query=and%7C%7Cerror_state%2Cis%2COPEN%7C%7Cerror-field_timestamp%2Cbetween_date%2C2023-06-21T15%3A37%3A59.586Z_2023-07-21T15%3A37%3A59.586Z
Discord: https://discord.com/channels/1026884757667188757/1026884757667188763/1131149181298429972
TBD
Monitor errors
=> Add killswitch to indexDB

frontend/src/pages/LogsPage/LogsTable/LogDetails.tsx
When we try to parse a string as JSON on the frontend, we don't correctly iterate over the parsed result. This results in some undesirable frontend UX (see Before in test plan below).
Send a log request via curl
```
curl -X POST http://localhost:4318/v1/logs \
-H 'Content-Type: application/json' \
-d '{
"resourceLogs": [
{
"resource": {
"attributes": []
},
"scopeLogs": [
{
"scope": {},
"logRecords": [
{
"timeUnixNano": "'$(date +%s000000000)'",
"severityNumber": 9,
"severityText": "Info",
"name": "logA",
"body": {
"stringValue": "Hello, world! This is sent from a curl command."
},
"attributes": [
{
"key": "highlight.project_id",
"value": {
"stringValue": "1"
}
},
{
"key": "response.body",
"value": {
"stringValue": "{\"code\":0,\"message\":\"User email not found. Please use the email …
```
=> Handle escaped JSON in nested logs view

.github/workflows/deploy.yml, backend/lambda-functions/journeys/handlers/handlers.go, backend/lambda-functions/journeys/updateNormalnessScores/main.go
- adds a lambda for updating sessions' normalness scores in batches (runs for all processed and not excluded sessions without a score)
- after the last change to remove normalness scoring in the worker, re-processed sessions have a score of 0, so they will be re-scored by this job too
- originally wanted to do this in the worker outside of `processSession`, but looking at the logs, most processing batches have <10 sessions so the speedup won't be huge
- it's reasonably fast (depending on how large the input size is, the first was for about 2 hours worth of unscored sessions)
```
UPDATE 28202
Time: 101.153s (1 minute 41 seconds), executed in: 101.153s (1 minute 41 seconds)
UPDATE 274
Time: 10.094s (10 seconds), executed in: 10.094s (10 seconds)
```
- ran script in prod
- will create a step …
=> batch job for normalness scoring

.prettierignore, .prettierrc, .reflame.config.jsonc, frontend/scripts/update-reflame-environment.mjs
I've been working on a new feature to programmatically update the Reflame config based on the NPM package entry points that are actually used (sneak peak [here](https://github.com/lewisl9029/highlight/pull/15/commits/05c4b7f817aa60f73a580e3dd560de886b354af5)). Realized that we need to take over formatting duties for the config from individual projects' prettier configurations, or otherwise there will always be discrepancies between our programmatic updates and prettier output, leading to issues in CI. This PR formats the config according to our new standard and updates prettier configs to ignore it to prevent CI failures.
Prettier's handling of jsonc files was a bit of a hack anyways (it's actually treating it as json5, which can result in subtle bugs and inconsistencies), so this should …
=> Standardize Reflame config formatting

frontend/src/components/Header/Header.tsx, packages/ai/package.json, render/package.json
`aws update-lambda` would be showing a lot of unnecessary details in the build step.
Local `yarn workspace render publish`
No
=> hide lambda update output

.github/workflows/stale.yml
Setup a bot to mark external issues at stale after 30 days, and close than after another 5 days.
This bot will help focus our efforts as we improve efforts to triage our external tickets.
It will also help us with getting updates on issues that are waiting for customer input.
N/A
Will be checking in on the action / issues with the label.
=> add stale bot for external issues

sdk/highlight-cloudflare/package.json, sdk/highlight-next/package.json, sdk/highlight-node/package.json, sdk/highlight-node/src/sdk.test.ts, yarn.lock
Per 
https://github.com/contentlayerdev/contentlayer/issues/506
https://github.com/open-telemetry/opentelemetry-js/releases/tag/v1.15.1
https://github.com/open-telemetry/opentelemetry-js/pull/4016
opentelemetry has issues with running in ESM due to some incorrect imports.
See https://discord.com/channels/1026884757667188757/1132761273432539278 for more context.
This change bumps relevant versions to include the fixed opentelemetry SDKs.
CI
New node, next, cloudflare packages released.
=> update opentelemetry dependency to fix cjs error

backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/schemas.tsx
Update the Service model to have:
- github repo link so we can fetch when appropriate
- status incase the repo link causes errors
Adds a query to fetch services by project id
Adds a mutation to update the service object
Postman - send GraphQL requests to the new Service query and EditService mutation
https://www.loom.com/share/6d46202e8fc0494ca798a571b87754c9?sid=69238973-4045-411f-b0df-4db3873ce5ee
N/A
=> Update Service model with Github repo

backend/opensearch/opensearch.go, backend/private-graph/graph/schema.resolvers.go
- there are a lot of fields with numeric keys that were inadvertently created for certain projects
- while the job is running to delete these, filter out the numeric fields in the opensearch query so they won't be visible in the UI
- click tested locally before / after change
- no
=> filter number fields out of UI

backend/public-graph/graph/resolver.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/Alerts/AlertConfigurationCard/AlertConfigurationCard.tsx, frontend/src/pages/Player/MetadataPanel/MetadataPanel.tsx
Adds support for setting up a session property by user domain by auto-reporting on `H.identify` calls.
* ensure multiple alerts are processed even when one is skipped
* fix user properties alert input not showing in the frontend
* ensure only one notification is sent per alert per session
* auto reports a `domain` user property when a session is identified.
* shows `H.identify` user properties in the session metadata panel
https://www.loom.com/share/e5fb8b3cbf3c469fba9882a8fe013184
No
Closes #5708
=> improve user property alert

scripts/upload.ts
Only publish client builds on `main` branch pushes that contain a firstload package bump.
Local `yarn publish:client`
No
=> fixup! publish preview client versions (#6015)

sdk/highlight-apollo/CHANGELOG.md, sdk/highlight-apollo/package.json, sdk/highlight-cloudflare/package.json, sdk/highlight-nest/CHANGELOG.md, sdk/highlight-nest/package.json, sdk/highlight-next/package.json, sdk/highlight-node/package.json, yarn.lock
As reported on [discord](https://discord.com/channels/1026884757667188757/1133363145885372517), our sdks have some unneeded dependencies. ie: https://npmgraph.js.org/?q=%40highlight-run%2Fnest
E2E test.
New package versions released. Bumping all node-dependent versions to be the same.
=> cleanup sdk unused dependencies

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql
Editing a session alert was not loading webhook destinations, so the edit page
would not show any that were previously saved.
create, edit, save, reload alert page -> now showing webhooks
No
=> fix webhook endpoints not showing when editing session alerts

highlight.io/pages/pricing/index.tsx
Change the "hobby deployment process" link to the correct one.
=> Fix wrong hobby deployment link

frontend/src/pages/Player/RightPlayerPanel/components/NetworkResourcePanel/NetworkResourceInfo.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/NetworkPage/NetworkPage.tsx, frontend/src/pages/Player/helpers.ts
Some logic for displaying the status codes of network requests is out of sync. Create a helper method to help keep this logic in sync
Status code 0 causes confusion on the frontend. Replace the 0 status code with "Canceled" and mark as red
1. View a session with a non websocket, XML, or fetch request.
2. Click on a 200 request
3. Confirm the request matches in the right panel
N/A
=> Fix network request status codes

backend/worker/kafka_worker.go, backend/worker/worker.go
Increase the number of batched queue workers for the larger number of partitions.
Report the write delay for log rows.
Local backend deploy.
No
=> optimize ingest and report log ingest delay

.github/workflows/turbo.yml, cypress/e2e/umd.cy.js
After #6015, the e2e test was broken in main as it would be trying to reference a dev client version.
This PR makes the e2e test default to `undefined` (script version set by the firstload package.json) in main.
CI
No
=> fix e2e test on main

backend/otel/extract.go, backend/otel/extract_test.go, backend/otel/otel.go
This PR writes `service.version` to clickhouse (stored in the column from #6107). This is not currently queryable in the UI, it just writes to the DB. 
[Confirm](http://localhost:8123/play) no records with `ServiceVersion` populated:
```sql
select * from logs where ServiceVersion != ''
```
=> Returns 0 results
Send curl request with `service.version` populated
```
curl -X POST http://localhost:4318/v1/logs \
-H 'Content-Type: application/json' \
-d '{
"resourceLogs": [
{
"resource": {
"attributes": [
{
"key": "service.name",
"value": {
"stringValue": "my service"
}
},
{
"key": "service.version",
"value": {
"stringValue": "abc123"
}
}
]
},
"scopeLogs": [
{
"scope": {},
"logRecords": [
{
"timeUnixNano": "'$(date +%s000000000)'",
"severityNumber": 9,
"severityText": "Info",
"name": "logA", …
```
=> write service version to clickhouse

backend/kafka-queue/kafkaqueue.go, backend/worker/kafka_worker.go
With a lot of consumers, kafka gets into a rebalance loop where it takes longer to rebalance 
consumers than the rebalance timeout. As a result, no consumers can do work while the topic is rebalancing.
This value could be set higher, but it also means that when we scale consumers, we have a window
where no messages are processed. 30s seems like a reasonable time for that.
On the producer, not sure what the `ReadTimeout` means, but this may help with preventing
connection errors when we have high broker load.
N/A
Will monitor release.
=> improve kafka rebalance performance

backend/event-parse/parse.go, backend/model/model.go, backend/private-graph/graph/resolver.go, backend/public-graph/graph/resolver.go, backend/store/workspace_settings.go, deploy/public-worker-service.json
Adds a workspace setting for saving assets to make it easier to disable the setting when needed.
Configures the maximum asset size based on how much storage the ECS containers have.
Bumps the CPU and storage of the workers (cpu based on recent limits at the max partitions we have).
ECS configuration deployed manually.
Checking with debugger that settings would load correctly and assets would be saved.
No
=> make asset replacement a workspace setting

frontend/src/components/BarChart/BarChart.tsx
We want to start using our new UI tooltip on the Errors page. This includes updating the BarChart to use the new component.
This component is used on the:
- Error result card
- Error details
- Alert table
View each of the components in the app, and confirm the tooltip works properly:
1.  Error result card (`/1/errors`)
2. Error Details (Click on error on `/1/errors`)
3. Alert Table (`/1/alerts`)
N/A
=> Convert BarChart to use new tooltip

backend/otel/extract.go, backend/otel/extract_test.go, backend/otel/otel.go, sdk/highlight-go/otel.go
A regression was introduced in #6053 whereby backend errors were missing their stacktraces. This was due to the fact that we weren't plucking the data out ahead of time in the `extractFields` function.
Verified stacktrace (and other error data) is populated:
Verified we have a stacktrace with a new error in the UI:
N/A
=> fix writing a backend error stacktrace

backend/main.go, backend/otel/otel.go, backend/worker/kafka_worker.go
batched queue is behind in just one partition
seems like a bunch of health messages are queued up and potentially not getting processed.
this change also consolidates the default random partition key logic (calling `.Submit()` with partition key `""` will generate one).
Local backend deploy.
No
=> skip health check kafka messages

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, backend/store/services.go, backend/store/services_test.go, backend/store/sessions_test.go, frontend/src/graph/generated/schemas.tsx
We want to add pagination to services now instead of needing to come back later and add it
1) Create a services via PSQL
2) Update the `SERVICE_LIMIT` to a number less than the number of services you created (or create more than 10)
3) Open postman to hit the `services` query
4) Hit the query with no additional parameters
5) Use the `endCursor` value in the `after` param
6) Use the `startCursor` value in the `before` param
7) Test with a `query` param
https://www.loom.com/share/bbf5a62c3f744a4fad5a0dcaefec8b14?sid=5e7e0cd1-e76c-4f6e-a1ba-fcbb957fb01a
N/A
=> Add pagination and query to services

backend/http/logging.go
Firehose logs are not using the OTEL semantic key. As a result, we get an extra `service_name` when fetching keys because one is the "reserved key" (which needs to be renamed #6098) and one is from `LogAttributes`:
Should be extracted out per the work in #6053
N/A
=> fix semantic service name key for firehose logs

backend/otel/extract.go, backend/otel/extract_test.go, backend/otel/otel.go
A regression was introduced in #6121 such that metric values were being casted to a string and causing a panic.
Long term, we probably need to consider whether this `.(type)` syntax is actually safe to be using. It would be better to try and use builtin functions that return errors when we can't safely parse a value.
Confirmed that the panic does not occur when a new metric comes in.
N/A
=> fix panic when extracting metric value

packages/ui/src/components/DatePicker/PreviousDateRangePicker.tsx
When we added a timepicker in #5629, we didn't consider an edge case where by someone might try to choose a time without both the start/end date being selected.
Specifically, this line: https://github.com/highlight/highlight/pull/5629/files#diff-cbeeacd5af75faf0a293a5be799a26ed033c8232dbafe25e57f3713bd30bfb60R297
`selectedDates[1]` isn't valid since there is no end date chosen.
Here's a loom show how to reproduce the bug: https://www.loom.com/share/dca5353e88d74a1da9b88080deab9542
Confirmed that the timepicker cannot be clicked when an end date is not selected.
https://www.loom.com/share/22127f1f53324681bf896d756d22785e
=> disable timepicker unless both a start and end time are chosen

frontend/src/pages/Player/Toolbar/DevToolsWindowV2/NetworkPage/NetworkPage.tsx
Our GraphQL requests all return a `200` status. When the request has errors there is an `errors` key in the response body which we should be checking for and marking requests as failed that have that populated.
Confirmed [a failed request that wasn't being displayed as failed](https://app.highlight.io/1/sessions/cO4nEWf3booIJzbyXFDJhhMYr1ui?errorId=198180084&network-resource-id=32) was being displayed as failed in the PR preview.
**Before**
**After**
N/A
=> Fix handling of network resources with errors

.github/workflows/turbo.yml
Allow `turborepo` to cache more of the `monorepo` job by setting the `REACT_APP_COMMIT_SHA`
to a dummy value which does not affect the CI build anyway. Setting it to a dummy value allows
the sourcemap to stay correct wrt. the line/col numbers.
CI
No.
=> improve monorepo build time

docs-content/getting-started/3_client-sdk/7_replay-configuration/canvas.md, e2e/nextjs/pages/_app.tsx, e2e/nextjs/src/app/components/canvas.tsx, e2e/nextjs/src/app/layout.tsx, sdk/client/src/index.tsx, sdk/client/src/types/types.ts, sdk/firstload/src/index.tsx
WebGL canvas elements can be double buffered, meaning that the canvas bitmap is not in javascript memory
when we try to call `createImageBitmap`. If we hook into the webgl render loop of a given library to do the
snapshotting, we have access to the canvas as it is still in memory.
Adds a new manual snapshotting mode that exposes this functionality.
Adds new rrweb logic in https://github.com/highlight/rrweb/pull/108
Babylon.js canvas snapshotting correctly in manual mode.
New docs on [vercel preview](https://highlight-landing-ld05dz2bn-highlight-run.vercel.app/docs/getting-started/client-sdk/replay-configuration/canvas).
New highlight.run minor version.
=> support manual canvas snapshotting

backend/lambda-functions/deleteSessions/deleteSessionBatchFromOpenSearch/main.go, backend/lambda-functions/deleteSessions/deleteSessionBatchFromPostgres/main.go, backend/lambda-functions/deleteSessions/deleteSessionBatchFromS3/main.go, backend/lambda-functions/deleteSessions/getSessionIdsByQuery/main.go, backend/lambda-functions/deleteSessions/main.go, backend/lambda-functions/deleteSessions/sendEmail/main.go, backend/main.go, backend/model/model.go, backend/opensearch/opensearch.go, backend/otel/otel.go, backend/public-graph/graph/generated/generated.go, backend/public-graph/graph/model/models_gen.go, backend/public-graph/graph/resolver.go, backend/public-graph/graph/resolver_test.go, backend/public-graph/graph/schema.graphqls, e2e/go/README.md, e2e/go/fiber.go, sdk/highlight-go/highlight.go, sdk/highlight-go/otel.go
This PR demonstrates populating service name and service version onto error_groups/objects.
I also added `WithServiceName` and `WithServiceVersion` to our go SDK (so one doesn't have to use curl) via options to `Start`. 
https://www.loom.com/share/c73a4c3f58a74fb08a19faa1259329bb
I didn't mention it in the video but I also confirmed that we update open search correctly
We will hold off on making a new release of the Go SDK. When we are confident this is working correctly, we will create a new git tag for customers to use (tracked in #6149)
=> add service to backend errors

backend/kafka-queue/kafkaqueue.go, backend/kafka-queue/kafkaqueue_test.go, backend/main.go, backend/scripts/reset-kafka-offset/main.go, backend/worker/worker.go
- allow overriding for topic settings (`QueueCapacity` for now)
- don't set delete policy for all topics
- add outer span to differentiate between batched and datasync topics
- will clicktest locally to make sure the 3 topics are still working
- no
=> update kafka settings for datasync queue

backend/private-graph/graph/schema.resolvers.go
**Describe the bug**
A customer tried to ask Harold for help on an error that had a stacktrace > 27k characters (~9000 tokens). OpenAI returns an error when we use more than the `4097` token max. Frontend errors that use `MappedStackTrace` are more susceptible to this due to the enhancement of other lines and information.
**Proposed solution**
Limit the length from the stack trace to 5000 characters that are provided to AI
1) Found an error with a stack trace more than 5000 characters (`Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`)
2) Ask Harold for help
N/A
=> Limit Stacktrace to 5000 characters when querying OpenAI

backend/worker/worker.go
- `select * from session_fields where session_id in (...)` is doing a sequential scan with 1000 elements in the in clause, but an index scan if there are 500
- looked at query plans in prod postgres
- no
=> change flush size to 500 for session_fields lookup

backend/hubspot/hubspot.go, backend/worker/worker.go
hubspot tasks seem to be taking a long time, potentially because of a recent change
to be creating association requests from the account creation flow with the longer timeout.
this change reduces the timeouts and also reports the plan tier to hubspot
Local backend deploy with hubspot enabled
No
=> hubspot contact/company creation performance improvements

backend/worker/kafka_worker.go, backend/worker/worker.go
- fixes issue where top level span wasn't finished
- add more spans in the datasync flush function
- will monitor in prod after deploying
- no
=> add more spans for datasync queue tuning

backend/kafka-queue/kafkaqueue.go, backend/store/workspace_settings.go, backend/worker/worker.go
Adjusting the number of messages down to prevent max-ing out kafka network bandwidth.
CI
Monitoring message consumption.
=> tune kafka message consumption

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/ErrorsV2/ErrorInstance/ErrorInstance.tsx
This PR adds a Version field to the error instance view if defined via the SDK (see #6108).
When defined:
Note: the above pulls from the env var in doppler (see #6163). I also hardcoded a git sha to ensure it looks good (i.e. no line wrapping):
When not defined:
N/A
=> add version to error instance view

backend/clickhouse/sessions.go
- seeing panics when dereferencing nil fields in the datasync code that eventually causes all the datasync workers to die out
- weird that these fields are nil so I'll investigate more
- will monitor in prod
- no
=> catch possible nil dereferences

backend/kafka-queue/kafkaqueue.go, backend/main.go, backend/worker/worker.go
- use the `Async` setting for the datasync producer
- ensured messages were still being submitted / processed locally
- no
=> queue datasync messages async

.github/workflows/turbo.yml, cypress/pages/local.html, e2e/html/index.html, frontend/src/env.d.ts, frontend/src/index.tsx, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts, sdk/firstload/vite.config.ts, turbo.json
Was getting errors building next.js.
Switching to default file names (which @deltaepsilon also found was required for remix).
```
unhandledRejection Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/vkorolik/work/highlight/node_modules/highlight.run/dist/index.cjs.js from /Users/vkorolik/work/highlight/e2e/nextjs/node_modules/@highlight-run/next/dist/HighlightInit.js not supported.
index.cjs.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.cjs.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in …
```
=> use default esm file naming

backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver.go, backend/worker/kafka_worker.go, backend/worker/worker.go
- seeing clickhouse writes time out a few minutes after deployment
- remove datasync producer / consumer for now to see if it's affecting main queue performance
- made sure main/batched queues are still working locally
- no
=> remove datasync producer / consumer to test

e2e/html/index.html, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts
Unpkg does not like `.cjs` files because it does not treat them as browser-javascript.
See https://highlightcorp.slack.com/archives/C02N2AZS8BV/p1690917075492479 for full context.
Will be testing with the `e2e/html` unpkg script.
New firstload package version.
=> fix unpkg export

frontend/src/components/Histogram/Histogram.tsx, packages/ui/src/components/Tooltip/Tooltip.tsx, packages/ui/src/components/index.ts
The histogram component uses Recharts tool tips that cannot be replaced by our UI package `Tooltip`. We can replace the content with the UI package `TooltipContent` to standardize the designs of the tooltips used throughout the app.
1. View the sessions page.
2. Hover over the histogram below the Search results
3. View the errors page.
4. Hover over the histogram below the Search results
N/A
=> Standardize the Histogram tooltip

.github/workflows/deploy.yml, deploy/Dockerfile.prod.arm64
Sets the github deploy sha for backend services and lambdas such that the service version is correctly populated (#6108).
Unsure without actually just merging this and validating it's set in clickhouse (see linked ticket #6168). I just copied the existing pattern for setting this for the frontend deploy so I assume it'll just work.
N/A
=> ensure REACT_APP_COMMIT_SHA is set for backend services deploys

frontend/src/__generated/rr/rr.js, frontend/src/pages/SettingsRouter/SettingsRouter.tsx
Bug on Chrome. This is due to the showBanner context variable being set to true, and this is used for css classes, although banners are disabled on settings pages. 
https://www.loom.com/share/46023c7331c14f2694ca4c045fe5f3dc
Retried this interaction and saw no bottom bar.
=> Fix height calculation for settings pages

backend/redis/cache.go, backend/redis/utils.go, backend/store/workspace_settings_test.go
`redis.CachedEval` can't use the [local LRU cache](https://github.com/highlight/highlight/blob/32a1326ebbf152e713c4cb2c0d9c8f65084f656f/backend/redis/utils.go#L78-L81) because we would always be acquiring a lock.
Before
After
No
=> improve performance of redis.CachedEval

backend/private-graph/graph/resolver.go, backend/private-graph/graph/resolver_test.go
Our slack channel fetching code had a bug if a workspace had more than 1k channels.
We would infinitely loop fetching more channels rather than using the cursor.
Adds a test, locally tested with access key of customer that was affected.
No
=> fix getting slack channels

backend/clickhouse/logs.go, backend/clickhouse/logs_test.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/LogsPage/LogsTable/LogDetails.tsx, frontend/src/pages/LogsPage/LogsTable/LogsTable.tsx
Allows searching logs for a service's version via `service_version:version`. 
Per #6108, we are setting the service version on logs (via the Go SDK) via the `REACT_APP_COMMIT_SHA` env var. On dev using doppler (using `yarn dev:frontend` and `cd backend && make start`), this evaluates to `asdf`
Direct match works:
No match works as expected:
Wildcard works:
Note: there is a different bug on wildcard searches not highlighting correctly (#6162)
On prod, `REACT_APP_COMMIT_SHA`, evaluates to the deploy sha (see #6168). I confirmed this column is being populated:
=> allow service version to be queried via clickhouse

backend/model/model.go, backend/store/services.go, backend/store/services_test.go, backend/worker/kafka_worker.go
This PR creates a service record when we process a log along with `process.*` data ([docs](https://opentelemetry.io/docs/specs/otel/resource/semantic_conventions/process/#process-runtimes)). We plan to only use `process.name` on the frontend (to show a logo of the language) but we are storing all the data in case we need it later on.
Confirmed I have one service record:
N/A
=> create service record on log ingest

frontend/src/pages/Player/Toolbar/DevToolsWindowV2/DevToolsWindowV2.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/LogLevelFilter/LogLevelFilter.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/LogSourceFilter/LogSourceFilter.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/RequestStatusFilter/RequestStatusFilter.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/utils.ts
All users to select multiple levels and sources (soon to be services) on the log viewer of a session.
1. View a session
2. Click into the DevTools, and switch to the Console Logs tab
3. Click around with the Level and Source filters
N/A
=> Use multi select component on session log filters

backend/worker/worker.go
Flush for logs is taking about 8 seconds, and since there is only one flush worker per ECS container,
we are not keeping up with writing logs fast enough.
This change adds concurrent flush workers to increase number of concurrent writes to clickhouse.
Local deploy ingesting logs.
No
=> introduce concurrent flush workers for batched queues

backend/private-graph/graph/resolver_test.go, backend/public-graph/graph/resolver.go, backend/public-graph/graph/resolver_test.go, backend/redis/cache.go
- caches `MarkBackendSetupImpl` calls by projectId + type with an hour TTL
- fixes issue where `redis.ReleaseLock` would clear the cache key in redis
- tested w/ debugger locally, verified keys were present in Redis
- no
=> cache mark backend setup calls

backend/worker/kafka_worker.go, backend/worker/worker.go
Help increase the batched processing flush size to avoid clickhouse too many parts errors.
N/A
Monitoring for errors
=> adjust batched queue flushing

backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver.go, backend/worker/kafka_worker.go, backend/worker/worker.go
- reverts changes from #6184 now that the main queue is looking good
- no
=> unrevert session consumer / producer

docs-content/sdk/go.md, docs-content/sdk/python.md, highlight.io/components/QuickstartContent/backend/go/shared-snippets.tsx, highlight.io/components/QuickstartContent/backend/python/django.tsx, highlight.io/components/QuickstartContent/backend/python/flask.tsx, highlight.io/components/QuickstartContent/backend/python/shared-snippets.tsx, highlight.io/components/QuickstartContent/logging/go/fiber.tsx, highlight.io/components/QuickstartContent/logging/go/other.tsx, highlight.io/components/QuickstartContent/logging/python/loguru.tsx, sdk/highlight-py/CHANGELOG.md, sdk/highlight-py/README.md, sdk/highlight-py/e2e/highlight_django/highlight_django/settings.py, sdk/highlight-py/e2e/highlight_fastapi/main.py, sdk/highlight-py/e2e/highlight_flask/app.py, sdk/highlight-py/e2e/highlight_loguru/main.py, sdk/highlight-py/highlight_io/sdk.py, sdk/highlight-py/pyproject.toml
This adds support to the python SDK to specify service information (similar to what I did for Go, see #6108).
* Python docs added
* Go docs added
Run the e2e flask app locally (`cd sdk/highlight-py/e2e/highlight_flask && poetry run flask run`) and confirmed logs and errors have `service_name` and `service_version` set:
Lots of docs added ([preview](https://highlight-landing-e4l9h1yo9-highlight-run.vercel.app/docs/general/welcome)).
* Python SDK should create a new release (`0.5.4`) automatically when merged ([source](https://github.com/highlight/highlight/blob/cea182f3a79d8c34d946b46cd5109c34bbb262f1/.github/workflows/python.yml#L46-L52)). See [package](https://pypi.org/project/highlight-io/) on pypi. 
* Will manually create git tag for releasing a new Go SDK (bumping up to `v0.9.10` from …
=> Add service config to python SDK

backend/worker/worker.go
- rewound batched queue and it's slowly catching up, expecting doubling the batch size will speed things up
- will monitor in prod
- no
=> double batch size for batched queue

backend/worker/kafka_worker.go, backend/worker/worker.go
- flush logs should flush every ~10k log rows (ideal per the clickhouse docs)
- previously, it was using the Kafka batch size, but each Kafka message has multiple log rows, so there would be unread messages until the next flush
- now, loop and flush all messages until the message queue is empty
- tested locally to make sure log ingestion was working, will monitor in prod
- no
=> flush logs every ~10k log rows until local queue is empty

highlight.io/components/QuickstartContent/logging/python/loguru.tsx, sdk/highlight-py/CHANGELOG.md, sdk/highlight-py/README.md, sdk/highlight-py/e2e/highlight_loguru/main.py, sdk/highlight-py/highlight_io/sdk.py, sdk/highlight-py/pyproject.toml
Serialized logs sent through loguru don't look great. This PR fixes that.
`cd sdk/highlight-py/e2e/highlight_loguru && poetry run python main.py`
Confirmed extra attributes are serialized properly:
Bumped the python SDK version.
=> Handle serialized logs sent via loguru

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/schemas.tsx
`system_configuration` table on a new deploy would not be populated, causing the graphql route
to error. Fixes by initializing a default value for the table with no maintenance window. 
Local deploy returning the default value correctly.
No
=> fix fresh deploy showing errors about system configuration not found

sdk/highlight-go/highlight.go
- `gin`'s `context.Set` method only allows string keys, and we're currently casting our context keys to strings in our `gin` middleware, causing the `ctx.Value()` lookup to fail for keys with type `contextKey`
- this changes the `validateRequest` function to also check for the keys after casting to string
- tested locally on a basic `gin` app
- will tag a new release after deploying
=> also check for string keys in context

backend/event-parse/parse.go, backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/schemas.tsx
This adds the SessionInsight model, where each row has the generated insight and the corresponding sessionID. 
If a session already has insights generated, the cache is used and no OpenAI API call is made. 
In the future, we might want to allow people to regenerate the session insights, but this will depend on usage of this feature. 
Also includes refining the event filtering. Now we filter out all Snapshots, Jank, and Performance events when generating insights since these are more related to metrics compared to actual interactions and experience of the user. 
Also moved the API calls into a resolver function, so the main SessionInsight function just takes care of whether a session already has an insight in the db. 
Clicked through a few sessions and generated insights, and generating …
=> Store session insights generated by Harold

frontend/src/pages/ProjectSettings/ErrorFiltersForm/ErrorFiltersForm.tsx
The error filters form was showing an empty string for new workspaces:
Visual test
Nope
=> Removing empty 'string' from Error filters form on a new workspace

backend/hubspot/hubspot.go
Making some changes to the hubspot logic to ensure a more reliable contact -> company association.
1. Adding logging to figure out why associations sometimes are missing
2. Adding locking to make sure duplicate companies / contacts can't be created
3. Refactoring logic to avoid creating duplicate company from workspace creation flow and company attribute updates.
Will be monitoring in prod.
No.
=> improve hubspot association reliability

backend/private-graph/graph/resolver.go
This [error](https://app.highlight.io/1/errors/T3GCRNOe1l4Do9xD040upP9gHSnY?page=1&query=and%7C%7Cerror_state%2Cis%2COPEN%7C%7Cerror-field_timestamp%2Cbetween_date%2C2023-07-05T15%3A52%3A32.453Z_2023-08-04T15%3A52%3A32.453Z) isn't getting grouped (see #5896).
Error should be grouped.
N/A
=> normalize auth error

.github/workflows/ruby.yml, sdk/highlight-ruby/highlight/.rubocop.yml, sdk/highlight-ruby/highlight/Gemfile, sdk/highlight-ruby/highlight/Gemfile.lock, sdk/highlight-ruby/highlight/README.md, sdk/highlight-ruby/highlight/Rakefile, sdk/highlight-ruby/highlight/bin/console, sdk/highlight-ruby/highlight/highlight.gemspec, sdk/highlight-ruby/highlight/lib/highlight.rb, sdk/highlight-ruby/highlight/lib/highlight/version.rb, sdk/highlight-ruby/highlight/test/highlight_test.rb, sdk/highlight-ruby/highlight/test/test_helper.rb
This PR lints the ruby sdk using [rubocop](https://github.com/rubocop/rubocop) which is the ubiquitous ruby linter. 
I used `bundle exec rubocop -a` to autocorrect as much as possible. From there, I used manual correction on everything else (or disabled in `.rubocop.yml`). For things I wasn't sure on, I added an inline comment to ignore that specific check.
Since a lot of this PR is formatting, [remove](https://github.com/highlight/highlight/pull/6254/files?w=1) whitespace changes when reviewing.
Build passes
=> add lint step to ruby sdk

backend/jobs/log-alerts/log-alerts.go, frontend/src/pages/Alerts/LogAlert/LogAlertPage.tsx
- log alerts weren't firing for frequencies > 30 mins due to hardcoded values
- remove hardcoding
- limit log alert options to >= 15 seconds (below that, I'm not sure if we can run a clickhouse query fast enough; existing alerts < 15 seconds will trigger at 15 second intervals)
- avoid resetting the timer on deploys
- created a 30 second log alert, ran `make start-log-alerts-watch` locally, validated that it triggered every 30 seconds
- no
=> support new frequencies in log alerts

backend/clickhouse/migrations/000014_create_fields_table.down.sql, backend/clickhouse/migrations/000014_create_fields_table.up.sql, backend/clickhouse/sessions.go, backend/clickhouse/sessions_test.go, backend/migrations/cmd/backfill-sessions-clickhouse/main.go, backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver.go, backend/worker/kafka_worker.go, backend/worker/worker.go
- did some benchmarking, having a separate table is significantly faster for field searches on projects with lots of fields
- use async inserts for writing sessions / fields
- reenable datasync producers
- click tested locally + benchmarked w/ 30 days worth of data for a large project in prod
- if all is looking good, will backfill existing sessions (for the past month) by writing their ids to the datasync queue
=> write a separate fields table in Clickhouse

backend/alerts/integrations/webhook/webhook.go
We are having some reports of webhooks not behaving as expected for users. This PR adds some logging with details for successful webhook requests so we have some information to use for troubleshooting.
N/A - only adding some logging
=> Add logging for webhooks

backend/otel/extract.go, backend/otel/extract_test.go, backend/otel/syslog.go, backend/otel/syslog_test.go, sdk/highlight-go/otel.go
We are leaking public graph service name and version into customer's frontend logs. The reason this is happening is because our OTEL endpoint serves as the backend for client SDK (i.e. the client SDK calls pub.highlight.io).
We actually already have similar code that guarded against this for leaking our public graph's OTEL information:
https://github.com/highlight/highlight/blob/6268-public-graph-service-information-leaking/backend/otel/extract.go#L263-L265
https://github.com/highlight/highlight/blob/6268-public-graph-service-information-leaking/sdk/highlight-go/otel.go#L42-L48
But we didn't update this when we introduced the service notion. This is also the reason why we were having issues when writing a service record on ingest (see …
=> avoid writing service.* for frontend logs

.github/workflows/ruby.yml
Similar to our [python publish](https://github.com/highlight/highlight/blob/main/.github/workflows/python.yml#L46-L51) build step, this adds a workflow for automating publishing ruby gems.
One distinction is that `poetry` has a `--skip-existing` flag which means that it won't error if an existing package with the same version exists. From what I could tell `gem push` doesn't have a equivalent behavior ([docs](https://guides.rubygems.org/command-reference/#gem-push)). 
Before adding a guard for running only on main (`if: github.ref == 'refs/heads/main'`), I verified that publish complains about the existing version (see [build output](https://github.com/highlight/highlight/actions/runs/5800263362/job/15751530260)). 
I intend to update the version when adding a service config (#6229) and …
=> add a publish step for ruby sdk

backend/public-graph/graph/resolver.go, backend/redis/utils.go, backend/store/error_groups_test.go, backend/store/main_test.go, backend/store/project_filter_settings_test.go, backend/store/projects.go, backend/store/projects_test.go, backend/store/services_test.go, backend/store/sessions_test.go, backend/store/workspace_settings_test.go, backend/worker/autoresolver.go, backend/worker/kafka_worker.go
This PR caches `GetProject` with redis for faster lookups. Since projects don't typically change, I did set the expiration to one minute.
The motivation here is that I would like restore #6214 but that was doing many project lookups in a loop. Hence, adding caching will ensure we don't bottleneck that code path.
Additionally this fixes an issue whereby redis was not cleaning itself up on test runs (see the first failing build on this PR).
Tests pass
N/A
=> cache GetProject

backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, backend/store/services.go, frontend/src/graph/generated/schemas.tsx
Add the following fields to the `Service` table:
- BuildPrefix: path that code is moved to for deployment that is displayed on the error stacktrace
- GithubPrefix: path that is removed in deployment that is needed to fetch from GitHub appropriately
- LastSeenVersion: string representation of the version last seen in logs
- ErrorDetails: details around why a service may be in the error state
1) Test the `service` query in postman to return fields
2) Test the `editServiceGithubSettings` mutation in postman to edit fields
https://www.loom.com/share/0f9349c7cbfa46a79973c175e9a1a979?sid=c1c4ebf2-1567-487d-ade8-60c7145aac68
N/A - not being used
=> Add additional columns to Services

frontend/src/__generated/index.css, frontend/src/pages/Alerts/LogAlert/LogAlertPage.tsx, frontend/src/pages/LogsPage/LogsHistogram/LogsHistogram.css.ts, frontend/src/pages/LogsPage/SearchForm/SearchForm.tsx
- fix bug where search box wouldn't let you enter in more than one value
- move search box to top of page
- only rerender histogram when the search form submits (avoid rerendering while the user is actively typing)
- no
=> ui fixes on log alerts page

backend/private-graph/graph/resolver.go, frontend/src/pages/Player/Toolbar/NewCommentForm/NewCommentForm.tsx
There was some confusion in the "From session url", so update the comment slack message to:
- Move the CTA button to the bottom with primary styles
- Rename urls to make more clear
- Combine additional info with error/session info
More info: https://highlightcorp.slack.com/archives/C02N2AZS8BV/p1691511184945239
1. View a sesion
2. Comment and tag the #spencer-test slack channel
N/A
=> Improve comment slack message UI/UX

highlight.io/components/QuickstartContent/backend/ruby/shared-snippets.tsx, highlight.io/components/QuickstartContent/logging/ruby/other.tsx, highlight.io/components/QuickstartContent/logging/ruby/rails.tsx, sdk/highlight-ruby/e2e/rails/blog/config/initializers/highlight.rb, sdk/highlight-ruby/highlight/CHANGELOG.md, sdk/highlight-ruby/highlight/Gemfile.lock, sdk/highlight-ruby/highlight/lib/highlight.rb, sdk/highlight-ruby/highlight/lib/highlight/version.rb, sdk/highlight-ruby/highlight/test/highlight_test.rb
Adds service name and service version to ruby sdk.
The tests hit a live account which actually makes the testing easier.
```
bundle exec rake
```
Observe log ([permalink](https://app.highlight.io/1394/logs/MjAyMy0wOC0wOVQyMDowNjowNVosOWU1YzY1MDktNWMxZS00ZGJkLWIwNTMtZDE2MGQzZTM2MzQ0)).
Docs updated and bumped ruby version (should autodeploy now per #6269 but will verify on [rubygems](https://rubygems.org/gems/highlight_io) after this is merged).
=> add service information to ruby sdk

backend/redis/utils.go, backend/worker/worker.go
- not necessary for the current performance issues, but noticed that the worker had a consistently high heap live size due to `GetSessionData`
- instead of decoding all data, return encoded data, then decode per row so the decoded row can be garbage collected
- click tested locally to make sure session could be played back, wasn't corrupted
- no
=> decode single redis msg at a time

backend/hubspot/hubspot.go, backend/kafka-queue/kafkaqueue.go, backend/kafka-queue/kafkaqueue_test.go, backend/kafka-queue/types.go, backend/main.go, backend/otel/otel.go, backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver.go, backend/public-graph/graph/schema.resolvers.go, backend/redis/utils.go, backend/worker/kafka_worker.go, backend/worker/worker.go
* adds the ability to batch kafka message submission to break up larger kafka messages
* splits the bulk batched logs messages into individual small messages submitted in a batch
* reduce size of batched kafka messages by omitting empty keys
Local deploy processing logs correctly.
Updated kafka unit test.
Will monitor deploy.
=> batch submission of kafka messages

frontend/src/components/Header/Header.tsx, frontend/src/hooks/useDataTimeRange.ts, frontend/src/hooks/useFeatureFlag/useFeatureFlag.ts
Gates the analytics and dashboards pages to our project for now (and for a customer that wants to preview them).
Will be bringing the pages back in the future when we revamp the implementation.
any project
customer that still wants this page
No
=> gate analytics pages

backend/otel/extract.go, backend/otel/extract_test.go, backend/vercel/README.md, sdk/highlight-go/log/util.go, sdk/highlight-go/otel.go
This PR ensures that our public graph service information doesn't leak into a vercel log drain. The previous way of slicing this out was checking if this is a frontend log (#6273). However, that approach wasn't robust since vercel logs aren't necessarily a frontend log.
Instead, we blank out the resource data (use `StartTraceWithoutResourceAttributes` instead of `StartTrace`) at the start of the trace (instead of chopping it off at the OTEL processing side). This approach makes more sense given we understand very clearly that this was sent from a 3rd party. The same logic is applied for submitting a frontend console log (`SubmitFrontendConsoleMessages`) and for `SubmitHTTPLog`
This PR also fixes some bugs with how the vercel logs were being formatted. Here is the payload that vercel sends …
=> send a trace with blank resource attributes

frontend/src/util/graph.tsx
Digging into why logs results are sometimes incorrect and out of order, found that
the results from our `fetchMore` query are sometimes using stale variables and hence showing
previous results for a page incorrectly.
Reflame preview trying but unable to reproduce the behavior described [here](https://highlightcorp.slack.com/archives/C02N2AZS8BV/p1691471534516159).
No
=> update logs cache keys

frontend/src/pages/Player/PlayerHook/PlayerState.ts
https://www.notion.so/runhighlight/replayer-crash-max-call-stack-exceeded-f11f6c24098b430f80359588a45140d9
and this slack: https://highlightcorp.slack.com/archives/C02N2AZS8BV/p1691715318507679?thread_ts=1691686829.763469&cid=C02N2AZS8BV
Tested on customer account with many events (see slack link above).
=> ensure number of events passed to rrweb is bounded

backend/hubspot/hubspot.go, backend/hubspot/merge.go
Extends the hubspot doppelgangers reverse engineering for contact merging.
Locally running the hubspot merge operation; went from 900 duplicate contacts to 0
No, this is a one-off script that can be executed manually.
=> add hubspot deduplication for contacts

backend/kafka-queue/types.go, backend/worker/kafka_worker.go
* remove type deprecated in #6307 now that all batched messages have been processed
* update another optional message field to omit empty
Local deploy ingesting logs.
No
=> remove deprecated kafka logs type

backend/model/model.go, backend/public-graph/graph/resolver.go, backend/public-graph/graph/resolver_test.go
We're seeing that the embedding match is too precise at the static 0.1 threshold.
This PR allows setting the threshold based on a workspace setting.
Unit test
No
=> use a threshold setting for matching by embedding

backend/model/model.go, backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver.go, backend/public-graph/graph/resolver_test.go, backend/store/system_configuration.go, backend/store/system_configuration_test.go
Adds a column for global error filters for next.js noisy errors.
Unit test
No
=> add global error filters

frontend/src/components/NewIssueModal/NewIssueModal.tsx, frontend/src/pages/IntegrationsPage/IssueTrackerIntegrations.ts, frontend/src/pages/IntegrationsPage/components/ClickUpIntegration/ClickUpListSelector.tsx, frontend/src/pages/IntegrationsPage/components/GitHubIntegration/GitHubRepoSelector.tsx, frontend/src/pages/IntegrationsPage/components/HeightIntegration/HeightListSelector.tsx, frontend/src/pages/IntegrationsPage/components/LinearIntegration/LinearTeamSelector.tsx, frontend/src/pages/Player/Toolbar/NewCommentForm/NewCommentForm.tsx
- fixes #5699 
- toggles disabled state for integration forms on submit
- no
=> disable inputs on integration submit

frontend/src/graph/generated/hooks.tsx
A merge comment wasn't fixed in https://github.com/highlight/highlight/pull/6305, but not caught since it was within a comment and hidden in the GitHub view
N/A
N/A
=> Fix merge conflict comment in generated hooks

.github/workflows/deploy.yml, deploy/collector-task.json, deploy/otel-collector.yaml
Noticed that our OTEL collectors were killed by running OOM.
Percentage values in the configuration were incorrect because of how 
the container is calculating the memory available (for some reason 2x what it actually is).
Switching to the static values to make this more robust.
Forcing a deploy from this PR.
Monitoring new CloudWatch [alert](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#alarmsV2:alarm/OpenTelemetry+Receiver+Unhealthy?).
=> update opentelemetry collector memory configuration

frontend/src/__generated/index.css, frontend/src/__generated/ve/pages/Alerts/AlertConfigurationCard/styles.css.js, frontend/src/__generated/ve/pages/Alerts/ErrorAlert/styles.css.js, frontend/src/__generated/ve/pages/Alerts/LogAlert copy/styles.css.js, frontend/src/__generated/ve/pages/Alerts/components/AlertNotifyForm/styles.css.js, frontend/src/pages/Alerts/Alerts.module.css, frontend/src/pages/Alerts/Alerts.tsx, frontend/src/pages/Alerts/AlertsRouter.tsx, frontend/src/pages/Alerts/EditAlertsPage.tsx, frontend/src/pages/Alerts/ErrorAlert/ErrorAlertPage.tsx, frontend/src/pages/Alerts/ErrorAlert/styles.css.ts, frontend/src/pages/Alerts/NewAlertPage.tsx, frontend/src/pages/Alerts/components/AlertNotifyForm/AlertNotifyForm.tsx, frontend/src/pages/Alerts/components/AlertNotifyForm/styles.css.ts, frontend/src/pages/Alerts/utils/AlertsUtils.ts
Work towards: https://github.com/highlight/highlight/issues/6077
Updated the components and ui for the Error alerts creation to match the redesign, matching the Log alert creation page. Currently the model for alerts is similar for error and other alerts, so they're all fetch with a single hook `GetAlertsPagePayload`. With 3 main types of alert being planned, I think it might make sense to separate the files, with ErrorAlertPage calling all the ErrorAlert mutations, and a future SessionAlertPage calling all SessionAlert mutations. 
The new Error alert page differs from the Figma redesign in a few ways: 
- The old error alert page does not have a `query` input field, it's not on the error alert data model either. Unsure what this would be. 
- The old error alert page does not have data for …
=> Implement redesign for error alert page

backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go, frontend/src/components/NewIssueModal/NewIssueModal.tsx
- load error group frequencies only when necessary
- issue submit button should use loading state instead of disabled
- click tested locally, validated frequency graphs were displaying
- no
=> remove frequency lookup from common code

docs-content/general/4_company/our-competitors.md, docs-content/getting-started/1_overview.md, docs-content/getting-started/backend-logging/2_js/1_overview.md
Updates logging docs.
[Vercel preview](https://highlight-landing-git-6351-add-pino-to-bac-bcbef3-highlight-run.vercel.app/docs/getting-started/backend-logging/js/overview).
No.
=> add pino to backend logging overview docs

backend/kafka-queue/kafkaqueue.go
Now that the datasync consumer is working well, make the noisy kafka stats logging debug only.
Builds
No
=> remove noisy kafka log

frontend/src/pages/Player/PlayerPage.tsx
The session player can get stuck in an infinite loading state sometimes when trying to view a session that is outside a project's billing quota. This simplifies the logic for determining whether the session should be shown vs an empty state and resolves this issue. It also prevents the loading state from being displayed after we have a session and know that it is excluded.
Local + PR preview click test. Here is [a session to click test with](https://app.highlight.io/7689/sessions/vpzADDKcO5l86X0ECOejKuNRcR1m).
N/A - client-side change only.
=> Fix infinite loading on excluded sessions

frontend/src/components/QueryBuilder/QueryBuilder.tsx, frontend/src/pages/FrontPlugin/components/HighlightSessions.tsx, frontend/src/pages/Player/SessionLevelBar/SessionLevelBarV2.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionQueryBuilder/SessionQueryBuilder.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionsFeedV3.tsx, frontend/src/pages/Setup/IntegrationBar.tsx
- add a `highlight-session-search-use-clickhouse` local storage flag - when set to true, will use clickhouse for sessions / field searching
- set flag and verified locally
- no
=> enable toggling clickhouse for sessions search frontend

backend/hubspot/hubspot.go, backend/hubspot/merge.go, backend/main.go, backend/model/pricing.go, backend/pricing/pricing.go, backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver.go, backend/public-graph/graph/resolver_test.go, backend/public-graph/graph/schema.resolvers.go, backend/redis/utils.go, backend/worker/kafka_worker.go, backend/worker/worker.go
Report a bunch of new hubspot fields.
* is_session_replay_integrated
* is_backend_error_monitoring_integrated
* is_backend_logging_integrated
* sessions_overage - number of sessions over the limit in the billing period
* errors_overage - number of errors over the limit in the billing period
* logs_overage - number of logs over the limit in the billing period
* discount
* product - subscription name
* price - subscription price, for non usage-based accounts
Local deploy enabling hubspot.
Creating fields in hubspot.
=> add new hubspot company fields

backend/hubspot/hubspot.go, backend/public-graph/graph/resolver.go
Fixes hubspot and error group related panics.
No
=> fix hubspot processing panic

backend/clickhouse/sessions.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/Sessions/SessionsFeedV3/SessionsFeedV3.tsx
- use clickhouse date aggregation functions to generate a histogram
- refactor inner sql generation into a separate function, used by both sessions search and histogram
- no, it's guarded by local storage var `highlight-session-search-use-clickhouse`
=> use clickhouse for sessions histogram

backend/embeddings/embeddings.go, backend/model/model.go, backend/public-graph/graph/resolver.go, backend/public-graph/graph/resolver_test.go
Switches our OpenAI embeddings usage to a self-hosted huggingface gte-large model.
Starts writing the new vectors and using them to group errors.
Locally grouping errors using new vectors.
Hosted model inference may be slower, but this is only for our project for now. Will monitor.
=> support huggingface hosted model

backend/otel/otel.go, backend/otel/otel_test.go, backend/otel/samples/fs.json, backend/otel/samples/nextjs.json
Recent changes in the otel ingest code caused us to drop next.js errors
because next.js reported spans would have the highlight project reported as a resource attribute.
New unit test.
Manually ingesting next.js app directory error.
No
=> fix next app directory error capture

frontend/src/pages/Player/PlayerHook/utils/index.tsx
We have a `tsAbs` param which allows people to link to a specific point in a session. Sometimes we have a formatted timestamp in that param (`tsAbs=2023-01-01-12:00:00`) and others it's a raw millisecond value (`tsAbs=1234567890`). The client sets formatted strings and [our Slack alerts set it in milliseconds](https://github.com/highlight/highlight/blob/main/backend/worker/worker.go/#L1007).
I confirmed I can repro the error accessing sessions from a rage click alert and that it _does_ work when I open the same link in a PR preview.
N/A
=> Handle milliseconds in tsAbs param

frontend/src/__generated/index.css, frontend/src/__generated/ve/components/TableList/TableList.css.js, frontend/src/components/TableList/TableList.css.ts, frontend/src/components/TableList/TableList.tsx, frontend/src/pages/LogsPage/LogsTable/LogDetails.tsx
1. Change alignItems `center` to `flex-start` in TableList.css.ts and LogDetails.tsx
2. Add `keyDisplayValue` styles for padding 
Closes #6023
=> fix: change alignItems center to flex-start

backend/jobs/log-alerts/log-alerts.go, backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go, backend/worker/worker.go
* fixes hubspot association submitting to kafka asynchronously
* fixes workerpool function submits that would be using an old context asynchronously that could be cancelled
Local backend deploy.
Monitoring for hubspot error logs.
=> fix workerpool using old context

sdk/highlight-apollo/package.json, sdk/highlight-nest/package.json, sdk/highlight-next/package.json, sdk/highlight-node/CHANGELOG.md, sdk/highlight-node/package.json, sdk/highlight-node/src/hooks.ts
Serialize node.js console method arguments.
This makes sure that a node.js call like `console.log('hey', {hello: 'world'})` will be correctly recorded.
See [discord](https://discord.com/channels/1026884757667188757/1139191530091974718) for customer report.
Local e2e nextjs app recording `console.log('whoa there', {hello: 'world'})`
New JS sdk versions released.
=> update node.js console recording for arguments

backend/clickhouse/sessions.go, backend/private-graph/graph/schema.resolvers.go, frontend/src/components/QueryBuilder/QueryBuilder.tsx, frontend/src/pages/FrontPlugin/components/HighlightSessions.tsx, frontend/src/pages/Player/SessionLevelBar/SessionLevelBarV2.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionQueryBuilder/SessionQueryBuilder.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionsFeedV3.tsx, frontend/src/pages/Setup/IntegrationBar.tsx
- active length filtering was excluding live sessions
- add "OR NOT Processed"
- click tested locally to make sure live sessions were showing up in the feed
- no
=> fix ch query for live sessions

sdk/client/src/listeners/network-listener/utils/xhr-listener.ts, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts
As reported in [discord](https://discord.com/channels/1026884757667188757/1052834249868324895/1138879337639186635),
some browsers do not have the `response.text` method available.
Local deploy correctly recording XHR requests.
New firstload version released.
=> make xhr listener compatible with older browsers

frontend/src/pages/Player/RightPlayerPanel/components/NetworkResourcePanel/NetworkResourceLogs.tsx
Fixes an issue where we weren't ever getting into the loading state when viewing logs for a network resource.
https://www.loom.com/share/e7f2e2c3b7dd4f219527ab180d0c41b8
N/A - client-side only change.
=> Fix logs loading state in network resource panel

frontend/src/pages/LogsPage/LogsTable/LogDetails.tsx
Fixes an error we were seeing when we have a wildcard filter applied that matches log attributes containing integer values (e.g. `code.lineno:*08`).
Local and PR preview click test.
Reproduce the error in prod: https://app.highlight.io/1/logs?query=code.lineno%3A%2A01
See issue fixed in PR preview: https://preview.highlight.io/1/logs?query=code.lineno%3A%2A01
N/A
=> Fix handling of integers in nested log attributes

backend/clickhouse/clickhouse.go, backend/worker/worker.go
Increase the number of connections per [slack](https://highlightcorp.slack.com/archives/C04NLEQMGF6/p1692854899861889).
Since we have 32+32+1 goroutines per ecs container writing to clickhouse, we need this to be a higher value.
clickhouse writing locally
Monitoring clickhouse write performance.
=> increase number of clickhouse connections

backend/private-graph/graph/resolver.go, backend/public-graph/graph/resolver.go, frontend/src/pages/ErrorTags/FindSimilarErrors.tsx
Paired with @deltaepsilon to improve the quality of the error-tags embeddings matching.
* l2 distance appears to work better than cosine distance for this model
* ensures only similar errors from our project are matched
* reduce the number of duplicate similar errors shown
* scores similar errors by similarity
Local deploy error-tags page
No
=> improve embedding grouping quality

backend/clickhouse/clickhouse.go, backend/clickhouse/traces.go, backend/worker/kafka_worker.go, backend/worker/worker.go
Traces still flushing slowly, with the bottleneck being the clickhouse write.
Trying to increase the flush count in lieu of having more concurrent writes.
Traces writing locally
No
=> optimize trace flushing

backend/clickhouse/trace_row.go, backend/clickhouse/traces.go, backend/model/model.go, backend/store/system_configuration.go, backend/store/workspace_settings.go, backend/worker/kafka_worker.go, backend/worker/worker.go
Reduce trace writing batch size and make the number of workers programmatic. 
Local deploy writing traces.
No
=> programmatic number of trace workers

backend/clickhouse/logs.go, backend/clickhouse/logs_test.go
Fixes an issue where multiple filters applied on log attributes weren't filtering on all the attributes. The problem was that we were using an `OR` clause on all the log attribute filters. I changed this to an `AND`, but it introduces a regression in the existing behavior which supported applying multiple filters on the same key and applying them as an `OR`. I commented out a test flexing logic to support that use case and we should discuss if we truly want to support it.
Local click test + updated tests.
Should be a fairly straightforward change, but should keep an eye on query performance for logs.
=> Use AND instead of OR for log attribute filters

frontend/src/pages/Player/components/EventStreamV2/EventStreamV2.tsx, frontend/src/pages/Player/components/EventStreamV2/StreamEventV2/StreamEventV2.tsx, frontend/src/pages/Player/context/PlayerUIContext.ts, frontend/src/routers/ProjectRouter/ProjectRouter.tsx
1. Added `activeEventIndex` and `setActiveEventIndex` in PlayerUIContext
2. Used `initialTopMostItemIndex` prop of react-virtuoso library. Checkout this prop in [API reference](https://virtuoso.dev/virtuoso-api-reference/)
3. Added `IconSolidArrowCircleRight` as per design and `onClick` Handler
4. Added `searchItem` and `setSearchItem` to preserve search state
/claim #6277 
closes #6277 
https://github.com/highlight/highlight/assets/39362422/2df4e9c3-0730-4ffe-a580-20c8c963592f
=> feat: preserve scroll position when go back to events list

backend/main.go, backend/util/tracer.go
Prints a log on every request to the private graph to help with
demoing the network logs association panel.
For every private graph request, we now have a log line printed and correctly associated.
No
=> write logs on every request in private graph and demo landing page app

sdk/client/src/index.tsx, sdk/client/src/listeners/error-listener.tsx, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts
We noticed that we get browser-side errors like [this](https://app.highlight.io/1/errors/uIzopzx1FAGMCkXv0SxeoGwcK1f0?page=2&query=and%7C%7Cerror_state%2Cis%2COPEN%7C%7Cerror-field_timestamp%2Cbetween_date%2C2023-07-26T18%3A05%3A17.091Z_2023-08-25T18%3A05%3A17.091Z) recorded without a stacktrace.
The stacktrace is sent from the client as `[]` because we had fallen back to that value when the
stacktrace parsing library would error. 
That library should only error when a stack trace of `null` or `undefined` was passed in,
so we should take care of cases where that could be happening. Otherwise, we should
be explicit about raising the error about a custom-passed stacktrace.
New highlight.run version released.
=> ensure stacktraces from promises are recorded correctly

backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/store/services.go, frontend/src/graph/generated/schemas.tsx
We thought tracking this might be useful for debugging but instead decided against it.
Confirmed services table still loads as expected.
Will manually drop the column on prod.
=> deprecate LastSeenVersion from services table

backend/otel/extract.go, backend/otel/otel.go, backend/otel/otel_test.go, backend/otel/samples/external.json, backend/util/environment.go
We've recently noticed that we have a bunch of errors for the highlight project
that seem to come from old code versions of highlight / do not have a service name associated.
We've traced this down to hobby deployments that are shipping phonehome data to our
cloud project as project 1, which means we record their errors (some of which are expected for a hobby deploy).
[This](https://app.highlight.io/1/errors/wvqgJG0ULiZ09vToq4wbnn2xH0Rb) is an example.
To filter them out, we can assume that for our production cloud deploy, all errors routed to project 1
will always be coming from one of our services, so we should check that the service name is defined.
New unit test.
No
=> drop errors from external hobby deployments

backend/clickhouse/logs.go, backend/clickhouse/sessions.go, backend/clickhouse/traces.go, backend/kafka-queue/kafkaqueue.go, backend/main.go, backend/model/model.go, backend/worker/kafka_worker.go, backend/worker/worker.go
With #6430, we found that async inserts were actually hindering out trace writing
because the async write flush was happening too frequently (only writing about 1MB/s).
It seemed impossible to configure the async flush settings with clickhouse cloud to write
the async batches with a larger batch and less frequently.
This PR moves away from async inserts for some of the clickhouse writes
and allows customizing the flush behavior programmatically per topic.
* Cleanup logic for batched flush workers across topics.
* Add programmatic flush parameters for all queues.
* Disable async inserts for logs writes.
Local backend deploy.
local performance is great writing 2 million logs in ~ 1 minute with just the 1 dev backend instance
for posterity, testing with `ab -k -f TLS1.2 -s 180 -t 600 -n …
=> consolidate duplicate kafka worker code

backend/private-graph/graph/schema.resolvers.go, backend/store/issues.go, backend/store/issues_test.go
The GitHub API is return 422 validation errors when we try to create an issue for an error with longer than 256 characters.
Update the API to take the first 200 characters of the proposed title, and keep them as the title. Move the rest of the characters to the description.
Create an issue from Highlight on an error with > 200 characters
https://www.loom.com/share/756699290db747088da287798a30872e?sid=676521f4-e499-4f14-af16-bf82549b136f
N/A
=> Fix long GitHub issue titles

backend/store/stacktraces.go
Since merging in https://github.com/highlight/highlight/pull/6458, our services have flipped to an error state with a dereferencing pointer message
Catch this case and log it, so we have more information on debugging this edge case
Not able to repro pointer error as errors still get enhanced properly locally
N/A
=> Fix error - Catch and log empty content from stack trace enhancement

backend/public-graph/graph/generated/generated.go, backend/public-graph/graph/schema.graphqls, backend/public-graph/graph/schema.resolvers.go
Make `serviceName` an optional parameter in the public graphql endpoint when initializing a session
Able to process sessions
N/A
=> Fix graphql validation of service name

sdk/highlight-go/log/util.go
Multiple vercel log drains can be created and we need to distinguish them (e.g. this vercel project sent X number of logs). This PR includes the vercel project id in the service name.
Used the test log drain feature and verified that a service is created with the project id included
Note: the test log drain doesn't use a real project id. 
* We should verify the project id looks good for non test log drains
* We should clean up vercel log drains services without project ids in our prod db
=> include project id in the service name for vercel log drains

frontend/src/components/TimeRangePicker/TimeRangePicker.tsx, frontend/src/hooks/useFeatureFlag/useFeatureFlag.ts
Per a thread with a customer, this changes enables the analytics page.
This also changes the analytics date picker to use a 7 day range by default,
which makes more sense given the data shown.
[Preview](https://frontend-pr-6474.onrender.com/9637/analytics)
No
=> enable analytics page for a certain workspace

backend/store/stacktraces.go
When we updated the StackTraces to iterate through more than the first 5 files, our `continue` condition only exited the inner loop, but really needed to continue though the outer loop
1. Set a break point in the GitHub fetch method, and ensure this is not fired when the file is a Golang package
Reset the Highlight services to start enhancing from GitHub again
=> Fix stacktraces interation

backend/redis/utils.go, backend/store/services.go, backend/store/services_test.go, backend/worker/kafka_worker.go
When we create a new service during ingestion (#6328), we aren't handling updates to `process.*` information. This is important because a lot of SDKs aren't currently including that information (#6465) and when they do start including it, we should update the existing service records.
This PR changes the logic to upsert that data.
Tests added
=> handle service updates during otel ingestion

backend/public-graph/graph/resolver.go, backend/public-graph/graph/resolver_test.go
This PR ensures that when using service name in the client config (#6453), a service is autocreated.
Ran a react app locally with this config:
```js
H.init('1xdn0e03', {
backendUrl: 'https://localhost:8082/public',
serviceName: 'my-frontend-app',
tracingOrigins: true,
networkRecording: {
enabled: true,
recordHeadersAndBody: true,
},
});
```
and confirmed a new service was created for my project:
=> autocreate frontend service

.github/workflows/turbo.yml, docs-content/getting-started/fullstack-frameworks/next-js.md, docs-content/getting-started/fullstack-frameworks/remix.md, docs-content/sdk/nextjs.md, e2e/nextjs/README.md, e2e/nextjs/highlight.config.ts, e2e/nextjs/instrumentation.ts, e2e/nextjs/src/app/layout.tsx, e2e/nextjs/src/app/utils/highlight.config.ts, e2e/remix/README.md, e2e/remix/app/entry.server.tsx, e2e/remix/app/root.tsx, e2e/remix/package.json, highlight.io/components/QuickstartContent/frontend/next.tsx, highlight.io/components/QuickstartContent/frontend/remix.tsx, highlight.io/highlight.config.ts, sdk/highlight-next/CHANGELOG.md, sdk/highlight-next/package.json, sdk/highlight-next/src/util/withHighlightConfig.ts, sdk/highlight-node/src/client.test.ts, sdk/highlight-node/src/client.ts, sdk/highlight-remix/CHANGELOG.md, sdk/highlight-remix/package.json
Allows service name to be set for nextjs and remix backends. Note: the frontend could already set this since `<HighlightInit />` uses `H.init` under the hood.
Using the nextjs e2e app (`yarn run e2e:nextjs`), confirmed NextJS errors have a service name attached:
Using the remix e2e app (`yarn run e2e:remix`), confirmed Remix errors have a service name attached:
Bumped versions for the remix and nextjs sdks
=> add service name to nextjs and remix

e2e/nextjs/package.json
The dependencies are not hoisted into the root level of the node modules, causing Vercel to error out when looking for the first none highlight workspace dependencie (e.g. `@next/env`). Update the hoistingLimits to include dependencies.
1) Vercel build passes
2) Able to deploy Next E2E app
N/A
=> Test vercel deployment

backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/public-graph/graph/resolver.go, backend/store/stacktraces.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/ProjectSettings/ProjectSettings.tsx
We are going to rollout the GitHub stacktrace enhancements for everyone, so remove the feature flag
1) The services page (`/1/settings/services`) can be viewed
2) Backend errors are enhanced
Keep an eye on services to update the system config's `IgnoredFiles`
=> Remove feature flag for github enhancement

backend/otel/extract.go, backend/otel/extract_test.go, backend/otel/otel.go, sdk/highlight-node/src/client.ts
Fix panic from log line when fields extraction would fail.
New unit test.
No
=> fix panic when ingesting otel data without a project

backend/kafka-queue/aws.go, backend/kafka-queue/kafkaqueue.go
Turns out that we've had the ability to have our consumers prefer the nearest broker 
since we have been on [kafka 2.4 ](https://cwiki.apache.org/confluence/display/KAFKA/KIP-392%3A+Allow+consumers+to+fetch+from+closest+replica), but we have not been using the feature.
This change is based on segment io tickets https://github.com/segmentio/kafka-go/issues/415 and https://github.com/segmentio/kafka-go/issues/984 which describe a way to provide the AZ name to the client
to have the consumer groups prefer the nearest rack (avoiding cross-az traffic). 
Local deploy continues to work.
Testing the ECS rack preference is challenging locally, but should be safe to rollback with no data loss (we might just have a small delay in ingesting data).
Will be monitoring the release. Only readers should …
=> prefer nearby brokers to avoid cross-az kafka network traffic

backend/alerts/alerts.go, backend/alerts/integrations/discord/messages.go, backend/alerts/integrations/discord/messages_test.go, backend/alerts/integrations/integrations.go, backend/model/model.go, backend/public-graph/graph/resolver.go, backend/worker/worker.go
Some errors will not have sessions associated with them since they are not recorded. Update the Slack, Discord, and Email alerts to handle this case.
**Slack**
**Discord**
**Email**
1. Add integrations for Slack and Discord
2. Create an Error alert with the following attributes (feel free to update with your channels/email):
a. Slack channel: #chris-errors-test
b. Discord channel: #spencer-test-alerts
c. Email: spencer@highlight.io
d. Alert threshold: 1
e. Alert frequency: 30 seconds
3. Kick off an error
3. In the `H.init` in `frontend/src/index.tsx` set `options.disableSessionRecording = true` to disable recording
5. Restart your frontend
6. Kick off an error again
N/A
=> Improve error alerts with no sessions

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/store/stacktraces.go, frontend/src/components/LinkButton/index.tsx, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/ErrorsV2/ErrorInstance/ErrorInstance.tsx, frontend/src/pages/ErrorsV2/ErrorSourcePreview/ErrorSourcePreview.tsx, frontend/src/pages/ErrorsV2/ErrorStackTrace/ErrorStackTrace.tsx
Improve the UI of the stacktraces when enhanced with GitHub to:
- show user stacktrace was enhanced with GitHub
- show version used to enhance GitHub
- Add link to file in GitHub
Next steps:
- documentation
- call out for setting up GitHub enhanced stacktraces
https://www.loom.com/share/06acd075d9304ee0b3972f83be8d54fb?sid=dae2f570-740a-46e3-8d53-6cfd2aa2c6b9
N/A
No - https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=11353-341142&mode=design&t=asncmzI0KAT02ukl-0
=> Improve GitHubstacktrace enhancement UI

backend/main.go, docker/.env, docker/compose.hobby.yml
This PR solves #6538, therefore it also solves one of the prerequisites for #6545
Locally. The changes provided by this PR are easy to verify.
If the variable isn't defined or if it is empty, the code will proceed just as before and either use `http://collector:4318` on Docker Compose environments, or `http://localhost:4318` everywhere else.  
Hence, no adjustments are needed for pre-existing installations.
No
=> feat: solve #6538 by fetching for the new OTLP_ENDPOINT env-variable

frontend/src/components/CommandBar/CommandBar.tsx, frontend/src/components/CommandBar/context.tsx
The command bar is not currently rendering results once you start typing in the input. This is happening because we aren't subscribing to state changes on the form values that drive the results, which is fixed in this PR.
N/A
Nope!
=> Fix commandbar not showing typeahead results

frontend/src/pages/ErrorsV2/ErrorStackTrace/ErrorStackTrace.tsx
UI component tooltip swap causes the function and line number to render on different lines
See https://app.highlight.io/1/sessions/HojiAyriw9l4eE7Q7JWPowdlKswl?commentId=12451&page=1&query=and%7C%7Ccustom_processed%2Cis%2Ctrue%7C%7Ccustom_created_at%2Cbetween_date%2C2023-08-08T20%3A00%3A05.339Z_2023-09-07T20%3A00%3A05.339Z&ts=3.478
1. View an error that has not been enhanced
N/A
N/A
=> Fix stacktrace tooltip

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/store/error_groups.go, backend/store/error_groups_test.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/ErrorsV2/ErrorInstances/ErrorInstancesTable.tsx
Some errors on the instances page have a session attached, but they are not playable. Check the `excluded` value on the session to conditionally render the link
1) View an error with instances in which there it is not playable (can update an `errorObject` in Postgres by setting `excluded = true`
N/A
=> Improve experience of viewing an error without sessions

backend/hubspot/hubspot.go, backend/worker/kafka_worker.go
* Remove locking since all hubspot tasks are processed serially (same partition key).
* Remove retry logic here since the tasks are retried at the kafka level.
* Add redis caching to slow hubspot requests (`getContact` and `getCompany`)
hubspot tasks are slow with a bunch of retries to fetching contacts
setting invalid hubspot ids locally, then checking they are reset 
turned into
No
No
=> remove hubspot retry looping

backend/hubspot/hubspot.go
Hubspot polls on association waiting for contact / company to be created and times out after 3 minutes.
However, this error is non-recoverable (since all the hubspot tasks are under the same partition, they happen serially).
If the contact cannot be found, something else happened earlier that caused the creation to fail on our end,
so there isn't a point to poll.
local
No
No
=> remove polling on association creation

frontend/src/pages/Alerts/ErrorAlert/ErrorAlertPage.tsx, frontend/src/pages/Alerts/LogAlert/LogAlertPage.tsx, frontend/src/pages/Billing/UpdatePlanPage.tsx, frontend/src/pages/ErrorTags/ErrorTags.tsx
Some more bugs were discovered after the Ariakit upgrade.
* The billing form wasn't updating when selecting different retention periods. This was happening because we weren't subscribing to updates to the values in the form. I updated a few places where we use `formStore.getState()` to `formStore.useState()`, which will create a subscription to the store values and rerender the component every time it updates.
* The error tags page was showing an error boundary. This was happening because a `Form.Input` did not have a containing `Form` component.
N/A
N/A
=> [hotfix] Billing page controls and error tags not working

backend/util/tracer.go
Getting a panic from a recent change to log private graph requests.
https://app.highlight.io/1/errors/MSQYy41pUCXpJREijV0zfWRmkAFv
N/A
N/A
no
=> fix private graph request panic

backend/kafka-queue/aws.go
Our rack naming from the AWS ECS metadata endpoint would return an `AvailabilityZone` value of  `us-east-2c`
However, AWS MSK sets the `broker.rack` to availability zone IDs, like `use2-az3`.
```bash
[ec2-user@ip-YYY bin]$ ./kafka-configs.sh --broker 1 --all --describe --bootstrap-server XXX.amazonaws.com:9096 --command-config client.properties | grep rack
broker.rack=use2-az3 sensitive=false synonyms={STATIC_BROKER_CONFIG:broker.rack=use2-az3}
```
N/A
Will monitor deploy and then the network transfer costs in ECS
No
=> update kafka rack names

experiments/performance/package.json, package.json, sdk/client/package.json, sdk/highlight-apollo/package.json, sdk/highlight-nest/package.json, sdk/highlight-next/package.json, sdk/highlight-node/package.json, sdk/highlight-react/package.json, sourcemap-uploader/package.json
Our npm packages had inconsistent `license` values that differed from the repo `LICENCE.md`
N/A
N/A
N/A
=> update license of npm packages based on repo license

frontend/src/pages/Alerts/ErrorAlert/ErrorAlertPage.tsx, frontend/src/pages/Alerts/LogAlert/LogAlertPage.tsx, frontend/src/pages/Alerts/SessionAlert/SessionAlertPage.tsx, frontend/src/pages/Alerts/components/AlertTitleField/AlertTitleField.tsx, frontend/src/pages/Auth/AdminForm.tsx, frontend/src/pages/Auth/InviteTeam.tsx, frontend/src/pages/Auth/JoinWorkspace.tsx, frontend/src/pages/Auth/MultiFactor.tsx, frontend/src/pages/Auth/ResetPassword.tsx, frontend/src/pages/Auth/SignIn.tsx, frontend/src/pages/Auth/SignUp.tsx, frontend/src/pages/ErrorsV2/ErrorInstances/ErrorInstances.tsx, frontend/src/pages/Player/Toolbar/NewCommentForm/NewCommentForm.tsx, frontend/src/pages/Player/components/EventStreamV2/EventStreamV2.tsx, frontend/src/pages/Setup/SetupRouter/AlertsSetup.tsx, packages/ui/src/__generated/ve/components/HStack/styles.css.js, packages/ui/src/components/ComboboxSelect/ComboboxSelect.tsx, packages/ui/src/components/Form/Form.tsx, packages/ui/src/components/SwitchButton/SwitchButton.tsx
Many of our forms were using `getState` to access form store values and reference them in the UI or `onSubmit` hooks. However, these values often weren't updating the UI as expected and were still empty when we attempt to access them in our submit handlers because we were pulling them from a stale copy of the form state.
This PR updates all the places we used `formStore.getState` and makes sure we are using `useValue` and `useState` wherever we are trying to access values from the store/state in our UI or submit logic.
Local click test. You can jump to this page in a preview by going to `/invite_team` and repro the error in prod if you're logged in at https://app.highlight.io/invite_team.
N/A - client-side only change.
Nope!
=> [hotfix] Forms using getState to access values incorrectly

frontend/src/pages/LogsPage/LogsTable/LogDetails.tsx, frontend/src/pages/LogsPage/utils.ts
Fixes two issues in logs search:
1. The matching attribute wasn't being surfaced when a log line is not expanded.
2. The matched portion of the attribute value was not being highlighted because our matching logic on the client was case-sensitive while our backend logic was not.
Here is a before & after of click testing https://app.highlight.io/1/logs?end_date=2023-08-15T05%3A00%3A00.000Z&query=testing&start_date=2023-08-12T05%3A00%3A00.000Z.
**Before**
**After**
N/A - client-side only change.
Nope!
=> Fix matching attribute highlight in logs

backend/public-graph/graph/resolver.go, backend/store/workspaces.go, backend/store/workspaces_test.go
Append session properties is processing slowly for a customer who's app seems to send
many consecutive `AddSessionProperties` messages into the same partition.
Adding some additional tracing here and using the store for project / workspace queries.
Local deploy processing visited url correctly.
Monitoring new traces.
No
=> additional tracing for slow append session properties

docs-content/getting-started/fullstack-frameworks/next-js.md
Sourcemaps versioning is not necessary in next.js as the js files are hashed by default.
With the automated sourcemap uploading, adding versioning by default is confusing
since our guide does not instruct to pass the same version string (which may not be easy to get)
to the frontend `<HighlightInit>` component.
Removes the following blurb:
```
// Make sure to implement `nextConfig.generateBuildId` so that our source map uploader can version your source maps correctly
const nextBuildId = require('next-build-id')
generateBuildId: () => nextBuildId({ dir: __dirname }),
```
[See intercom report](https://app.intercom.com/a/inbox/gm6369ty/inbox/shared/all/conversation/41392?view=List).
Vercel preview.
No
No
=> remove versioning for next js sourcemaps

backend/integrations/github/github.go, backend/private-graph/graph/resolver.go, backend/store/stacktraces.go
Every time we enhance an error, we make a request to GitHub to get the owner's username, even though it isn't used. Move this request out of the installation request, and cache this value for a day since it should never change.
1) Create an issue locally with GitHub
2) View a newly created backend error and confirm it is still enhanced
N/A
N/A
=> Optimize GitHub requests

backend/clickhouse/sessions.go, frontend/src/components/QueryBuilder/QueryBuilder.tsx, frontend/src/pages/ErrorsV2/ErrorQueryBuilder/ErrorQueryBuilder.tsx
Errors will start coming in with an associated service, and we want to allow users to filter by this service name/
1) Navigate to the errors page
2) Add a new filter
3) Click on the service filter
4) Select an option
https://www.loom.com/share/Errors-unknown-column-servicename-13-September-2023-6270eed6ece14fe59f08bf94c07b4b2b?sid=a746ac6f-ebc3-456f-a65b-672b6bf78471
N/A
N/A
=> Allow filter errors by service for Clickhouse

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/store/error_groups.go, backend/store/error_groups_test.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/ErrorsV2/ErrorInstances/ErrorInstancesTable.tsx
This PR updates the error instances table to fetch the version off of the error object instead of the session. 
Previously, backend only errors wouldn't have a version visible because they lacked a session. Per #6108, backend errors write their version to the error object and per #6453, frontend errors write the version onto the error object (in addition to the session).
* Run the go fiber e2e app ([README](https://github.com/highlight/highlight/blob/6446-ensure-error-instances-table-uses-error_object-version/e2e/go/README.md))
* Confirmed error instances table has the version shown
* Simulated a frontend error from the buttons page
* Confirmed version is visible
=> update error instances table to fetch version off of error object

sdk/highlight-apollo/CHANGELOG.md, sdk/highlight-apollo/package.json, sdk/highlight-nest/CHANGELOG.md, sdk/highlight-nest/package.json, sdk/highlight-next/CHANGELOG.md, sdk/highlight-next/package.json, sdk/highlight-node/CHANGELOG.md, sdk/highlight-node/package.json, sdk/highlight-node/src/hooks.test.ts, sdk/highlight-node/src/hooks.ts, sdk/highlight-remix/CHANGELOG.md, sdk/highlight-remix/package.json, sdk/pino/CHANGELOG.md, sdk/pino/package.json
We've received a report that our node sdk would not serialize `BigInteger` messages correctly.
Relates to existing discord report.
New unit test
No
No
=> correctly serialize node console messages

frontend/src/components/QueryBuilder/QueryBuilder.tsx, frontend/src/pages/ErrorsV2/ErrorFeedHistogram/ErrorFeedHistogram.tsx, frontend/src/pages/ErrorsV2/ErrorMetrics/ErrorDistributions.tsx, frontend/src/pages/ErrorsV2/ErrorMetrics/ErrorMetrics.tsx, frontend/src/pages/ErrorsV2/ErrorsV2.tsx, frontend/src/pages/ErrorsV2/SearchPanel/SearchPanel.tsx, frontend/src/pages/Player/RightPlayerPanel/components/ErrorDetails/ErrorDetails.tsx, frontend/src/pages/Player/RightPlayerPanel/components/NetworkResourcePanel/NetworkResourceErrors.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionQueryBuilder/SessionQueryBuilder.tsx, frontend/src/pages/Setup/IntegrationBar.tsx
- error data is backfilled - want to roll this out over the next few days, start by turning on clickhouse for all highlight admins
- `highlight-session-search-use-clickhouse-v2` was still being referenced for the field types query, remove this
- testing in preview environment
- no, should only affect Highlight admins and can revert if there are issues
- no
=> enable clickhouse errors for highlight admins

docker/compose.yml
Noticed that our kafka docker setup did not use persistent storage, which
would result in docker restarts breaking the docker cluster (because the volumes
would have some internal state that was incorrectly persisted).
Local `./start-infra.sh` - stack running healthy.
e2e test
No
No
=> use persistant storage for kafka

frontend/src/__generated/index.css, frontend/src/__generated/ve/components/CreateAlertButton/style.css.js, frontend/src/components/CreateAlertButton/CreateAlertButton.tsx, frontend/src/components/CreateAlertButton/style.css.ts, frontend/src/pages/ErrorsV2/ErrorsV2.tsx, frontend/src/pages/Player/SessionLevelBar/SessionLevelBarV2.tsx
Adds new buttons to link to creating alerts from the sessions and errors pages.
[Reflame preview on our project](https://preview.highlight.io/1/errors/VBdaIpZpjLHI4iewzsz7LlTAeEav?page=1&query=and%7C%7Cerror_state%2Cis%2COPEN%7C%7Cerror-field_timestamp%2Cbetween_date%2C2023-08-15T23%3A06%3A38.376Z_2023-09-14T23%3A06%3A38.376Z&%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201HAAZ1WSXSX97PNTR2QMG1MCK%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%226078-turn-on-error-session-alerts-from-the-errors-sessions-pages%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D).
[Reflame …
=> add alert creation buttons to sessions and errors

backend/clickhouse/log_row.go, backend/clickhouse/logs.go
- tune the histogram query by:
- removing ordering
- avoiding the nested select
- reducing the number of function calls per row
- grouping on one column instead of two, and avoiding grouping on the string column
- seeing speedup on a 1 day query in prod from about ~30s execution time to ~7s
- generated the 30 day query and ran in prod
```
SELECT intDiv(48 * (toRelativeSecondNum(Timestamp) - 1692199700), (1694791700 - 1692199700)) * 8 + SeverityNumber, count() FROM logs WHERE ProjectId = 1 AND Timestamp <= '2023-09-15 11:28:20' AND Timestamp >= '2023-08-16 11:28:20' GROUP BY 1
```
Took 32s, read 5B rows / 61GB
It's unlikely to get much better performance without either increasing the number of threads (which could have an impact when many of these queries are running …
=> perf tuning for logs histogram query

backend/otel/extract.go, sdk/highlight-go/otel.go, sdk/highlight-go/tracer.go
* Uses the exception message for logs that are [produced from an error](https://github.com/highlight/highlight/blob/4d5e658dc3094badb9e722d73f64e5b9adce61d9/backend/otel/otel.go#L237-L248)
* Ensures our traces does not report duplicate errors / graphql schema errors from `InterceptResponse` as `InterceptField` already captures meaningful graph errors
No
No
=> adjust where tracer records error spans

frontend/src/pages/Player/PlayerPage.tsx
Loading state would sometimes be blurred before if the session was loading.
[reflame preview](https://preview.highlight.io/1/sessions/hRIgH0DgjDvHfOoVx8ye2giXg7Rq?page=1&query=and%7C%7Ccustom_processed%2Cis%2Ctrue%7C%7Ccustom_created_at%2Cbetween_date%2C2023-08-17T00%3A00%3A42.024Z_2023-09-16T00%3A00%3A42.024Z&%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201HADMHEHBVYYWASD8586QKXBW%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22vadim%2Ffix-player-loading-blur%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D)
https://www.loom.com/share/5a86094a72254136bfa1c3c64347428b
No
No
=> only blur player when player ready

backend/alerts/alerts.go, backend/alerts/integrations/discord/messages.go, backend/alerts/integrations/discord/messages_test.go, backend/alerts/integrations/integrations.go, backend/model/model.go, backend/public-graph/graph/resolver.go, backend/worker/worker.go, frontend/src/index.tsx
If an error occurs at the start of the session, we are displaying that the session is excluded because there were no user events at the time of the error. However, the user can continue the session, leading to a session being linked on the error page UI.
Update the logic to check if the session has been processed, as well as excluded. This is the case when the user sets `disableSessionRecording`.
1) Load an page with an error occurring on load
2) Set `options.disableSessionRecording = true`
3) Load an page with an error occurring on load
https://www.loom.com/share/Improve-error-alerts-with-no-sessions-by-SpennyNDaJets-Pull-Request-6532-highlig-ba3822796fb54c509ad10e163ef87acd?sid=e2427a4f-809d-4aa0-9ff9-14c119c0e992
N/A
N/A
=> Fix error alerts for errors in newly started sessions

frontend/src/pages/ProjectSettings/AutoresolveStaleErrorsForm/AutoresolveStaleErrorsForm.tsx, frontend/src/pages/ProjectSettings/FilterExtensionForm/FilterExtensionForm.tsx
This resolves an issue with states being improperly updated for `Extension Error Filtering` and `Auto-Resolve Stale Errors` inside the project settings page.
Related Issue: #6631 
Tested locally and on a self deployed version of highlight
None, just frontend logic changes
No
=> Resolves issue with error monitoring inputs

frontend/src/pages/Alerts/LogAlert/LogAlertPage.tsx, yarn.lock
This resolves an issue when defining a log alert query. When a user inputs a log query the value was being set into a local variable to update the histogram but was not updating the formStore that was being used to populate the mutation input variables. This PR should resolve this issue and allow for query to be sent along to the mutation.
Related Issue: #6630 
Test both locally and in self deployed version
None, purely frontend changes
No
=> Fixes log alert query not saving

highlight.io/components/QuickstartContent/frontend/sveltekit.tsx
Per a customer email, we've learned that sveltekit may generate relative CSS paths
for stylesheets which are not always valid (relying on some weird browser path behavior
to load correctly). This adds a note to the SvelteKit docs about disabling relative paths.
[Vercel preview](https://highlight-landing-du7eloxoc-highlight-run.vercel.app/docs/getting-started/client-sdk/sveltekit).
No
No
=> update sveltekit docs for relative paths

backend/clickhouse/querybuilder.go, frontend/src/pages/ErrorsV2/ErrorFeedHistogram/ErrorFeedHistogram.tsx, frontend/src/pages/ErrorsV2/ErrorMetrics/ErrorDistributions.tsx, frontend/src/pages/ErrorsV2/ErrorMetrics/ErrorMetrics.tsx, frontend/src/pages/ErrorsV2/ErrorsV2.tsx, frontend/src/pages/ErrorsV2/SearchPanel/SearchPanel.tsx, frontend/src/pages/Player/RightPlayerPanel/components/ErrorDetails/ErrorDetails.tsx, frontend/src/pages/Player/RightPlayerPanel/components/NetworkResourcePanel/NetworkResourceErrors.tsx, frontend/src/pages/Setup/IntegrationBar.tsx
- backend fix for query breaking when no `error_group` conditions applied
- remove local storage flag, enable clickhouse errors for all projects
- no, can revert if there are issues
- no
=> enable clickhouse errors for all projects

frontend/src/components/Header/Header.tsx, frontend/src/components/TableList/TableList.tsx, frontend/src/pages/Alerts/AlertConfigurationCard/SlackLoadOrConnect.tsx, frontend/src/pages/Buttons/Buttons.tsx, frontend/src/pages/ErrorTags/ErrorTagsContainer.tsx, frontend/src/pages/ErrorTags/ErrorTagsSearch.tsx, frontend/src/pages/Player/MetadataPanel/MetadataPanel.tsx, frontend/src/pages/Player/RightPlayerPanel/components/SessionInsights/SessionInsights.tsx, frontend/src/pages/Player/RightPlayerPanel/components/WebSocketMessages/WebSocketMessages.tsx, frontend/src/pages/Player/SessionLevelBar/SessionLevelBarV2.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ConsolePage/ConsolePage.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ErrorsPage/ErrorsPage.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/NetworkPage/NetworkPage.tsx, frontend/src/pages/Player/Toolbar/TimelineIndicators/TimelineIndicatorsBarGraph/TimelineIndicatorsBarGraph.tsx, frontend/src/pages/Player/components/EventStreamV2/EventStreamV2.tsx, packages/ui/src/components/Box/Box.tsx, packages/ui/src/components/Button/Button.tsx, packages/ui/src/components/Tag/Tag.tsx
closes #6521 
* Added className in Omit<T,K> key of BoxProps. This enables type errors on the use of the className prop
* Manually replaced all instances of className props used in Box component with cssClass, modified the contents to an array of ClassValue where clsx used
* Local `npm run build:frontend` passed successfully
* Verified a few instances on local build. No visual changes were noticed
* A full render test for checking all instances is required
=> fix: Prevent className prop to Box component #6521

backend/private-graph/graph/schema.resolvers.go, frontend/src/pages/Alerts/LogAlert/LogAlertPage.tsx
- query was selecting an arbitrary alert in the project rather than by id
- refetching `GetLogAlert` after deletion was returning an error as the alert doesn't exist anymore
- fixes #6620 
- no
- no
=> fix log alert delete

backend/clickhouse/clickhouse.go
The old string replacement path could result in a double slash being prepended to the folder location for the clickhouse migrations folder. The new solution utilizes filepath join to cleanly build the path,
Deployed locally using docker
=> fix: resolves issue with string replacement for migrations folder

highlight.io/components/QuickstartContent/self-host/self-host.tsx
I noticed, that the [Hobby deployment guide](https://www.highlight.io/docs/getting-started/self-host/self-hosted-hobby-guide) had a minor mistake (without any consequences, should be purely cosmetic), and showed the env-variable `REACT_APP_FRONTEND_URI=https://your-ip-address:3000` twice in Step 3.
**Before:**
**After:**
No, this is just a single line of text in a multi-line string removed on the frontend.
=> docs: fix the duplicate env-variable in the self-hosting guide

highlight.io/components/QuickstartContent/self-host/dev-deploy.tsx
1. Change order of sub steps in `(Optional) Running in different terminals` step of https://www.highlight.io/docs/getting-started/self-host/dev-deployment-guide.
frontend depends on backend and backend depends on infra
=> fix: change order of sub steps in dev deploy optional step

frontend/src/components/CreateAlertButton/CreateAlertButton.tsx, highlight.io/components/Home/CalendlyPopover.tsx
Carries over utm params from our site to the calendly widget.
clicking
no
=> Adds utm params to calendly widget

frontend/src/pages/Alerts/LogAlert/LogAlertPage.tsx
- show validation message + red highlighting on submit if query is empty
- no
- no
=> show validation error for empty query in log alerts page

frontend/src/pages/Alerts/ErrorAlert/ErrorAlertPage.tsx, frontend/src/pages/Alerts/LogAlert/LogAlertPage.tsx, frontend/src/pages/Alerts/SessionAlert/SessionAlertPage.tsx, frontend/src/pages/Alerts/components/AlertNotifyForm/AlertNotifyForm.tsx, frontend/src/pages/Alerts/utils/AlertsUtils.ts
Any value on the alert form that uses the select component is missing the initial state when configuring a form
1) Create a new session, log, and error alert - adding values to the select components
2) When editing the alert, the correct information is displayed as an initial value
https://www.loom.com/share/2a355d8a5ea84a4e8c1f4e20cc246d0d?sid=6b7edd38-7212-4487-a5f1-d83492e7b380
N/A
N/A
=> Fix alert form initial state

highlight.io/components/QuickstartContent/logging/hosting/render.tsx
Logo was rendering incorrectly due to a broken path.
No
No
=> update setup page render logo

.github/workflows/ruby.yml
Our main branch is failing the ruby check because
the publish command does not like that we are republishing existing versions.
This makes sure that the github action will pass even if the publish fails (because the version exists).
The downside of the change is that an actual new version bump that fails to publish for another reason
will not be obvious, but it seems like a proper solution would require migrating to 
Github Action
No
No
=> ignore ruby republish error

backend/clickhouse/querybuilder.go, frontend/src/pages/ErrorsV2/ErrorFeedHistogram/ErrorFeedHistogram.tsx, frontend/src/pages/ErrorsV2/SearchPanel/SearchPanel.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionsFeedV3.tsx
- length filter should be multiplied by 1000, max value should be treated as infinity
- parse as float because "advanced mode" passes in float values
- fetch results and histogram using 'network-only' to skip cache
- fixes #6647 
- no
- no
=> fix length filter, skip cache for sessions/errors query/histogram

backend/redis/utils.go, backend/store/stacktraces_test.go
The `github-rate-limit-exceeded-%s` key is being set indefinitely, causing errors to never be enhanced when the rate limit is hit. Default this time to one hour
Test code logic in sandbox
Monitor rate limits hit
N/A
=> Default Github rate limit hit cache to 1 hour

backend/clickhouse/logs.go, backend/clickhouse/query.go, backend/clickhouse/traces.go, backend/event-parse/parse.go, backend/hubspot/hubspot.go, backend/pricing/pricing.go, backend/private-graph/graph/middleware.go, backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver.go, backend/public-graph/graph/schema.resolvers.go, backend/redis/utils.go, backend/util/tracer-graphql.go, backend/util/tracer.go, backend/worker/kafka_worker.go, backend/worker/worker.go, docker/otel-collector.hobby.yaml, docker/otel-collector.yaml, frontend/src/pages/Traces/TracesList.tsx, packages/ui/src/components/Callout/Callout.tsx, packages/ui/src/components/Form/Form.tsx
We are currently sending traces to Datadog for all of our manual tracing, but we want to start sending these to Highlight as well, and ultimately phase out DD for traces. This PR adds some new utility methods that can be used as alternatives to where we call `tracer.*`. All method calls to create spans will also send spans to Highlight.
Local click test. Can't test in PR preview because of the backend changes.
Here is some data from my local machine showing traces coming into Clickhouse:
We should ensure that all tracing information is landing in both places by checking Clickhouse + the DD UI.
N/A
=> Send traces to Highlight + Datadog

sdk/highlight-apollo/CHANGELOG.md, sdk/highlight-apollo/package.json, sdk/highlight-go/otel.go, sdk/highlight-java/highlight-sdk/src/main/java/io/highlight/sdk/HighlightOpenTelemetry.java, sdk/highlight-java/pom.xml, sdk/highlight-nest/CHANGELOG.md, sdk/highlight-nest/package.json, sdk/highlight-next/CHANGELOG.md, sdk/highlight-next/package.json, sdk/highlight-node/CHANGELOG.md, sdk/highlight-node/package.json, sdk/highlight-node/src/client.ts, sdk/highlight-py/CHANGELOG.md, sdk/highlight-py/highlight_io/sdk.py, sdk/highlight-py/pyproject.toml, sdk/highlight-remix/CHANGELOG.md, sdk/highlight-remix/package.json, sdk/highlight-ruby/highlight/CHANGELOG.md, sdk/highlight-ruby/highlight/Gemfile.lock, sdk/highlight-ruby/highlight/lib/highlight.rb, sdk/highlight-ruby/highlight/lib/highlight/version.rb, sdk/pino/CHANGELOG.md, sdk/pino/package.json
* Increase frequency of opentelemetry export 
* enable gzip compression for opentelemetry export
Local go sdk testing
Python SDK unit testing
Ruby SDK unit testing
Java SDK unit testing
New package versions released
No
=> tune otel export settings

backend/clickhouse/migrations/000025_create_logs_sampling_mv.up.sql
- failing during migration because mv already existed, this should be idempotent
- ran script locally
- no
- no
=> add if not exists to ch mv script

backend/alerts/alerts.go, backend/alerts/logalerts.go, backend/alerts/sessionalerts.go, backend/jobs/log-alerts/log-alerts.go, backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.resolvers.go
- log alerts were not firing for certain projects because the "latest log timestamp" was in the future. there's quite a few more edge cases where latest log timestamp doesn't quite work, e.g.:
- kafka partitions unbalanced
- log processing backlog catching up 
- no logs for a project for some amount of time causing the alert to be stuck alerting
- I think it would be better to remove this logic for now and just use the current time minus 1 minute since under normal circumstances our expected latency is only a few seconds, can revisit if we want to move to a "evaluate alert on log ingest" model
- refactor welcome message code and add to log alerts
- fixes #6630 
- validated log alerts were being triggered with `make start-log-alerts-watch`
- validated slack welcome …
=> fix log alerts not firing, add welcome message

docs-content/getting-started/2_frontend-backend-mapping.md
Per [slack](https://highlightcorp.slack.com/archives/C05F8UHA4KZ/p1691644783628959), documenting how
a distributed application can instrument highlight to connect the frontend to the backend.
[Vercel preview](https://highlight-landing-git-vadim-distributed-tr-fcf178-highlight-run.vercel.app/docs/getting-started/frontend-backend-mapping).
No
=> document distributed tracing with highlight

sdk/client/src/index.tsx, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts
Per a customer report, `127.0.0.1` stylesheets are not recorded automatically, though
they are not accessible over the network. This changes the setting to record for other
local references (where hostname is `''`).
E2E test
New client version bump.
No
=> auto inline css on 127.0.0.1

backend/model/model.go, backend/phonehome/phonehome.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/__generated/index.css, frontend/src/__generated/ve/pages/Auth/AdminForm.css.js, frontend/src/graph/generated/schemas.tsx, frontend/src/pages/Auth/AdminForm.css.ts, frontend/src/pages/Auth/AdminForm.tsx
* records contact info (with ability to opt-out) for self-hosted deployments
* makes `/about_you` page fields required ( cc @jay-khatri )
with checkbox unchecked
data stored when checked, not stored when not checked
No
Yes
=> record contact info for self serve app

backend/clickhouse/log_row_test.go, backend/otel/extract_test.go, backend/util/logs.go, sdk/highlight-py/CHANGELOG.md, sdk/highlight-py/highlight_io/sdk.py, sdk/highlight-py/pyproject.toml
* Removes redundant `Highlight caught a ...` logs from our python SDK as they are failing to clean up the stacktrace correctly from our SDK. Our ingest will produce error logs for the ingested exceptions in any case.
* Increases the max log line limit to help with formatting larger messages / attributes.
Python SDK unit tests.
New python sdk patch version released.
No
=> remove redundant error logs from python sdk

backend/clickhouse/migrations/000025_create_logs_sampling_mv.down copy.sql
- accidentally introduced in #6689 , I don't think it'll have an effect but removing this to avoid build failures
=> remove copy of migration file

sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts, sdk/firstload/src/index.tsx
Per [discord discussion](https://discord.com/channels/1026884757667188757/1126647034380824606), using `H.onHighlightReady` can cause issues with `H.snapshot`
usage which can be called frequently as we have a chance to block the event loop
by queueing too many timeouts.
Changes the `H.snapshot` behavior to do nothing if highlight is not initialized.
`/1/canvas` recording
New highlight.run version 7.5.3
No
=> avoid using setTimeout in H.snapshot

frontend/src/pages/Setup/SetupRouter/AlertsSetup.tsx
* fixes sequential toggle of alerts switches and race condition with updating UI
* shows `save` for the action, disabled when there are no changes
* updates empty state for setup alerts page if alerts exist
[Reflame preview](https://preview.highlight.io/1/setup/alerts?%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201HAQT6PEW8CXZDJEZRJZ3EXMH%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%226657-add-empty-state-for-alerts-onboarding-when-people-already-created-alerts%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D)
No
Yes
=> address alerts setup flow feedback

frontend/src/__generated/index.css, frontend/src/index.tsx, frontend/src/pages/Auth/AdminForm.css.ts, frontend/src/pages/Auth/AuthRouter.tsx, frontend/src/pages/Auth/InviteTeam.tsx, frontend/src/pages/Auth/SignIn.tsx, frontend/src/pages/Auth/SignInRedirect.tsx, frontend/src/pages/Auth/utils.ts, frontend/src/pages/IntegrationAuthCallback/IntegrationAuthCallbackPage.tsx, frontend/src/pages/NewProject/NewProjectPage.tsx, frontend/src/routers/ProjectRouter/ApplicationRouter.tsx, frontend/src/routers/ProjectRouter/ProjectRedirectionRouter.tsx
We noticed a couple issues with people going through the setup flow of our Vercel integration.
1. They were getting stuck in the loading state once redirect to the `/sign_in` page.
2. They weren't being redirected back to the Vercel integration page after signing up/in.
This PR fixes both issues and adds general support for redirecting to the originally request page after a user authenticates.
I also addressed a minor issue I saw on the admin form where a top border was being applied to the last name field when hovered or focused.
Local click test. I just hit the callback URL manually locally since I couldn't trigger the real auth redirect from Vercel. We should verify the behavior initiating it from Vercel once this goes live.
Need to verify the full flow starting from Vercel once …
=> Redirect to originally request page after sign up/in

backend/clickhouse/traces.go, backend/public-graph/graph/resolver.go, backend/util/tracer.go, backend/worker/kafka_worker.go, backend/worker/worker.go, deploy/public-worker-service.json, docker/otel-collector.yaml
* update trace operation name constant for kafka batch worker operations
* report project id for internal metrics to track which project they come from
* add debug logging for local dev otel collector
Local deploy working.
No
No
=> update internal metrics

frontend/src/__generated/index.css, frontend/src/__generated/ve/pages/Player/Toolbar/TimelineIndicators/ZoomArea/ZoomArea.css.js, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/DevToolsWindowV2.tsx, frontend/src/pages/Player/Toolbar/TimelineIndicators/ZoomArea/ZoomArea.css.ts, frontend/src/pages/Player/Toolbar/TimelineIndicators/ZoomArea/ZoomArea.tsx
There has been some confusion around what you can click and drag in the devtools. This PR updates the cursor type to make it more clear what interactions you can perform.
1. Changes the cursor on the handle for resizing the devtools to `ns-resize` to make it clear it's something you can drag up and down.
2. Only makes the cursor of the zoom bar a `grab` when you can actually drag it (you are not zoomed out all the way).
https://www.loom.com/share/2a6c8cada1cc45a291031464ca166aac
N/A
Will have @julian-highlight click test to confirm the UX.
=> Fix cursor confusion in dev tools

frontend/src/pages/Player/Toolbar/TimelineIndicators/TimelineIndicatorsBarGraph/TimelineIndicatorsBarGraph.tsx
Allows you to click on empty spaces on the canvas to move to that point in the timeline.
https://www.loom.com/share/eee16dfd1bd946bda39015baac1f8881
N/A
Got Julian's sign off on a click test on the PR preview.
=> Allow clicking openings on canvas to update time

docs-content/sdk/java.md, sdk/highlight-java/highlight-common/src/main/java/io/highlight/sdk/common/HighlightOptions.java, sdk/highlight-java/highlight-sdk/src/main/java/io/highlight/sdk/HighlightOpenTelemetry.java, sdk/highlight-java/highlight-sdk/src/test/java/io/highlight/sdk/test/HighlightOptionsTest.java, sdk/highlight-java/pom.xml
adds `service_name` to Java SDK
/closes #6449
/claim #6449
=> feat: support services in Java SDK

backend/model/model.go
When an alert is created, we try to join the channel. When this channel is private, the request fails and we exit early, so not private channels will ever receive alerts.
Still send the message, even if the join conversation request fails. Keeping it consistent with the other post message sends.
1) Create a private channel
2) Add the highlight bot
3) Create an alert to point to that private channel
4) Check that the alert is created in the channel
N/A
N/A
=> Allow alerts to private channels

backend/util/tracer.go
Noticed our datadog traces had the `resource_name` in a strange format.
Turns out the opentelemetry `attribute.Value()` returns a struct rather than a string, so an `AsString()` conversion
is needed for string tags.
Will monitor datadog traces.
No
No
=> fix datadog trace resource names

backend/lambda-functions/journeys/handlers/handlers.go
- this "or" is not necessary, explain for this query is 10x faster, runs in about 20 mins for a full day
- fixes #6576 
- ran script on previous week of data
- no
- no
=> remove "or" in join for normalness

backend/lambda-functions/sessionInsights/handlers/handlers.go
- session insights emails are generated with react email so there's no sendgrid template id to use, add a category to these emails so we can filter when looking at analytics
- will validate with a dry run in prod
- no
- no
=> add category to session insights emails for analytics

backend/embeddings/embeddings.go, backend/otel/extract.go, backend/otel/otel.go, backend/public-graph/graph/resolver.go, backend/util/tracer-graphql.go, backend/worker/kafka_worker.go, backend/worker/worker.go, sdk/highlight-go/otel.go
The project for internal metrics was not being saved correctly because we would be
overriding the project id with the project id for our backend.
* correctly prioritize passed in tags for metrics and spans
* key traces by trace id to preserve child trace ordering
* record random duration logs with a numeric seconds value
Local deploy.
No
No
=> correctly report project for internal metrics

backend/model/model.go, backend/worker/worker.go
Kafka errors happening when a new trace worker is joining.
For the trace workers, we want a high batch size for writing larger payloads to clickhouse.
However, a large pretech queue from kafka causes significant network load on kafka when the queue is being filled.
Limit the prefetch queue size using a separate parameter. 
Local deploy.
No
No
=> limit kafka prefetching

backend/embeddings/embeddings.go, backend/public-graph/graph/resolver.go
The embeddings inference endpoint may slow down dramatically under heavy load but never time out.
In this case, each request takes >30 seconds and may take much longer, with the increasing load
preventing any requests from completing. This introduces a timeout to make sure we
will fail requests that take too long (longer than 1 second, where the normal p95 request time is 250ms)
local testing with a fake sleep inserted
```ERRO[0009]/Users/vkorolik/work/highlight/backend/public-graph/graph/resolver.go:768 github.com/highlight-run/highlight/backend/public-graph/graph.(*Resolver).HandleErrorAndGroup() failed to get embeddings                      error="Post \"https://rxti97k7hsleuekl.us-east-1.aws.endpoints.huggingface.cloud\": context deadline exceeded" error_object_id=0```
objects stored …
=> add timeout for embedding generation

frontend/src/pages/ErrorsV2/ErrorInstances/ErrorInstances.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ConsolePage/ConsolePage.tsx
Fix console page of dev tools `go to` button not working.
[Reflame preview](https://preview.highlight.io/1/sessions?page=1&query=and%7C%7Ccustom_processed%2Cis%2Ctrue%7C%7Ccustom_created_at%2Cbetween_date%2C2023-08-29T18%3A45%3A17.134Z_2023-09-28T18%3A45%3A17.134Z&%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201HBEH7FJJYG79YRZDJHNBJS1Z%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%226710-memory-issue-w-goto-button%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D) clicking goto.
No
No
=> fix console dev tools goto button

sdk/highlight-next/CHANGELOG.md, sdk/highlight-next/bin/clean-dist.sh, sdk/highlight-next/package.json, sdk/highlight-next/tsup.config.ts, sdk/highlight-node/CHANGELOG.md, sdk/highlight-node/package.json, yarn.lock
- Repairing the client import by publishing `client.d.ts`
- Repair `clean-dist.sh`
- Internalize `@highlight-run/sourcemap-uploader`
- Downgrade `@opentelemetry/api`
closes #6747 closes #6692
=> Attempting to repair npm published package

cypress/pages/unpkg.html, e2e/html/index.html, sdk/client/src/types/types.ts, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts, sdk/firstload/src/index.tsx
A race condition in our client `H.start` and `H.stop` methods would mean that if someone called `H.stop()` before `H.init()`, the stop would be queued in an interval that would race with other methods called (like other `H.start()` calls), since the calls would each get their own interval.
This rewrites the `onHighlightReady` handler to run the functions serially in the order in which they were queued. 
Expands a cypress test to validate the behavior.
with the following html script
```js
H.stop()
H.init('2', {
// Get your project ID from https://app.highlight.io/setup
environment: 'production',
scriptUrl: 'http://localhost:8080/dist/index.js',
manualStart: true,
networkRecording: {
enabled: true,
recordHeadersAndBody: true,
},
})
H.start({ forceNew: true }) …
```
=> fix race condition between client start and stop

.github/workflows/turbo.yml, backend/otel/extract.go, backend/otel/otel.go, backend/otel/systemd.go, backend/otel/systemd_test.go, docs-content/getting-started/backend-logging/10_systemd.md, docs-content/getting-started/backend-logging/11_syslog.md, docs-content/getting-started/backend-logging/6_http.md, e2e/opentelemetry/filelog/compose.yml, e2e/opentelemetry/journald/Dockerfile, e2e/opentelemetry/journald/compose.yml, e2e/opentelemetry/journald/otel-collector.yaml, go.work.sum, highlight.io/components/QuickstartContent/QuickstartContent.tsx, highlight.io/components/QuickstartContent/logging/systemd.tsx
Adds support for ingesting systemd / systemctl logs via the journald receiver.
Adds new documentation for the supported feature.
Docs here https://highlight-landing-git-vadim-journald-highlight-run.vercel.app/docs/getting-started/backend-logging/systemd
https://www.loom.com/share/35b2e1d1645e4a39baaed2a42097905c
No
No
=> add example for running journald

backend/migrations/cmd/backfill-session-properties-clickhouse/main.go, backend/public-graph/graph/resolver.go
- this was inadvertently removed when removing opensearch
- session properties should be converted into fields and saved in the `session_fields` table
- tested `country is United States` filter locally
- tested backfill script locally and verified more sessions were added with `country is United States`
- will run backfill script after deploying
- no
=> save session properties as fields

backend/clickhouse/migrations/000041_create_traces_table_new.down.sql, backend/clickhouse/migrations/000041_create_traces_table_new.up.sql, backend/clickhouse/migrations/000042_exchange_traces_tables.down.sql, backend/clickhouse/migrations/000042_exchange_traces_tables.up.sql
- replaces timestamp columns with DateTime64(9) for nanosecond precision
- it seems we save with microsecond (6) precision right now, not sure if this can/will change in the future, but the only downside to using a higher precision column is a more limited range of dates (up to `2262-04-11 23:47:16`)
- copies the partitioning and `min_age_to_force_merge_seconds` settings from logs table as this seems to improve performance compared to no partitioning
- ran migration scripts, validated data was inserted and queryable without code changes
- no, old traces can be copied to this new table after deploying
- no
=> use nanosecond precision for traces timestamp

backend/otel/extract.go, highlight.io/components/QuickstartContent/logging/fluentd.tsx
Fixes fluent bit ingest for other non-docker agents that report the tag without a wrapper.
Adds documentation for running the fluent bit agent with a configuration file.
Running fluent bit docker image locally with config file.
No
No
=> support ingesting logs from fluent bit

packages/ui/src/components/ComboboxSelect/ComboboxSelect.tsx, packages/ui/src/components/Menu/Menu.tsx
**Suggestion: Review hiding whitespace**
Menu's are being displayed underneath relatively positioned components rendered further down in the down. Render the aria kit menu in a portal that will render the menu in the bottom of the dom.
1) View the errors page
2) Make your screen width small enough so the error title is as close to the left panel as it can be
3) Open the segments popover
4) Scroll up and down with the popover open
5) Add a filter and open the combobox to select a value
6) Scroll up and down with the combobox open
7) Repeat for other menus (e.g. header menus)
N/A
N/A
=> Fix ariakit menu z-index

frontend/src/components/CommandBar/CommandBar.tsx
Ariakit's `useValue` is a hook that cannot be called inside the bodu of a function component, and causing the `onClick` method to exit early. Update to use `getValue` here, since it will fetch the value when called.
1) Open the command bar with `command-k`
2) Search for a field
3) Select the time frame
4) Click on the appropriate option
https://www.loom.com/share/3c15513a77194841b5b7fd05094671e9?sid=d1213027-ef9c-4214-8824-0b35e0a0ab7d
N/A
N/A
=> Fix command bar click

frontend/src/__generated/index.css, frontend/src/__generated/ve/pages/ErrorsV2/styles.css.js, frontend/src/pages/ErrorsV2/ErrorsV2.tsx, frontend/src/pages/ErrorsV2/styles.css.ts, packages/ui/src/components/ComboboxSelect/ComboboxSelect.tsx, packages/ui/src/components/Menu/Menu.tsx
Had to https://github.com/highlight/highlight/pull/6762 since it caused issues with popovers rendering under the session search panel. Update the Error search panel to have a higher zIndex to match the session search panel.
Note: an alternative solution is to remove the zIndex of the session search panel, but unsure how this could break things
1) View the sessions page
2) Open the popover by search for filters
3) View the errors page
4) Open the popover by search for filters
N/A
N/A
=> Fix aria kit menu z index

backend/public-graph/graph/resolver.go, backend/util/recovery.go
`recover()` must be called directly by the deferred fn, or else the panic is not recovered.
https://go.dev/ref/spec#Handling_panics
Fixes panic in the main push payload processing.
N/A
No
No
=> fixup! fix nil ptr reference in stripe update (#6780)

docs-content/getting-started/fullstack-frameworks/next-js.md, docs-content/sdk/nextjs.md, e2e/nextjs/README.md, e2e/nextjs/next.config.mjs, highlight.io/next.config.js, sdk/highlight-next/CHANGELOG.md, sdk/highlight-next/config.d.ts, sdk/highlight-next/package.json, sdk/highlight-next/src/config.ts, sdk/highlight-next/src/server.ts, sdk/highlight-next/tsup.config.ts, sourcemap-uploader/package.json, sourcemap-uploader/tsup.config.ts, yarn.lock
Closes #6747 
`withHighlightConfig` was exported by `@highlight-run/next/server`, which also exported some Node packages that were incompatible with `next.config.js`.
This PR moves `withHighlightConfig` to ``@highlight-run/next/config` to remove those excess dependencies. 
`withHighlightConfig` also relies on `@highlight-run/sourcemap-uploader`, which had some bundling issues that are also resovled in this PR.
Local test with `yarn e2e:nextjs`. Vercel test with `cd e2e/nextjs && yarn deploy`.
Major bump to `@highlight-run/next` and minor bump to `@highlight-run/sourcemap-uploader`
Nope.
=> Repairing withHighlightConfig

backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/components/Header/Header.tsx, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql
Show the billing issue banner only if the workspace feature flag is set to true (default).
This allows overriding the billing issue banner for a customer who has an invoice issue that cannot be immediately resolved.
feature flag default on
feature flag off
No
No
=> feature flag billing issue banner

backend/clickhouse/logs.go, backend/clickhouse/query.go, backend/clickhouse/traces.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/Alerts/LogAlert/LogAlertPage.tsx, frontend/src/pages/LogsPage/LogsHistogram/LogsHistogram.tsx, frontend/src/pages/LogsPage/LogsPage.tsx, frontend/src/pages/Traces/TracesPage.tsx
- queries the materialized views for trace keys / values
- adds queries for metrics (count, p50, p90)
- these query the `traces_sampling` table for queries > 1 hour
- use metrics queries with a histogram and line chart on top of the traces list view
- did not put much effort into styling here, would like to deploy as a first version to see what the performance is like in prod
https://www.loom.com/share/71dd9d8301ec493095d8dbbb90dfe19f
- no, materialized views / sampling table have already been created in prod
- eventually, but the traces page is feature flagged atm
=> use materialized views for trace perf, add trace histogram/metrics

.changeset/config.json, .github/workflows/turbo.yml, internal-docs/rfcs/003-changesets.md, package.json, yarn.lock
Adds a [new doc](https://github.com/highlight/highlight/blob/c99084498ced39240f90a39de3606a4942b3fcfb/internal-docs/rfcs/003-changesets.md) on using changesets to publish js packages.
Configures changesets for our monorepo.
In short, run `yarn changeset` locally when making changes to published js packages.
CI
Will monitoring github action in main.
No
=> add rfc on adding changesets

.github/workflows/turbo.yml, docker/frontend.Dockerfile, packages/ai/package.json, sdk/highlight-cloudflare/package.json, sdk/highlight-next/package.json, yarn.lock
Ensure that our docker image build can reference the opentelemetry-sdk-workers submodule.
Ensure cloudflare types are imported by our next SDK.
CI
Deploying new docker image release
No
=> ensure opentelemetry is build for docker image

backend/model/model.go
Ensures that partitions of `error_object_embeddings_partitioned` are attached 
[without requiring a table lock](https://www.postgresql.org/docs/current/ddl-partitioning.html#DDL-PARTITIONING-DECLARATIVE-MAINTENANCE).
Automates creating L2 distance indexes for new partitions.
Local migration with debug
```
2023/10/05 11:45:39 /home/vkorolik/work/highlight/backend/model/model.go:1595
[1.964ms] [rows:0] 
CREATE TABLE IF NOT EXISTS error_object_embeddings_partitioned_1007
(LIKE error_object_embeddings_partitioned INCLUDING ALL);
2023/10/05 11:45:39 /home/vkorolik/work/highlight/backend/model/model.go:1602
[149.305ms] [rows:0] 
CREATE INDEX ON error_object_embeddings_partitioned_1007
USING ivfflat (gte_large_embedding vector_l2_ops) WITH (lists = 1000);
2023/10/05 11:45:39 …
```
=> ensure error embeddings partitioned table runs migration without table level lock

backend/model/model.go, backend/util/environment.go
We saw out-of-disk errors from test invocation due to the number of partition indexes created as part of #6805 
```
2023-10-06T19:54:32.9732974Z time="2023-10-06T19:54:32Z" level=error msg="error creating testdb: error migrating test db: Error creating index error_object_embeddings for index 885: ERROR: could not extend file \"base/23587/30785\": No space left on device (SQLSTATE 53100)" DB_HOST=localhost DB_NAME=highlight_testing_db
2023-10-06T19:54:32.9735255Z === RUN   TestIsProjectIntegrated
2023-10-06T19:54:32.9735884Z === RUN   TestIsProjectIntegrated/TestIsProjectIntegrated
2023-10-06T19:54:32.9736486Z --- FAIL: TestIsProjectIntegrated (0.00s)
2023-10-06T19:54:32.9737181Z     --- FAIL: TestIsProjectIntegrated/TestIsProjectIntegrated (0.00s)
2023-10-06T19:54:32.9745917Z panic: …
```
=> fix backend test running out of disk space

.changeset/wicked-bugs-type.md, sdk/highlight-cloudflare/package.json, sdk/highlight-next/package.json, sdk/highlight-next/src/server.ts, sdk/highlight-next/src/util/highlight-node.ts
Turns out that NEXT_RUNTIME can be undefined 😢
=> handling process.env.NEXT_RUNTIME as 'undefined'

frontend/src/pages/Sessions/SessionsFeedV3/SessionQueryBuilder/components/SessionFeedConfigurationV2/SessionFeedConfigurationV2.tsx
- fixes #6705 by removing custom opening / closing logic for the context menu
- no
- no
=> fix sessions context menu not visible

packages/react-email-templates/emails/session-insights.tsx
- the session insights and weekly digests emails use pretty much the same style, but on mobile the sessions insights email is displayed at a smaller scale because it is wider. this adjusts the widths to max out at 400px instead of 600px to match the weekly digest email
- tested by sending samples in react-email, will test with a dry run after deploying
- no
- no
=> make session insights email better on mobile

backend/public-graph/graph/sampling.go, backend/public-graph/graph/sampling_test.go
Error exclusion with events was not using the project based filters
because we would be using the `query` criteria to skip the exclusion.
New unit test.
No
No
=> fix filtering for errors ingest based on project event filters
