- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .vscode/settings.json
- CODE_OF_CONDUCT.md
- README.md
- package.json
This PR cleans up after https://github.com/highlight/highlight/pull/3589 which returned the sdk repos, but did not remove submodules from git (see [a68078b](https://github.com/highlight/highlight/pull/3600/commits/a68078b85e7d4719910948927927ce2e559d8b97)).
Sneaks in small formatting fixes as well.
n/a
> hotfix: deployment

- .github/workflows/backend.yml
- .github/workflows/docker.yml
- docker/backend.Dockerfile
- docker/compose.yml
- docker/frontend.Dockerfile
- docker/run.sh
- sdk/client/src/index.tsx
- sdk/client/src/types/types.ts
- sdk/firstload/package.json
- sdk/firstload/src/index.tsx
Update rrweb to include latest cross-origin iframe fixes.
Fixes docker build to run on relevant changes.
Local docker image build.
Updated firstload version.
> fix docker build and update rrweb

- sourcemap-uploader/src/index.ts
- this was included in the previous `index.ts` file, reintroducing it because the build was breaking
- will validate build success
- no
> fixup: add env shebang

- frontend/src/components/Header/Header.module.scss
- frontend/src/components/Header/Header.module.scss.d.ts
- frontend/src/components/Header/Header.tsx
> add banner for youtube live

- .github/workflows/docker.yml
try out buildjet github actions runners @adamshiervani
> switch to buildjet runners

- .github/workflows/deploy.yml
- .github/workflows/docker.yml
- backend/worker/kafka_worker.go
- backend/worker/worker.go
Speed up AWS deploy using native arm workers.
Tune batched consumer worker.
> deploy aws arm image using native runners

- backend/event-parse/sample-events/input.json
- backend/event-parse/sample-events/output.json
- frontend/index.html
- frontend/public/manifest.json
- frontend/src/index.tsx
Ensure all frontend names reference highlight.io
Preview
No
> update highlight name

- frontend/src/components/Header/Header.tsx
* Adds a github button right of community.
* Updates the highlight roadshow banner time.
Preview
No
> add github button

- backend/private-graph/graph/generated/generated.go
- backend/private-graph/graph/model/models_gen.go
- backend/private-graph/graph/resolver.go
- backend/private-graph/graph/schema.graphqls
- backend/private-graph/graph/schema.resolvers.go
- frontend/src/graph/generated/schemas.tsx
This PR contains the backend changes for #4202. We wanted to merge these in so we can click test in the PR preview for #4202.
The new flow was tested as part of the work on #4202 and will be tested further after this is merged.
N/A - Only changes are a new endpoint that will be used by the new sign up flow.
> Backend changes for new sign up flow

- packages/ui/README.md
Documentation for adding a component to the UI package.
N/A
N/A
> Docs for adding a component to the UI library

- backend/worker/kafka_worker.go
Adds additional metric for monitoring clickhouse.
> add a metric for recording the clickhouse payload in bytes

- frontend/src/pages/LogsPage/LogsPage.tsx
Reverts highlight/highlight#4251
I spoke too soon about the react-router upgrade working. Re-renders aren't actually happening 😢 
Probably going to need to pair with Sasha on this.
> Revert "Remove manual routing changes."

- frontend/src/pages/ErrorsV2/ErrorBody/components/ErrorBodyText/index.tsx
- frontend/src/pages/ErrorsV2/ErrorBody/components/ErrorBodyText/style.css.ts
- frontend/src/pages/Player/RightPlayerPanel/components/ErrorDetails/ErrorDetails.tsx
Resolves #4216.
1. Go to https://frontend-pr-4262.onrender.com/1725/sessions/oMMlWxf6mZavUqBnAWdeEaKCmFn3
2. Click on the first error
3. Check that the right panel shows error details without breaking the interface
no
> fix(#4216): error details in session view

- packages/ui/tsconfig.json
Not using `strict: true` everywhere can cause undesirable type mismatches (see [comment](https://github.com/highlight/highlight/pull/4274#issuecomment-1431596631)).
Fixes #4277
Build passes
N/A
> use strict typing in ui package

- frontend/src/routers/OrgRouter/ProjectRouter.tsx
Adds a missing param preventing the front UI from rendering (go to https://front.highlight.io)
go to https://frontend-pr-4283.onrender.com/front
no
> hotfix: routing for front

- backend/vercel/vercel.go
ensure we do not error on empty lines
> fix vercel log drain parsing

- backend/main.go
Fix enhanced health check influxdb query in prod.
Add additional logging to make it easier to figure out which health check is failing (before the change rolls out).
> fix enhanced health check

- backend/clickhouse/logs.go
- backend/main.go
Clickhouse is experiencing high throughput due to the health check.
Local deploy.
No
> reduce clickhouse load from health check

- frontend/package.json
- frontend/src/index.tsx
- packages/ui/package.json
- sdk/client/package.json
- sdk/firstload/package.json
- yarn.lock
* Updates rrweb
* Enables concurrent render root
Local deploy; preview.
New highlight.run package version.
> update rrweb to be54981

- backend/main.go
- docker/backend.Dockerfile
- e2e/go/fiber.go
* Fixes hubspot not being initialized in worker resolver.
* Adds random error to fiber example.
* Fixes local docker debug backend.
Local deploy.
No
> fix hubspot panic

- docker/compose.dev.yml
- docker/compose.yml
- docker/frontend.Dockerfile
- sdk/firstload/package.json
Fixes missing paths in docker configuration.
Local docker deploy.
No.
> fix dev docker deploy

- .github/workflows/deploy.yml
Reverts highlight/highlight#4313
> Revert "temporarily disable migration during deploy"

- .github/workflows/turbo.yml
Ensure that forks of our branch can run CI.
CI
No
> fix secrets breaking fork prs

- frontend/src/pages/Setup/SetupPage.tsx
Links were broken on the setup page. Got a heads up from https://twitter.com/pena_austin/status/1628796479484854278
Check links are correct.
Nope.
> Update SetupPage doc links

- README.md
Old link was made invalid by new docs changes
> Update company values link

- frontend/src/components/CommandBar/CommandBar.tsx
- frontend/src/components/CommandBar/style.css.ts
Makes the position absolute to avoid janky experience.
Press cmd/ctrl-k.
no
> hotfix: make commandbar position absolute

- README.md
- backend/errors/errors_test.go
- backend/otel/otel.go
- backend/private-graph/graph/schema.resolvers.go
- backend/storage/storage.go
- docker/nginx.conf
- e2e/nextjs/README.md
* cleanup sourcemap versions code
* add http -> https redirect to prod docker build
* fix incorrect community links
Local deploy debugging customer project.
No
> cleanup sourcemap version handler

- backend/main.go
- sdk/highlight-py/e2e/highlight_azure/HttpTrigger/__init__.py
- sdk/highlight-py/e2e/highlight_django/polls/views.py
- sdk/highlight-py/e2e/highlight_fastapi/main.py
- sdk/highlight-py/e2e/highlight_flask/app.py
- sdk/highlight-py/e2e/highlight_script/main.py
- sdk/highlight-py/highlight_io/sdk.py
- sdk/highlight-py/pyproject.toml
Pass python structured log attributes as log attributes.
Local flask app deploy.
Python SDK version bump.
> allow python logging to correctly record structured attributes

- .github/workflows/deploy.yml
planning on restarting DMS today
Reverts highlight/highlight#4352
> Revert "Revert "temporarily disable migration during deploy""

- frontend/src/pages/ErrorsV2/ErrorQueryBuilder/components/QueryBuilder/QueryBuilder.css.ts
- frontend/src/pages/ErrorsV2/ErrorQueryBuilder/components/QueryBuilder/QueryBuilder.tsx
- frontend/src/pages/Sessions/SearchSidebar/SegmentButtons/CreateSegmentModal.tsx
- frontend/src/pages/Sessions/SessionsFeedV3/SessionQueryBuilder/components/QueryBuilder/QueryBuilder.css.ts
- frontend/src/pages/Sessions/SessionsFeedV3/SessionQueryBuilder/components/QueryBuilder/QueryBuilder.tsx
- packages/ui/src/components/Button/styles.css.ts
before
after
create long segments and try to edit session segments (the list must update)
no
> hotfix: ux for long error & session segments + edits

- frontend/src/pages/LogsPage/LogsPage.tsx
- frontend/src/pages/LogsPage/LogsTable/LogsTable.tsx
This PR fixes two frontend issues (see inline comments below).
See inline comments below.
N/A
> fix refetching logs

- .github/workflows/deploy.yml
Reverts highlight/highlight#4412
reenabling migrations after stopping DMS work
> Revert "Revert "Revert "temporarily disable migration during deploy"""

- docker/otel-collector.yaml
Added [Traceloop](https://www.traceloop.dev/) exporter support so tests can be automatically generated for Highlight.
We should enable it in staging first.
> feat: added traceloop exporter

- frontend/src/components/CommandBar/context.ts
- frontend/src/pages/ErrorsV2/ErrorQueryBuilder/components/QueryBuilder/QueryBuilder.tsx
Resolves #4397 by fixing the filter attribute names. 
cmd/ctrl + k and search for each filter
no
> fix(#4397): commandbar filters

- frontend/src/components/EmptySearchResults/EmptySearchResults.tsx
- frontend/src/pages/IntegrationsPage/Integrations.tsx
- frontend/src/pages/Player/SessionShareButton/SessionShareButtonV2.tsx
- frontend/src/pages/Player/Toolbar/DevToolsWindowV2/EmptyDevToolsCallout/EmptyDevToolsCallout.tsx
Update references to changed URLs.
Local frontend deploy.
No
> fix broken docs links

- backend/clickhouse/logs.go
- backend/clickhouse/logs_test.go
- backend/private-graph/graph/generated/generated.go
- backend/private-graph/graph/model/models_gen.go
- backend/private-graph/graph/schema.graphqls
- frontend/src/graph/generated/schemas.tsx
GraphQL is complaining because these values are coming back as undefined.
Render preview should work
N/A
> hotfix - fix logs graphql schema

- backend/clickhouse/logs_test.go
Each logs test is creating the test db and running migrations. Let's use `TestMain` so we only run this once.
> try to fix logs tests

- frontend/src/pages/Player/Toolbar/DevToolsWindowV2/DevToolsWindowV2.tsx
- frontend/src/pages/Player/Toolbar/DevToolsWindowV2/NetworkPage/NetworkPage.tsx
- frontend/src/pages/Player/Toolbar/DevToolsWindowV2/utils.ts
- Resolves #4415, "Network request types don't properly filter network data." 
- Updated RequestType enum values to match received request types
- Just dev mode click test
-none
> #4415 Fix network request filtering

- frontend/src/components/Header/Header.module.scss
- frontend/src/components/Header/Header.module.scss.d.ts
- frontend/src/components/Header/Header.tsx
Adds a maintenance window banner.
> add maintenance window banner

- .github/workflows/turbo.yml
- sdk/highlight-react/package.json
* fix the github action check to work outside of pull requests
* bump `@highlight-run/react` version to publish new error boundary
> fix npmjs package publishing

- frontend/src/@types/window.d.ts
- frontend/src/pages/Auth/AdminForm.tsx
> Add gtag call to track ad conversions

- frontend/src/pages/Player/PlayerHook/PlayerHook.tsx
* fix playback pausing at session start
* fix timeline position not resetting when switching sessions
Local deploy and preview.
No
> fix session replay bugs

- backend/private-graph/graph/schema.resolvers.go
- frontend/src/pages/Player/PlayerHook/PlayerHook.tsx
- frontend/src/pages/Player/PlayerHook/PlayerState.ts
* Fixes slow playback of session due to constant `play` action
* Fixes slow query for errors based on a log cursor.
> fixup! fix session replay bugs (#4533)

- backend/main.go
Allows hosting our frontend on https://reflame.app/
cc @lewisl9029
Checking that local public / private graph work.
No
> add reflame endpoint for cors

- backend/hubspot/hubspot.go
- backend/private-graph/graph/schema.resolvers.go
- backend/public-graph/graph/resolver.go
- backend/util/environment.go
- backend/worker/worker.go
- frontend/src/pages/WorkspaceTeam/WorkspaceTeam.tsx
Use the `referral_url` property which exists on contacts.
Local gdb tracing creating a contact.
No
> fix hubspot creation of contacts

- docker/frontend.Dockerfile
Ensures `yarn` is ran for for nest js sdk packages (#4581)
> Fix frontend docker build

- README.md
First of all, thanks for highlight.io and making it open source, looks great! 
Fix the anchors in the links in the readme
Found the anchors on the readme and clicked on them
--
> Fix readme anchors

- .devcontainer/devcontainer.json
- .vscode/extensions.json
- DEVELOPER_ONBOARDING.md
- docker/.env
-Adding codespaces configuration file
-Added commented-out compose dev variable
-Ran codespaces locally using this config file
-None
> GitHub Codespaces config v1

- frontend/src/util/db.ts
- if there's a `mutation` in the operation, short circuit the caching logic
- this was causing an issue on the billing page where an expired url was returned for a stripe checkout session
- tested locally with indexeddb on
- no, can revert if any issues
> skip indexeddb caching for mutations

- frontend/src/pages/ErrorsV2/ErrorStateSelect/ErrorStateSelect.tsx
Relate to https://github.com/highlight/highlight/issues/4557
Local UI is ok.
No
> [issue_4557] Fix alignment issues in the error state switch

- backend/model/model.go
- backend/pricing/pricing.go
- backend/private-graph/graph/schema.resolvers.go
- backend/public-graph/graph/resolver.go
- backend/worker/worker.go
Reverts highlight/highlight#4796
> Revert "Revert "use materialized view for errors count""

- sdk/highlight-py/e2e/highlight_azure/HttpTrigger/__init__.py
- sdk/highlight-py/e2e/highlight_azure/requirements.txt
- sdk/highlight-py/highlight_io/sdk.py
- sdk/highlight-py/pyproject.toml
Adjusts python SDK flushing settings to ensure SDK does not increase azure function memory usage significantly.
`poetry run build; poetry run flask run`
New python SDK version bump.
> make python sdk flush more frequently

- frontend/src/pages/Player/Toolbar/DevToolsWindowV2/DevToolsWindowV2.tsx
- frontend/src/pages/Player/Toolbar/DevToolsWindowV2/EmptyDevToolsCallout/EmptyDevToolsCallout.tsx
- frontend/src/pages/Player/Toolbar/DevToolsWindowV2/NetworkPage/NetworkPage.tsx
- frontend/src/pages/Player/Toolbar/DevToolsWindowV2/NetworkPage/style.css.ts
- frontend/src/pages/Player/Toolbar/DevToolsWindowV2/utils.ts
Issue #4456, "Add new filters/fields to network requests "
- adds latency row
- adds network request filter based on status
-Dev mode click test, Render URL click test
-None
> Add latency field and http status filter to network requests

- docs-content/general/1_welcome.md
Fixed a small typo on the main docs page.
CI build.
no
> Small typo to "session replay"

- .github/workflows/docker.yml
- docker/compose.dev.yml
- docker/frontend.Dockerfile
Ensure the `docker` build runs on all PRs.
The `docker` workflow is important to outside contributors and is quite easy to break.
CI
No
> run docker on app PRs

- docs-content/general/4_company/1_values.md
Adds a section to `values.md` to talk more about OSS.
CI
n/a
> Small change to `values.md`

- docs-content/general/6_product-features/1_session-replay/session-search.md
> Fix typo on session search page

- backend/model/model.go
- backend/private-graph/graph/generated/generated.go
- backend/private-graph/graph/resolver.go
- backend/private-graph/graph/schema.graphqls
- backend/private-graph/graph/schema.resolvers.go
- frontend/src/graph/generated/hooks.tsx
- frontend/src/graph/generated/operations.tsx
- frontend/src/graph/generated/schemas.tsx
- frontend/src/graph/operators/mutation.gql
- frontend/src/graph/operators/query.gql
- frontend/src/pages/ProjectSettings/FilterExtensionForm/FilterExtensionForm.tsx
- frontend/src/pages/ProjectSettings/ProjectSettings.tsx
Add opt-in filtering for chrome-extension errors
https://github.com/highlight/highlight/issues/4744
https://www.loom.com/share/8255701600d441339e92095f34c05ea6
> [Feature 4744] Add opt-in filtering for chrome-extension errors

- docs-content/general/4_company/open-source/contributing/1_getting-started.md
- docs-content/general/4_company/open-source/contributing/architecture.md
- docs-content/general/4_company/open-source/contributing/good-first-issues.md
- docs-content/package.json
- highlight.io/package.json
- package.json
- turbo.json
- yarn.lock
resolves #4867 
- fixes a broken link to the first issue doc
- renames "best first issue" to "good first issue"  everywhere
CI
> Update wording of "best first issue" in the docs.

- docs-content/general/6_product-features/2_error-monitoring/1_overview.md
- docs-content/general/6_product-features/2_error-monitoring/manually-send-errors.md
Very simple doc on how to manually report errors. 
CI, clicktest.
n/a
> Add docs for `consumeError`

- backend/main.go
- backend/private-graph/graph/middleware.go
- frontend/src/components/Header/Header.tsx
- frontend/src/components/Header/HelpMenu/HelpMenu.tsx
- frontend/src/components/Header/components/FeedbackButton/FeedbackButton.tsx
- frontend/src/components/KeyboardShortcutsEducation/KeyboardShortcutsEducation.tsx
- highlight.io/components/common/Footer/Footer.tsx
- highlight.io/components/common/Navbar/ResourceDropdown.tsx
Update old canny feedback links to point to the new changelog and community.
CI
No.
> update old canny links

- docs-content/general/6_product-features/1_session-replay/1_overview.md
- docs-content/general/6_product-features/1_session-replay/ignoring-sessions.md
- docs-content/general/6_product-features/1_session-replay/session-url.md
- docs-content/general/6_product-features/2_error-monitoring/1_overview.md
- docs-content/general/6_product-features/2_error-monitoring/ignoring-errors.md
- docs-content/general/7_integrations/segment-integration.md
- frontend/src/pages/ProjectSettings/ProjectSettings.tsx
- cleans up some formatting here and there
- adds a doc for Ignoring Errors, Ignoring Sessions, and Extracting the URL out of a session (things we've heard form customers these past few weeks).
- Renames the tabs in the project settings page
CI, clicking around.
> Update docs for ignoring errors, ignoring sessions, and `getSessionDetails`

- highlight.io/pages/docs/[[...doc]].tsx
- highlight.io/pages/for/[slug].tsx
A few changes to our usage of interactionObserver. Before this PR, docs pages were broken on certain iOS devices.
Used https://saucelabs.com/resources/blog/how-to-inspect-element-on-iphone to inspect element on Safari for my iphone.
n/a
> Update InteractionOberserver Usage for iOS

- docs-content/getting-started/1_overview.md
- docs-content/getting-started/4_backend-sdk/go/1_overview.md
- docs-content/getting-started/4_backend-sdk/js/1_overview.md
- docs-content/getting-started/4_backend-sdk/python/1_overview.md
- docs-content/getting-started/4_backend-sdk/ruby/1_overview.md
- docs-content/getting-started/backend-logging/1_go/1_overview.md
- docs-content/getting-started/backend-logging/1_go/fiber.md
- docs-content/getting-started/backend-logging/1_go/logrus.md
- docs-content/getting-started/backend-logging/1_go/other.md
- docs-content/getting-started/backend-logging/2_js/1_overview.md
- docs-content/getting-started/backend-logging/2_js/nestjs.md
- docs-content/getting-started/backend-logging/2_js/nodejs.md
- docs-content/getting-started/backend-logging/3_python/1_overview.md
- docs-content/getting-started/backend-logging/3_python/python-install.md
- docs-content/getting-started/backend-logging/3_python/python.md
- docs-content/getting-started/backend-logging/4_ruby/1_overview.md
- highlight.io/components/Features/features.tsx
- updates titles of all the logging pages
- adds a logging section to the overview / getting started page
click test
n/a
> Logging Docs Changes

- internal-docs/onboarding/deltaepsilon.md
This is Chris E's onboarding document. Per #4931, we are moving more of our processes to github including onboarding.
[View rendered markdown](https://github.com/highlight/highlight/blob/et/deltaepsilon-onboarding/internal-docs/onboarding/deltaepsilon.md)
I've attached names and issues for pairing tasks. We're trying to give Chris the opportunity to learn as much of the stack from every member of the team. Feel free to comment or edit this pull request as appropriate:
> add deltaepsilon's onboarding

- highlight.io/components/common/Roadmap/RoadmapUtils.ts
- highlight.io/pages/docs/[[...doc]].tsx
Added some checking for nonexistent data in the roadmap fetcher.
Also, made changes such that getStaticProps only calls roadmapFetcher for roadmap path, rather than all docs paths.
> roadmap error checking

- frontend/src/pages/Alerts/LogAlert/LogAlertPage.tsx
- need a way to refresh slack channels
- basic logic copied over from other alerts
- click test locally
- no
> add sync slack button to log alerts slack dropdown

- backend/alerts/logalerts.go
- backend/jobs/log-alerts/log-alerts.go
- add some more logging around log alert triggering
- set `Frequency` to `ThresholdWindow` field (was previously not set / defaulting to 15)
- fix sign for start date
- fix issue with captured loop variable 
- ran the log alert watcher locally
- no
> log alert fixups

- docs-content/getting-started/3_client-sdk/7_replay-configuration/content-security-policy.md
cleans up csp docs.
local deploy / ci.
n/a
> Update styling for csp docs

- frontend/src/components/Header/Header.tsx
- "upgrade here" text is already being added, remove it here
- click tested locally w/ mocked billing data
- no
> fixup - duplicate upgrade text

- docs-content/general/1_welcome.md
- docs-content/general/4_company/1_values.md
- docs-content/general/4_company/compliance-and-security.md
- docs-content/general/4_company/open-source/contributing/2_backend.md
- docs-content/general/4_company/open-source/contributing/4_landing-site.md
- docs-content/general/4_company/open-source/contributing/adding-an-sdk.md
- docs-content/general/4_company/open-source/contributing/architecture.md
- docs-content/getting-started/1_overview.md
- docs-content/getting-started/2_frontend-backend-mapping.md
- docs-content/getting-started/backend-logging/1_go/1_overview.md
- docs-content/getting-started/backend-logging/2_js/1_overview.md
- docs-content/getting-started/backend-logging/4_ruby/1_overview.md
- docs-content/sdk/go.md
- highlight.io/components/QuickstartContent/frontend/other.tsx
- highlight.io/components/QuickstartContent/self-host/shared-snippets.tsx
I took a pass at various pages of the docs and cleaned up lots of grammar and inconsistent wording. I did find a bug when linking the ruby docs as well another bug when linking the Go SDK docs.
Visual test
N/A
> Many doc updates

- highlight.io/components/Blog/Blog.module.scss
Adds a border radius to the `mainImage` component.
clicktest
n/a
> Update border radius for blog images

- docs-content/general/6_product-features/2_error-monitoring/ignoring-errors.md
typo in ignoring errors doc.
clicktest
n/a
> Fix typo in `ignoring-errors` doc

- e2e/nestjs/package.json
- e2e/nextjs/package.json
- package.json
Reviewed with Vadim when setting up highlight locally to develop for the highlight/next package. 
Ran commands on frontend
NA
> Changed nextjs port and run

- .dockerignore
- .github/workflows/docker.yml
- docker/backend.Dockerfile
- docker/compose.prod.yml
- docker/compose.yml
- docker/frontend.Dockerfile
- docker/run-hobby.sh
- docker/start-infra.sh
Fixes collector networking on linux (based on [stackoverflow](https://stackoverflow.com/questions/48546124/what-is-linux-equivalent-of-host-docker-internal/67158212#67158212)).
Fixes pull syntax for linux docker compose.
`./start-infra.sh` and dev workflow on linux
`./run-hobby.sh` on linux
No
> fix docker deploy on linux

- docs-content/general/6_product-features/4_logging/1_overview.md
Replaces "beta" wording with getting started content on logs.
clicktest.
n/a
> Logging is out of beta

- README.md
- docs-content/general/1_welcome.md
- docs-content/general/4_company/product-philosphy.md
- docs-content/general/6_product-features/4_logging/1_overview.md
Edits for upcoming logging launch.
Clicktest.
n/a
> Updates for logging lauch

- README.md
- adds new logging image
visuals
n/a
> Update README.md logging content

- README.md
- highlight.io/components/QuickstartContent/self-host/self-host.tsx
- highlight.io/components/QuickstartContent/self-host/shared-snippets.tsx
Our Docker resource requirement recommendations were out of date after #4820 and #4993 .
Viewing highlight.io locally.
No
> update and standardize resource recommendations for docker

- backend/main.go
Just a quick update to the reflame preview origin in preparation for https://github.com/highlight/highlight/pull/4586
Haven't been able to test it yet. Can only test properly once shipped. Here's a [Reflame preview](https://preview.highlight.io/~r/start-preview/?mode=production&variantId=01GY11FVTK9FMXX2DSCR6T4VRD&variantName=git%7Enew-reflame-app-1&userId=01FQZZ7XJFDA799Z1Z9DRCFXWA) from that branch where everything seems to be working except for API requests due to CORS errors.
> Update reflame CORS origin

- README.md
Got some good feedback from an HN comment:
- updates thumbnail image to remove comma
- replaces "read more here" with actual text
> Update README.md Typos + Image Edits

- docs-content/general/4_company/compliance-and-security.md
- highlight.io/components/Docs/Docs.module.scss
Adds a lits of SubProcessors to our security docs.
clicktest
n/a
> Add subprocessors to security doc

- docs-content/general/changelog/1_overview.md
- docs-content/general/changelog/changelog-18.md
> Add changelog 18

- frontend/src/pages/Player/PlayerHook/PlayerHook.tsx
- frontend/src/pages/Player/PlayerHook/utils/index.tsx
- frontend/src/pages/Player/PlayerHook/utils/mui.ts
Inject MUI stylesheets for a customer.
This is a workaround for a problem in rrweb (which causes the stylesheets to be injected broken and repeated).
Pulling in a known broken session auH6iXPRSNSscJuiPwuJ2SFMeH8q
https://www.loom.com/share/13013fdbc8c04897889dd3feebad02f8
No, gated to customer's project.
> apply missing mui stylesheets

- docs-content/general/4_company/compliance-and-security.md
Adds Clickhouse as SubProcessor 
clicktest
n/a
> Adds Clickhouse as SubProcessor

- sdk/highlight-react/package.json
I should've bumped this version with an earlier PR. Better late than never!
> Major version bump for @highlight-run/react

- .github/workflows/e2e.yml
- .github/workflows/turbo.yml
Fix incorrect branch reference in github actions.
> fixup! revert error boundary error reporting change (#5176)

- backend/main.go
- backend/worker/kafka_worker.go
- backend/worker/worker.go
- frontend/src/index.tsx
* fix frontend -> backend linking with tracingOrigins after pri domain migration
* fix kafka panic when no messages received
* fix fs session storage not resolving assets correctly
* reduce worker processing delay
Local deploy recording errors correctly.
Local deploy resolving in-lined assets correctly.
No
> fix misc issues

- backend/public-graph/graph/resolver.go
- backend/public-graph/graph/resolver_test.go
This PR cleans up some code I saw in the error grouping logic.
Build passes
N/A
> clean up error grouping code

- highlight.io/components/QuickstartContent/logging/js/winston.tsx
Update documentation for winston to be ESM / CJS compatible.
https://www.loom.com/share/16efccaa2f944786b5ee520b0304f64f
No
> fix winston docs

- blog-content/5-best-logging-libraries-for-go.md
- blog-content/5-best-python-logging-libraries.md
Update creation dates for a few blog posts.
n/a
> Update creation dates for blog posts

- frontend/src/components/Header/Header.tsx
Fixes billing header looking for the wrong project id.
No
> fix billing header

- docs-content/general/4_company/our-competitors.md
This addresses comments in #5291. I resolved comments before pushing up my changes (my mistake). 
clicktest
n/a
> Followup on datadog competitor change

- .vscode/settings.json
- docs-content/getting-started/fullstack-frameworks/next-js.md
- e2e/nextjs/README.md
- e2e/nextjs/next.config.js
- e2e/nextjs/pages/_app.tsx
- e2e/nextjs/src/app/layout.tsx
- sdk/firstload/src/__generated/version.ts
- sdk/highlight-next/.npmignore
- sdk/highlight-next/bin/clean-highlight-init.sh
- sdk/highlight-next/highlight-init.d.ts
- sdk/highlight-next/index.d.ts
- sdk/highlight-next/package.json
- sdk/highlight-next/src/HighlightInit.tsx
- sdk/highlight-next/tsconfig.json
- sdk/highlight-node/package.json
- yarn.lock
It turns out that we need to transpile `<HighlightInit>`.
closes #5319
> <HighlightInit> transpilation

- docs-content/getting-started/fullstack-frameworks/next-js.md
- highlight.io/components/QuickstartContent/frontend/next.tsx
- highlight.io/components/QuickstartContent/frontend/shared-snippets.tsx
> Cleaning up Next.js quickstart

- backend/model/model.go
- backend/opensearch/opensearch.go
- backend/private-graph/graph/generated/generated.go
- backend/private-graph/graph/schema.graphqls
- backend/private-graph/graph/schema.resolvers.go
- backend/public-graph/graph/resolver.go
- backend/public-graph/graph/resolver_test.go
- frontend/src/graph/generated/hooks.tsx
- frontend/src/graph/generated/operations.tsx
- frontend/src/graph/generated/schemas.tsx
- frontend/src/graph/operators/mutation.gql
This PR fixes updating the error group state. Additionally, it makes the value more typesafe by using just the graphql enum. 
Fixes #5357
https://www.loom.com/share/c8495d485fad4f90aedf84e921deece2
N/A
> fix resolving errors

- backend/public-graph/graph/resolver.go
- introduced with billing changes
- tested locally
- no
> fix nil deref

- frontend/src/pages/ErrorsV2/ErrorQueryBuilder/components/QueryBuilder/QueryBuilder.tsx
- frontend/src/pages/Sessions/SessionsFeedV3/SessionQueryBuilder/components/QueryBuilder/QueryBuilder.tsx
hey @Vadman97 
This PR is the first pass for the bug fix on the session/error datePicker
#5353
> fix: set default selected date range from params

- backend/pricing/pricing.go
- if on the free tier, return the included amount as the limit
- click tested free, paid unlimited, and paid limited cases
- no
> fix billing limit calcs for banner for free tier

- docs-content/general/6_product-features/1_session-replay/1_overview.md
- docs-content/general/6_product-features/1_session-replay/graphql.md
- docs-content/getting-started/3_client-sdk/7_replay-configuration/recording-network-requests-and-responses.md
> GraphQL, not GraphQl

- docs-content/getting-started/3_client-sdk/7_replay-configuration/canvas.md
Fix some grammatical issues and make the overview more concise.
CI
No
> update canvas docs

- docs-content/general/changelog/changelog-19.md
> Changelog 19: Video Embed

- backend/worker/worker.go
Reduce the number of goroutines as we decrease the number of kafka partitions.
prod
https://highlightcorp.slack.com/archives/C02CJANPHQS/p1684883468832739
> update number of goroutine kafka consumers

- frontend/index.html
- highlight.io/components/common/Buttons/PrimaryButton.tsx
- highlight.io/pages/_document.js
Update the gtag references to the new tag.
> update google tag manager setup

- backend/public-graph/graph/resolver.go
Needed to store changing media asset urls.
[See Slack for motivation](https://highlightcorp.slack.com/archives/C03R2TXAVL2/p1685073958522869)
N/A
N/A
> enable asset storage for motion

- docs-content/sdk/cloudflare.md
Updates documentation for the cloudflare SDK.
[Preview](https://vercel.com/highlight-run/highlight-landing/4MRh9GTAebuZ1A4S7Lv2UgmrDxJc)
No
> update cloudflare sdk docs

- highlight.io/styles/globals.scss
> Mobile iframe / img tags were overflowing

- vercel.json
Disable commit notifications per https://vercel.com/guides/how-to-prevent-vercel-github-comments
No
No
> add vercel.json to silence commit notifications

- highlight.io/components/Animate.tsx
- highlight.io/components/Competitors/ComparisonTable.tsx
- highlight.io/pages/[slug].tsx
- highlight.io/pages/compare/[slug].tsx
Fixed extremely large images on competitor pages.
> Competitor Page Image Fix

- .vscode/settings.json
Fixes auto imports from packages/ui no longer working in vscode.
> Remove auto import exclusion

- .github/workflows/backend.yml
There appears to be an issue with the latest version of golanglint-ci (https://github.com/golangci/golangci-lint/issues/3862) and it's failing our builds ([example](https://github.com/highlight/highlight/actions/runs/5151066157/jobs/9275930200?pr=5518)).
Build passes
N/A
> pin golangci-lint version

- backend/public-graph/graph/resolver.go
We are noticing that sometimes opensearch can be out of sync with postgres (#5511, #5454, #5301) due to the fact that the default behavior is to perform the updates asynchronously.
Per this [slack](https://highlightcorp.slack.com/archives/C02CJANPHQS/p1685660764377189) conversation, we would like to make all opensearch updates synchronous. The reasoning behind doing async updates predates having kafka to throttle updates. Now that we have kafka, we would like to switch to only doing sync updates to see if that fixes our opensearch data quality problems. 
Since the public resolver is where we'll experience the most amount of updates, we want to make this change independently so we can monitor the effect it has on our opensearch cluster (and roll back if it's problematic).
Confirmed …
> make all public resolver opensearch updates be synchronous

- highlight.io/components/Home/FeatureCarousel/CarouselCard.tsx
- highlight.io/components/Home/Home.module.scss
- highlight.io/components/Home/LandingInfoRow.tsx
- highlight.io/components/Products/InfoRow.tsx
Made suggested changes to the home page regarding alignment of various elements. Also fixed unusually large images.
> home page changes + image fixes

- frontend/src/pages/Auth/MultiFactor.tsx
- frontend/src/pages/Auth/ResetPassword.tsx
- frontend/src/pages/Auth/SignIn.tsx
- frontend/src/pages/Auth/SignUp.tsx
Adds some missing tracking events for our pre-auth pages.
N/A - only tracking changes
> Add tracking for auth pages

- docs-content/general/changelog/1_overview.md
> Updating Changelog overview

- .github/workflows/docker.yml
Fix bash logic in publishing docker images.
> correctly publish docker images

- backend/public-graph/graph/resolver.go
- fix copy paste error in the errors pricing config, use the correct meter
- click test
- no
> use correct lookup for error meter

- internal-docs/prds/002-feed-clickhouse-migration.md
- internal-docs/rfcs/002-feed-clickhouse-migration.md
Adds an RFC for migrating opensearch usage to clickhouse.
> RFC: Session/Error Feeds ClickHouse Migration

- backend/opensearch/opensearch.go
- backend/public-graph/graph/resolver.go
This reverts commit 4d2ff3c0320e27549528aa9add4bc03d1568c2b4.
> Revert "Revert "make PushPayload processing use async opensearch updates (#5568)" (#5580)"

- internal-docs/development/organizing-code.md
This PR creates some documented opinions on how to organize our backend code as a result of a retrospective.
[View Rendered](https://github.com/highlight/highlight/blob/d406f9ba1609354b5babb65ffaa355191d793a30/internal-docs/development/organizing-code.md)
N/A
> add doc on organizing backend code

- README.md
Moves all-contributors higher on the readme.
clicktest. visualtest.
no
> Move all contribs higher on the readme

- docs-content/general/1_welcome.md
- docs-content/general/4_company/open-source/hosting/2_self-host-hobby.md
- highlight.io/pages/pricing/index.tsx
Fixes self host hobby links in our docs.
Clicktest.
no
> Fix self hosted hobby links

- backend/hubspot/hubspot.go
Resolve an issue that is causing our hubspot backend integration to create duplicate companies.
Here's the idea of what's going on:
1. new user fills out about you and frontend calls `UpdateAdminAndCreateWorkspace`. user has ad blocker so the hubspot frontend snippet does not create a contact / company.
2. backend `UpdateAdminAndCreateWorkspace` calls `CreateContactForAdmin` and `CreateCompanyForWorkspace` which both happen asynchronously because they are piped thru kafka to allow polling hubspot, since the backend does not know that the frontend has an ad blocker that prevented the frontend from creating a contact / company.
3. the hubspot kafka tasks both run concurrently, one polling for 3 minutes for a `contact` and the other for a `company`.
4. after 3 minutes, both polling loops …
> fix duplicate hubspot companies being created

- backend/public-graph/graph/resolver.go
- backend/worker/kafka_worker.go
Fixup to #5689. PushPayloads from old clients were causing a panic due to nil pointer dereference.
N/A
Rewinding kafka offset.
> fix pushpayload processing of messages with nil websocket data

- docs-content/general/1_welcome.md
Replaced existing demo video with another [embedded video](https://www.youtube.com/watch?v=EvGsmbt0F7s)
[View the docs link here](https://highlight-landing-poj6w6pr6-highlight-run.vercel.app/docs)
Click Testing
> New Demo Video in Docs

- backend/private-graph/graph/resolver.go
Missed an auth error from #5821.
See [error in Highlight](https://app.highlight.io/1/errors/kZ35faADwk3q0K8s6geCkFxG53ux?page=2&query=and%7C%7Cerror_state%2Cis%2COPEN%7C%7Cerror-field_timestamp%2Cbetween_date%2C2023-06-10T17%3A28%3A58.784Z_2023-07-10T17%3A28%3A58.784Z).
Auth error should be grouped.
N/A
> normalize auth error

- .github/ISSUE_TEMPLATE/ui_package.md
Creates an issue template for requesting changes to the UI package.
N/A
N/A
> Create an issue template for UI package requests

- backend/private-graph/graph/schema.resolvers.go
Normalize more auth errors.
Fixes #5895
Error is resolved in Highlight
N/A
> normalize more auth errors

- backend/hubspot/hubspot.go
Add additional metadata reported to hubspot.
Will be checking hubspot.
No
> report workspace trial end to hubspot

- highlight.io/components/common/Navbar/Navbar.module.scss
- highlight.io/components/common/Navbar/Navbar.tsx
- highlight.io/components/common/Navbar/ResourceDropdown.tsx
Removed Blog button from Navbar and placed it in the resource dropdown
> removed blog from navbar

- backend/private-graph/graph/generated/generated.go
- backend/private-graph/graph/schema.graphqls
- backend/private-graph/graph/schema.resolvers.go
- frontend/src/components/Header/CommandBar/CommandBar.tsx
- frontend/src/graph/generated/hooks.tsx
- frontend/src/graph/generated/operations.tsx
- frontend/src/graph/operators/query.gql
@jay-khatri recently noticed a stutter when loading app.highlight.io
Turns out, this was due to some logic in the old command bar for processing suggested workspaces.
The change removes the workspace grouping logic since we now auto-populate project names in the about you form.
[Reflame preview](https://preview.highlight.io/1/sessions?page=1&query=and%7C%7Ccustom_processed%2Cis%2Ctrue%7C%7Ccustom_created_at%2Cbetween_date%2C2023-06-13T22%3A49%3A05.448Z_2023-07-13T22%3A49%3A05.448Z&%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22sjc%22%2C%22variantId%22%3A%2201H58Q09N1S5MAPGSB47P8328N%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22vadim%2Ffix-load-perf%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C% …
> improve old commandbar performance

- frontend/src/graph/generated/schemas.tsx
- frontend/src/pages/ErrorsV2/ErrorInstances/ErrorInstancesTable.tsx
Some design updates requested by Julian.
Before:
After:
N/A
> style updates to error instances

- backend/private-graph/graph/schema.resolvers.go
- frontend/src/pages/ErrorsV2/ErrorInstance/AiErrorSuggestion.tsx
- frontend/src/pages/HaroldAISettings/HaroldAISettings.tsx
- frontend/src/pages/Player/RightPlayerPanel/components/SessionInsights/SessionInsights.tsx
- packages/ai/src/prompts.ts
- packages/ai/src/server.ts
- packages/ai/src/utils.ts
https://github.com/highlight/highlight/issues/5880
https://github.com/highlight/highlight/issues/5875
Also, changed up the session insights logic and prompt, so that identify and authentication events are excluded. Also chunked a session up and found the most eventful parts of the session for feeding into chatgpt instead of all sessions. 
Visual changes
> Fixed copy on AI components and linked blog post

- blog-content/building-our-logging-integrations.md
- blog-content/java-sdk-open-source-contribution.md
Adds a blog post on how we built our logging integrations.
Based on https://docs.google.com/document/d/1TJErgh2lwhKZI9SCUkQAWhoHjp78wonOtLLs59frEDM/edit
[Blog vercel preview](https://highlight-landing-j7v9ssj72-highlight-run.vercel.app/blog/building-our-logging-integrations)
No
> add a blog post on building logging integrations

- frontend/src/pages/ErrorsV2/ErrorInstance/ErrorInstance.tsx
Ungating the button to see all error instances (see #5830).
See All Instances button shows for all users.
N/A
> ungate instances view

- e2e/nextjs/src/app/another-page/page.tsx
- e2e/nextjs/src/app/page.tsx
> Next <Link> test

- docs-content/general/6_product-features/1_session-replay/1_overview.md
> Spelling: GrqphQL to GraphQl

- highlight.io/components/common/Navbar/ResourceDropdown.tsx
Update stale reference to status page (old one does not have working SSL).
Clicking link in [vercel preview](https://highlight-landing-e6u0t616t-highlight-run.vercel.app/).
No
> update status page

- docs-content/general/6_product-features/3_general-features/alerts.md
Fixed a typo in the docs
Github's markdown preview
No
> Fix broken link syntax in the docs

- highlight.io/components/Launch/DayFour.tsx
- highlight.io/pages/launch-week-2.tsx
Updated launch day to the correct day (4)
Click Testing
> Launch day 4 edits

- backend/worker/worker.go
- as `user_journey_steps` grows, this is using an increasing amount of CPU in RDS
- will be replacing this with a batched query, but wanted to disable this for now as CPU is very high in prod at the moment
- will monitor prod after deployment
- no
> remove normalness query in session processing for now

- backend/lambda-functions/sessionInsights/handlers/handlers.go
- not expecting any errors from the child lambdas called, so we should rethrow any errors
- this wasn't causing an issue, but I wanted to do this before sending out emails in case there's an issue with one project; would rather not send out a badly formatted email
- will retest after deployment
- no
> rethrow lambda errors

- frontend/src/components/Header/Header.tsx
Fix text for the maintenance banner.
Text only
No
> fixup! add a dynamic maintenance banner (#6032)

- frontend/src/components/QueryBuilder/QueryBuilder.tsx
- frontend/src/pages/Player/Toolbar/TimelineIndicators/TimelineBar/TimelineBar.tsx
- packages/ui/src/components/DatePicker/PreviousDateRangePicker.tsx
Fix a few frontend errors accessing invalid attributes.
https://app.highlight.io/1/errors/m6jXwd0ITu9GXmz7hiwE0qoT8Quv
https://app.highlight.io/1/errors/SuthbHDniS1eLCoJ6pOO9F95oC0g
https://app.highlight.io/1/errors/u0pCiHvuyIPMT1DnIcedBvzvFi4I
https://app.highlight.io/1/errors/PniyGnk6tM33otORlNE52yo2Cjnt
Local deploy reproducing frontend crashes.
No
> fix frontend errors

- .github/workflows/turbo.yml
- backend/private-graph/graph/schema.resolvers.go
- backend/public-graph/graph/resolver.go
- backend/store/sessions.go
- sdk/client/src/listeners/error-listener.tsx
- sdk/firstload/CHANGELOG.md
- sdk/firstload/package.json
- sdk/firstload/src/__generated/version.ts
* Fixes schema bug in private graph returning `nil`
* Centralizes session queries to the store with additional logging
* Fixes browser client bug when parsing certain stack traces.
Local deploy
https://www.loom.com/share/b776f936fe064b3ba64d619dc2d7419e
Fixes #6009
Fixes #5818
> fix more bugs

- frontend/scripts/build-rrweb.mjs
- frontend/src/__generated/rr/rr.js
- frontend/src/__generated/rr/rr.min.css
- frontend/src/__generated/rr/rrTypes.js
Quick update to minimize opportunity for merge conflicts in rrweb generated modules.
Longer term, I'll be looking into how we could handle cross-repo projects natively to remove the need for these.
> Stop minifying rrweb generated modules

- highlight.io/components/QuickstartContent/backend/python/aws.tsx
- highlight.io/components/QuickstartContent/backend/python/azure.tsx
- highlight.io/components/QuickstartContent/backend/python/django.tsx
- highlight.io/components/QuickstartContent/backend/python/fastapi.tsx
- highlight.io/components/QuickstartContent/backend/python/flask.tsx
- highlight.io/components/QuickstartContent/backend/python/gcp.tsx
- highlight.io/components/QuickstartContent/backend/python/other.tsx
- highlight.io/components/QuickstartContent/backend/python/shared-snippets.tsx
Make it more obvious how to set up python logging instrumentation while using loguru.
See https://highlightcorp.slack.com/archives/C059NFA87EG/p1690328441098099
Vercel preview.
No
> clarify loguru logging configuration

- highlight.io/components/QuickstartContent/frontend/shared-snippets.tsx
Docs were incorrect for angular since they referenced `useEffect`.
Vercel preview.
No
> improve frontend docs for angular

- highlight.io/components/common/Navbar/Navbar.tsx
Removed Launch Week Banner
Click-testing and observing that the banner was no longer present.
> removed launch banner

- backend/hubspot/hubspot.go
- backend/private-graph/graph/schema.resolvers.go
- backend/worker/worker.go
Send additional data to hubspot.
Fix company -> contact association in hubspot.
Fix situations where we update the wrong company data because of merged companies.
Local deploy enabling hubspot.
No
> improve hubspot data

- backend/hubspot/hubspot.go
- backend/worker/worker.go
Correcting issues with hubspot data reporting.
no errors reporting trial date
No
> fix hubspot count and date reporting

- backend/otel/extract.go
- backend/otel/extract_test.go
- sdk/highlight-ruby/highlight/lib/highlight.rb
This PR rewrites service name if it's invalid (see [slack](https://highlightcorp.slack.com/archives/C02CJANPHQS/p1690575385382839)).
Unit test added
N/A
> rewrite service name if is invalid

- docs-content/getting-started/3_client-sdk/7_replay-configuration/1_overview.md
Fix broken link on SDK config page
click
no
> Fix broken link on SDK config page

- docs-content/getting-started/backend-logging/5_hosting/1_overview.md
- docs-content/getting-started/backend-logging/5_hosting/render.md
- highlight.io/components/Integrations/integration.ts
- highlight.io/components/QuickstartContent/logging/hosting/render.tsx
Per request, updating docs to reflect the correct name of https://render.com/
CI Preview
No
> update render (hosting) docs

- backend/hubspot/hubspot.go
- backend/private-graph/graph/resolver.go
- backend/redis/utils.go
Trying to figure out why hubspot tasks take a long time.
Monitoring hubspot tasks.
No
> troubleshoot hubspot slowdown

- backend/kafka-queue/kafkaqueue.go
- backend/worker/kafka_worker.go
Seeing long flush times.
https://highlightcorp.slack.com/archives/C02CJANPHQS/p1690918841068819
N/A
Monitoring release.
> reduce logs flush size

- frontend/src/__generated/rr/rr.js
- frontend/src/hooks/useFeatureFlag/useFeatureFlag.ts
- sdk/client/src/graph/generated/operations.ts
- sdk/client/src/graph/generated/schemas.ts
Feature flag was off for session insights. This turns it on
> Enable AI session insight

- backend/otel/otel.go
- backend/otel/otel_test.go
https://highlightcorp.slack.com/archives/C02CJANPHQS/p1690988700412539?thread_ts=1690985864.381839&cid=C02CJANPHQS
> disable writing traces

- backend/public-graph/graph/resolver.go
- main queue has more producing than consuming, bulk of time is spent handling push payload messages
- for longer running push payloads, seeing lots of time spent in the `parseEvents` code
- made sure push payloads were still working locally
- no
> push payload perf - hoist settings lookup out of loop

- backend/worker/kafka_worker.go
There's a lot of noise spamming customers due to #6181. This is a hack to filter that out until we can fix the root cause.
Confirmed this only filters out the expected strings.
N/A
> Filter out nextjs SDK noise

- backend/model/model.go
- backend/store/services.go
- backend/store/services_test.go
- backend/worker/kafka_worker.go
Reverts highlight/highlight#6204
> Revert "create service record on log ingest"

- backend/clickhouse/logs.go
- unclear from the docs if this will work with batch inserts + native protocol, but can try it out
- will monitor for `too many parts` errors in prod
- no
> try async insert

- backend/private-graph/graph/schema.resolvers.go
- backend/public-graph/graph/resolver.go
- backend/worker/kafka_worker.go
- backend/worker/worker.go
Reverts highlight/highlight#6208
> Revert "unrevert session consumer / producer"

- docs-content/getting-started/fullstack-frameworks/remix.md
- sdk/highlight-remix/CHANGELOG.md
- sdk/highlight-remix/package.json
I goofed and didn't update the `files` attribute in `package.json` to include the new `*.d.ts` files.
> Adding *.d.ts files

- .github/workflows/ruby.yml
- sdk/highlight-ruby/highlight/test/highlight_test.rb
This PR sets up a ruby SDK workflow. Currently it only runs the test suite but I plan on extending it for publishing new version of the SDK as well as linting.
Confirmed that the `Ruby SDK / Ruby SDK` build step runs and passes.
N/A
> github workflow for ruby

- backend/clickhouse/logs.go
- use the `async_insert` and `wait_for_async_insert` settings correctly when writing to Clickhouse
- using `Exec` instead of `AsyncInsert` because the latter does not support an `args` argument and `sqlbuilder.Interpolate` was not working with `map` fields
- single insert takes much longer (~6s vs 200ms from local) when waiting for async insert, but this is in line with our 5s batched queue timeout and will help create backpressure when writing too quickly to Clickhouse
- validated before / after a small benchmark test against prod to verify that logs were written and the number of active parts was reasonable (<200); will turn this into a formal benchmark in a bit
```
func TestBatchWriteLogs(b *testing.T) {
ctx := context.Background()
const workers = 32
const batchesPerWorker = 100
const …
```
> write logs async

- frontend/src/pages/LogsPage/LogsTable/LogDetails.tsx
- frontend/src/pages/LogsPage/LogsTable/LogsTable.tsx
- frontend/src/pages/LogsPage/SearchForm/utils.test.ts
- frontend/src/pages/LogsPage/SearchForm/utils.ts
- frontend/src/pages/LogsPage/utils.test.ts
- frontend/src/pages/LogsPage/utils.ts
Fixes surfacing of matched attributes on nested/wildcard attributes and highlighting on wildcard attributes.
Click test + unit tests.
N/A
> Fix nested and wildcard attribute matching on logs

- backend/otel/otel.go
> remove log line that is causing a lot of noise for our project

- frontend/src/__generated/index.css
- frontend/src/__generated/ve/components/FeedResults/FeedResults.css.js
- frontend/src/components/FeedResults/FeedResults.css.ts
- frontend/src/components/FeedResults/FeedResults.tsx
- frontend/src/components/QueryBuilder/QueryBuilder.tsx
- frontend/src/context/SearchState.ts
- frontend/src/pages/Alerts/LogAlert/LogAlertPage.tsx
- frontend/src/pages/ErrorsV2/SearchPanel/SearchPanel.tsx
- frontend/src/pages/LogsPage/LogsPage.tsx
- frontend/src/pages/LogsPage/SearchForm/SearchForm.tsx
- frontend/src/pages/LogsPage/constants.ts
- frontend/src/pages/LogsPage/useGetLogs.ts
- frontend/src/pages/Sessions/SessionsFeedV3/SessionsFeedV3.tsx
- frontend/src/util/graph.tsx
- frontend/src/util/search.ts
- packages/ui/src/components/DatePicker/PreviousDateRangePicker.stories.tsx
- packages/ui/src/components/DatePicker/PreviousDateRangePicker.tsx
- packages/ui/src/components/DatePicker/utils.ts
- packages/ui/src/components/index.ts
Poll for new sessions, errors, and logs and display a button when there are new results
that updates the queried time interval. 
https://www.loom.com/share/0c7ce5a684294081ba2b0743a61710d0
No
> poll for new sessions, errors, and logs and display a button when new results exist

- backend/http/logging.go
- backend/http/logging_test.go
- docs-content/getting-started/backend-logging/2_js/pino.md
- highlight.io/components/QuickstartContent/QuickstartContent.tsx
- highlight.io/components/QuickstartContent/logging/js/pino.tsx
- highlight.io/components/QuickstartContent/logging/js/winston.tsx
- highlight.io/package.json
- highlight.io/pages/api/sitemap.tsx
- sdk/highlight-go/log/util.go
- yarn.lock
Ingest pino logs in structured format so that individual messages appear as logs in highlight.
[New docs here.
](https://highlight-landing-egqtj0q9m-highlight-run.vercel.app/docs/getting-started/backend-logging/js/pino)
> support pino.js logging

- docs-content/getting-started/3_client-sdk/7_replay-configuration/monkey-patches.md
Fix typo in monkey patches docs
n/a
n/a
> Fix typo in monkey patches docs

- docs-content/getting-started/fullstack-frameworks/next-js.md
closes #6321 
[![image](https://github.com/highlight/highlight/assets/878947/6ce3e63e-cf72-4d05-9c4e-3afe5ea925ce)](https://user-images.githubusercontent.com/878947/260533717-80fb8f3f-df10-45a3-84c6-e54e1f68f623.png)
> Clear up App vs Page Router confusion

- docs-content/getting-started/fullstack-frameworks/next-js.md
Suggests that only app router users use `instrumentation.ts` for simplicity.
clicktest.
n/a
> Update verbiage for page router usage

- backend/hubspot/hubspot.go
Seeing a bunch of hubspot update failures due to an issue in the logic.
Correctly setting hubspot properties attribute.
No
> fix hubspot update failure

- frontend/src/__generated/index.css
- frontend/src/pages/Alerts/AlertEnableSwitch/AlertEnableSwitch.module.css
- frontend/src/pages/Alerts/AlertEnableSwitch/AlertEnableSwitch.tsx
- frontend/src/pages/Alerts/Alerts.tsx
- frontend/src/pages/Alerts/EditAlertsPage.tsx
- frontend/src/pages/Alerts/EditMonitorPage.tsx
- frontend/src/pages/Alerts/ErrorAlert/ErrorAlertPage.tsx
- frontend/src/pages/Alerts/NewMonitorPage.tsx
Reverts highlight/highlight#6369
> Revert "Fix consistency bugs and style alert list page"

- backend/hubspot/hubspot.go
Hubspot contact -> company association was failing for contacts created client side
because we would not have their hubspot ID stored.
checking that association path would update the hubspot contact id locally 
No
> make hubspot logic for associating clients more robust

- frontend/src/__generated/index.css
- frontend/src/__generated/ve/components/FeedResults/FeedResults.css.js
- frontend/src/components/FeedResults/FeedResults.css.ts
- frontend/src/components/FeedResults/FeedResults.tsx
- frontend/src/pages/ErrorsV2/SearchPanel/SearchPanel.tsx
- frontend/src/pages/LogsPage/LogsPage.tsx
- frontend/src/pages/LogsPage/useGetLogs.ts
- frontend/src/pages/Sessions/SessionsFeedV3/SessionsFeedV3.tsx
- frontend/src/util/search.ts
* Updates styles per latest feedback from @julian-highlight 
* Fixes async race condition in the frontend that would cause 'more' button to flicker and show incorrect values
[Reflame preview](https://preview.highlight.io/1/sessions?page=1&query=and%7C%7Ccustom_processed%2Cis%2Ctrue%7C%7Ccustom_created_at%2Cbetween_date%2C2023-07-25T05%3A15%3A00.490Z_2023-08-24T05%3A15%3A00.490Z&%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22sjc%22%2C%22variantId%22%3A%2201H8JZCYQBN0QGSS6VFCT48WKQ%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%226396-update-more-logs-design%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D)
No
> update more logs design

- docs-content/getting-started/fullstack-frameworks/remix.md
- e2e/remix/app/entry.server.tsx
> Remix streaming error handling

- e2e/nextjs/package.json
I had some trouble deploying to Vercel. This fixes it.
> Cleaning up Vercel deploy

- docs-content/getting-started/fullstack-frameworks/next-js.md
> Dropped text

- backend/clickhouse/sessions.go
- previous implementation was buggy leading to invalid queries
- no
> use sqlbuilder functions to combine and/or exprs

- .github/PULL_REQUEST_TEMPLATE.md
For frontend changes, we should encourage tagging @julian-highlight ( the design team )
to make sure we have a better feedback loop on implementing from figma.
N/A
N/A
> add design feedback to pull request template

- sdk/highlight-java/highlight-common/pom.xml
- sdk/highlight-java/highlight-log/highlight-log-api/pom.xml
- sdk/highlight-java/highlight-log/highlight-log-java/pom.xml
- sdk/highlight-java/highlight-log/highlight-log-log4j/pom.xml
- sdk/highlight-java/highlight-log/pom.xml
- sdk/highlight-java/highlight-sdk/pom.xml
- sdk/highlight-java/pom.xml
Fixing a maven version mismatch in deployment step.
Also moved the description to the right project.
Locally
A deployment is needed to fix this issue on maven central.
> Fix: maven deploy undefined version in pom.xml

- sdk/highlight-apollo/package.json
- sdk/highlight-nest/package.json
- sdk/highlight-next/package.json
- sdk/highlight-node/CHANGELOG.md
- sdk/highlight-node/package.json
- sdk/highlight-node/src/client.ts
- sdk/highlight-node/src/types.ts
- sdk/highlight-remix/package.json
This PR adds an options to enable node fs instrumentation. default value is false
/claim #6553
> fix: node fs instrumentation

- backend/hubspot/hubspot.go
* Use the [correct hubspot api](https://legacydocs.hubspot.com/docs/methods/companies/get-all-companies) to fetch all companies
* Account for possible hubspot rate limiting
Now fetching all companies correctly
No
No
> properly get all hubspot companies

- frontend/src/__generated/index.css
- frontend/src/pages/ErrorsV2/ErrorInstances/ErrorInstances.css.ts
Bug Fix : #6551 
Search Button alignment fix
> search button alignment fix

- backend/clickhouse/query.go
- query for logs / traces with an inner query that only selects `Timestamp, UUID` to avoid loading extra data that isn't needed. tested in prod and saw a roughly 30x reduction in the amount of data loaded for longer time range queries
```
SELECT Timestamp, UUID, SeverityText, Body, LogAttributes, TraceId, SpanId, SecureSessionId, Source, ServiceName, ServiceVersion 
FROM logs 
WHERE ProjectId = 1 
AND (Timestamp, UUID) IN (
SELECT Timestamp, UUID 
FROM logs 
WHERE ProjectId = 1 
AND Timestamp <= '2023-09-13 17:27:50' 
AND Timestamp >= '2023-09-13 16:27:50' 
ORDER BY Timestamp DESC, UUID DESC 
LIMIT 51) 
ORDER BY Timestamp DESC, UUID DESC
```
- remove the `date -> toDateTime -> toUInt64` conversion because we can compare `Timestamp` directly and it seems to be a bit faster
- click tested …
> tuning clickhouse logs / traces query

- frontend/src/pages/Auth/InviteTeam.tsx
- frontend/src/routers/ProjectRouter/ProjectRedirectionRouter.tsx
Fixes an issue where users were being redirected to the wrong page after submitting the invite team form in onboarding.
Local + PR preview click tests.
N/A - all client-side logic.
N/A
> Fix onboarding redirect after invite team form

- docs-content/general/4_company/1_values.md
- docs-content/general/4_company/product-philosophy.md
- frontend/src/components/CreateAlertButton/CreateAlertButton.tsx
- minor edits on proxy docs
- as discussed with @et, restructures our values & philosophy docs. very open to feedback.
clicktest
n/a
> Update Philosophy / Values Docs

- backend/private-graph/graph/schema.resolvers.go
- return specific fields for demo project
- made demo project id = 1 locally, click tested
- no
- no
> fix demo fields

- backend/private-graph/graph/resolver.go
Adds a new promo code for a potential collaboration with usegolang.com.
N/A
No
No
> add free trial sign up promo code

- docs-content/general/6_product-features/3_general-features/services.md
Remove confusing sentence from service documentation
View in preview
N/A
N/A
> Update service documentation

- highlight.io/components/QuickstartContent/logging/hosting/fly-io.tsx
Updates mispelling of fly.io in docs.
N/A
No
No
> update spelling of fly docs

- .github/workflows/deploy.yml
- backend/lambda-functions/deleteSessions/deleteSessionBatchFromOpenSearch/main.go
- backend/lambda-functions/deleteSessions/deleteSessionBatchFromPostgres/main.go
- backend/lambda-functions/deleteSessions/deleteSessionBatchFromS3/main.go
- backend/lambda-functions/deleteSessions/getSessionIdsByQuery/main.go
- backend/lambda-functions/deleteSessions/sendEmail/main.go
- backend/lambda-functions/digests/getDigestData/main.go
- backend/lambda-functions/digests/getProjectIds/main.go
- backend/lambda-functions/digests/sendDigestEmails/main.go
- backend/lambda-functions/journeys/updateNormalnessScores/main.go
- backend/lambda-functions/sessionExport/handlers/handlers.go
- backend/lambda-functions/sessionExport/main.go
- backend/lambda-functions/sessionExport/saveSessionExport/main.go
- backend/lambda-functions/sessionExport/sendEmail/main.go
- backend/lambda-functions/sessionInsights/getSessionInsightsData/main.go
- backend/lambda-functions/sessionInsights/sendSessionInsightsEmails/main.go
- backend/private-graph/graph/schema.resolvers.go
- frontend/src/pages/Player/Toolbar/ToolbarControlBar/ToolbarControlBar.tsx
- frontend/src/pages/ProjectSettings/SessionExportForm/SessionExportForm.tsx
- sdk/highlight-go/highlight.go
- sdk/highlight-go/otel.go
* fixes incorrect session export sql query that would not update existing export records
* adds flush logic to our go sdk and has lambdas flush all data
* updates styling inconsistency with session exports feature on frontend
Manual deploy of lambdas
No
No
> fix session export and flush lambdas

- .github/workflows/stale.yml
* Make stale bot not affect customer-reported tickets
* Make stale bot ignore issues with milestones / assignees
* Increase stale -> close timeout
> update stale bot behavior

- backend/model/model.go
Speed up DB migration by limiting the `error_object_embeddings_partitioned` partition creation
to the ones that are actually needed, rather than iterating over existing ones.
No
No
> speed up db migration

- sdk/highlight-next/package.json
added client.d.ts to "files" section of package.json
> fixes highlight/highlight#6716

- backend/clickhouse/errors.go
- backend/migrations/cmd/backfill-errors-clickhouse-v2/main.go
- frontend/src/pages/ErrorsV2/ErrorInstances/ErrorInstances.tsx
- packages/ui/src/components/SwitchButton/SwitchButton.tsx
Fix logic for selecting sessions errors with a session to include a check for exclusion.
https://www.loom.com/share/1bd2cb38edd6400ba53814262fbb38ec
Will be using the backfill datasync queue migration.
No
> fix error with sessions filter

- backend/clickhouse/migrations/000043_create_traces_sampling_table.down.sql
- backend/clickhouse/migrations/000043_create_traces_sampling_table.up.sql
- backend/clickhouse/migrations/000044_create_traces_sampling_mv.down.sql
- backend/clickhouse/migrations/000044_create_traces_sampling_mv.up.sql
- backend/clickhouse/migrations/000045_create_trace_attributes.down.sql
- backend/clickhouse/migrations/000045_create_trace_attributes.up.sql
- backend/clickhouse/migrations/000046_create_trace_key_values.down.sql
- backend/clickhouse/migrations/000046_create_trace_key_values.up.sql
- backend/clickhouse/migrations/000047_create_trace_keys.down.sql
- backend/clickhouse/migrations/000047_create_trace_keys.up.sql
- backend/clickhouse/migrations/000048_create_trace_keys_mv.down.sql
- backend/clickhouse/migrations/000048_create_trace_keys_mv.up.sql
- backend/clickhouse/migrations/000049_create_trace_key_values_mv.down.sql
- backend/clickhouse/migrations/000049_create_trace_key_values_mv.up.sql
- backend/clickhouse/migrations/000050_create_trace_attributes_mv.down.sql
- backend/clickhouse/migrations/000050_create_trace_attributes_mv.up.sql
- backend/clickhouse/migrations/000051_create_trace_state_mv.down.sql
- backend/clickhouse/migrations/000051_create_trace_state_mv.up.sql
- backend/clickhouse/migrations/000052_create_trace_span_name_mv.down.sql
- backend/clickhouse/migrations/000052_create_trace_span_name_mv.up.sql
- backend/clickhouse/migrations/000053_create_trace_span_kind_mv.down.sql
- backend/clickhouse/migrations/000053_create_trace_span_kind_mv.up.sql
- backend/clickhouse/migrations/000054_create_trace_service_name_mv.down.sql
- backend/clickhouse/migrations/000054_create_trace_service_name_mv.up.sql
- backend/clickhouse/migrations/000055_create_trace_service_version_mv.down.sql
- backend/clickhouse/migrations/000055_create_trace_service_version_mv.up.sql
- similar to logs, add materialized views for trace attributes, keys, values for better performance for search suggestions
- confirmed that all tables were being populated locally
- no
- no
> add materialized view for traces perf

- backend/store/error_groups.go
- backend/store/error_groups_test.go
- frontend/src/pages/ErrorsV2/ErrorInstances/ErrorInstances.tsx
* fixes backend error instances filter
* fixes frontend pagination bug
New unit test
https://www.loom.com/share/87e79755e5ae4b39aedc585450688ef2
No
No
> additional improvements to error filtering

- backend/main.go
- backend/pricing/pricing.go
- backend/util/recovery.go
* fix bug referencing incorrect limit variable in stripe update
* recover and flush logs on worker panics
Local backend deploy running the stripe update worker
No
No
> fix nil ptr reference in stripe update

- frontend/src/components/Header/Header.tsx
- frontend/src/components/Header/components/ProjectPicker/ProjectPicker.tsx
- frontend/src/hooks/useProjectId.ts
- frontend/src/pages/Landing/Landing.tsx
- frontend/src/pages/NewProject/NewProjectPage.tsx
- frontend/src/pages/WorkspaceTeam/WorkspaceTeam.tsx
- frontend/src/pages/WorkspaceTeam/components/AutoJoinForm.tsx
- frontend/src/routers/AppRouter/AppRouter.tsx
Fixes bugs from #6682 
* fix white landing page background
* fix position of new workspace / new projects modal
* fix overlay of new pages over the existing ones
Before
After
Before
After
No
Yes
> fixup styling of new workspace page

- backend/model/model.go
- backend/private-graph/graph/generated/generated.go
- backend/private-graph/graph/schema.graphqls
- backend/private-graph/graph/schema.resolvers.go
- frontend/src/graph/generated/hooks.tsx
- frontend/src/graph/generated/operations.tsx
- frontend/src/graph/generated/schemas.tsx
- frontend/src/graph/operators/query.gql
- frontend/src/pages/ErrorsV2/ErrorShareButton/ErrorShareButton.tsx
- frontend/src/pages/Player/SessionShareButton/SessionShareButtonV2.tsx
Adds a workspace feature flag to disable unlisted session / error sharing.
Validates that the OpenAI feature flag can only be adjusted by workspace admins.
https://www.loom.com/share/173972cf571d4350b81e03b1d64b46cf
Will be manually setting feature flag for relevant customer.
No
> feature flag unlisted sharing

- frontend/src/__generated/index.css
- frontend/src/__generated/ve/components/Header/styles.css.js
- frontend/src/components/Header/Header.tsx
- frontend/src/components/Header/styles.css.ts
- moves traces to a top-level header item w/ "beta" tag
https://www.loom.com/share/30f64085752b49a483d4e6fef6c5bb2e
- no
- still only enabled for highlight admins
> add beta tag to traces in header

- .github/workflows/turbo.yml
Incorrect yarn script was referenced.
Testing: forced a deploy
> fixup! fix publishing of packages (#6813)

- blog-content/session-replay-performance.md
- docs-content/general/6_product-features/1_session-replay/performance-impact.md
Added session replay perf blog post to the relevant docs page
Click-testing
No
No
> added blog post

- blog-content/session-replay-performance.md
Updated Session Replay Performance Blog
I looked at it pretty hard. 
None
No
> Session Perf Blog Edits

- blog-content/session-replay-performance.md
> update session replay performance blog

- .changeset/five-beds-shake.md
- sdk/highlight-next/config.d.ts
Fixes [#6903](https://github.com/highlight/highlight/issues/6903)
> fix export from @highlight-run/next/config

- frontend/src/pages/Traces/TracesList.tsx
- previous link was invalid, update to the getting started guide
- navigated to `https://www.highlight.io/docs/getting-started/tracing/overview`
- no
- no
> link to quickstart guide when no traces

- blog-content/session-replay-performance.md
- docs-content/getting-started/3_client-sdk/7_replay-configuration/recording-network-requests-and-responses.md
Small tweaks to session replay post
clicktest
n/a
n/a
> Small tweaks to session replay post

- backend/clickhouse/traces.go
- added a projection to the traces table that orders by projectId, traceId so queries by traceid will be much faster
- when the query orders by Timestamp, Clickhouse uses the primary index instead
- remove ordering from Clickhouse and order in code
- no
- no
> get backend to use trace id projection

- frontend/src/routers/ProjectRouter/ApplicationRouter.tsx
- removes `isHighlightAdmin` check in router
- will test w/ personal account in preview env
- no
- no
> remove isHighlightAdmin check for traces in router

- .github/workflows/java-sdk.yml
- sdk/highlight-java/highlight-common/pom.xml
- sdk/highlight-java/highlight-framework/highlight-framework-spring/pom.xml
- sdk/highlight-java/highlight-framework/pom.xml
- sdk/highlight-java/highlight-log/highlight-log-api/pom.xml
- sdk/highlight-java/highlight-log/highlight-log-java/pom.xml
- sdk/highlight-java/highlight-log/highlight-log-log4j/pom.xml
- sdk/highlight-java/pom.xml
Java SDK has not been correctly publishing to maven.
This SDK makes sure we set the version correctly and publish.
Forcing CI.
Version https://central.sonatype.com/artifact/io.highlight/highlight/0.1.0 is now published correctly.
No
No
> fix java sdk publishing

- backend/model/model.go
- backend/public-graph/graph/resolver.go
- backend/public-graph/graph/sampling.go
- backend/worker/kafka_worker.go
- backend/worker/worker.go
- frontend/src/pages/LogsPage/LogsHistogram/LogsHistogram.tsx
- frontend/src/pages/ProjectSettings/ProjectFilters/ProjectFilters.tsx
- highlight.io/pages/_app.tsx
- sdk/highlight-go/otel.go
* Fixes backend logic for reporting sampling results by project
* Only shows ingested percentages
* Fixes loading and empty states for sampling results
* Adds details on filter customization page
[Reflame preview](https://preview.highlight.io/1/settings/filters?%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201HDM7WEXX7P1F1WVA989DQN73%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22vadim%2Fupdate-filters-ui%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D).
https://www.loom.com/share/20b6a60f16454e07ba800c74c32e6e4c
No
@julian-highlight
> update filter defauls

- .reflame.config.jsonc
Noticed main was failing because of these missing entrypoints. I already had the updates ready from my debugging session yesterday, so I figured I might as well PR it. :)
> Update reflame config with new entrypoints

- .changeset/empty-mayflies-count.md
- e2e/nestjs/tsconfig.json
- e2e/nextjs/tsconfig.json
- e2e/react-router/tsconfig.json
- highlight.io/highlight.config.ts
- highlight.io/highlight.edge.config.ts
- highlight.io/package.json
- highlight.io/pages/api/docs/search/[searchValue].ts
- highlight.io/pages/api/og/blog/[slug].tsx
- highlight.io/pages/api/og/doc/[[...doc]].tsx
- highlight.io/pages/api/sitemap.tsx
- highlight.io/pages/demo.tsx
- highlight.io/tsconfig.json
- package.json
- packages/component-preview/tsconfig.json
- sdk/firstload/package.json
- sdk/highlight-next/bin/clean-dist.sh
- sdk/highlight-next/package.json
- sdk/highlight-next/src/server.ts
- sdk/highlight-next/src/util/highlight-edge.ts
- sdk/highlight-next/src/util/types.ts
- sdk/highlight-next/src/util/with-highlight-edge.ts
- sdk/highlight-next/src/util/with-highlight-nodejs-app-router.ts
- sdk/highlight-next/tsconfig.json
- tsconfig.json
- yarn.lock
Adds more instrumentation to highlight.io for demos.
Adds backend logging to show server-side logs associated to sessions.
Vercel
No
No
> add a demo page on highlight.io to demo backend logging

- frontend/src/components/DemoModal/DemoModal.tsx
> update copy for demo project email gate

- docs-content/getting-started/fullstack-frameworks/next-js/2_page-router.md
- docs-content/getting-started/fullstack-frameworks/next-js/3_app-router.md
- docs-content/getting-started/fullstack-frameworks/next-js/4_api-page-router.md
- docs-content/getting-started/fullstack-frameworks/next-js/5_api-app-router.md
- docs-content/getting-started/fullstack-frameworks/next-js/6_edge-runtime.md
- docs-content/getting-started/fullstack-frameworks/next-js/7_advanced-config.md
I noticed some capitalization issues.
> Capitalization

- .changeset/flat-pumas-grin.md
- .github/workflows/backend.yml
- .github/workflows/deploy.yml
- .github/workflows/docker.yml
- .github/workflows/force-go-release.yml
- .github/workflows/go-sdk.yml
- .github/workflows/java-sdk.yml
- .github/workflows/python.yml
- .github/workflows/ruby.yml
- .github/workflows/turbo.yml
- cypress/e2e/client.cy.js
- e2e/tests/test_oauth_graphql.py
- sdk/client/vite.config.ts
- sdk/firstload/CHANGELOG.md
- sdk/firstload/package.json
- sdk/firstload/src/__generated/version.ts
- sdk/firstload/src/index.tsx
- sdk/firstload/vite.config.ts
- sdk/highlight-apollo/CHANGELOG.md
- sdk/highlight-apollo/package.json
- sdk/highlight-nest/CHANGELOG.md
- sdk/highlight-nest/package.json
- sdk/highlight-next/CHANGELOG.md
- sdk/highlight-next/package.json
- sdk/highlight-node/CHANGELOG.md
- sdk/highlight-node/package.json
- sdk/highlight-remix/CHANGELOG.md
- sdk/highlight-remix/package.json
See https://highlightcorp.slack.com/archives/C02CJANPHQS/p1698939038456589
The client seems to be making extra requests that can cause site crashes.
> revert #7005

- sdk/highlight-java/highlight-common/src/main/java/io/highlight/sdk/common/HighlightHeader.java
- sdk/highlight-java/highlight-common/src/main/java/io/highlight/sdk/common/HighlightOptions.java
- sdk/highlight-java/highlight-common/src/main/java/io/highlight/sdk/common/Severity.java
- sdk/highlight-java/highlight-common/src/main/java/io/highlight/sdk/common/record/HighlightRecord.java
- sdk/highlight-java/highlight-log/highlight-log-java/src/main/java/io/highlight/log/java/HighlightLoggerHandler.java
- sdk/highlight-java/highlight-sdk/src/main/java/io/highlight/sdk/Highlight.java
- sdk/highlight-java/highlight-sdk/src/main/java/io/highlight/sdk/HighlightSession.java
- sdk/highlight-java/pom.xml
Ensure the Java SDK is comparible with Java 11 per customer request.
CI testing
Will be tagging and releasing a new SDK version.
No
> ensure the highlight SDK is compatible with java 11

- highlight.io/components/QuickstartContent/backend/js/express.tsx
> Update express setup documentation

- docs-content/getting-started/3_client-sdk/2_nextjs.md
- docs-content/getting-started/fullstack-frameworks/next-js/1_overview.md
- docs-content/getting-started/fullstack-frameworks/next-js/index.md
Update Nextjs Titles for Algolia indexing
click
n/a
n/a
> Update Next Titles for Algolia indexing

- packages/ui/src/components/ComboboxSelect/ComboboxSelect.tsx
- packages/ui/src/components/Dialog/Dialog.stories.tsx
This PR adds an example Reflame interaction test for the ComboboxSelect component.
We can turn a screenshot test (i.e. a React component/element exported with a name that ends in `_test`) into a interaction test by assigning a `.run` function to it. 
This function will receive the `screen` and `user` named args from [testing library](https://testing-library.com/docs/) that we can use to select elements and interact with them. It will also receive a `captureScreenshot` function that will take a screenshot to be compared to previous reference screenshots captured in the default branch.
A simple interaction test for a Switch component could look something like this: 
```js
export const Switch_test = <Switch />
Switch_test.run = async ({ user, screen, captureScreenshot }) => {
// calling …
```
> Add Reflame interaction test

- frontend/src/pages/IntegrationsPage/components/Integration.tsx
- branch was missing a return statement causing the settings component to be blank within the integration modal
- no
- no
> integration settings update page not showing

- backend/public-graph/graph/resolver.go
- backend/redis/utils.go
- another heuristic we can use to move things out of redis is the key count - when we've accumulated enough payloads, the resulting file should be large enough to move to object storage
- the current average set size is ~55 and there are a bunch of bigkeys still (many from excluded sessions since they are skipped in processing)
- tested locally to make sure the lua script is returning the correct count
- will monitor redis memory after deployment
- no
- no
> remove resources from redis w/ more than 100 keys

- highlight.io/components/QuickstartContent/self-host/shared-snippets.tsx
Just a bunch of typos in the docs.
> Typos in shared-snippets.tsx

- highlight.io/components/QuickstartContent/self-host/self-host.tsx
> Typo in self-host.tsx

- backend/model/model.go
- backend/pricing/pricing.go
- backend/pricing/pricing_test.go
- backend/private-graph/graph/generated/generated.go
- backend/private-graph/graph/model/models_gen.go
- backend/private-graph/graph/schema.graphqls
- backend/private-graph/graph/schema.resolvers.go
- backend/public-graph/graph/resolver.go
- frontend/src/__generated/rr/rr.js
- frontend/src/graph/generated/hooks.tsx
- frontend/src/graph/generated/operations.tsx
- frontend/src/graph/generated/schemas.tsx
- frontend/src/graph/operators/query.gql
- frontend/src/pages/Billing/BillingPageV2.tsx
- frontend/src/pages/Billing/UpdatePlanPage.tsx
- highlight.io/pages/pricing/index.tsx
Reflect new graduated pricing model on highlight.io/pricing
[Vercel preview](https://highlight-landing-git-vadim-pricing-landing-highlight-run.vercel.app/pricing).
No
No
> update pricing page

- frontend/src/pages/Player/MetadataBox/MetadataBox.tsx
Closes #7183 
Click test
nope!
nope!
> Using session_device_id for user filter if unidentified

- backend/private-graph/graph/schema.resolvers.go
Fixes runtime error https://app.highlight.io/1/errors/h2yfoNmOw44yHVUc1uzdeDCFba8Y/instances/226248307
Validating that the error does not happen when locally loading a network request in dev tools.
No
No
> fix slice error when fetching network metrics

- frontend/vite.config.ts
> Try removing vite less config again

- frontend/src/__generated/index.css
- frontend/src/pages/Auth/AdminForm.css.ts
- packages/ui/src/components/Form/styles.css.ts
> Fix http token error

- e2e/opentelemetry/fluentbit/compose.yml
- e2e/opentelemetry/fluentbit/fluent.conf
Setup sample fluentbit collector for validating 
the fluentbit protocol.
See https://discord.com/channels/1026884757667188757/1174995436810023013
Locally running fluentbit collector
No
No
> add example fluentbit collector

- frontend/src/components/DemoModal/DemoModal.tsx
Add logic to filter out non-work emails
n/a
n/a
n/a
> Add logic to filter out non-work emails

- backend/model/model.go
- backend/pricing/pricing.go
- backend/private-graph/graph/generated/generated.go
- backend/private-graph/graph/model/models_gen.go
- backend/private-graph/graph/schema.graphqls
- backend/private-graph/graph/schema.resolvers.go
- backend/public-graph/graph/resolver.go
- backend/public-graph/graph/resolver_test.go
- frontend/src/__generated/index.css
- frontend/src/__generated/ve/pages/Billing/BillingPageV2.css.js
- frontend/src/graph/generated/hooks.tsx
- frontend/src/graph/generated/operations.tsx
- frontend/src/graph/generated/schemas.tsx
- frontend/src/graph/operators/mutation.gql
- frontend/src/graph/operators/query.gql
- frontend/src/pages/Billing/BillingPageV2.css.ts
- frontend/src/pages/Billing/BillingPageV2.tsx
- frontend/src/pages/Billing/UpdatePlanPage.tsx
- highlight.io/pages/pricing/index.tsx
- sdk/client/src/graph/generated/operations.ts
- sdk/client/src/graph/generated/schemas.ts
Updates billing details to make base charges and discounts more obvious.
Adds trace billing limits for consistency (though they are disabled for new workspaces).
This allows us to manually turn off trace ingest for a customer if required.
Closes #5486, closes #5487
Local preview, reflame.
No
No
> update billing frontend

- deploy/Dockerfile.prod
- deploy/Dockerfile.prod.arm64
- docker/backend.Dockerfile
- fixes error during build
- ran `docker buildx build --build-arg REACT_APP_COMMIT_SHA=zane --platform linux/arm64 -f deploy/Dockerfile.prod.arm64 .` locally, was successful
- no
- no
> fix grafana datasource build issue

- backend/private-graph/graph/generated/generated.go
- backend/private-graph/graph/model/models_gen.go
- backend/private-graph/graph/schema.graphqls
- backend/private-graph/graph/schema.resolvers.go
- frontend/src/__generated/index.css
- frontend/src/__generated/ve/pages/Sessions/SessionsFeedV3/SessionQueryBuilder/components/SessionFeedConfigurationV2/SessionFeedConfigurationV2.css.js
- frontend/src/components/QueryBuilder/QueryBuilder.tsx
- frontend/src/context/SearchState.ts
- frontend/src/graph/generated/hooks.tsx
- frontend/src/graph/generated/operations.tsx
- frontend/src/graph/generated/schemas.tsx
- frontend/src/graph/operators/query.gql
- frontend/src/pages/Sessions/SessionsFeedV3/SessionQueryBuilder/SessionQueryBuilder.tsx
- frontend/src/pages/Sessions/SessionsFeedV3/SessionQueryBuilder/components/SessionFeedConfigurationV2/SessionFeedConfigurationV2.css.ts
- frontend/src/pages/Sessions/SessionsFeedV3/SessionQueryBuilder/components/SessionFeedConfigurationV2/SessionFeedConfigurationV2.tsx
- frontend/src/util/session/report.ts
Add feature flagged ability to export a session report in the following format:
filters | num_results |
-- | -- |
custom_created_at:between_date:2023-11-07T01:58:22.327Z_2023-12-07T01:58:22.328Z\|session_country:is:United States\|custom_sample:is_editable:496974bfe286b849 | 15 |
key | user_properties | num_sessions | num_days_visited | num_months_visited | avg_active_length_mins | max_active_length_mins | total_active_length_mins | avg_length_mins | max_length_mins | total_length_mins | location
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
vadim@highlight.run |   | 14 | 5 | 1 | 15.3720535714286 | 76 | 215.20875 | 1702.18174285714 | 13089 | 23830.5444 | California
[::1]:59662 |   | 1 | 1 | 1 | 3.40421666666667 | 3 | 3.40421666666667 | 9816.60625 | 9816 | 9816.60625 | …
> session feed report

- backend/clickhouse/querybuilder.go
- exists queries were not working correctly because the "IS NOT NULL" condition was added in the argument loop, and exists doesn't have any arguments
- validated exists/not exists queries with top level attributes and fields
- no
- no
> fix exists queries

- e2e/nextjs/src/app/components/log-buttons.tsx
- e2e/nextjs/src/app/layout.tsx
- e2e/nextjs/src/app/page.tsx
No production code is changed in this PR.
We got a bug report that `consoleMethodsToRecord` wasn't working correctly.
This PR adds buttons to test that.
https://discord.com/channels/1026884757667188757/1179210954836279326
> Adding buttons to test consoleMethodsToRecord

- frontend/src/pages/Auth/AdminForm.tsx
- frontend/src/pages/Player/MetadataBox/MetadataBox.tsx
* Update admin about you page to include HN
* Display the session IP address when recorded.
Reflame
No
No
> show ip and update about you

- packages/ui/src/components/ComboboxSelect/ComboboxSelect.tsx
Updates the ComboboxSelect test for the new `step` API. There's a bit of extra noise due to the lack of proper ts types, will be adding those soon!
Here's what results look like (https://github.com/highlight/highlight/pull/7315/checks?check_run_id=19536714491):
Still need to update results display to include step names. This is coming next!
Let me know what you think! 🙏
> Update combobox test for new API

- backend/email/email.go
- backend/model/model.go
- backend/pricing/pricing.go
- backend/private-graph/graph/generated/generated.go
- backend/private-graph/graph/model/models_gen.go
- backend/private-graph/graph/resolver.go
- backend/private-graph/graph/schema.graphqls
- backend/private-graph/graph/schema.resolvers.go
- backend/public-graph/graph/resolver.go
- backend/redis/utils.go
- backend/worker/worker.go
- docker/compose.yml
- e2e/tests/src/test_sdk.py
- frontend/src/graph/generated/hooks.tsx
- frontend/src/graph/generated/operations.tsx
- frontend/src/graph/generated/schemas.tsx
- frontend/src/graph/operators/query.gql
- frontend/src/pages/LogsPage/OverageCard/OverageCard.tsx
- frontend/src/pages/Sessions/SessionsFeedV3/OverageCard/OverageCard.tsx
Requires that payment details are correct to allow ingesting data.
Payment detail validity are checked based on the following criteria:
* An uncollectible invoice is present
* An open invoice with failed attempts is present
* The customer has no valid payment methods in stripe
We check these criteria as part of our stripe reporting. If an issue is detected for the first time,
the customer gets an email and has 7 days to correct the issue. If the issue is not corrected in that time,
highlight stops ingesting data and shows the billing issue banner and feed cards. 
Closes #7274
https://www.loom.com/share/baa17f8cc8dd484da21fe07840fa17b5
once a payment method is added to the test customer
https://www.loom.com/share/805c9d2c26984ccf92e5d0a12086d57e
No
No
> ensure billing details are correct to ingest data

- backend/pricing/pricing.go
* Validate a customer with at least one valid payment method, even if there is an invalid payment method.
* Use the workspace email notification helper to track invalid email notifications being sent.
Checking test customer cus_PAwk9vRu9e7C4d get processed.
No
No
> ensure billing checks are ok with at least one valid payment method

- backend/pricing/pricing.go
We would only check the upcoming invoice for a past due (upcoming invoice if the next payment will fail).
Check that a subscription is valid when processing a stripe customer.
Local deploy.
No
No
> treat past due subscriptions as needing fixing

- backend/kafka-queue/kafkaqueue.go
- backend/public-graph/graph/resolver.go
- backend/public-graph/graph/schema.resolvers.go
- backend/worker/worker.go
- deploy/collector-task.json
- deploy/private-graph-task.json
- deploy/public-worker-batched-service.json
- deploy/public-worker-datasync-service.json
- deploy/public-worker-main-service.json
- deploy/public-worker-traces-service.json
- deploy/worker-task.json
Chunk data for kafka to reduce message size (and reduce the fetch size of a consumer).
Local deploy.
Monitoring kafka.
No
> chunk push payload messages

- highlight.io/components/Animate.tsx
- highlight.io/components/Customers/CustomerQuote/CustomerQuote.module.scss
- highlight.io/components/Customers/Customers.module.scss
- highlight.io/pages/customers/index.tsx
Customer images on /customers are flickering on refresh.
Additionally, the mobile view is shown on desktop for each individual testimonial
Click-testing
https://highlight-landing-n4dzuxjfm-highlight-run.vercel.app/customers
No
No
> Customer page bugs

- backend/public-graph/graph/resolver.go
- log when the project id can't be determined from the backend error object's session or verbose project id
- tested locally to make sure backend error ingestion was still happening
- no
- no
> log case when no project_id is associated with an error

- docs-content/getting-started/fullstack-frameworks/next-js/3_app-router.md
Correct App router in the title
This should fix the duplicated docuement title in the sidebar
> Update 3_app-router.md title

- highlight.io/components/common/Navbar/Navbar.tsx
See attached issue. Flashing white line under navbar.
Scroll testing
No
No
> fixed white line on navbar

- backend/model/model.go
Reverts highlight/highlight#7391
> Revert "switch to hnsw embeddings index"

- backend/public-graph/graph/resolver.go
- `SELECT * FROM "projects" WHERE "projects"."id" = $1 LIMIT ?` has the 2nd highest resource usage. Most of these lookups are likely coming from processing payloads. Since we're only using the workspace id from the project, we can use the cached version instead as this doesn't change
- made sure session payloads were processed normally locally
- no
- no
> lookup project from store in ProcessPayload

- highlight.io/components/QuickstartContent/backend/otlp.tsx
- highlight.io/components/QuickstartContent/logging/otlp.tsx
Few docs updates based on customer feedback.
CI
No
No
> otel endpoint updates

- .changeset/fluffy-yaks-bathe.md
- frontend/src/pages/Buttons/Buttons.tsx
- sdk/client/src/listeners/error-listener.tsx
- sdk/firstload/src/index.tsx
Ensures that async promises report the promise stack trace correctly for unhandled rejections.
Closes #6594
Buttons page testing. https://preview.highlight.io/1/errors/WWtIP0IKI3ta1yt1Mn13JziN80Zw
Changeset
No
> make client tweaks for async stack trace

- docs-content/general/4_company/1_values.md
> typo in 1_values.md

- highlight.io/components/QuickstartContent/frontend/remix.tsx
> stray angle bracket in remix.tsx

- backend/public-graph/graph/resolver.go
- cut device memory + web vitals metrics over to clickhouse, the postgres metrics table is no longer being queried so no need to update it
- will truncate the metrics table after deploying
- no
> stop writing metrics to postgres

- docs-content/general/1_welcome.md
- docs-content/getting-started/6_backend-tracing/3_python/1_overview.md
Fix some copy and add additional links
N/A
N/A
> Fix tracing documentation

- highlight.io/components/Launch/Week4/DayOne.tsx
- highlight.io/components/Launch/Week4/HiddenDay.tsx
- highlight.io/pages/launch/week-4.tsx
Visual tweaks for `/launch/week-4`
Local deploy
Yes
> tweaks for launch week page

- blog-content/lw4-d2-query-builder.md
- highlight.io/components/Launch/Week4/DayOne.tsx
- highlight.io/components/Launch/Week4/DayTwo.tsx
> Link repair

- highlight.io/components/common/Navbar/Navbar.tsx
While working on launch week 4 navbar, I accidentally disabled the links on the navbar on other pages. Added links back to navbar except on launch week page.
Click-testing
No
No
> Fixed Default Navbar Links

- frontend/src/components/Header/Header.tsx
- links to launch week 4 and updates dates for enabling banner
- will test in preview
- no
- no
> enable banner for launch week

- README.md
> Add trace section to readme

- README.md
Update tracing image on readme.
n/a
n/a
> Update README.md for tracing image

- blog-content/clickhouse-materialized-views.md
- highlight.io/components/Docs/Docs.module.scss
- highlight.io/pages/blog/[slug].tsx
Update ClickHouse Materialized Views blog post.
Supports ```hint``` blocks in blog md files.
[Vercel](https://highlight-landing-git-vadim-update-ch-mv-blog-highlight-run.vercel.app/blog/clickhouse-materialized-views)
no
no
> update clickhouse materialized views blog post

- docker/frontend.Dockerfile
- frontend/src/components/CustomColumnPopover/index.tsx
- frontend/src/pages/LogsPage/useGetLogs.ts
Fix build error found in https://github.com/highlight/highlight/actions/runs/7822415691/job/21341578436
CI testing docker image build
https://github.com/highlight/highlight/actions/runs/7822728770
no
no
> fix typescript error breaking frontend docker image build

- backend/otel/otel.go
- backend/otel/otel_test.go
- backend/redis/utils.go
- backend/worker/kafka_worker.go
Reverts highlight/highlight#7725
> Revert "move flushLogs logic to otel.go"

- frontend/src/pages/Sessions/SessionsFeedV3/SessionQueryBuilder/components/SessionFeedConfigurationV2/SessionFeedConfigurationV2.tsx
- frontend/src/util/session/report.ts
* Improves CSV export download notifications.
* Fixes fetching multiple pages worth of sessions.
* Fixes incorrect date range in report.
https://www.loom.com/share/1633c16a08d94d92b29e10d69d4a800c?sid=d91d5574-39a4-408d-85e8-7b81e718e4ef
no
no
> fix session report showing incorrect data

- frontend/src/__generated/rr/rr.js
This file accidentally got reverted - sync it back up
N/A
N/A
N/A
> Sync reflame's rrweb

- .github/workflows/turbo.yml
- .vscode/settings.json
- backend/http/logging.go
- backend/http/logging_test.go
- backend/main.go
- backend/otel/otel_test.go
- backend/phonehome/phonehome.go
- backend/private-graph/graph/resolver.go
- backend/public-graph/graph/resolver.go
- backend/vercel/vercel.go
- docker/.env
- docker/collector.yml
- docker/compose.hobby.yml
- docker/env.sh
- docker/frontend-entrypoint.py
- docker/nginx.conf
- docker/run-hobby.sh
- docker/run.sh
- frontend/src/pages/Setup/SetupDocs.tsx
- frontend/src/util/auth.tsx
- highlight.io/components/QuickstartContent/self-host/self-host.tsx
- sdk/highlight-go/log/util.go
- sdk/highlight-go/otel.go
* fix setup docs showing incorrect public uri
* fix frontend entrypoint try catch
* mount ssl certificates to allow changing ssl and document ssl changes
* fix browser logs / traces not going to the right place
* fix phonehome not reporting version / email correctly
Closes #5873
hobby deploy on ec2 vm
new docker image release
no
> fix self hosted bugs

- frontend/src/components/Search/SearchForm/SearchForm.tsx
Support users searching for parts of strings in the log and trace search
https://www.loom.com/share/f854864750b54d52b959824faa639227?sid=a839f370-a8e9-4699-80b8-ae6b20bf5663
1) Navigate to the logs/traces page
2) Select a string key to search by
4) Click on the "Contains" operator
5) Search for part of a string
6) Repeat for "does not contain"
N/A
N/A
> Support contains operator in new search

- backend/clickhouse/query.go
- fixes an issue `Missing columns: '_sample_factor'`
- don't need to sample in inner limit query - metric is only used for relative ordering, and multiplying all by the sample factor will not affect the order
- no
- no
> fix error grouping sessions / errors

- docs-content/getting-started/self-host/1_overview.md
- docs-content/getting-started/self-host/integrations/index.md
- docs-content/getting-started/self-host/integrations/teams.md
- adds section for self-hosted integrations and steps for configuring Teams
- testing in preview env
- no
- no
> add instructions for self-hosted MS Teams

- backend/clickhouse/sessions.go
- backend/private-graph/graph/generated/generated.go
- backend/private-graph/graph/model/models_gen.go
- backend/private-graph/graph/schema.graphqls
- frontend/src/graph/generated/schemas.tsx
Sessions filters would not be applied on all columns.
Local deploy of grafana
Releasing new docker image
No
> support more session attributes as clickhouse filters

- highlight.io/components/Customers/CustomerQuote/CustomerQuote.tsx
- highlight.io/components/Customers/Customers.module.scss
- highlight.io/pages/customers/[slug].tsx
- highlight.io/pages/customers/index.tsx
Added ability to hide customer testimonials. These testimonials won't appear on the main /customers page but can be visiting with a secret link
Click-testing
No
No
> Hidden Customer Testimonial

- backend/private-graph/graph/generated/generated.go
- backend/private-graph/graph/model/models_gen.go
- backend/private-graph/graph/schema.graphqls
- backend/private-graph/graph/schema.resolvers.go
- frontend/src/graph/generated/hooks.tsx
- frontend/src/graph/generated/operations.tsx
- frontend/src/graph/generated/schemas.tsx
- frontend/src/graph/operators/query.gql
- frontend/src/pages/Billing/BillingPageV2.tsx
change billing plan page for aws marketplace subscriptions to meet policy
reflame
no
no
> change billing plan page for aws mp subscriptions

- highlight.io/pages/startups.tsx
> Change HFS wording

- frontend/src/pages/Billing/BillingPageV2.tsx
- frontend/src/pages/Billing/utils/utils.ts
Tweak billing page UI for workspaces connected to AWS Marketplace.
reflame
no
no
> update billing page for aws marketplace

- .changeset/stupid-bugs-bathe.md
- sdk/client/src/index.tsx
- sdk/client/src/types/client.ts
Report metrics from the client for performance data.
local deploy
changeset
no
> report browser performance events as metrics

- .changeset/breezy-poets-warn.md
- backend/private-graph/graph/schema.resolvers.go
- backend/worker/worker.go
- sdk/client/src/index.tsx
- sdk/client/src/types/types.ts
We hear many concerns about folks needing to inline stylesheets because of their website setup.
There isn't much of a downside to it (except for edge cases where stylesheets may change programmatically, in which case the setting can be disabled).
reflame
no
no
> default to inlining stylesheets

- backend/event-parse/parse.go
https://discord.com/channels/1026884757667188757/1202178622694096896
CI
no
no
> add log to troubleshoot capacitor saved urls

- .changeset/red-melons-develop.md
- sdk/client/src/listeners/console-listener.tsx
- sdk/client/src/types/shared-types.tsx
- sdk/highlight-go/log/console_messages_parser.go
Fixes issue encountered when trying to serialize functions into a console log from our client.
before
after
changeset
no
> fix console serialization

- .changeset/proud-mayflies-reflect.md
- e2e/nextjs/src/highlight.logger.ts
- highlight.io/highlight.logger.ts
- sdk/highlight-next/src/server.edge.ts
- sdk/highlight-next/src/server.ts
- sdk/highlight-next/src/util/highlight-node.ts
- sdk/highlight-next/src/util/is-node-js-runtime.ts
- sdk/highlight-next/src/util/register-highlight.ts
HIG-4429
Closes #7982 
An `undefined` value for `NEXT_RUNTIME` is unexpected, but it appears to be occurring in the wild... so it's time to handle it.
> Handling undefined NEXT_RUNTIME

- .github/workflows/deploy.yml
- deploy/Dockerfile.prod
- deploy/Dockerfile.prod.arm64
- deploy/private-graph-task.json
Reverts highlight/highlight#8011
> Revert "use backend.Dockerfile in prod deployment"

- docs-content/getting-started/fullstack-frameworks/next-js/2_page-router.md
- docs-content/getting-started/fullstack-frameworks/next-js/3_app-router.md
- docs-content/getting-started/fullstack-frameworks/next-js/6_edge-runtime.md
I'm going through our Next.js docs again, step by step, and I found some errors :(
> Doc repair

- .github/workflows/deploy.yml
- backend/kafka-queue/kafkaqueue.go
- deploy/public-worker-main-service.json
- docker/compose.hobby.yml
- docker/compose.yml
- docker/run-hobby.sh
- sdk/highlight-go/otel.go
* restart infra on failure
* simplify self hosted run-hobby script to avoid needing yarn
* optimize opentelemetry exporting data
forcing deploy to aws
no
no
> self hosted improvements

- frontend/src/pages/Player/PlayerHook/PlayerHook.tsx
Fixes bug with player autoplay not working correctly.
Fixes HIG-4450
tested with auto play on switching sessions in reflame
no
no
> tweak player behavior

- frontend/src/pages/IntegrationAuthCallback/IntegrationAuthCallbackPage.tsx
- frontend/src/pages/IntegrationsPage/components/common/useIntegration.ts
- frontend/src/routers/AppRouter/AppRouter.tsx
As discovered with @SpennyNDaJets , editing a github integration in the github settings can trigger a callback to the app with no state. In this case, we should consider adding/updating the integration using the default workspace of the user.
https://app.highlight.io/callback/github?installation_id=XXX&setup_action=update in reflame
no
no
> fix github integration callback failure

- highlight.io/components/common/CallToAction/OSSCallToAction.tsx
- highlight.io/components/common/Navbar/Navbar.tsx
Added links to the upcoming webinar on distributed tracing
Click-testing
No
No
> Webinar Links

- highlight.io/components/Home/CalendlyPopover.tsx
- highlight.io/pages/comments/index.tsx
- highlight.io/pages/pricing/index.tsx
Update demo link references to new calendly link.
vercel preview
no
no
> update calendly popover demo url

- .github/workflows/deploy.yml
- scripts/delete_logs.py
Updates lambda deploy.
[Manual CI invocation](https://github.com/highlight/highlight/actions/runs/8700008953)
no
no
> fix lambda fn updates emitting to stdout

- backend/scripts/migrate-error-segments/main.go
- backend/scripts/migrate-error-segments/main_test.go
Update error saved segment task to wrap the query in a json object.
https://www.loom.com/share/7967a14553c04d00b4fcf01aa122285c 
1) Create a saved segment with the old query builder
2) Migrate the query
3) Load it with the new search UI
N/A
N/A
> Fix error segment migration

- .changeset/shiny-horses-bathe.md
- __generated/rr/rrweb/rr.js
Fix `.tagName` null access issue reported on [discord](https://discord.com/channels/1026884757667188757/1229747689353252875) via https://github.com/rrweb-io/rrweb/pull/1445
https://github.com/highlight/rrweb/pull/115
Closes HIG-4504
reflame
changeset
no
> update rrweb to fix `.tagName` null access error

- frontend/src/__generated/index.css
- packages/ui/src/__generated/ve/components/ComboboxSelect/styles.css.js
- packages/ui/src/components/ComboboxSelect/ComboboxSelect.tsx
- packages/ui/src/components/ComboboxSelect/styles.css.ts
New flex value is causing combobox to collapse on words
Revert flex property
Need to add back solution for dashboards page
N/A
> Revert combobox changes

- highlight.io/components/common/CallToAction/OSSCallToAction.tsx
- highlight.io/components/common/Navbar/Navbar.tsx
> New livestream link and promo text

- frontend/src/components/SearchPagination/SearchPagination.tsx
- frontend/src/pages/ErrorsV2/ErrorsV2.tsx
- frontend/src/pages/ErrorsV2/SearchPanel/SearchPanel.tsx
- frontend/src/pages/Sessions/SessionsFeedV3/SessionsFeedV3.tsx
Pass in the pagination props to the SearchContext
1) View the errors
2) Click to change the page
N/A
N/A
> Fix error pagination

- docs-content/getting-started/fullstack-frameworks/next-js/2_page-router.md
> getInitialProps error docs

- blog-content/django-monitoring-solutions.md
* new blog posts on observability with django
vercel deploy
no
no
> add new blog posts on observability

- backend/go.mod
- backend/vercel/vercel_test.go
- sdk/highlight-go/log/util.go
Closes WHO-24
unit test, locally setting up logdrain w ngrok
no, will apply to existing logdrains
no
> report additional vercel log drain attributes

- backend/jobs/log-alerts/log-alerts.go
Log alerts would use the `frequency` as the lookback, but the `frequency` is meant to dictate how often the alert triggers.
Use the `threshold_window` to query a configurable time range for the alert.
Local deploy
no
no
> ensure log alerts use threshold window for lookback

- blog-content/lw5-d1-sdk-additions.md
- change timestamp of first post
- add correct youtube link
> Updates for launch day 1

- .github/workflows/codeql.yml
- .github/workflows/devskim.yml
Adds automated codescanning for security issues.
> add codeql.yml

- blog-content/lw5-d1-sdk-additions.md
- blog-content/lw5-d2-sdk-logs-and-traces.md
- blog-content/lw5-d3-metrics.md
- blog-content/lw5-d4-cohesion.md
- blog-content/lw5-d5-self-hosted.md
- highlight.io/pages/blog/index.tsx
* correctly filter blog posts to hide future dates
vercel
no
> correctly show launch week posts

- backend/clickhouse/query.go
Fixes `CountDistinct` operator not working for non-numeric values.
https://www.loom.com/share/8a00fd6e20d84a20a853796ea87fc625
no
no
> fix count distinct for metrics api

- backend/private-graph/graph/generated/generated.go
- backend/private-graph/graph/model/models_gen.go
- backend/private-graph/graph/schema.graphqls
- backend/private-graph/graph/schema.resolvers.go
- frontend/src/graph/generated/hooks.tsx
- frontend/src/graph/generated/operations.tsx
- frontend/src/graph/generated/schemas.tsx
- frontend/src/graph/operators/query.gql
- frontend/src/pages/Billing/BillingPageV2.tsx
- frontend/src/pages/Graphing/components/BarChart.tsx
- frontend/src/pages/Graphing/components/Graph.tsx
* Improves performance of the `/current-plan` page when loading past product usage
* Switches to the new Graphing `BarChart` component to share logic with graphing product
* Updates styling of details per figma designs. graphs are not exactly the same but i'm waiting HIG-4554 to support better legend customization
https://www.loom.com/share/8542c0bd245b4344a2a52f871b47036d
no
yes @julian-highlight
> billing page polish

- blog-content/lw5-clickhouse-performance-optimization.md
- docs-content/general/4_company/open-source/hosting/3_self-host-enterprise.md
Updates enterprise hosting doc.
vercel
no
no
> add doc on self hosted deployment options

- highlight.io/pages/_document.js
Adds a tracking snippet for website visits.
> Add another js snippet

- frontend/src/pages/Graphing/components/Graph.tsx
- frontend/src/pages/ProjectSettings/ProjectFilters/ProjectFilters.tsx
* Updates ingestion filters reporting to use new graphs
https://www.loom.com/share/ea910ae40fdd49598bc0efe3d9bf7fbf
no
no
> correctly report ingestion percentages

- highlight.io/pages/_document.js
Adds another js tag for site tracking.
> Add js script tag

- .reflame.config.jsonc
- frontend/index.html
- frontend/src/clearbit.js
Add clearbit snippet to frontend to track demo page views.
reflame
no
no
> add clearbit snippet

- .vscode/settings.json
- blog-content/lw5-clickhouse-performance-optimization.md
Small edits to clickhouse post.
> Edit Clickhouse Post

- docs-content/general/6_product-features/99_frequently-asked-questions.md
- docs-content/general/6_product-features/99_frequently_asked_questions.md
- docs-content/getting-started/self-host/traefik-proxy.md
* add doc on supporting self hosted traefik proxying
* add FAQ doc from Duckie.ai
vercel CI
no
no
> new docs pages

- highlight.io/components/common/Navbar/Navbar.tsx
Banner changed to Observability in Vercel
Click-testing
No
No
> Update Banner for new live stream

- highlight.io/components/common/CallToAction/OSSCallToAction.tsx
Changed the card at the bottom of the page to link to the upcoming livestream
Click-testing
No
No
> Update Card for livestream

- frontend/src/__generated/index.css
- frontend/src/__generated/ve/components/Toaster/styles.css.js
- frontend/src/components/Toaster/index.tsx
- frontend/src/components/Toaster/styles.css.ts
Update the toast UI:
- medium color title
- add drop shadow
- add transition
View the toast in the buttons page
N/A
@julian-highlight
> Update toasts UI

- frontend/src/__generated/index.css
- frontend/src/pages/Player/RightPlayerPanel/components/NetworkResourcePanel/NetworkResourceLogs.tsx
- frontend/src/pages/Player/Toolbar/DevToolsWindowV2/DevToolsWindowV2.tsx
- frontend/src/pages/Player/Toolbar/DevToolsWindowV2/LogLevelFilter/LogLevelFilter.tsx
- frontend/src/pages/Player/Toolbar/DevToolsWindowV2/LogSourceFilter/LogSourceFilter.tsx
- frontend/src/pages/Player/Toolbar/DevToolsWindowV2/RequestStatusFilter/RequestStatusFilter.tsx
- frontend/src/pages/Player/Toolbar/DevToolsWindowV2/RequestTypeFilter/RequestTypeFilter.tsx
- packages/ui/src/__generated/ve/components/MultiSelectButton/styles.css.js
- packages/ui/src/components/MultiSelectButton/MultiSelectButton.stories.tsx
- packages/ui/src/components/MultiSelectButton/MultiSelectButton.tsx
- packages/ui/src/components/MultiSelectButton/styles.css.ts
Stop the dev tools from overflowing
https://www.loom.com/share/640834ad6dc94f1db33712363b9c46d0?sid=06ba8d22-eaed-4afd-aa34-4b271a598e50
1) View a session
2) Click to open the dev tools
3) Play with the screen width
N/A
@julian-highlight
> Fix dev tools overflow

- docker/run-backend.sh
- e2e/dotnet/HighlightConfig.cs
- e2e/dotnet/dotnet.csproj
- highlight.io/components/QuickstartContent/traces/dot-net.tsx
* reports additional attributes on spans in .NET
local invocation of `Program.cs`
no
no
> improve .NET instrumentation example

- highlight.io/components/common/CalendlyModal/CalendlyModal.tsx
- highlight.io/pages/[slug].tsx
- highlight.io/pages/index.tsx
- highlight.io/pages/pricing/index.tsx
Generalized the calendly modal for usage across the frontend.
Updated enterprise pricing to allow for contacting sales instead of listing base price.
Click-testing
No
No
> Pricing updates

- backend/scripts/reprocess-sessions/main.go
Incident script for future session reprocessing.
Running in prod VPC.
no
no
> add script to reprocess sessions with broken session_intervals

- sdk/highlightinc-highlight-datasource/pkg/plugin/datasource.go
- sdk/highlightinc-highlight-datasource/src/components/QueryEditor.tsx
- sdk/highlightinc-highlight-datasource/src/components/VariableQueryEditor.tsx
- sdk/highlightinc-highlight-datasource/src/datasource.ts
- sdk/highlightinc-highlight-datasource/src/module.ts
- sdk/highlightinc-highlight-datasource/src/types.ts
Allow users to query the backend for attributes that can be used as variables.
https://www.loom.com/share/c060b69eee0e487cb5cc26f6c0bf013a?sid=a9dcc254-2c93-4f0e-bb77-f0df3a5a12f7
1. Click to add a variable
2. Select the query type 
3. Enter a table
4. Enter a Key
5) Apply the variable
6) Edit a graph
7) Add the variable to the query
N/A
N/A
> Grafana query variables

- backend/event-parse/parse.go
- backend/event-parse/parse_test.go
- backend/model/model.go
- backend/private-graph/graph/schema.resolvers.go
- backend/public-graph/graph/resolver.go
- backend/store/error_group_activity_logs.go
- backend/store/error_groups.go
- backend/store/error_groups_test.go
- backend/store/main_test.go
- backend/store/oauth.go
- backend/store/oauth_test.go
- backend/store/project_assets.go
- backend/store/project_filter_settings.go
- backend/store/project_filter_settings_test.go
- backend/store/projects.go
- backend/store/projects_test.go
- backend/store/services.go
- backend/store/services_test.go
- backend/store/sessions.go
- backend/store/sessions_test.go
- backend/store/stacktraces.go
- backend/store/stacktraces_test.go
- backend/store/store.go
- backend/store/system_configuration.go
- backend/store/workspace_settings.go
- backend/store/workspace_settings_test.go
- backend/store/workspaces.go
- backend/store/workspaces_test.go
- backend/worker/autoresolver.go
Adds a new `ProjectAssetTransform` model that stores project+scheme that should be transformed.
unit tests
no
no
> support custom asset transformations via new model

- backend/private-graph/graph/generated/generated.go
- backend/private-graph/graph/model/models_gen.go
- backend/private-graph/graph/resolver_test.go
- backend/private-graph/graph/schema.graphqls
- backend/private-graph/graph/schema.resolvers.go
- frontend/src/graph/generated/schemas.tsx
Adds basic functionality to generate a query from a plain english query.
> AI query builder / server logic

- backend/go.mod
- backend/go.sum
- backend/model/model.go
- backend/private-graph/graph/generated/generated.go
- backend/private-graph/graph/schema.graphqls
- backend/private-graph/graph/schema.resolvers.go
- backend/store/workspace_settings.go
- frontend/src/graph/generated/hooks.tsx
- frontend/src/graph/generated/operations.tsx
- frontend/src/graph/generated/schemas.tsx
- frontend/src/graph/operators/mutation.gql
- frontend/src/graph/operators/query.gql
- frontend/src/pages/HaroldAISettings/HaroldAISettings.tsx
Add AI query builder toggle for Harold
> Add AI query builder toggle for Harold

- backend/public-graph/graph/resolver.go
- sdk/highlight-go/log/console_messages_parser.go
* fix console message attribute unmarshalling
* fix network payload integer overflow.
no
no
> fix 2 task processing errors

- backend/model/model.go
- backend/pricing/pricing.go
- backend/private-graph/graph/generated/generated.go
- backend/private-graph/graph/model/models_gen.go
- backend/private-graph/graph/resolver.go
- backend/private-graph/graph/schema.graphqls
- backend/private-graph/graph/schema.resolvers.go
- frontend/src/components/CalendlyModal/CalendlyButton.tsx
- frontend/src/components/Header/Header.tsx
- frontend/src/components/Header/useBillingHook.tsx
- frontend/src/components/Search/SearchForm/hooks.ts
- frontend/src/graph/generated/hooks.tsx
- frontend/src/graph/generated/operations.tsx
- frontend/src/graph/generated/schemas.tsx
- frontend/src/graph/operators/query.gql
- frontend/src/hooks/useFeatureFlag/useFeatureFlag.ts
- frontend/src/index.tsx
- frontend/src/pages/Alerts/ErrorAlert/ErrorAlertPage.tsx
- frontend/src/pages/Billing/UpdatePlanPage.tsx
- frontend/src/pages/Billing/utils/utils.ts
- frontend/src/pages/ErrorsV2/ErrorsV2.tsx
- frontend/src/pages/IntegrationAuthCallback/IntegrationAuthCallbackPage.tsx
- frontend/src/pages/IntegrationsPage/components/ClearbitIntegration/utils.ts
- frontend/src/pages/Player/PlayerPage.tsx
- frontend/src/routers/AppRouter/AppRouter.tsx
- frontend/src/routers/AppRouter/context/ApplicationContext.tsx
- frontend/src/util/graph.tsx
- frontend/src/util/integrated.tsx
Reverts highlight/highlight#8769
> Revert "[SUP-48] support 7 day retention for sessions / errors"

- backend/private-graph/graph/schema.resolvers.go
Encourage "*" operator for contains queries in AI logs builder
> Encourage "*" operator for contains queries in AI logs builder

- backend/worker/kafka_worker.go
- packages/ui/src/components/DatePicker/DateRangePicker/index.tsx
Unnecessary log that is being written many times - remove it
N/A
N/A
N/A
> Remove noisy log

- highlight.io/components/common/CallToAction/OSSCallToAction.tsx
- highlight.io/components/common/Navbar/Navbar.tsx
Update event links on landing page
> Update event links on landing page

- frontend/src/index.tsx
- frontend/src/pages/Auth/Firebase.tsx
- frontend/src/routers/AppRouter/AppRouter.tsx
Fix issue with workspace invite links not being able to verify email.
https://www.loom.com/share/1c34fef66d424d659937393a0450c88f?sid=54d63ba5-34ff-4619-9ed6-e6bbadc62a28
no
no
> correct issue with verifying sign up email

- .github/workflows/docker.yml
Ensure github releases publish a docker image
TMP commit to publish
republishing main manually
no
> fix publishing docker images

- frontend/src/__generated/index.css
- frontend/src/__generated/ve/pages/Graphing/Combobox/styles.css.js
- frontend/src/__generated/ve/pages/Graphing/GraphingEditor.css.js
- frontend/src/__generated/ve/pages/Graphing/OptionDropdown/styles.css.js
- frontend/src/__generated/ve/pages/Graphing/Settings/styles.css.js
- frontend/src/pages/Graphing/Combobox/index.tsx
- frontend/src/pages/Graphing/Combobox/styles.css.ts
- frontend/src/pages/Graphing/GraphingEditor.css.ts
- frontend/src/pages/Graphing/GraphingEditor.tsx
- frontend/src/pages/Graphing/LabeledRow/index.tsx
- frontend/src/pages/Graphing/OptionDropdown/index.tsx
- frontend/src/pages/Graphing/OptionDropdown/styles.css.ts
- frontend/src/pages/Graphing/Settings/BarChartSettings.tsx
- frontend/src/pages/Graphing/Settings/LineChartSettings.tsx
- frontend/src/pages/Graphing/Settings/TableSettings.tsx
- frontend/src/pages/Graphing/Settings/index.tsx
- frontend/src/pages/Graphing/Settings/styles.css.ts
- frontend/src/pages/Graphing/constants.tsx
- frontend/src/pages/IntegrationsPage/components/ClickUpIntegration/ClickUpListSelector.tsx
- frontend/src/pages/IntegrationsPage/components/GitHubIntegration/GitHubRepoSelector.tsx
- frontend/src/pages/IntegrationsPage/components/GitlabIntegration/GitlabProjectSelector.tsx
- frontend/src/pages/IntegrationsPage/components/HeightIntegration/HeightListSelector.tsx
- frontend/src/pages/IntegrationsPage/components/JiraIntegration/JiraProjectSelector.tsx
- frontend/src/pages/IntegrationsPage/components/LinearIntegration/LinearTeamSelector.tsx
Refactor the `GraphingEditor` so the components can be easily reused in the alerts form. Other changes called out in comments
Also fixes a bug related to searching keys
https://www.loom.com/share/7a73ce23853441f7a6ac7d12cccadd3f?sid=d77aa4ab-b476-4cd7-8260-477426e8a36b
1. Load a metrics graph
N/A
N/A
> Refactor metrics components

- .github/workflows/docker.yml
- seems to be skipping this step and failing with a 403 error later - not sure if this is the cause
- will test in draft release
- no
- no
> call docker / github login during release

- backend/private-graph/graph/resolver.go
- due to how Slack applies the limit 1000 param before filtering, for slack workspaces with many channels, it was taking 60+ iterations and many were returning <10 results
- somehow, calling the api separately for each channel type fixes this
- tested locally against large slack workspace
- no, will re-validate after deploying
- no
> [SUP-73] faster to call slack api separately for each channel type

- frontend/src/__generated/index.css
- frontend/src/components/Header/Header.tsx
- frontend/src/components/Header/components/ProjectPicker/ProjectPicker.tsx
- packages/ui/src/components/Button/styles.css.ts
- packages/ui/src/components/icons/IconSolidTraces.tsx
Correct styling of the header icons per [figma](https://www.figma.com/design/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=13019-80008&m=dev).
[reflame](https://app.highlight.io/1/sessions?%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201J1FPA3E3EPGS3G1NNTMAAT27%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22vadim%2Ffix-traces-icon%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D)
no
yes @julian-highlight
> fix size of traces icon

- .reflame.config.jsonc
- forces reflame to load 9.1.0
- testing in preview
- no
- no
> force highlight.run update in reflame

- frontend/src/components/Header/Header.tsx
Switch workspace button is not working -> change prevent default to stop propogation.
1) Click on Switch workspace button in settings dropdown
N/A
N/A
> Fix switch workspace

- frontend/src/__generated/index.css
- frontend/src/__generated/ve/components/Search/SearchForm/AiSearch/style.css.js
- frontend/src/components/Search/SearchForm/AiSearch/index.tsx
- frontend/src/components/Search/SearchForm/AiSearch/style.css.ts
- frontend/src/components/Search/SearchForm/SearchForm.tsx
- frontend/src/components/Search/SearchForm/constants.ts
- frontend/src/pages/ErrorsV2/ErrorsV2.tsx
- frontend/src/pages/ErrorsV2/SearchPanel/SearchPanel.tsx
- frontend/src/pages/ErrorsV2/constants.ts
- frontend/src/pages/Player/PlayerPage.tsx
- frontend/src/pages/Player/constants.ts
- frontend/src/pages/Sessions/SessionsFeedV3/SessionsFeedV3.tsx
Extend the AI search to all search products
https://www.loom.com/share/4d6d8d7cfd2c456191022ac5095589a3?sid=138a5cd2-b6ed-4872-9290-045186c61997
Run a search for all product areas
N/A
N/A
> Extend AI queries to all searches

- highlight.io/pages/pricing/index.tsx
> Pricing Tier Edits

- .github/workflows/turbo.yml
- frontend/src/components/Header/Header.tsx
- highlight.io/components/Home/FeatureCarousel/FeatureCarousel.tsx
- remove beta tags from app and landing page
- no
- no
> [GRO-60] remove beta tags from metrics in app and landing

- backend/go.mod
- backend/go.sum
- sdk/highlight-ruby/highlight/Gemfile.lock
- yarn.lock
- merging in dependabot fixes to address some open dependency vulnerabilities
- ran frontend/backend locally
- no
- no
> Zane/dep upgrades 7.30.24

- frontend/src/hooks/useFeatureFlag/useFeatureFlag.ts
Enable AI query builder for Launch Week
1) View a project
2) Confirm the AI query builder is enabled for each product
N/A
N/A
> Enable ai query builder

- backend/private-graph/graph/resolver.go
- backend/private-graph/graph/resolver_test.go
- frontend/src/components/Header/Header.tsx
Update the Chat/Support button to provide an email callout.
render preview
no
no
> update support button

- frontend/src/pages/ProjectSettings/ProjectFilters/ProjectFilters.tsx
Project filters would redirect to billing page.
https://www.loom.com/share/724ee4346ba24a6ba3371a131bce2a38
no
no
> fix project filters gate

- .github/workflows/backend.yml
- .github/workflows/go-sdk.yml
- sdk/highlight-go/trace/tracer.go
Fixes [test failure](https://github.com/highlight/highlight/actions/runs/10407916057/job/28824184570) in main.
ci
no
no
> fix golang ci lint

- frontend/src/__generated/index.css
- frontend/src/pages/Graphing/DashboardOverview.tsx
- frontend/src/pages/ProjectSettings/ServicesTable/ServicesTable.tsx
- packages/ui/src/__generated/ve/components/Table/Row/styles.css.js
- packages/ui/src/__generated/ve/components/Table/styles.css.js
- packages/ui/src/components/Table/Body/Body.tsx
- packages/ui/src/components/Table/Body/styles.css.ts
- packages/ui/src/components/Table/Head/styles.css.ts
- packages/ui/src/components/Table/Row/styles.css.ts
- packages/ui/src/components/Table/Search/Search.tsx
- packages/ui/src/components/Table/Search/styles.css.ts
- packages/ui/src/components/Table/Table.stories.tsx
- packages/ui/src/components/Table/Table.tsx
- packages/ui/src/components/Table/styles.css.ts
The tables borders are not being applied correctly. Update the table component to move the borders to the outer most element when possible.
https://www.loom.com/share/c3e67f1d629a425296fb03c472c79982?sid=c0b1becb-6f0a-4219-91d8-b5b209fbc181
1. View the metrics table
2. View the services table
N/A
N/A
> Fix table borders

- e2e/python/poetry.lock
- e2e/python/pyproject.toml
- upgrade urllib3 to 2.2.2
- builds locally
- no
- no
> upgrade urllib3 version

- e2e/dotnet4/cs/App_Start/HighlightConfig.cs
- e2e/dotnet4/cs/cs.csproj
- e2e/dotnet4/cs/packages.config
- highlight.io/components/QuickstartContent/traces/dot-net-4.tsx
Documents setting up serilog logging in .NET 4.
customer testing
no
no
> add serilog documentation for .NET4

- .changeset/chilled-ads-change.md
- __generated/rr/rrweb/rr.js
- yarn.lock
https://github.com/rrweb-io/rrweb/pull/1458 introduced issues with certain customers' applications such as: 
```js
Uncaught CssSyntaxError: <css input>:1778:83: Unknown word
Uncaught CssSyntaxError: <css input>:1:65502: Unknown word
Uncaught CssSyntaxError: <css input>:1:2: Unclosed block
```
example of such a session: https://app.highlight.io/92422/sessions/qGaSpGVNh4Ewqj8k23lNC5zNtcB1
affected highlight.run clients are >=9.1.5 with certain bundled CSS
this may also affect the replayer so the new frontend usage of rrweb is affected
fixes playback of [session that used to not play](https://app.highlight.io/92422/sessions/qGaSpGVNh4Ewqj8k23lNC5zNtcB1)
new client build working
new changeset
no
> correct issue with session replay live mode and bundled css

- frontend/src/components/Search/SearchForm/SearchForm.tsx
Show loading state when we are fetching more keys/values.
1. When typing for keys
2. When typing for values
N/A
N/A
> Add loading state to fetching keys/values

- docs-content/getting-started/3_client-sdk/7_replay-configuration/salesforce-lwc.md
Updates the content in the LWC docs to hit more keywords people might be searching for when trying to figure out how to monitor and record sessions for an LWC app.
Local PR click test.
N/A
N/A
> Improve LWC content for SEO

- packages/ai/src/utils.ts
This pull request addresses issue [#9165](https://github.com/highlight/highlight/issues/9165)
- Changed the AI model from gpt-3.5-turbo-16k to gpt-4o-mini.
> Change gpt-3.5-turbo-16k to gpt-4o-mini

- docs-content/getting-started/3_client-sdk/7_replay-configuration/proxying-highlight.md
Changes "annual" plan to "business".
> Add reference to business tier

- backend/alerts/v2/destinations/discord/messages.go
- backend/alerts/v2/destinations/email/messages.go
- backend/alerts/v2/destinations/microsoft-teams/templates/log-alert.go
- backend/alerts/v2/destinations/microsoft-teams/templates/metric-alert.go
- backend/alerts/v2/destinations/microsoft-teams/templates/session-alert.go
- backend/alerts/v2/destinations/microsoft-teams/templates/trace-alert.go
- backend/alerts/v2/destinations/slack/messages.go
- backend/temp-alerts/temp-alerts.go
Keep the alerts consistent. Change `fired!` -> `Alert`
View alert in slack
N/A
N/A
> Consistent alert test

- frontend/src/__generated/index.css
- frontend/src/pages/Graphing/GraphingEditor.tsx
- packages/ui/src/components/Form/Form.stories.tsx
- packages/ui/src/components/Form/Form.tsx
- packages/ui/src/components/Form/styles.css.ts
- packages/ui/src/components/Select/Select.tsx
Tweaks the behavior of the number input. Some changes were at the component level and others in the logic where the component was being used.
* Changes the `type` of the input control buttons for incremeneting/decrementing the number so that they don't try to submit the form.
* Adds functionality to increment/decrement by 10x when the `shift` key is held while clicking the buttons.
* Fixes the color of the button icons and makes them match the mocks + the icons used in select dropdowns.
* Updates logic in the graph editor to not convert to an integer before setting the value that controls the input. This allows the user to clear the input entirely rather than it always showing a `0` for empty values.
Click tested locally and in a PR preview on the graph editor.
N/A
Will have …
> Number input behavior tweaks

- backend/stacktraces/stacktraces.go
Ruby errors should be processed separately than golang errors due to a different regex
1. Start the ruby app
2. Create an error at http://127.0.0.1:2343/
N/A
N/A
> Fix ruby stackktraces

- backend/clickhouse/query.go
- had copy pasted SessionsJoinedTableConfig instead of the proper config
- tested group by locally
- no
- no
> fix metrics group by

- e2e/react-router/package.json
- frontend/package.json
- highlight.io/package.json
- yarn.lock
- fixes 4 open dependabot issues
- ensuring everything builds / unit tests pass
- no
- no
> js dependency upgrades

- frontend/src/hooks/useFeatureFlag/useFeatureFlag.ts
Enable user events for a few workspaces.
reflame
no
no
> enable user events for more workspaces

- frontend/src/pages/Graphing/components/Graph.tsx
Support linking session metrics to session related resources panel.
https://www.loom.com/share/e1bc1f7bf69948b9b205e15368e5e3ae
no
no
> add session related resource for web vitals

- backend/public-graph/graph/resolver.go
- backend/worker/worker.go
- frontend/src/pages/Player/PlayerHook/utils/index.tsx
Start writing click and navigation events to the session events table.
https://www.loom.com/share/29ebe079c64940bfbfb3c2ee225d68bd?sid=65b7a0e9-fe15-48e6-af31-402bf0312b3d
1. Complete a session
2. Create an events metric chart
3. Add the click event
4. Change to the Navigate event
5. Change to the Reload event
N/A
N/A
> Write clicks and naviagation events:

- backend/alerts/integrations/microsoft-teams/microsoft_teams.go
Add check for nil pointer dereference
CI
no
no
> address ms teams integration panic

- highlight.io/components/common/Footer/Footer.tsx
- highlight.io/components/common/Navbar/ResourceDropdown.tsx
- highlight.io/pages/ambassador-program.tsx
Adds a page to our marketing site for the Highlight ambassador program.
Local and PR preview click test.
N/A
N/A
> Add page on ambassador program

- .changeset/shaggy-rabbits-remain.md
- .reflame.config.jsonc
- __generated/rr/rrweb/rr.js
- frontend/src/hooks/useFeatureFlag/useFeatureFlag.ts
- frontend/src/pages/Player/PlayerHook/PlayerHook.tsx
- frontend/src/pages/Player/PlayerHook/PlayerState.ts
- frontend/src/pages/Player/ResourcesContext/ResourcesContext.tsx
- yarn.lock
Bring back postcss css parsing which offers better reliability with inlined stylesheets and better performance.
Fixes replay of a session where the existing CSS parsing of rrweb was broken.
Incorporates https://github.com/rrweb-io/rrweb/pull/1580 to fix broken replays due to postcss crash.
https://preview.highlight.io/102751/sessions/35zPFX0OPXs166n5L7m1GEZaqWgL?%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201J8GFGDTWBWCRZZZ7G92P9HJX%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22vadim%2Fsession-troubleshooting%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D
fixes replay that is …
> fix session replay crash

- frontend/src/pages/Graphing/Dashboard.tsx
- frontend/src/pages/Graphing/ExpandedGraph.tsx
- frontend/src/pages/Graphing/GraphingEditor.tsx
- frontend/src/pages/Graphing/components/DashboardCard.tsx
- frontend/src/pages/Graphing/components/Graph.tsx
- frontend/src/pages/Graphing/constants.tsx
- frontend/src/pages/Graphing/context/GraphContext.ts
- frontend/src/pages/Graphing/hooks/useExportGraph.ts
- frontend/src/pages/Graphing/hooks/useGraphData.tsx
- frontend/src/util/session/report.ts
Supports exporting dashboard charts via a new `Download CSV` button.
https://www.loom.com/share/0e6a4af7a784484087b7ba6713012efb
no
@julian-highlight if you want to check the download button
> data export for metric charts and tables

- frontend/src/pages/Auth/InviteTeam.tsx
- should be an opt-in setting
- local clicktest 
- no
- no
> make auto-join default false

- .github/workflows/dotnet.yml
- backend/otel/extract.go
- backend/otel/otel.go
- sdk/highlight-dotnet/Highlight.ASPCore.csproj
- sdk/highlight-dotnet/OpenTelemetry.cs
Tweak .NET SDK to support Azure Function exception reporting.
Capture exceptions from .NET logs (send from `logRecord.attributes` on `exception.` semconv keys).
no
no
> fix Highlight.ASPCore for .NET Azure Functions

- docs-content/getting-started/fullstack-frameworks/next-js/2_page-router.md
> Fix missing apostrophe in Next docs

- backend/clickhouse/events.go
Fix the event drill down search to use the correct config
Able to load event sessions when there is a filer included in the search
N/A
N/A
> event drilldown fix

- backend/alerts/v2/alerts.go
- backend/alerts/v2/destinations/discord/messages.go
- backend/alerts/v2/destinations/email/messages.go
- backend/alerts/v2/destinations/microsoft-teams/messages.go
- backend/alerts/v2/destinations/slack/messages.go
- backend/alerts/v2/destinations/webhook/messages.go
- backend/jobs/metric-alerts/metric-alerts.go
Metric alerts do not seem to be working properly - add tracing to debug better
1. Able to send alerts locally
N/A
N/A
> Add tracing to metric alerts

- backend/clickhouse/events.go
Revert back to async write while investigating why batch writes are causing no events to populate
Able to process events and create event graphs/alerts
N/A
N/A
> Switch events to async writes

- frontend/src/__generated/index.css
- frontend/src/__generated/ve/components/Search/SearchForm/SearchForm.css.js
- frontend/src/components/Search/SearchForm/SearchForm.css.ts
- frontend/src/components/Search/SearchForm/SearchForm.tsx
Fix the padding for the search query component when disabled
https://www.loom.com/share/40fd721ea2fd41318d2f28e2b9f8baef?sid=a379c347-a054-458c-b34c-6d46f6bbfcab
1. View related logs/traces that would cause a query to be populated
2. Test responsiveness when making side panel smaller/larger
N/A
N/A
> Fix search form overflow

- frontend/src/pages/Alerts/AlertForm/index.tsx
- frontend/src/pages/Alerts/AlertGraph/index.tsx
- frontend/src/pages/Graphing/components/DashboardCard.tsx
- frontend/src/pages/Graphing/components/Graph.tsx
- frontend/src/pages/Graphing/components/LineChart.tsx
- update alert threshold styling to get closer to figma design
- no
> updated styling for alert thresholds

- frontend/src/pages/Alerts/AlertForm/index.tsx
- frontend/src/pages/Graphing/GraphingEditor.tsx
- stores the current settings for alerts and metrics as a base64 encoded `settings` url param
- if a user navigates or closes / reopens window, they will be shown the same settings
- if a user exits the settings page via the `cancel` or `save` buttons, the settings param will be cleared and the user will be shown the default settings next time
- no
- no
> save alert and graph settings in url

- backend/clickhouse/query.go
a few bugs noticed in prod after this change -
- data stops after some number of buckets in constant interval queries
- empty group shown in session graphs (and maybe others?)
reverting until this is fixed
> Revert "optimize group w/ limit queries"

- frontend/src/components/Search/useSavedSegments/index.tsx
/claim #9250
https://www.loom.com/share/681e33eb000c4d91b37b89fd3be60ddd
> feat: segment improvement change

- .github/workflows/deploy.yml
- inverting the order of these redirect commands
- tested commands locally
- no
- no
> fix stderr redirect

- backend/otel/otel.go
* suppress noisy log from otel ingest caused by cases where exception is not expected
Deploying from PR
no
no
> remove noisy otel logs

- backend/clickhouse/traces.go
- split out certain otel standard attributes into their own column and dual write (writes will be ignored in db right now)
- checked ingested traces locally without and with adding these columns to db 
- will follow up with https://github.com/highlight/highlight/pull/9673
```
> step 1: add new fields to ClickhouseTraceRow for writes
step 2: create new columns in traces / traces_sampling tables
step 3: backfill new columns for existing data
step 4: reference new columns in queries
step 5: remove these attributes from TraceAttributes
```
- no
> add new fields to clickhouse writes

- frontend/src/pages/Graphing/components/Table.tsx
- values too long, can't see them
- no
- no
> add tooltips for overflowing values

- highlight.io/components/Pricing/EstimatorDetails.ts
> Add 15 seat limit to free tier

- frontend/src/__generated/index.css
- frontend/src/__generated/ve/pages/Graphing/GraphingEditor.css.js
- frontend/src/__generated/ve/pages/Graphing/components/Panel.css.js
- frontend/src/pages/Graphing/GraphingEditor.css.ts
- frontend/src/pages/Graphing/GraphingEditor.tsx
- frontend/src/pages/Graphing/components/Panel.css.ts
- frontend/src/pages/Graphing/components/Panel.tsx
- copies some of the code from related resource `Panel` to apply to the graphing editor
- no
> make graph editor panel draggable

- backend/private-graph/graph/schema.resolvers.go
Correct the business tier check for dashboards to match the UI.
CI
no
no
> correct check for number of dashboards on payg tier

- .changeset/light-elephants-pull.md
- .reflame.config.jsonc
- frontend/package.json
- frontend/src/pages/Buttons/Buttons.tsx
- frontend/src/pages/Buttons/XYFlow.tsx
- sdk/client/src/otel/user-interaction.ts
- yarn.lock
Fixes bug in `user-instrumentation.ts` debounce code which would incorrectly call the listener.
This was causing libraries relying on event listeners to break.
* Updates `user-instrumentation.ts` based on latest opentelemetry webjs repo.
https://www.loom.com/share/32282d20f7d348ea932b09cae20e8da9
changeset
no
> update otel user interaction instrumentation

- backend/alerts/integrations/microsoft-teams/microsoft_teams.go
- backend/private-graph/graph/resolver.go
- backend/private-graph/graph/schema.resolvers.go
- frontend/src/pages/Alerts/DestinationInput/index.tsx
FIxes customer reported issue in slack sync not refreshing existing channel names.
Adds tracing to microsoft teams code to identify performance regression.
Fixes typo in frontend alerts slack form.
CI
no
no
> fix slack channel sync

- backend/util/tracer.go
- backend/worker/kafka_worker.go
- backend/worker/worker.go
* improve tracing of batch worker
CI
looking at new spans
no
> debug performance of datasync worker

- blog-content/the-complete-guide-to-python-and-opentelemetry.md
adds a few imports to the otel/python guide
> Small edits to python OTEL guide

- backend/kafka-queue/kafkaqueue.go
Reduce CPU usage on Kafka cluster without a significant latency increase.
Decreased broker CPU usage due to fewer commits.
no
no
> increase public graph write batching

- blog-content/how-to-instrument-your-react-native-app-with-opentelemetry.md
- blog-content/the-complete-guide-to-python-and-opentelemetry.md
- highlight.io/components/QuickstartContent/mobile/react-native.tsx
Blog post for react native guide.
View in preview: https://highlight-landing-hlwexxti2-highlight-run.vercel.app/blog/how-to-instrument-your-react-native-app-with-opentelemetry
N/A
N/A
> React Native blog post

- e2e/python/highlight_fastapi/logger.py
- sdk/highlight-py/highlight_io/sdk.py
- sdk/highlight-py/pyproject.toml
- sdk/highlight-py/tests/test_sdk.py
As mentioned by a customer, our span context access pattern may break for `NonRecordingSpan`s.
CI
new patch version
no
> fix span context access for NonRecordingSpan

- frontend/src/routers/AppRouter/AppRouter.tsx
- fixes HIG-5043
- doesn't redirect on routes that are not the root `/`
https://www.loom.com/share/97205f5d15954fcbb5470ee85963cd51?sid=23c8419c-262a-4c1b-b42b-a06264684db8
No
No
> load last viewed product 

- .github/workflows/turbo.yml
- frontend/src/index.tsx
- frontend/src/util/attribution.ts
Remove recording of storage events as that can cause recursive ballooning of the export payload to highlight.
CI / deploy
https://www.loom.com/share/64ce3f57dfd54657b739d7c41bf168f2
no
no
> remove recording of storage events

- blog-content/aws-firehose-opentelemetry-collector.md
- blog-content/supporting-opentelemetry-metrics.md
Add a new blog on OpenTelemetry firehose learnings.
vercel preview
no
no
> introduce new blog post

- backend/clickhouse/query.go
Fixes an issue @mayberryzane and I came across while pairing. We noticed attributes from `traces.TelemetryAttributes` weren't appearing as keys in the typeahead for filtering and they weren't working as filters when applied in a query. This fixes the latter, and there's another PR coming to get the key recommendations working.
Local click test from the metrics dashboard.
Will verify the filters work once this goes live. I wanted to build a graph that shows usage of product features broken down by `telemetry.(sdk|distro).name`.
N/A
> Fix attribute filter column

- frontend/src/pages/Player/StreamElement/Renderers/WebVitals/WebVitalRender.tsx
- frontend/src/pages/Player/components/EventStreamV2/EventStreamV2.tsx
- frontend/src/pages/Player/components/EventStreamV2/utils.ts
- add some logging
- fix case for search on null value
- testing in preview
- no
- no
> fix search on web vitals

- frontend/src/components/Header/Header.tsx
- frontend/src/components/Header/components/ProjectPicker/ProjectPicker.tsx
Make the topbar responsive so it moves items in and out of the menu depending on the width
https://www.loom.com/share/22f632be79e94af8aa2790a2f63499ae?sid=3b80ed53-9ee3-445e-997e-21d5b5598c0f
1. View the topbar on any page
2. Make the page smaller
N/A
N/A
> Responsive topbar

- docker/.env
Update pinned version to the latest release.
CI
no
no
> update pinned docker image version

- highlight.io/components/common/Roadmap/Roadmap.tsx
- highlight.io/components/common/Roadmap/RoadmapUtils.ts
- highlight.io/pages/docs/[[...doc]].tsx
Update the public roadmap view to take into account the changes on the Github side of the roadmap
View the road map in the preview at  `/docs/general/roadmap` 
N/A
N/A
> Public roadmap touchups

- .github/workflows/deploy.yml
- backend/email/email.go
- backend/lambda-functions/deleteSessions/deleteSessionBatchFromOpenSearch/main.go
- backend/lambda-functions/deleteSessions/deleteSessionBatchFromPostgres/main.go
- backend/lambda-functions/deleteSessions/deleteSessionBatchFromS3/main.go
- backend/lambda-functions/deleteSessions/getSessionIdsByQuery/main.go
- backend/lambda-functions/deleteSessions/sendEmail/main.go
- backend/lambda-functions/digests/getDigestData/main.go
- backend/lambda-functions/digests/getProjectIds/main.go
- backend/lambda-functions/digests/sendDigestEmails/main.go
- backend/lambda-functions/journeys/updateNormalnessScores/main.go
- backend/lambda-functions/metering/awsMarketplaceListener/main.go
- backend/lambda-functions/sessionExport/saveSessionExport/main.go
- backend/lambda-functions/sessionExport/sendEmail/main.go
- backend/lambda-functions/sessionInsights/getSessionInsightsData/main.go
- backend/lambda-functions/sessionInsights/sendSessionInsightsEmails/main.go
- backend/lambda-functions/utils.go
- render/package.json
- render/src/render.ts
Fixes inactivity pausing logic in the render lambda that would cause rendering to freeze.
Fixes all go lambdas being build in arm but running in x86 runtime.
Closes SUP-165
testing produced video
already tested in prod
no
> improvements to render lambda

- highlight.io/middleware.ts
- highlight.io/scripts/backlinks.py
- Fixes GRO-319
- Navigate to old links and check if they redirect
No
No
> add backlinks script for reorganized docs and updated middleware

- backend/clickhouse/migrations/000143_update_phonehome_tables.down.sql
- backend/clickhouse/migrations/000143_update_phonehome_tables.up.sql
Use new materialized column in the materialized view.
new data inserted correctly in prod
no
no
> fix phonehome materialized view

- blog-content/launch-week-day-1.md
- blog-content/web-socket-recording.md
- docs-content/general/changelog/changelog-18.md
- highlight.io/components/QuickstartContent/backend/elixir/other.tsx
- highlight.io/components/QuickstartContent/backend/ruby/rails.tsx
- highlight.io/components/QuickstartContent/backend/rust/actix.tsx
- highlight.io/components/QuickstartContent/backend/rust/other.tsx
- highlight.io/components/QuickstartContent/backend/shared-snippets.tsx
- highlight.io/components/QuickstartContent/logging/python/loguru.tsx
- highlight.io/components/QuickstartContent/logging/python/other.tsx
- highlight.io/components/QuickstartContent/traces/shared-snippets.tsx
- Fix launch week page links
- `http` to `https`
- Fixes GRO-326
- Click and check if links are valid
No
No
> more ahrefs fixes

- .changeset/breezy-meals-repair.md
- .changeset/chilly-ducks-battle.md
- .changeset/little-cooks-deny.md
- .changeset/red-birds-lay.md
- .changeset/rude-ears-marry.md
- .changeset/slimy-icons-grin.md
- __generated/rr/rrweb/rr.js
- sdk/highlight-apollo/CHANGELOG.md
- sdk/highlight-apollo/package.json
- sdk/highlight-cloudflare/CHANGELOG.md
- sdk/highlight-cloudflare/package.json
- sdk/highlight-hono/CHANGELOG.md
- sdk/highlight-hono/package.json
- sdk/highlight-nest/CHANGELOG.md
- sdk/highlight-nest/package.json
- sdk/highlight-next/CHANGELOG.md
- sdk/highlight-next/package.json
- sdk/highlight-node/CHANGELOG.md
- sdk/highlight-node/package.json
- sdk/highlight-react/CHANGELOG.md
- sdk/highlight-react/package.json
- sdk/highlight-react/tsup.config.ts
- sdk/highlight-remix/CHANGELOG.md
- sdk/highlight-remix/package.json
Releases:
@highlight-run/node@3.12.0
@highlight-run/next@7.9.0
@highlight-run/cloudflare@3.0.0
@highlight-run/react@12.1.0
@highlight-run/apollo@3.4.27
@highlight-run/hono@1.0.3
@highlight-run/nest@3.6.12
@highlight-run/remix@2.0.84
@highlight-run/node; @highlight-run/next; @highlight-run/cloudflare; @highlight-run/apollo; @highlight-run/hono; @highlight-run/next
fix @highlight-run/node traceparent parent_span_id propagation
configure Node.js OTLPLogExporter and OTLPMetricExporter
replace dependence on opentelemetry-sdk-workers with @opentelemetry/sdk-trace-web
@highlight-run/react
ensure ErrorBoundary component is compatible with react 18 and react 19
ensure correct version of @types/react is installed
> RELEASING: Releasing 8 package(s)

- backend/alerts/alerts.go
Use the error object event for the old error alerts
N/A
N/A
N/A
> Fix error alert title

- blog-content/auto-generating-open-api-documents-with-type-script-interfaces.md
- blog-content/launch-week-day-1.md
- blog-content/product-updates.md
- blog-content/publishing-private-pnpm-monorepo.md
- blog-content/typesafe-tailwind.md
- docs-content/general/7_integrations/amplitude-integration.md
- Fixes GRO-327
- Clicking the links to check
No
No
> ahrefs fixes for links to broken page

- backend/event-parse/parse.go
- backend/public-graph/graph/resolver.go
- backend/public-graph/graph/schema.resolvers.go
- backend/redis/utils.go
- backend/worker/kafka_worker.go
- backend/worker/worker.go
* improve tracing for pushpayload processing
> improve performance of pushpayload processing

- backend/public-graph/graph/schema.resolvers.go
> fix sample logic

- __generated/rr/rrweb/rr.js
Sync rrweb reflame files - believe they were introduced in https://github.com/highlight/highlight/commit/774b40cfe949f23f35f93285679aff2d28c8f930#diff-2313ba8c661628ebcf963cac5032a2b7713c65698738750fdf5b5959d937414d without anyy changes to reflame
N/A
Fix build
N/A
> Reflame rrweb sync

- backend/public-graph/graph/schema.resolvers.go
- removes ingest filter completely
- will monitor in prod after deploying
- processing sampling still at 50% - will raise after confirming no issues with a larger ingest rate
- can revert if issues
- no
> remove ingest filter completely

- backend/env/environment.go
- backend/env/environment_test.go
- backend/private-graph/graph/auth_client.go
- backend/private-graph/graph/auth_route.go
- backend/private-graph/graph/schema.resolvers.go
- frontend/src/index.tsx
- frontend/src/util/auth.tsx
For production, app.highlight.io and pri.highlight.io are different domains and need a cross-domain cookie.
https://www.loom.com/share/5fa72e0c27d24fa5a2f89f3a4d261bb2
no
no
> fix state issue in oauth sso signin

- backend/private-graph/graph/auth_client.go
Fix bug: https://app.highlight.io/1/errors/azvH5U1kf7z0aZJ1cMiuQOrPsk4j
N/A
N/A
N/A
> Fix undefined access in auth client

- backend/private-graph/graph/resolver.go
Update the default dashboard to correctly render web vitals.
manually updating dashboards
no
no
> update default dashboard to correctly render web vitals

- backend/model/model.go
- backend/pricing/pricing.go
- backend/public-graph/graph/resolver.go
- backend/worker/kafka_worker.go
Received a customer report that we are sendning erroneous notifications for billing,
saying that there is a billing issue originally when the subscription is created.
Add new logging to help troubleshoot the issue.
CI
checking for this log
no
> add log for stripe billing error email notification

- backend/worker/worker.go
Setup task cancelation to avoid partitions being stuck
CI
monitoring prod deploy
no
> cancel long running tasks

- highlight.io/components/Home/CompaniesReel/CustomerReel.tsx
- highlight.io/pages/customers/index.tsx
Reflect changes to customers on landing page.
[Vercel preview](https://highlight-landing-git-vadim-update-customers-highlight-run.vercel.app/)
no
no
> update customers list

- .changeset/flat-feet-unite.md
- frontend/package.json
- frontend/src/components/LaunchDarkly/LaunchDarklyProvider.tsx
- frontend/src/pages/Buttons/Buttons.tsx
- sdk/highlight-run/src/client/types/types.ts
- sdk/highlight-run/src/integrations/launchdarkly/index.ts
- yarn.lock
Enable client integration.
local deploy
no
no
> turn on dogfooding of ld client integration

- backend/alerts/v2/destinations/slack/messages.go
- backend/private-graph/graph/auth_client.go
- backend/temp-alerts/temp-alerts.go
* Fixes auth logic panic
* Fixes alerts panic
local deploy, CI
no
no
> fix backend panics

- backend/model/model.go
- backend/public-graph/graph/client_sampling.go
- backend/public-graph/graph/client_sampling_test.go
- backend/public-graph/graph/generated/generated.go
- backend/public-graph/graph/model/models_gen.go
- backend/public-graph/graph/schema.graphqls
- backend/public-graph/graph/schema.resolvers.go
- backend/store/client_sampling_configuration.go
> Implement support for client-side sampling.

- backend/env/environment.go
- backend/redis/utils.go
- docker/.env
- docker/compose.yml
Due to security vulnerabilities in an unauthenticated redis server,
add a default redis password.
CI
local testing
no
no
> add default redis password

- backend/worker/worker.go
Debugging some very-long active intervals in a session.
deploying and looking for logs
no
no
> ignore excessively-long active intervals

- frontend/src/pages/Player/PlayerHook/PlayerState.ts
Fix to resolve issues with session replay freezing
Tested in launch darkly
No
No
> Small change improving session replay stability
