highlight/highlight

.github/workflows/turbo.yml, package.json
Using `yarn changeset publish` in our repo does not work because of monorepo `workspace:*` dependencies.
Use our custom `yarn npm publish` logic which will be triggered by the changeset github action.
CI
No
No
=> fix publishing of packages

packages/ui/src/components/Dialog/Dialog.stories.tsx
New version of Reflame tests can now reuse results from a previous test when it finds one with an identical dependency graph, a critical cost-savings measure for large test suites.
I also updated the test results display to use markdown content with embedded images directly instead of the images field in github checks, and split tests results into failed, completed, skipped sections, which should make test results a lot easier to digest.
While testing this out I actually found a bug with one of the stories and fixed it here. :)
Check out the new test results display [here](https://github.com/highlight/highlight/pull/6816/checks?check_run_id=17488390451), and let me know what you think!
=> Fix dialog story & try out reflame test update

backend/model/model.go, backend/private-graph/graph/resolver.go, backend/public-graph/graph/resolver.go, frontend/src/pages/Player/Toolbar/NewCommentForm/NewCommentForm.tsx
Slack alerts are not standardized and can be hard to decipher. Update the Slack alerts to use different colors to signify level and standardize how they are displayed.
1) Create each of the alert and view in #spencer-error-test channel
N/A
Yes
=> Update Slack alerts

backend/public-graph/graph/resolver.go, sdk/highlight-go/otel.go
Fixes frontend network trace recording to store the request ID as the trace ID.
Propagates the request ID to the child span context to associate backend traces 
with the frontend network request by using the request ID as a trace ID.
Backend traces correctly associated with network request trace.
No
No
=> use request id when set for the trace id

backend/private-graph/graph/schema.resolvers.go
Project settings were not loading because the graphql schema was failing with the `sampling` object not set.
correctly saving + loading project settings now
No
No
=> fix loading of project settings

backend/alerts/alerts.go, backend/alerts/integrations/discord/messages.go, backend/alerts/integrations/discord/messages_test.go, backend/alerts/integrations/integrations.go, backend/model/model.go, backend/public-graph/graph/resolver.go, frontend/src/pages/ErrorsV2/ErrorFeedCard/ErrorFeedCard.tsx
Highlight new errors in the app and alerts to help developers quickly squash new bugs that occur.
Alert changes: New preview text and heading for Slack and Discord alerts to help users be able to search on their app. This can also be used to see when an alert first occurs.
App changes: Add a "New" badge to the error search page to help point users to recently created error groups.
1) Create an error alert that reports to a Slack and Discord channel. (Recommend setting threshold to 1)
2) Find a frontend file that is rendered
3) Add a `console.log(madeUpVariable)` to the file
4) Load the screen, and it should crash
N/A
Yes
=> Update slack and discord error alerts

frontend/src/__generated/index.css, frontend/src/__generated/ve/pages/ErrorsV2/ErrorBody/components/ErrorBodyText/style.css.js, frontend/src/__generated/ve/pages/Player/RightPlayerPanel/style.css.js, frontend/src/pages/ErrorsV2/ErrorBody/components/ErrorBodyText/index.tsx, frontend/src/pages/ErrorsV2/ErrorBody/components/ErrorBodyText/style.css.ts, frontend/src/pages/Player/RightPlayerPanel/RightPlayerPanel.tsx, frontend/src/pages/Player/RightPlayerPanel/style.css.ts
When the error instance event is over a certain amount of lines, it overflows into the other content. Allow the container to grow and scroll when necessary.
https://www.loom.com/share/aa4c61e67d52492cb8b40d354ca34896?sid=91820b21-6462-4fc8-a414-5a179953aba5
1) Fix the error event to a long excerpt of text
2) View the error instance on the error show page
3) View a session with an error, and click to display an error in the right panel
N/A
N/A
=> Fix error instance overflow

frontend/src/pages/ErrorsV2/ErrorFeedCard/ErrorFeedCard.tsx
Error card tags are taking up too much space and make the feed look too busy.
[Reflame](https://preview.highlight.io/1/errors?page=1&query=and%7C%7Cerror_state%2Cis%2COPEN%7C%7Cerror-field_timestamp%2Cbetween_date%2C2023-09-11T21%3A53%3A32.316Z_2023-10-11T21%3A53%3A32.316Z&%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201HCGBMHNTK8T87QXQDN1JZ3PW%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22vadim%2Fremove-error-feed-tags%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D)
No
Yes
=> remove feed error card tags

backend/alerts/integrations/discord/messages.go, backend/jobs/log-alerts/log-alerts.go, backend/model/model.go, backend/private-graph/graph/resolver.go
The log alerts and comment alerts were not updated to the new styling. Give them an update:
Log alert
Comment alert
1) Create a new log alert that is easy to fire
2) Add a Discord and Slack channel to alert
3) Run the log alert watcher locally: `make start-log-alerts-watch`
4) Comment on a session
5) Reply to comment
N/A
Yes
=> Update log alerts

backend/clickhouse/traces.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/__generated/index.css, frontend/src/__generated/ve/pages/Traces/TraceErrors.css.js, frontend/src/__generated/ve/pages/Traces/TraceLogs.css.js, frontend/src/__generated/ve/pages/Traces/TracePage.css.js, frontend/src/__generated/ve/pages/Traces/TraceSpanAttributes.css.js, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/Traces/TraceErrors.css.ts, frontend/src/pages/Traces/TraceErrors.tsx, frontend/src/pages/Traces/TraceLogs.tsx, frontend/src/pages/Traces/TracePage.css.ts, frontend/src/pages/Traces/TracePage.tsx, frontend/src/pages/Traces/TraceSpanAttributes.tsx, frontend/src/pages/Traces/TracesList.tsx, frontend/src/routers/ProjectRouter/ApplicationRouter.tsx, packages/ui/src/components/Tabs/Tabs.tsx
* Highlights the selected span from the traces list in the flame graph on the trace detail page
* Adds an "Errors" tab to view the errors related with the trace
* Adds a "Logs" tab to view logs related with the trace
https://www.loom.com/share/375f3125baf84450b8b82c4e5556cc46
Local + PR preview click test
Need to confirm backend changes work in prod, but any new backend logic is only hit when making requests from the new traces pages, which are only available to Highlight admins at the moment.
Yes, I'm planning to do some polish work w/ Julian once this goes out and people get to play with it a little.
=> Updates to individual trace view

backend/private-graph/graph/oauth.go, scripts/migrations/init.sql
Operation name isn't a good way to validate the request
since it is client-determined.
Instead, changes the OAuth operation validation to use the field name.
Updates e2e test on `test_oauth_graphql.py`
No
No
=> validate oauth access by graphql field

backend/private-graph/graph/schema.resolvers.go
- added an index to query error_objects by project_id + trace_id faster: `create index concurrently idx_error_objects_trace_id on error_objects (project_id, trace_id)`. this change adds project_id to the query so it can use the index.
- tested query in prod, ran in <100ms
```
select * from error_objects where trace_id = 'X' and project_id = 1
```
- clicktested individual trace view to confirm it was still working
- no
- no
=> query trace errors w/ project id to use index

backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, backend/worker/kafka_worker.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/Setup/IntegrationBar.tsx, frontend/src/pages/Setup/SetupRouter/SetupRouter.tsx, frontend/src/util/integrated.tsx, highlight.io/components/QuickstartContent/QuickstartContent.tsx, highlight.io/components/QuickstartContent/traces/go/go.tsx, highlight.io/components/QuickstartContent/traces/shared-snippets.tsx
- adds logic to private graph / trace ingest to record and query when backend traces are being sent
- add traces quickstart step guarded by `isHighlightAdmin`
- will add guide for OLTP and add to docs page later
- no
=> add backend setup logic for traces, add quickstart guide for go

frontend/src/components/Header/Header.tsx
- adds banner for launch week 3, active between 10/16 and 10/21 9am PST
- click tested locally and changed start/end dates
- requires #6868 to be deployed first to add launch week 3 route
- no
=> add app banner for launch week 3

backend/private-graph/graph/schema.resolvers.go, frontend/src/pages/Alerts/LogAlert/LogAlertPage.tsx
Fix: https://www.loom.com/share/2020b947f0fc4dd28eb9e4ee9507388b
Did some deep dive into it because I had trouble repo'ing. It looks like it only affects Log Alerts, as I tried it on all alerts in prod and only that one cause duplication. 
Solution: Change save() to updates() because save creates a new object if it doesn't exist already for a primary key. 
Also bug fix by adding a redirect to alerts home after updating log alert
=> Fix log alert saving logic to use update, prevent duplication

frontend/src/pages/Auth/SignInRedirect.tsx, frontend/src/routers/ProjectRouter/ProjectRedirectionRouter.tsx
Visiting `app.highlight.io` on a new incognito tab and logging in to a
existing account would cause a redirection back to `/` rather than to the default project,
resulting in a blank screen.
Broken in production if you visit https://app.highlight.io and sign in.
Tested by visiting [reflame](https://preview.highlight.io?%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201HCZ6H069VV7ZSXGCDBDXTMM9%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22vadim%2Ffix-redirection%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D) in incognito and signing in.
No
No
=> fix lack of redirection on login

frontend/src/pages/Alerts/ErrorAlert/ErrorAlertPage.tsx, frontend/src/pages/Alerts/LogAlert/LogAlertPage.tsx, frontend/src/pages/Alerts/SessionAlert/SessionAlertPage.tsx
- fixes #6792 by validating alert thresholds >= 1
- click tested creating session/log/error alerts
- no
- no
=> enforce alert threshold >= 1

frontend/src/components/Header/Header.tsx, frontend/src/pages/Setup/SetupRouter/SetupRouter.tsx
- removes the highlight admin checks from showing traces in the navbar and traces in the setup menu
- will deploy this sometime between now and 9am tomorrow
- no
=> remove feature flags from traces

highlight.io/components/Launch/Week3/DayFour.tsx
- should link to `https://www.highlight.io/blog/migrating-opensearch-to-clickhouse` without .md 
- no
- no
=> fix opensearch migrate blog link

docs-content/general/6_product-features/1_session-replay/1_overview.md, docs-content/general/6_product-features/1_session-replay/privacy.md, docs-content/sdk/client.md
Removes an unnecessary privacy doc here: https://www.highlight.io/docs/general/product-features/session-replay/privacy.
Click test.
no
no
=> Remove unnecessary privacy doc

.changeset/two-dots-occur.md, sdk/client/src/index.tsx
The client would be resetting the user identifier of the new session when
`H.init({forceNew: true})` is set, since the new session is likely going to `H.identify` as
a different user, but we only maintain the first user identifier.
Local deploy.
Changeset
No
=> fix forceNew maintaining user

backend/main.go, backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver.go, backend/public-graph/graph/schema.resolvers.go, sdk/highlight-go/middleware/chi/middleware.go, sdk/highlight-go/middleware/echo/middleware.go, sdk/highlight-go/middleware/fiber/middleware.go, sdk/highlight-go/middleware/gin/middleware.go, sdk/highlight-go/middleware/gorillamux/middleware.go
Noticed with @ccschmitz that we have some traces (`highlight/chi`) that do not have
the parent span recorded. We suspect this is because we are sampling by trace id, but our
middleware ordering did not propagate the trace id correctly.
Renaming some middleware span naming to be more consistent with the rest of our traces.
I've also refactored the private graph tracing per the [DD docs for resource name](https://docs.datadoghq.com/tracing/services/resource_page/), 
where we have some confusion with how we name traces. 
Local deploy showing correct propagation of the trace.
No
No
=> cleanup internal traces

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/Alerts/LogAlert/LogAlertPage.tsx, frontend/src/pages/ErrorsV2/ErrorInstance/ErrorBoundaryFeedback.tsx, frontend/src/pages/ErrorsV2/ErrorInstance/ErrorInstance.tsx, frontend/src/pages/Sessions/SessionsFeedV3/MinimalSessionCard/utils/utils.ts
Adds support for querying session comments on the error_instance
Shows error boundary session comment feedback on UI as [per design](https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=11613%3A575444&mode=dev)
I made a page crush and the error boundary feedback component was shown
I filled the form and submitted
On the error instance, I checked to make sure the feedback is shows
And the link on the feedback component takes me to the related session
No
Yes
This shows the feedback on the error instance under user details
Also demonstrates the link to related session
https://www.loom.com/share/b357e312b57d4b5cb362ec4c816d029e?sid=1fd0eac7-b127-4030-9f25-0da9597f4eaf
/claim #6642
fixes #6642
=> show error boundary feedback on error instances

backend/clickhouse/querybuilder.go, frontend/src/components/QueryBuilder/QueryBuilder.tsx
- active length should use the `getTimeLabel` label function
- length needs to be converted from minutes to ms (`*= 60000`)
- fixes #6899 
https://www.loom.com/share/63b231d9f1744b0a9213057c19ff8a5c
- no
- no
=> fix "between time" label and ms conversion

backend/clickhouse/cursor_test.go, backend/clickhouse/logs_test.go, backend/clickhouse/test_utils.go, backend/main.go, backend/migrations/cmd/backfill-session-properties-clickhouse/main.go, backend/otel/otel_test.go, backend/private-graph/graph/resolver_test.go, backend/public-graph/graph/resolver_test.go, backend/store/error_groups.go, backend/store/main_test.go, backend/store/store.go, backend/worker/autoresolver_test.go
- when an error group's state is updated by the user, apply that update synchronously in clickhouse so there's no delay
- fixes #6688 
- https://www.loom.com/share/e2a1343ac7f84e73b2aeec8e3fd616c4
- no
- no
=> synchronously apply user-driven error group updates

backend/otel/otel.go
- it seems like the `exceptionMessage` field is blank for certain exception events coming from Next.js - add some logging here to see 1. if this codepath is the cause of the blank error logs and 2. what the other event fields are when this occurs to see if there's another field we should extract
- related to #6916 
- will monitor this log in prod after deployment
- no
- no
=> logging for empty exceptions

backend/otel/otel.go
- these events have only happened 27 times in the past 2 hours and all of the Next.js ones are related to a `DevServer.handleCatchallMiddlewareRequest` error - it doesn't seem like this error has user impact as all the associated requests have status code 200 and looking at https://github.com/vercel/next.js/blob/d0e92b19af6672c44533eb8b6826007f645a943d/packages/next/src/server/next-server.ts#L1644 it doesn't seem like a real error but I don't really know what that's for
- examples:
```
map[exception.stacktrace:Error at DevServer.handleCatchallMiddlewareRequest (.../node_modules/next/dist/server/next-server.js:1067:33) at async DevServer.handleRequestImpl (.../node_modules/next/dist/server/base-server.js:735:32) exception.type:Error]
```
```
map[exception.stacktrace:Error at …
```
=> skip exception events with no message

.changeset/lazy-dogs-smoke.md, sdk/client/src/index.tsx
Manual canvas snapshotting broke the existing auto functionality by removing
the `canvas: 2` default we used to have.
This change ensures that when `enableCanvasRecording: true` is provided with no `samplingStrategy`,
auto snapshotting at 2FPS will be used.
CI
Changeset
No
=> fix default canvas snapshotting

e2e/nextjs/next.config.mjs, e2e/nextjs/pages/api/trpc/[trpc].ts, e2e/nextjs/src/app/components/trpc-queries.tsx
I couldn't reproduce the TS error from #6849.
I added a tRPC mutation error handler to test that, just in case I was missing something. It worked first try.
closes #6849
=> tRPC mutation error thrower

frontend/src/pages/ErrorsV2/ErrorStackTrace/ErrorStackTrace.tsx, frontend/src/pages/ErrorsV2/ErrorTag/ErrorTag.tsx
Make a couple tweaks to the error UI:
- remove the 0 line number from the stack trace
- Add "padding" to the error tags
https://www.loom.com/share/85b14b9e4fb14fb08b0f4825985df9dc?sid=fa17c519-8bae-472a-81c5-bbf86a2cb590
N/A
N/A
=> Error UI tweaks

backend/private-graph/graph/schema.resolvers.go, frontend/src/index.tsx, frontend/src/pages/Auth/InviteTeam.tsx
- fix issue where invite had role "0" instead of "MEMBER" / "ADMIN" - workspace_admins were created with this "0" role which led to some buggy behavior in places where "MEMBER" or "ADMIN" were expected
- sets the invitee role as the same as the inviter
- should we add an option for ADMINs to invite MEMBERs or is this ok for now?
- hides the "Allow joining by email domain" option for non-ADMINs since the resolver throws an error
- clicktested locally as both a MEMBER and ADMIN
- will run the following:
```
begin
update workspace_admins set role = 'MEMBER' where role not in ('ADMIN', 'MEMBER')
update workspace_invite_links set invitee_role = 'MEMBER' where invitee_role not in ('ADMIN', 'MEMBER')
commit
```
- no
=> team invite role should match inviter's

.changeset/old-waves-deny.md, docs-content/getting-started/3_client-sdk/7_replay-configuration/recording-network-requests-and-responses.md, sdk/client/src/listeners/first-load-listeners.tsx, sdk/client/src/listeners/network-listener/network-listener.ts, sdk/client/src/listeners/network-listener/utils/network-sanitizer.ts, sdk/client/src/listeners/network-listener/utils/utils.ts, sdk/client/src/types/client.ts
While Highlight does provide whitelisting to [redact network header and body](https://www.highlight.io/docs/getting-started/client-sdk/replay-configuration/recording-network-requests-and-responses#redacting-headers-and-bodies), the current functionality is very limiting. It is a non-trival job to whitelist all sort of data types and keys for PIIs, tokens, passwords and so on by hand. It's specially harder when using graphql due to the single endpoint nature of the protocol.
Instead of having a rigid list of keywords and url rules, I'd like to be able to modify the entire network data to my liking based on my application needs and privacy rules. Allow for the client application to customize the request/response right before sending any data to its platform.
One can for instance, modify …
=> Allow users to pass in sanitize method for XHR/fetch requests

docs-content/getting-started/fullstack-frameworks/remix.md
closes #6834 
Adding `onShellReady` and `onShellError` example code.
=> Demonstrating onShellReady and onShellError handlers

frontend/src/pages/ErrorsV2/ErrorTag/ErrorTag.tsx
We had [a ticket](https://github.com/highlight/highlight/issues/6898) for fixing an issue where text was being cut off. I dug in to investigate and found it was fixed in https://github.com/highlight/highlight/pull/6936, but realized the only reason we needed the fix was because we had an unnecessary `<Text>` element wrapping the contents of the tag. This PR cleans up the markup since `Tag` already wraps the contents with `<Text>`:
https://github.com/highlight/highlight/blob/c699d1944192267691b2ef5ff5a19bb2facb3f3f/packages/ui/src/components/Tag/Tag.tsx#L72-L83
N/A - small client-side tweak.
Nope!
=> Clean up error tags component

e2e/express/src/index.mjs, sdk/highlight-py/e2e/highlight_fastapi/main_2.py, sdk/highlight-py/highlight_io/sdk.py, sdk/highlight-py/pyproject.toml, sdk/highlight-py/tests/test_sdk.py
Turns out the opentelemetry `self.tracer.start_as_current_span` contextmanager
already reports an exception if the inner contents raise an error. Since we want
to `raise` there to propagate the exception to the outer web framework, we
set `record_exception=False` to avoid having the opentelemetry context manager
reporting the exception event a second time (in addition to our manual time that reports custom attributes).
Unit test
Local testing
one error recorded with fix, two duplicate errors without the fix
New python patch version.
No
=> ensure only one error is sent for the trace context manager

backend/event-parse/parse.go, backend/event-parse/parse_test.go, backend/public-graph/graph/resolver.go
Some CSS stylesheets have relative path references from which they need to be fetched. Previously, this would be fetched from `app.highlight.io`, but we should use the url of the site in the snapshot.
I am not currently able to test on their site (waiting for an invite), but confirmed that Highlight sessions with absolute urls are not broken.
N/A
N/A
=> Fix relative stylesheets

frontend/src/pages/Auth/InviteTeam.tsx, frontend/src/pages/Auth/JoinWorkspace.tsx, frontend/src/pages/Auth/SignUp.tsx
1. Fixes a bug where the join workspace submit button was disabled until you interacted with the form. It would look like you had a workspace selected to join, but the button was disabled until you interacted with the workspace dropdown, which caused confusion for people joining workspaces.
1. Updates the CTA to dismiss the join workspace page when your able to join a workspace based on your email domain.
1. Fixes a bug where the `allowed_auto_join_email_origins` field wasn't being populated even when the checkbox was selected on the invite team page. This was because the server expected a string that could be parsed as JSON - an array of allowed email domains.
1. Updates the loading state of the form submit button on the sign up form so that it is always dismissed after a successful …
=> Join workspace fixes

frontend/src/components/DemoModal/DemoModal.tsx, frontend/src/components/Header/Header.tsx, frontend/src/components/Header/components/ProjectPicker/ProjectPicker.tsx
* create a hubspot contact when the demo page gets an email submission
* fix `go back to your project` header
* make projects dropdown more useful in demo project
Local deploy
https://www.loom.com/share/38ca6ab46e8e45178f4e5267e58b7308
No
No
=> misc demo project fixes

docs-content/getting-started/3_client-sdk/7_replay-configuration/privacy.md
Call out the privacy settings in `Recording Network Requests and Responses` in our overall privacy document
1. View https://highlight-landing-ar4rc84b4-highlight-run.vercel.app/docs/getting-started/client-sdk/replay-configuration/privacy#network-request-redaction
N/A
N/A
=> Add privacy documentation link to network options

backend/private-graph/graph/schema.resolvers.go
"Welcome" messages are sent when an alert is created/updated/deleted to let the Slack message know to expect messages to start or stop receiving messages. These include a link to the alert, which is some cases was broken due to a bad slug. Update the slugs of the alerts to fix the links.
1) Create an error alert that is sent to a slack channel
2) Update the error alert
3) Delete the error alert
4) Create an session alert that is sent to a slack channel
5) Update the session alert
6) Delete the session alert
https://www.loom.com/share/d8b3c2a711674faeb72f3021cc023098?sid=935c013d-0ebf-4a0a-b593-b68c24439572
N/A
N/A
=> Fix alert welcome message

highlight.io/pages/for/[slug].tsx
Next.js page (and other feature pages) had large bug images. I added a height and width of 250px to match the main landing page. Check it out at /for/next
Looking at the bugs on different screen sizes
No
No
=> edited bug size

backend/storage/storage.go
- `PutObjectInput` has a `ContentType` field - set this when saving session resources
- fixes #6658 
- fixes #6924 
https://www.loom.com/share/9c64f110b40440b89814451765fb57da
- click tested locally w/ S3 object storage
- no
- no
=> use content type setting when saving s3 asset

highlight.io/pages/pricing/index.tsx
- adds included traces quantity to the pricing cards
- adds a traces section to the pricing calculator
https://www.loom.com/share/52c69ccad9a74b7abe158c486422baee
- no
- no
=> add traces to website billing calculator

.changeset/mighty-suns-grow.md, .changeset/serious-cooks-bathe.md, .changeset/stale-zebras-switch.md, .changeset/thick-papayas-confess.md, e2e/express/src/index.mjs, sdk/highlight-node/package.json, sdk/highlight-node/rollup.config.js, sdk/highlight-node/src/client.ts, sdk/highlight-node/src/hooks.ts, yarn.lock
Our node SDK was throwing red-herring errors while shipping logs / traces because of
the interval flush logic. This logic was not needed as OTEL has it's own loop for flushing data.
* fixes recursion error during stringification of certain objects #6839 
* ensures console attributes are correctly reported correctly as structured attributes
* ensures we fully rely on bundling opentelemetry to help with #7010
Closes #6987
tested locally by ingesting a network latency `tc qdisc add dev lo root netem delay 10000ms`
before
after
Logs coming through correctly locally
tested in next js edge runtime as well
No
Changeset
=> fix node sdk timeouts

.changeset/mighty-sloths-deny.md, cypress/e2e/client.cy.js, e2e/tests/test_oauth_graphql.py, sdk/client/vite.config.ts, sdk/firstload/src/index.tsx, sdk/firstload/vite.config.ts
Next.js tends to duplicate our highlight.run call in a way that can insert copies of the highlight.run
(with all but one being unused). The bundle is small, but pulls in our large static.highlight.io script
potentially more than once.
This PR adds an HTML id to check whether the script tag has already been inserted.
Before
Only one script tag added
static.highlight.io no longer in lighthouse report
session still records
Changeset
No
=> ensure highlight.run script tag is only added once

.changeset/fuzzy-rules-press.md, e2e/express/src/index.mjs, highlight.io/components/Home/SnippetTab/SnippetTab.tsx, highlight.io/components/QuickstartContent/backend/js/express.tsx, sdk/highlight-apollo/src/apollo.ts, sdk/highlight-apollo/src/apolloV3.ts, sdk/highlight-nest/src/index.ts, sdk/highlight-next/src/util/highlight-edge.ts, sdk/highlight-next/src/util/types.ts, sdk/highlight-next/src/util/with-highlight-edge.ts, sdk/highlight-next/src/util/with-highlight-nodejs-app-router.ts, sdk/highlight-next/src/util/with-highlight-nodejs-page-router.ts, sdk/highlight-node/src/client.ts, sdk/highlight-node/src/handlers.ts, sdk/highlight-node/src/sdk.test.ts, sdk/highlight-node/src/sdk.ts
Support highlight request context globally to associate async console logs / errors with highlight.
In backend node.js, our console method instrumentation was never associated with
frontend sessions because we were not tracking request context globally.
This is now accomplished thru the use of `AsyncLocalStorage` (when supported) and a global
attribute when now (for instance, in edge runtime). Closes #6996
Express E2E sending logs locally with the associated session / request
otel reported attributes
```json
{
"result": 499447.28171779995,
"value": 220.68512975204024,
"exception.stacktrace": "\"Error\\n    at console.<computed> [as info] (/hom.../dist/index.cjs:63:921668\"",
"highlight.project_id": "1",
"log.severity": "info",
"log.message": "some work happening …
```
=> node.js should associate console logs with session context

backend/clickhouse/query.go, backend/clickhouse/traces.go
Filter out `IsIngestedBy` and other internal traces from our queries (listing traces, showing trace metrics).
Local deploy shows no internal traces
generates query
```sql
SELECT Timestamp, ...
FROM traces
WHERE ProjectId = 1
AND (Timestamp, UUID) IN (SELECT Timestamp, UUID
FROM traces
WHERE ProjectId = 1
AND Timestamp ...
AND (TraceAttributes['highlight.type'] != 'highlight.internal')
ORDER BY Timestamp DESC, UUID DESC
LIMIT 51)
ORDER BY Timestamp DESC, UUID DESC
```
No
No
=> remove ingested by traces by default

backend/model/model.go, backend/pricing/pricing.go, backend/private-graph/graph/schema.resolvers.go, scripts/migrations/init.sql
Adds support for custom overage price IDs that will be used when attaching
overage invoice items. Can work alongside the existing pricing model or can replace
existing default prices.
* new workspace model columns allow setting a custom overage price id
* the billing logic now supports metered prices (recurring prices) that are usage-billed.
Closes #6381
tested on a stripe subscription that previously had a default non-graduated invoice item for sessions to make sure the new path will remove the existing invoice item.
No
No
=> support custom and graduated pricing

backend/clickhouse/query.go, backend/clickhouse/traces.go, frontend/src/components/Search/SearchForm/utils.ts
- use "message" as `BODY_KEY` in the UI for consistency
- use `bodyColumn` when querying instead of hardcoding "Body"
- fixes #6859 
- https://www.loom.com/share/3dc2f8dc061b45f8a010386566d133c6
- no
- no
=> use 'message' instead of body in logs UI, use dynamic body column

.changeset/healthy-dancers-swim.md, e2e/nextjs/next.config.mjs, sdk/highlight-node/src/client.ts
It looks like I broke a resource merge a few months back. It didn't appear to break anything, because we were setting session data on every span manually.
BUT, with this resource fixed, we can get automatic tracing data straight from Next.js.
HT to @Vadman97 for finding the bug!
=> Node SDK Resource merge

highlight.io/components/QuickstartContent/traces/otlp.tsx
The `Resource` example was incorrect and was missing an import.
CI / vercel preview
No
No
=> fix opentelemetry tracing example

.changeset/small-glasses-sit.md, docs-content/getting-started/fullstack-frameworks/next-js/2_page-router.md, docs-content/getting-started/fullstack-frameworks/next-js/3_app-router.md, e2e/nextjs/instrumentation.ts, e2e/nextjs/next.config.mjs, e2e/nextjs/pages/redirect.tsx, e2e/nextjs/pages/ssr.tsx, e2e/nextjs/src/app/_utils/page-router-highlight.config.ts, e2e/nextjs/src/app/app-router/redirect/page.tsx, e2e/nextjs/src/app/app-router/ssr/page.tsx, e2e/nextjs/src/app/components/path-buttons.tsx, sdk/highlight-next/src/util/highlight-edge.ts, sdk/highlight-next/src/util/register-highlight.ts, sdk/highlight-next/src/util/types.ts, sdk/highlight-next/src/util/with-highlight-edge.ts, sdk/highlight-node/src/types.ts
Edge doesn't provide `global`, so we're using `AsyncLocalStorage` instead.  
Testing also revealed that the header parsing logic was inverted, causing headers to get lost on all Edge requests. 
Deploys to Vercel
No.
Batch bump to Next SDK
=> Repair Next.js Edge SDK

.changeset/quick-planes-hug.md, .changeset/shaggy-olives-invite.md, sdk/highlight-nest/src/index.ts, sdk/highlight-next/src/util/highlight-edge.ts, sdk/highlight-next/src/util/highlight-node.ts, sdk/highlight-next/src/util/instrument-server.ts, sdk/highlight-next/src/util/types.ts, sdk/highlight-next/src/util/with-highlight-nodejs-app-router.ts, sdk/highlight-next/tsup.config.ts, sdk/highlight-node/src/client.ts, sdk/highlight-node/src/index.ts, sdk/highlight-node/src/sdk.ts
Removes our usage of `global.__HIGHLIGHT__` which does not work in edge runtime.
Consolidates duplicate types that expose the highlight session / request context.
Vercel deploy of highlight.io edge runtime methods.
Changeset
No
=> refactor node sdk highlight context types

frontend/src/pages/ErrorsV2/ErrorStackTrace/ErrorStackTrace.tsx
We do not have a good idea of what users are viewing in the error traces. Add an event, `error-stack-trace-clicked` when a user clicks to expand/hide the error stack trace, so we can filter sessions with this event name.
1) View an error
2) Click to expand an error trace. Click to hide it
3) Close your session and let process
4) Filter sessions out by the `error-stack-trace-clicked` event
N/A
N/A
=> Track error trace clicks

backend/clickhouse/logs_test.go, backend/clickhouse/query.go, docs-content/general/6_product-features/4_logging/log-search.md, frontend/src/components/Search/SearchForm/SearchForm.tsx
Adds support for `NOT` clauses on logs and traces by prefixing attributes with `-`. Also updates the docs and adds a link to view the docs for the search specification.
https://www.loom.com/share/e8482f8dc3f54d27bf0caaac330e879c
Note that this maintains the ability to assign multiple filters on the same attribute as OR queries, but any NOT filters will be applied using an AND.
Should keep an eye on performance of queries, especially on traces, otherwise just need to ensure filters continue to work as expected.
N/A
=> Support NOT filters for logs and traces

.github/workflows/backend.yml, backend/embeddings/embeddings.go, backend/event-parse/parse.go, backend/pricing/pricing.go, backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver.go, backend/store/error_group_activity_logs.go, backend/store/error_groups.go, backend/store/project_filter_settings.go, backend/store/projects.go, backend/store/services.go, backend/store/sessions.go, backend/store/system_configuration.go, backend/store/workspace_settings.go, backend/store/workspaces.go, backend/worker/kafka_worker.go, backend/worker/worker.go
Adds a new CI rule checking that we call `WithContext` everywhere we perform certain GORM operations and fixes all the violations. Currently ignoring many areas of the codebase and many violations were fixed by using `context.TODO()`. We should look at filling in the missing contexts and expanding coverage of the linting rule over time, but the key areas of our background codebase are covered with this.
Ran in CI + click tested locally.
Should keep an eye on any new errors, but should be a fairly safe change if builds are clean.
N/A
=> Add CI check for WithContext on GORM calls

backend/clickhouse/migrations/000059_create_traces_by_id_mv.down.sql, backend/clickhouse/migrations/000059_create_traces_by_id_mv.up.sql, backend/clickhouse/traces.go
- currently using a projection for querying traces by their id, however it is a bit slow because it is partitioned by date like the parent table
- this creates a separate table + materialized view with the same `order by` 
- closes #7098 
- the materialized view has already been created in prod
- can drop the existing projection after this is deployed
- no
=> create new mv to for indexing traces by id

sdk/highlight-java/highlight-sdk/src/main/java/io/highlight/sdk/HighlightOpenTelemetry.java
Tune OTLP export for the Java SDK.
* Turns on gzip compression for logs
* Decreases frequency of export and increases batching.
* Increases export timeouts.
Local deploy
Releasing new java tag.
No
=> tweak export settings

frontend/src/__generated/index.css, frontend/src/__generated/ve/components/FeedResults/FeedResults.css.js, frontend/src/components/FeedResults/FeedResults.css.ts, frontend/src/components/FeedResults/FeedResults.tsx, frontend/src/pages/Traces/TracePage.tsx, frontend/src/pages/Traces/TracePanel.tsx, frontend/src/pages/Traces/TraceProvider.tsx, frontend/src/pages/Traces/TracesList.tsx, frontend/src/pages/Traces/TracesPage.tsx
Fetches more traces in the background and notifies users when there are more traces to load.
https://www.loom.com/share/0a43bec8b3064716931527a2f1955e00
N/A - all client-side changes.
Nope!
=> Notify users when there are more traces to load

.changeset/five-stingrays-glow.md, sdk/highlight-next/src/util/highlight-edge.ts, sdk/highlight-node/package.json, yarn.lock
@highlight-run/node would crash in certain tRPC installations due to a missing `node:encoding` polyfill.
https://discord.com/channels/1026884757667188757/1168583618537472010
Vercel deploy
Changeset
No
=> fix @highlight-run/node crashing due to encoding not being polyfilled

.changeset/popular-kangaroos-repeat.md, sdk/highlight-next/src/util/highlight-edge.ts, sdk/highlight-next/src/util/types.ts, sdk/highlight-node/src/sdk.ts
Allows explicitly waiting to flush to ensure console logs are shipped to highlight.
Vercel deploy
Changeset
No
=> add support for @highlight-run/next flush and wait

.changeset/violet-ducks-worry.md, .reflame.config.jsonc, sdk/client/src/index.tsx, sdk/client/src/listeners/segment-integration-listener.tsx, sdk/client/src/types/types.ts, sdk/client/src/utils/sessionStorage/highlightSession.ts, sdk/client/src/utils/storage.ts, sdk/firstload/src/index.tsx
Support entirely bypassing sessionStorage for environments such as
figma plugins where `window.sessionStorage` may not be accessible.
Recording a session from [figma](https://app.highlight.io/1/sessions/3VbfjNPILWcBYEcY4Xktp1Up952F).
Changeset
No
=> allow using only local storage

.changeset/witty-geckos-cough.md, sdk/highlight-node/src/hooks.ts
Objects were sent as the structured message attributes and serialized.
Avoid serializing them to the message to avoid verbose message bodies.
Local deploy recording a log from @highlight-run/node
Changeset
No
=> change serialization for node to avoid reporting objects as the message

backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver.go, backend/redis/utils.go, backend/worker/worker.go
- when processing a session, move all data (events, network, websocket) out of redis to storage
- make the `RemoveValues` and `GetRawZRange` functions generic to work with all payload types
- tested locally by processing a session multiple times + live mode
- will monitor redis usage after deployment
- no
=> evict redis on session processing

backend/payload/payload.go
- looking at a few benchmarks, brotli level 5 is about 3x faster than level 9 while having only a percent or two better compression (e.g. https://blog.cloudflare.com/results-experimenting-brotli/)
- if the same ratios hold for our data, the cost of this extra computation outweighs the ~1% extra storage cost for session payloads
- will monitor the rate of growth in s3
- no, can revert if necessary
- no
=> reduce object storage brotli level from 9 to 5

backend/worker/worker.go
- `daily_sessions_count_view` is used instead, stop reading/writing to the old table in the worker
- this was showing up in the RDS top queries
- confirmed session processing still working locally
- no
- no
=> remove daily session count in worker

sdk/highlight-py/e2e/highlight_loguru/main.py, sdk/highlight-py/highlight_io/sdk.py, sdk/highlight-py/poetry.lock, sdk/highlight-py/pyproject.toml, sdk/highlight-py/tests/test_loguru.py
Python `logging` can report `exc_info` on the exception which should
be prioritized over the message, since the message will be a non-machine-readable
format of the stacktrace.
This supports loguru logging as well as custom usage of decorators to catch exceptions
with tools like loguru.
Updated e2e test, new unit test.
New python SDK version
No
=> capture exceptions reported on logs

.changeset/short-moons-applaud.md, sdk/client/src/index.tsx
A web app may have issues with cross origin iframe recording when the iframe
would be reloaded because the parent window would stop sending setup events
to child iframes.
This change ensures we continue to send setup events to potential highlight-instrumented
iframes so that iframe reloading would successfully record.
Reflame preview continuing to record correctly.
Changeset
No
=> ensure we set up cross origin iframe recording correctly

e2e/express-ts/package.json, e2e/express-ts/src/index.ts, e2e/express-ts/tsconfig.json, e2e/express/package.json, yarn.lock
Add express server example in typescript
for testing sourcemap backend error enhancement.
Local deploy of express server with `yarn build && yarn start`
No
No
=> add express.js typescript example

backend/public-graph/graph/resolver.go
- there are a group of sessions which are excluded but still receiving events - they should only be added to the processing queue if not excluded
- this is inflating the "sessions processed" metrics and causing unnecessary calls to postgres just to find that the session is excluded
- will monitor RDS metrics and worker dashboard after deployment to make sure this change addresses the issues
- no
- no
=> only queue session to process if not excluded

frontend/src/__generated/index.css, frontend/src/__generated/ve/pages/Traces/TraceFlameGraph.css.js, frontend/src/pages/Traces/TraceFlameGraph.css.ts, frontend/src/pages/Traces/TraceFlameGraph.tsx, frontend/src/pages/Traces/TraceFlameGraphNode.tsx, frontend/src/pages/Traces/TraceProvider.tsx, frontend/src/pages/Traces/utils.test.ts, frontend/src/pages/Traces/utils.ts
Updates the logic for displaying spans so that if there are multiple spans overlapping on the same level they will be spread out vertically to so they are easier to parse. Because children could be more than one level away from their parent now, we also show a line connecting the parent and child if they are more than one level apart.
**Before**
**After**
Also fixes a bug where the spans were overflowing the graph on render.
Note that I tried to connect spans with lines visually, similar to how Datadog handles this, but it didn't look very good. I think we'll need to think about how we want to lay this out + work with Julian to design it if we want this feature.
Local and PR preview click test.
N/A - all client-side changes. Should check in with Lewis at Reflame to see if this resolves …
=> Prevent spans from overlapping in flame graph

frontend/src/__generated/index.css, frontend/src/components/QueryBuilder/QueryBuilder.tsx, frontend/src/components/QueryBuilder/utils.ts, frontend/src/context/SearchState.ts, frontend/src/pages/Errors/ErrorSegmentSidebar/SegmentButtons/CreateErrorSegmentModal.tsx, frontend/src/pages/Sessions/SearchSidebar/SegmentButtons/CreateSegmentModal.tsx
Segments currently persist the date filters that are being used when they are created/updated. This isn't the expected behavior and it's even more problematic because after 30 days there's a good chance a segment will show empty search results because there isn't any data to show anymore.
This PR prevents us from persisting the time range for the query and also filters it out when applying a segment so that existing segments will work as expected.
I also uncovered a bug where the query would be reset to the default when toggling the segment create/edit modal - that is fixed as well.
Ensure the date field isn't applied in the following scenarios:
N/A - all client-side changes
Nope!
=> Don't use time fields in segments

.reflame.config.jsonc, frontend/scripts/build-css-bundle.mjs, frontend/src/__generated/index.css, frontend/src/__generated/rr/rr.js, frontend/src/__generated/ve/components/CommandBar/style.css.js, frontend/src/__generated/ve/components/Search/SearchForm/SearchForm.css.js, frontend/src/__generated/ve/pages/Alerts/ErrorAlert/styles.css.js, frontend/src/__generated/ve/pages/Alerts/LogAlert/styles.css.js, frontend/src/__generated/ve/pages/Alerts/SessionAlert/styles.css.js, frontend/src/__generated/ve/pages/Alerts/components/AlertNotifyForm/styles.css.js, frontend/src/__generated/ve/pages/Player/RightPlayerPanel/components/NetworkResourcePanel/NetworkResourcePanel.css.js, frontend/src/__generated/ve/pages/SettingsRouter/SettingsRouter.css.js, frontend/src/__generated/ve/pages/Traces/TracePage.css.js, frontend/src/__generated/ve/pages/Traces/TracePanel.css.js, packages/ui/entryPoints.mjs, packages/ui/vite.config.ts
The Reflame css bundle script is designed to bundle css from both the frontend app and the UI lib into a single file directly from source, meaning we don't actually need to import a separate css file for the UI lib, so I've replaced it with a noop.ts file in the Reflame config.
The bigger problem was the fact that the entry point changes broke module resolution for UI entry points in the Reflame css bundle script. This was fixed by adding some custom resolution logic for the vanilla extract plugin to make sure `@highlight-run/ui/*` references resolved to sources again.
=> Update reflame CSS bundle script to resolve new ui entry points

frontend/src/__generated/index.css, frontend/src/pages/ErrorsV2/ErrorInstance/AiErrorSuggestion.css.ts
=> Add manual css vendor prefixing for harold gradient

sdk/highlight-py/e2e/highlight_fastapi/main.py, sdk/highlight-py/highlight_io/integrations/fastapi.py, sdk/highlight-py/highlight_io/sdk.py, sdk/highlight-py/pyproject.toml, sdk/highlight-py/tests/test_fastapi.py
A customer brought up that our [FastAPI integration](https://app.intercom.com/a/inbox/gm6369ty/inbox/shared/all/conversation/41483?view=List) does not report
much detail on HTTP errors, with a stacktrace that is not useful since
it will be pointing to FastAPI internal code.
This change introduces additional attributes to the FastAPI integration.
Unit test
No
No
=> support additional fastapi attributes on http errors

backend/vercel/README.md
This PR adds [Tunnelmole](https://github.com/robbie-cahill/tunnelmole-client) as an open source local testing option.
Tunnelmole is a FOSS tunneling solution with a growing community. It works out of the box and can be optionally self hosted with the [Tunnelmole Service](https://github.com/robbie-cahill/tunnelmole-service). Both the client and service are open source.
Example:
```
➜  ~ tmole 8000
http://bvdo5f-ip-49-183-170-144.tunnelmole.net is forwarding to localhost:8000
https://bvdo5f-ip-49-183-170-144.tunnelmole.net is forwarding to localhost:8000
```
=> Add Tunnelmole as an open source local testing option

.changeset/empty-cherries-pay.md, frontend/src/__generated/rr/rr.js, frontend/src/components/Search/SearchForm/SearchForm.tsx, sdk/client/src/utils/privacy.ts
Default privacy mode is missing a few fields and inputs. More aggressively obfuscate these fields for default privacy mode:
- obfuscate all inputs
- allow inputs to be recorded with `data-hl-record` attribute
1) Set the privacy mode of the Highlight app to be "default"
2) Click around the app, touch inputs and fields
3) Close out session
4) View session
https://www.loom.com/share/2473e236e70b424c9779ff76a242edec?sid=0707d37e-8799-4740-946a-191dcb8dc0cf
N/A
N/A
=> Improve default privacy mode

backend/clickhouse/sessions.go, backend/clickhouse/sessions_test.go, backend/lambda-functions/deleteSessions/handlers/handlers.go, backend/private-graph/graph/schema.resolvers.go, frontend/src/components/QueryBuilder/QueryBuilder.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionQueryBuilder/SessionQueryBuilder.tsx
Adds a new `sample` session filter that allows picking a random subset of sessions
based on a randomly generated (or set) hex string.
The subset does not have a given count limit but sets the order of
sessions that are returned, so that a given page number identifies the sample.
v0 https://www.loom.com/share/289a58d71f664e329dd73509887df035
No
No
=> support selecting a random subset of sessions

frontend/src/components/TableList/TableList.tsx, frontend/src/pages/Player/MetadataPanel/MetadataPanel.tsx
Session metadata would be carried over when switching sessions because the keys of the rendered
react components would be shared across sessions, so react wouldn't know to rerender the DOM.
Before
After
No
No
=> fix session metadata persisting when switching sessions

frontend/src/pages/Traces/utils.ts
Fixes a bug where we could get in an infinite loop on a trace with a single span.
Reflame preview click test of [the page which rendered an error](https://preview.highlight.io/22330/traces/76145821-502e-4eff-b983-93b231912a99?end_date=2023-11-28T19%3A55%3A40.475Z&start_date=2023-11-27T19%3A55%3A40.475Z&%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201HGBVE03QH0DGXYZWJDRCXWF4%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22hotfix%2Fflame-graph-error%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D).
Should let customer know it's resolved if they noticed the issue.
N/A
=> Fix flame graph error

.changeset/tidy-plants-wink.md, e2e/nextjs/src/app/api/edge-test/route.ts, sdk/highlight-next/src/util/highlight-edge.ts, sdk/highlight-next/src/util/types.ts, sdk/highlight-next/src/util/with-highlight-edge.ts, sdk/highlight-next/src/util/with-highlight-nodejs-app-router.ts, sdk/highlight-node/src/client.ts, sdk/highlight-node/src/handlers.ts, sdk/highlight-node/src/sdk.ts
We've received a report in discord that our API router wrappers fail to
parse headers correctly because they expect an `IncomingHTTPHeaders` structure
while the `request.headers` there uses the `Headers` type.
Support both in the node / next SDKs.
[Vercel e2e deploy](https://nextjs-highlight-demo-p1480gm3t-highlight-run.vercel.app/) & click testing for error ingestion.
with fix in https://github.com/highlight/highlight/pull/7195/commits/5e3054854c2c067fac6b234ed23a87a3ea696da4
No
No
=> update header parsing types for node / next SDKs

frontend/src/components/DemoModal/DemoModal.tsx
Send attribution data coming from highlight.io as part of the 
analytics data sent with the highlight demo page user submission.
This will allow us to query clickhouse for demo signups' attribution data (such as gclick id)
Reflame preview
No
No
=> send attribution data from demo page signups

frontend/src/pages/Billing/BillingPageV2.tsx, frontend/src/pages/Billing/UpdatePlanPage.tsx
Fixes https://app.highlight.io/1/errors/0E5xN9i7FIIjAP4z9g7S111IGIc3
to avoid crashing the billing page when the price was not an even number of cents.
before
after, vising the same page on reflame preview
No
No
=> round billing cents to avoid dinero errors

.changeset/chilly-rats-leave.md, sdk/highlight-node/package.json, sdk/highlight-node/src/types.ts
As reported on [discord](https://discord.com/channels/1026884757667188757/1178754207600349215),
our @highlight-run/node sdk depends on highlight.run for types but can lead to node.js runtime
typescript errors when lib checking is on.
CI
Changeset
No
=> remove @highlight-run/node dependency on highlight.run for types

docs-content/sdk/nodejs.md, highlight.io/components/QuickstartContent/backend/js/shared-snippets.tsx
Documents the `serviceName` and `serviceVersion` options on `H.init()` in the Node SDK.
N/A - docs only.
N/A - text only.
=> Document serviceName and serviceVersion in Node SDK

.github/workflows/turbo.yml, backend/pricing/pricing.go
Fixes two issues
* Plans on non-3-month session retention would apply the session retention to traces / logs, failing to find a price
* Plans manually subscribed from the startup discount would have a different product ordering, failing to find the base product.
Locally testing with stripe test mode.
No
No
=> fix stripe pricing updates

backend/lambda/lambda.go, packages/react-email-templates/components/alerts.tsx, packages/react-email-templates/emails/index.tsx, packages/react-email-templates/emails/new-session-alert.tsx, packages/react-email-templates/emails/new-user-alert.tsx, packages/react-email-templates/emails/rage-click-alert.tsx, packages/react-email-templates/emails/track-event-properties-alert.tsx, packages/react-email-templates/package.json, packages/react-email-templates/src/index.ts
The previously created lambda was handling one email format, but will need to respond to multiple email template requests. Allow a parameter to be passed to determine which template should be used.
Also updates the session alerts to not show unavailable data (i.e. these alerts are sent out for live sessions)
Step function test on AWS
Breaking change to previous lambda function
N/A
=> Update insights lambda to handle multiple requested emails

.github/workflows/turbo.yml, package.json
Changes to ` react-email-templates` are not publishing via GitHub Actions. Add the publish to the script
Able to run the publish command from the top level directory - `yarn publish:react-email-templates`
Make sure deployments are not blocked
N/A
=> Publish react-email-templates via github actions

backend/private-graph/graph/schema.resolvers.go
Fix a stripe issue reported in [discord](https://discord.com/channels/1026884757667188757/1052834249868324895/1181681404346630154) 
`CreateOrUpdateStripeSubscription` returns correctly
No
No
=> fixup! more graduated billing fixes (#7265)

backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go, backend/redis/utils.go
- use the original context instead of `context.Background()` in the live mode loop to avoid auth error
- load all events from s3 the first time events are queried in live mode
- fix `cursor.EventIndex <= len(allEvents)` check - if no new events have been added, should return nothing
- fixes #7250 
- no
- no
=> live mode fixes

backend/public-graph/graph/resolver.go, backend/temp-alerts/temp-alerts.go, backend/worker/worker.go
Some null pointer errors due to lack of session in inputs
Test session email alerts following test plan in https://github.com/highlight/highlight/pull/7261
N/A
N/A
=> Fix alert inputs

backend/clickhouse/traces.go
We don't populate suggestions for `trace_id` and `span_id` in the `trace_keys` table because the results are so unique. However, this means these keys also don't show up in the typeahead for suggestions when creating filters on the traces search.
This PR manually adds `trace_id` and `span_id` to the suggestions for trace keys.
Local click test. Couldn't test in the PR preview because the backend changes aren't deployed.
Should verify functionality in prod.
N/A
=> Add trace_id and span_id as trace key suggestions

backend/private-graph/graph/schema.resolvers.go
* Fixes [panic](https://app.highlight.io/1/errors/azvH5U1kf7z0aZJ1cMiuQOrPsk4j/instances/228406210) related to loading the trace billing limit.
Local deploy with `MonthlyTracesLimit` set to not null
No
No
=> fix incorrect billing limit variable reference

frontend/src/__generated/index.css, frontend/src/components/Search/SearchForm/SearchForm.css.ts, frontend/src/components/Search/SearchForm/utils.test.ts, frontend/src/components/Search/SearchForm/utils.ts
There's a bug in our current query parsing logic with quotes that messes up formatting unless you have matching opening/closing quotes. There's also a bug with how whitespace is rendered. This PR still isn't perfect, but the behavior is better. Also note that we are iterating on this area of the product this week to improve query parsing further as we develop our own grammar for search queries and parsers for client and server to provide a structured representation of a query (see #7297, #7298, and #7309 for more details).
https://www.loom.com/share/1062c60e94a14460b44aca8f46ee8b86
https://www.loom.com/share/04fda202cd8d4dc3b5c2ca82d4c91d60
N/A
N/A
=> Fix query parsing with quotes and whitespace in tags

backend/clickhouse/logs.go, backend/clickhouse/logs_test.go, backend/clickhouse/query.go, backend/clickhouse/traces.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, go.work.sum, sdk/highlight-grafana-datasource/pkg/plugin/datasource.go, sdk/highlight-grafana-datasource/src/components/QueryEditor.tsx
- we're doing backend filtering now in the `traces_keys` resolver and limiting the number of results - add the filter query and type in Grafana
- adds to logs as well to keep them consistent, is backwards compatible without type filtering
- click tested in the grafana plugin
- no
- no
=> pass query and filter to backend for traces_keys

backend/worker/kafka_worker.go, backend/worker/worker.go, e2e/express-ts/src/index.ts, e2e/express/src/index.mjs, e2e/tests/src/test_sdk.py, scripts/migrations/init.sql
A bug in the batched queue flush logic is causing the last message to never get flushed.
- datasync batch worker receives the error object update
- datasync batch worker sets the last message timestamp and waits for more messages to flush
- on the next kafka receive(), there are no more messages so the call returns nil
- we return without ever calling flush()
The change ensures we keep trying to flush (to purge previously received messages) even if we stop receiving a message.
The change also sets a receive timeout in the batched worker to wait for no more than the flush timeout
for a new message, to avoid delaying flushes.
e2e test
No
No
=> ensure batched workers flush correctly if no new messages are arriving

backend/clickhouse/logs_test.go, backend/clickhouse/query.go
- moved type filter to the backend, not necessary to return the type as all records will match the passed-in type
- fixes a bug with the `trace_metrics` table which lacks a `type` column
- clicktested metrics suggestions, log keys, trace keys
- no
- no
=> remove unnecessary type query

backend/public-graph/graph/resolver.go
- sessions are being processed at roughly 4x the rate after switching to redis for the worker queue
- if the Redis logic is correct, this could be caused by the redis implementation returning faster than the SQL query
- try increasing the session processing delay to 2 mins to see how this reduces the number of sessions being processed
- will monitor in prod after deployment
- no
- no
=> increase session processing wait time to 2 min

sdk/highlight-go/trace/tracer.go, sdk/highlight-go/trace/tracer_test.go
@mayberryzane aptly discovered that our sdk wastes a lot of cpu marshalling the graphql args / vars for each request.
Switch to go format with `%+v` syntax to serialize much faster.
example vars output:
```
map[direction:DESC params:map[date_range:map[end_date:2023-12-15T00:28:37.564391000-00:00 start_date:2023-12-15T00:28:37.522161000-00:00] query:work happening] project_id:1]
```
Local deploy
```go
// old
func BenchmarkName(b *testing.B) {
data := map[string]interface{}{"direction": "DESC", "params": map[string]interface{}{"date_range": map[string]interface{}{"end_date": "2023-12-15T00:28:37.564391000-00:00", "start_date": "2023-12-15T00:28:37.522161000-00:00"}, "query": "work happening"}, "project_id": "1"}
for i := 0; i < b.N; i++ {
json.MarshalIndent(data, "", "")
}
}
// …
```
=> switch args serializer

.changeset/nervous-clocks-bathe.md, sdk/highlight-next/package.json, yarn.lock
I suspect this is the source of our recent bugs where users with fancy monorepos are having trouble importing `@highlight-run/next`.
=> docs(changeset): Make Next a peer dependency to @highlight-run/next

backend/main.go, backend/public-graph/graph/resolver.go, backend/public-graph/graph/sampling.go, backend/util/tracer.go, sdk/highlight-go/highlight.go, sdk/highlight-go/log/logrus.go, sdk/highlight-go/log/util.go, sdk/highlight-go/otel.go
Ensure we ingest all customer logs / metrics that come from the frontend data or other
logging ingest endpoints by sampling our own traces but ensuring the traces emitted to record
a log or a metric are sampled
still doing a bit more testing, but
frontend logs volume looks right
trace distribution coming thru
Will monitor prod logs ingest
No
=> segment trace sampling by span kind to ingest all customer logs / metrics

docs-content/sdk/nodejs.md
- these specific scripts are being passed to the `HighlightCodeBlock` as a react component rather than text, not sure why this is but it's rendered as `[object Object]`
- adding extra whitespace is a workaround 
- local docs build
- no
- no
=> add extra whitespace to fix node.js code highlighting

frontend/src/pages/LogsPage/LogsPage.tsx, frontend/src/pages/LogsPage/LogsTable/LogsTable.tsx, frontend/src/pages/Player/RightPlayerPanel/components/NetworkResourcePanel/NetworkResourceLogs.tsx, frontend/src/pages/Traces/TraceLogs.tsx, frontend/src/pages/Traces/TracesList.tsx, frontend/src/pages/Traces/TracesPage.tsx, frontend/src/pages/Traces/useGetTraces.ts
Update the traces table to have an infinite scroll
Note: I also removed the "backwards" infinite scroll on the logs page since this it is not really used in favor of the "Load more" option
1. View the traces page
2. Scroll down to the bottom of the table
https://www.loom.com/share/ff7c9ac5b00e4f468289f154df0efba7?sid=f4efff9d-c624-463d-9d5b-d9757b72b1d3
N/A
N/A
=> Infinite scrolling for traces

sdk/highlight-py/CHANGELOG.md, sdk/highlight-py/highlight_io/sdk.py, sdk/highlight-py/highlight_io/utils/lru_cache.py, sdk/highlight-py/pyproject.toml
Usage of `tuple[str, str]` in method definitions is only supported in Python 3.10+. Remove the usage
Used the following program to test
```
def main():
print("Starting program")
lru = LRUCache(4)
lru.put(1, ("1", "2"))
lru.put(2, ("3", "4")) 
lru.put(3, ("5", "6")) 
lru.put(4, ("7", "8")) 
lru.get(1, ("", ""))
lru.put(5, ("9", "10"))
lru.put(None, ("11", "12"))
print(lru.get(1, ("", "")))
print(lru.get(2, ("", "")))
print(lru.get(3, ("", "")))
print(lru.get(4, ("", "")))
print(lru.get(5, ("", "")))
print(lru.get(None, ("", "")))
print("Ending program")
if __name__ == "__main__":
main()
```
1. Run the original LRUCache class with python 3.8
2. Run the new LRUCache class with python 3.8
N/A
N/A
=> Fix python SDK for python versions 3.9 and lower

frontend/vite.config.ts
Vite doesn't support tailwind with lightningcss transformer yet, because tailwind depends on postcss: https://github.com/vitejs/vite/discussions/13835#discussioncomment-6534835
Reflame works around this by implementing its tailwindcss compat on top of unocss, but in the long term i recall the tailwind folks are moving towards a rust based compiler that also leverages lightningcss. Should probably wait until then to switch over.
The m-0 class now properly applies to the divider in this modal locally:
=> Revert to postcss transformer

backend/public-graph/graph/resolver.go
- in cases where a tab is minimized, there can be large delays between when payloads are sent, causing sessions to be reprocessed unnecessarily often due to the limited activity
- if it's been more than a minute since the last payload, wait longer before processing the session 
- will monitor metrics in prod after deployment
- no
- no
=> use variable delay for processing sessions

frontend/src/pages/NewProject/AutoJoinInput.module.css, frontend/src/pages/NewProject/AutoJoinInput.tsx, frontend/src/pages/NewProject/NewProjectPage.tsx, frontend/src/pages/WorkspaceSettings/WorkspaceSettings.tsx, frontend/src/pages/WorkspaceTeam/WorkspaceTeam.tsx, frontend/src/pages/WorkspaceTeam/components/AutoJoinForm.module.css, frontend/src/pages/WorkspaceTeam/components/AutoJoinForm.tsx
Update the workspace settings to allow users to input email domains they want to auto-approve for their workspace
1) Try to create a new workspace
2) Go to the workspace settings
https://www.loom.com/share/5948481d3e4241c4bbce61587d0e3a1a?sid=04b1be01-2da0-4601-be66-cd6bfc2f8817
N/A
Sure
=> Allow autojoin email input

.github/workflows/deploy.yml, backend/kafka-queue/kafkaqueue.go, deploy/public-worker-main-service.json
Some more tuning to our kafka configuration.
Switches back to sync writes since MSK is fine with that and we want to make sure data isn't dropped by a client.
Adds per-topic consumer groups to avoid rebalances slowing down other topic consumers.
Manually deploying.
Watching kafka metrics.
No
=> limit kafka data prefetching

backend/vercel/vercel.go
Getting a lot of log spam recently from vercel empty messages which incurs quite a bit of cloudwatch processing cost.
Rather than emitting the warning log, we should write a log message for vercel requests.
CI
No
No
=> fix vercel log spam

sdk/highlightinc-highlight-datasource/README.md, sdk/highlightinc-highlight-datasource/dashboards/highlight-test-dashboard.json, sdk/highlightinc-highlight-datasource/docker-compose.yaml, sdk/highlightinc-highlight-datasource/provisioning/dashboards/dashboard.yaml, sdk/highlightinc-highlight-datasource/src/components/QueryEditor.tsx
- provision example dashboard using all resource types
- fix README image link
- fix group by aggregate function using non-numeric columns
- no
- no
=> provision example dashboard

docker/frontend.Dockerfile, frontend/package.json, package.json, yarn.lock
* Docker image build was failing due to yarn v4 upgrade
* npm package publishing was broken due to yarn v4 upgrade.
[CI Passing](https://github.com/highlight/highlight/actions/runs/7304388436)
`yarn turbo:publish` works locally
```bash
[highlight.run]: Process started
[highlight.run]: ➤ YN0000: Registry already knows about version 8.3.1; skipping.
[highlight.run]: ➤ YN0000: Done with warnings in 0s 264ms
[highlight.run]: Process exited (exit code 0), completed in 0s 655ms
Done in 12s 761ms
➤ YN0000: Registry already knows about version 8.3.1; skipping.
➤ YN0000: Done with warnings in 0s 216ms
➤ YN0000: Registry already knows about version 1.0.3; skipping.
➤ YN0000: Done with warnings in 0s 680ms
```
No
No
=> fix docker image build

.reflame.config.jsonc
Removes some redundant options that have been made default, and migrates to our new package.json exports compat where possible so there's a single source of truth for import resolution.
Left comments on each change for more context.
Reflame preview & tests still work.
=> Use Reflame exports detection

sdk/highlight-py/e2e/highlight_fastapi/main.py, sdk/highlight-py/highlight_io/integrations/fastapi.py, sdk/highlight-py/pyproject.toml, sdk/highlight-py/tests/test_fastapi.py
Reading the request body in the SDK breaks application code that also reads the request body.
There isn't a way in fastapi to clone the request, so we should avoid reading one-shot attributes like the body.
Local deploy with curl post body on a request not blocked by the SDK.
New 0.6.10 version released. Closes #7403
No
=> remove request body reader in python sdk

backend/model/model.go
Once we upgrade PG Aurora to 15.5, switch to [HNSW indexes](https://supabase.com/blog/increase-performance-pgvector-hnsw) for better embeddings search accuracy and performance.
Creating new index locally.
Check that index creation will work first in prod for project 1.
Will need to create new / drop old indexes manually.
No
=> switch to hnsw embeddings index

backend/migrations/cmd/add-hnsw-indexes/main.go
- hnsw is a new vector index type introduced in pgvector v0.5.0 with better performance than ivfflat
- this migration adds hnsw indexes for all partitions of error_object_embeddings_partitioned
- ran script locally, currently running in prod
- new partitions are already using hnsw indexes
- will remove the existing ivfflat indexes after confirming these new indexes are created for all partitions and working as expected
- no
=> create hnsw indexes for all partitions of the error_object_embeddings_partitioned table

backend/pricing/pricing.go
CVC and address checks may fail even if the payment method is valid, esp. for international customers.
Avoid using those checks to avoid incorrect billing warning notifications.
CI
Will be monitoring [logs](https://app.highlight.io/1/logs?end_date=2024-01-03T17%3A39%3A44.744Z&query=stripe%20check%20failed%20%20&start_date=2024-01-03T17%3A24%3A44.744Z) for this.
No
=> remove incorrect payment method checks

frontend/src/pages/ErrorsV2/ErrorQueryBuilder/ErrorQueryBuilder.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionQueryBuilder/SessionQueryBuilder.tsx, frontend/src/util/db.ts
We've been seeing more indexeddb errors recently and it seems in some cases they prevent our app from loading.
The session preloading often causes browser crashes for larger projects, so we should try
and turn off indexeddb caching by default for now to see if it could help for now.
[Reflame preview](https://preview.highlight.io/1/errors?page=1&query=and%7C%7Cerror_state%2Cis%2COPEN%7C%7Cerror-field_timestamp%2Cbetween_date%2C2023-12-06T14%3A53%3A49.366Z_2024-01-05T14%3A53%3A49.366Z&%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201HKBQ4EAR5WYZAAGFWP305CWS%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22vadim%2Findexeddb-disable%5C%22%2C%5C%22githubOwnerName%5C%22% …
=> disable indexeddb by default

.changeset/pink-baboons-look.md, highlight.io/components/QuickstartContent/logging/js/pino.tsx, highlight.io/highlight.logger.ts, highlight.io/pages/api/docs/github.ts, highlight.io/pages/api/docs/search/[searchValue].ts, highlight.io/pages/docs/[[...doc]].tsx, sdk/pino/src/index.ts
When using the pino transport in next-js, the import would cause errors in the browser
because client code would try to use the transport.
Detect next runtimes and avoid importing the node-specific SDK.
Testing on highlight.io and in the e2e app.
https://www.loom.com/share/bdcc5faf75db45c8bbf0e8d12c3d9981
Changeset
No
=> ensure pino transport works correctly in non-node environments  @Vadman97

backend/kafka-queue/kafkaqueue.go
- these messages are pretty big and could be a cause for elevated cloudwatch ingest, removing them 
- will monitor cloudwatch ingest bytes for public graph after deploying
- no
- no
=> remove message from large kafka message logs

highlight.io/components/common/Navbar/ResourceDropdown.tsx
Replaced the community section in the resource dropdown with Customers, which links to /customers. I decided to remove community since it links to Discord, which is already linked elsewhere on the Navbar.
Click-testing
No
No
=> replaced Community with Customers

backend/clickhouse/query.go, backend/go.mod, backend/go.sum
- fixes bug where numeric keys would not show up as group by options (e.g. enum types), should handle those as both potential metric types and group by types
- applies `where` conditions before limiting the number of groups
- removes prewhere logic as clickhouse should handle this automatically, did not see any meaningful performance difference between the two
- validated that the correct data was shown in the grafana plugin after applying a filter and limit = 1 
- no
- no
=> fix more grafana bugs

backend/clickhouse/migrations/000070_add_session_metrics.down.sql, backend/clickhouse/migrations/000070_add_session_metrics.up.sql, backend/clickhouse/sessions.go, backend/private-graph/graph/schema.resolvers.go
- device memory and web vitals are the last two types of metrics being read from postgres
- add a clickhouse materialized view indexed on session secure id to look up these metrics efficiently from clickhouse
- tested locally to make sure migration created the table/mv and the resolver was behaving correctly
- table / mv already created in prod, will remove the code for saving to the metrics table once this is looking good
- no
=> use clickhouse for session metrics

sdk/highlight-py/CHANGELOG.md, sdk/highlight-py/README.md, sdk/highlight-py/e2e/highlight_fastapi/main.py, sdk/highlight-py/highlight_io/integrations/boto.py, sdk/highlight-py/highlight_io/integrations/boto3.py, sdk/highlight-py/highlight_io/integrations/boto3sqs.py, sdk/highlight-py/highlight_io/integrations/redis.py, sdk/highlight-py/highlight_io/sdk.py, sdk/highlight-py/poetry.lock, sdk/highlight-py/pyproject.toml, sdk/highlight-py/tests/test_boto.py, sdk/highlight-py/tests/test_boto3sqs.py, sdk/highlight-py/tests/test_redis.py
Add tracing auto-instrumentation support for python libraries:
- Redis
- Boto
- Boto3 (sqs only)
1) Add your AWS credentials as environment variables
2) Start the fastapi app (make sure Redis is running)
3) Hit the redis endpoint (`/redis`)
4) Hit the boto endpoint (`/boto`)
5) Hit the boto3 send endpoint (`/boto3sqs_send`)
6) Hit the boto3 receive endpoint (`/boto3sqs_receive`)
https://www.loom.com/share/f0d12fef893b43b39df54b0e6e723081?sid=5baa9042-5957-4151-9be4-b8b5e87f7e91
N/A
N/A
=> Add autoinstrumentation for redis and boto libraries

highlight.io/pages/docs/[[...doc]].tsx
Fix for "Suggest Edits" docs button not linking properly in prod. When merging the github docs link with the relative docs path, precautions were taken to prevent double slashes. The links would replace every '//' with '/'. However, this also applied to the '//' in 'https://', which broke the link.
Click-testing
No.
No.
=> Fixed "Suggested Edits" Docs link

.github/workflows/deploy.yml, backend/kafka-queue/kafkaqueue.go
Change the max message size to avoid broker preload overloading
when the main topic workers try to join and prefetch too much data.
before -> after of disk throughput
Monitoring kafka in production. Potential to have message too large errors, will look for those.
No
=> reduce kafka message size to help with broker load

.github/workflows/backend.yml, .vscode/settings.json, backend/clickhouse/clickhouse.go, backend/clickhouse/sessions.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, docker/.env, docker/compose.hobby.yml, docker/env.sh, frontend/src/graph/generated/schemas.tsx
Session reports feature would break for large projects because we would be feeding
a list of IDs from ClickHouse to postgres.
```jsx
Uncaught (in promise) Error: No sessions data: extended protocol limited to 65535 parameters
at report.ts:131:17
at async Promise.all (/762/index 0)
at async generateSessionsReportCSV (report.ts:119:39)
at async onClick (SessionFeedConfigurationV2.tsx:398:9)
```
Replace the query with a nested CH query that also hits postgres for some of the session data.
Local deploy producing the report.
No
No
=> ensure session report works for large number of sessions

backend/otel/otel.go, backend/public-graph/graph/resolver.go
- pointer reference in loop points to last project id
- declare `messages` in loop to prevent duplicate metrics
- will monitor logs in prod after deploying
- no
- no
=> fix potential bugs in otel.go, better logging in resolver.go

frontend/src/pages/Billing/utils/utils.ts
Ensures that backend changes to how billing limits are reported (breaking up the
plan included quota and the allowed overage quota) are correctly used on the frontend
to determine when a billing quota is exceeded.
Corrects issue in #7474 that would show plans with an allowed base quota as having the limit exceeded.
[Reflame preview for customer](https://preview.highlight.io/14909/errors?page=1&query=and%7C%7Cerror_state%2Cis%2COPEN%7C%7Cerror-field_timestamp%2Cbetween_date%2C2023-12-17T19%3A21%3A30.547Z_2024-01-16T19%3A21%3A30.547Z&%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201HM9VC4WB5VKB8K36VPH4G4KF%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22vadim%2Ffixu …
=> fixup! fix reporting of billing limits on frontend

frontend/src/pages/Player/PlayerHook/PlayerHook.tsx, frontend/src/pages/Player/PlayerHook/PlayerState.ts
Having too many events in one chunk (typically in live mode where the number
of events in the main chunk can be unbounded) can crash JS array operations.
Try to salvage the session by truncating the chunk correctly to a size that works.
https://www.loom.com/share/8446c85775a84784bea65442b3d27003
No
No
=> truncate large chunks

frontend/src/pages/Player/RightPlayerPanel/components/NetworkResourcePanel/NetworkResourcePanel.tsx, frontend/src/pages/Traces/TracePage.tsx, frontend/src/pages/Traces/TracesPage.tsx, packages/ui/src/components/icons/IconSolidTraces.tsx
Adds view tracking in the following areas:
* Traces page
* Individual traces
* Network request panel tabs
Also fixes an error I saw in the new traces icon.
Local click test + observing network request data.
N/A
N/A
=> Add view tracking for traces and network resources

backend/kafka-queue/kafkaqueue.go, docs-content/sdk/python.md, highlight.io/components/QuickstartContent/backend/python/other.tsx, highlight.io/components/QuickstartContent/traces/python/manual.tsx, sdk/highlight-py/highlight_io/sdk.py, sdk/highlight-py/pyproject.toml
Allow reporting a `span_name` attribute in the python SDK
to label traces when manually reported.
Local deploy, CI
New python SDK version
No
=> allow reporting span_name on H.trace

backend/public-graph/graph/resolver.go
Record project ID to figure out which inference is slow.
Keep 100% of spans for the inference match.
CI
No
No
=> improve tracing for embedding match

frontend/src/pages/Auth/SignInRedirect.tsx
Fixes a bug where users could get stuck in the loading state of the app permanently. The problem was that we were storing the initial URL the user was supposed to be redirected to which included a search string in the URL. We would try to redirect back to this from the `ProjectRedirectionRouter` which would give precedence to any URL stored in the auth redirect cookie vs falling back to the default project.
This PR ensures we don't store a redirect URL for the root path (`/`) even if there is a search string after it.
In the PR preview, I dropped a debugger in `SignInRedirect` to see if `authRedirect.set` was called. I confirmed that the new logic was avoiding storing the redirect URL and that I was able to get into the app after coming to it from the homepage.
N/A
N/A
=> Don't set auth redirect if on homepage

frontend/src/pages/Traces/TraceFlameGraph.tsx, frontend/src/pages/Traces/TraceFlameGraphNode.tsx
Fixes an issue where the tooltip on the flame graph would get squished when hovering on the right side of the graph (#7284) and improves the styles of the spans to better match the mocks.
N/A - all client-side changes.
No, but heads up @julian-highlight that I snuck in some of the color palette updates in this PR!
=> Improve flame graph tooltip positioning and styles

backend/parser/listener/listener.go
All custom attributes sent on traces are stored as strings and we're unable to use the numeric operators (`>`, `<=`, etc.) to query on them correctly. This PR uses `toFloat64OrNull` to coerce the value to an integer for the comparison on custom attributes, which makes the numeric operators behave as expected.
Local click test searching on numeric attributes (e.g. `process.pid`) and string attributes (e.g. `process.owner`).
N/A
N/A
=> Support numeric operators on custom attributes

.changeset/silent-ads-smash.md, .changeset/unlucky-spoons-move.md, backend/private-graph/graph/middleware.go, e2e/nextjs/next.config.mjs, e2e/nextjs/package.json, e2e/nextjs/pages/ssr.tsx, e2e/nextjs/src/app/another-page/page.tsx, e2e/nextjs/src/app/api/app-router-test/route.ts, e2e/nextjs/src/app/api/app-router-trace/route.ts, e2e/nextjs/src/app/app-router/redirect/page.tsx, e2e/nextjs/src/app/app-router/ssr/page.tsx, e2e/nextjs/src/app/page.tsx, e2e/nextjs/src/highlight.logger.ts, e2e/nextjs/src/instrumentation.ts, highlight.io/highlight.logger.ts, highlight.io/next.config.js, highlight.io/pages/api/docs/search/[searchValue].ts, highlight.io/pages/docs/[[...doc]].tsx, sdk/highlight-next/src/ssr.tsx, sdk/highlight-next/src/util/with-highlight-nodejs-app-router.ts, sdk/highlight-next/src/util/with-highlight-nodejs-page-router.ts, sdk/highlight-node/src/client.ts, yarn.lock
* Fix @highlight-run/next importing `next/error` in a way that breaks with next 14
* Add pino transport usage to e2e example
* Update pino example to log to highlight and stdout.
changeset
No
=> enhance pino transport

backend/clickhouse/query.go, backend/clickhouse/traces.go, backend/model/model.go, backend/parser/parser.go
- change `DefaultFilter` to be a string appended to the input query
- add filter to sampling table too
- add filtering back to metrics `limit by` clause
- clicktested traces search to check that `IsIngestedBy` results were excluded and there was no conflict with another `highlight.type` query
- clicktested in grafana plugin
- no
- no
=> append default filter to input query, add where clause back to metrics

frontend/src/__generated/index.css, frontend/src/__generated/ve/components/Header/styles.css.js, frontend/src/components/Header/Header.tsx, frontend/src/components/Header/styles.css.ts, frontend/src/pages/Setup/SetupRouter/SetupRouter.tsx, highlight.io/components/Home/FeatureCarousel/FeatureCarousel.tsx
Remove the `beta` tag from traces in the docs and product.
Temporarily fix the link to the traces docs while the new landing page is in progress.
1) Load the product
- Traces no longer in beta
2) View the setup doc
3) Load the Highlight landing page
N/A
N/A
=> Remove beta for traces

backend/public-graph/graph/resolver.go
Backend stacktraces were not being enhanced because the mapped stacktrace was `"null"`. Add a check to make sure we don't overwrite any stacktrace in this condition.
1) Integrate with Github (make sure not to connect to the prod app, reachout if you need to use my personal GitHub app)
2) Cause a backend error
https://www.loom.com/share/e9cc85b49734403988efd6b5e48d965b
N/A
N/A
=> Fix Github enhanced stacktraces for backend errors

backend/alerts/integrations/discord/messages.go, backend/go.mod, backend/go.sum, backend/jobs/log-alerts/log-alerts.go, backend/main.go
Discord recently changed the API to cause our go client to get an error when sending a button component with no emoji.
This must be because our client does not have an `omitEmpty` on the json serialization for the `emoji` key, but discord
must have made the value required when the key is present.
```json
{"message": "Invalid Form Body", "code": 50035, "errors": {"components": {"0": {"components": {"0": {"emoji": {"name": {"_errors": [{"code": "BUTTON_COMPONENT_INVALID_EMOJI", "message": "Invalid emoji"}]}}}}}}}}
```
Fixes the error by adding a highlight emoji to the button.
local testing
no
no
=> fix discord notifications by adding emoji buttons

.github/workflows/deploy.yml, backend/event-parse/parse.go, deploy/otel-collector.yaml, docker/otel-collector.hobby.yaml, docker/otel-collector.yaml
We've received reports of timeouts to the collector again recently.
Tuning the export timeout to see if public graph latency for large batches
may cause us to reject batches.
Forcing prod deploy.
No
No
=> update otel collector export settings

frontend/src/components/Search/SearchForm/SearchForm.tsx
- adds `EXISTS` / `NOT EXISTS` to suggested operators for logs/traces search
- no
- no
=> add exists operators to suggestions

frontend/src/pages/LogsPage/utils.ts
The logs table doesn't know what to do with matching attributes when using the `exists` keyword. Skip trying to match when using `exists` and `not exists` for now.
1) Complete a search on the logs table using `exists`
2) Complete a search on the logs table using `not exists`
N/A
N/A
=> Fix logs exists

frontend/src/pages/Traces/CustomColumns/renderers.tsx
Trace durations are being received as `ns` but being treated as `ms`
1) View traces
2) Add duration column
N/A
N/A
=> Fix duration renderer on traces

highlight.io/components/Home/CalendlyPopover.tsx, highlight.io/pages/pricing/index.tsx
Add calendly widget for enterprise pricing tier
clicktest
n/a
n/a
=> Add calendly widget for enterprise pricing tier

frontend/src/pages/Sessions/SessionsFeedV3/SessionsFeedV3.tsx
Typo - `selectedSegment` -> `selectedPreset` to start polling
1) Load the sessions page and clear the filters
2) Start a new session in another window, and complete some actions
3) View the sessions page on the original window
N/A
N/A
=> Fix sessions polling

frontend/src/__generated/index.css, frontend/src/__generated/ve/pages/Traces/CustomColumns/Popover/styles.css.js, frontend/src/pages/Traces/CustomColumns/Popover/index.tsx, frontend/src/pages/Traces/CustomColumns/Popover/styles.css.ts, packages/ui/src/components/ComboboxSelect/ComboboxSelect.tsx
The traces popover changes width based on the longest attribute name.
- fix the width to 300px
- hide any text that is more than the 300px width
- add a popover to show the full text
N/A
Sure
=> Fix the width of the traces column popover

frontend/src/index.tsx, frontend/src/pages/Player/PlayerHook/PlayerState.ts
Per [customer thread](https://highlightcorp.slack.com/archives/C05DXNT5L8L/p1706318071001079), discovered that the rrweb `node not found` when a session is missing some data
(due to a broken data upload or rejected large message, which may not break the session) can cause the
browser to crash because of the number of logs emitted, even if the session is playable.
Throttle rrweb logging to fix the issue.
[reflame preview](https://app.highlight.io/1419/sessions/yv7NCvVGKLpyKCuZO7GoFWZLEkeZ?page=1&query=and%7C%7Ccustom_processed%2Cis%2Ctrue&%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201HNBWQVKYD3WY6SAW28NPC2EJ%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22vadim% …
=> throttle rrweb logging

backend/private-graph/graph/schema.resolvers.go
Incorrect query resulted in over-counted sessions.
correct number of sessions shown
no
no
=> correct sessions report session overcounting

frontend/src/__generated/index.css, frontend/src/__generated/ve/pages/Player/RightPlayerPanel/style.css.js, frontend/src/pages/Player/RightPlayerPanel/RightPlayerPanel.tsx, frontend/src/pages/Player/RightPlayerPanel/style.css.ts
Fixes an issue with the right panel height being taller than it should and cutting off some of the UI.
https://www.loom.com/share/bc62b4d1bcd94ca39501678896646df8
Local + PR preview click testing.
N/A
N/A
=> Fix player right panel height

backend/clickhouse/query.go, frontend/src/pages/ProjectSettings/ProjectFilters/ProjectFilters.tsx
- fixes graphs shown on ingest filters page
- fixes "count" query if a metric is provided by ignoring that metric
- clicktested ingest page + grafana
- no
- no
=> fix ingest graphs, ignore column if count metric is used

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/Player/RightPlayerPanel/components/NetworkResourcePanel/NetworkResourcePanel.tsx, frontend/src/pages/Traces/TraceProvider.tsx
Our ShowHN links a [session](https://app.highlight.io/1383/sessions/COu90Th4Qc3PVYTXbx9Xee7xbQqN?network-resource-id=25&page=1&query=and%7C%7Ccustom_processed%2Cis%2Ctrue&ts=5.243) that has a flame graph,
but the flame graph does not load despite the session being public.
Update the Trace resolver to consider whether the session is public when loading data.
Local deploy
No
No
=> allow loading traces for publicly-shared sessions

backend/clickhouse/errors.go, backend/clickhouse/errors_test.go, backend/clickhouse/logs.go, backend/clickhouse/logs_test.go, backend/clickhouse/query.go, backend/clickhouse/sessions.go, backend/clickhouse/sessions_test.go, backend/clickhouse/traces.go, backend/clickhouse/traces_test.go, backend/kafka-queue/kafkaqueue.go, backend/parser/listener/listener.go, backend/parser/parser.go, backend/parser/parser_test.go, backend/public-graph/graph/resolver.go, backend/public-graph/graph/sampling.go, backend/stacktraces/enhancer.go, frontend/src/pages/ProjectSettings/ProjectFilters/ProjectFilters.tsx
Our ingest filters would not work with the new traces / logs syntax
as they were built for parsing the older syntax used for sessions and errors. 
Switches the ingestion filters to use the new syntax.
Closes #7269
Unit testing / local deploy
https://www.loom.com/share/0fc5aad6a04842f6b3b562a804b2381b
We may need to convert old exclusion queries to the new syntax, but there are only a handful configured right now so I'll do it manually once this is deployed.
No
=> switch ingest parsing to antlr

frontend/src/pages/Traces/utils.ts
Falls back to a span in a trace even if there is no root span. This makes it possible to render a trace even if the root span isn't available, which we've noticed happening because of issues with our sampling logic.
Local + PR preview click test. I viewed [a problematic trace](https://app.highlight.io/1/traces/84964c51a1df8e9ae344b60dbd5ddeeb/c78b971eb0bcb4ac) in prod and in the PR preview to ensure it was working as expected.
N/A
N/A
=> Show trace even if no root span

backend/private-graph/graph/schema.resolvers.go
Fixes panic mentioned in HIG-4284 when loading a trace that is not yet in `traces_by_id`.
CI
No
No
=> fix trace panic when span does not exist in traces_by_id

frontend/src/pages/Alerts/SessionAlert/SessionAlertPage.tsx
fixes #7128
@SpennyNDaJets, thought I'd try my hands on this.
Update the SessionAlertPage to not update the session form when alertType changes
https://drive.google.com/file/d/1frNqhyQCxQHo5neDWvLjVS3ALBav9UlW/view?usp=sharing
Since we were no longer resetting the form we needed to omit previously "filled" form data that 
is not relevant to the session type being created. I omitted fields based on the alert configuration.
Alert threshold and threshold window fields are however not omitted. 
- Visit the new/edit session page and fill in some form like "excluded environments" or any of the channels to notify
- Change the alert type
- Observe that data in the channels to notify/excluded envs or any other field that is displayed for the form remains
NO
NO
=> SessionAlertPage update

frontend/src/pages/LogsPage/utils.ts, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/DevToolsWindowV2.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/LogSourceFilter/LogSourceFilter.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/utils.ts
Player dev tools level and source filters would apply an `AND` filter on multiple options which would never show results.
Removing `all` setting for sources as well as I've heard from customers that this causes confusion (and isn't really useful for the 2 sources we have).
https://www.loom.com/share/88557d411054490fa5c3b2f41b918ee0
no
no
=> fix session player dev tools level and source filters

frontend/src/__generated/index.css, frontend/src/pages/ErrorsV2/ErrorBody/ErrorBody.tsx, frontend/src/pages/ErrorsV2/ErrorInstance/ErrorInstance.tsx, frontend/src/pages/ErrorsV2/ErrorSourcePreview/ErrorSourcePreview.tsx, frontend/src/pages/ErrorsV2/ErrorStackTrace/ErrorStackTrace.css.ts, frontend/src/pages/ErrorsV2/ErrorStackTrace/ErrorStackTrace.tsx
Theres a few places where we could make the layouts be more compact. 
Examples:
- Distance in between 'Instance Title' & 'Instance Body' is much bigger than in the designs
- Distance in between error group data (the squares on top) & their respective title is bigger than in the designs
- Our Stacktrace is using weird paddings both on the headers as well as on the trace content. Make sure that all headers have the same height, while the trace content should be as compact as seen in the designs
1) Load the error page and select an error
2) Open a stacktrace
N/A
Sure
=> Update error instance padding

frontend/src/__generated/antd.css, frontend/src/index.css, frontend/src/style/AntDesign/antd.overrides.less
Antd 4 would apply a global anchor tag color transition via the generated antd less css.
Turns off that transition and other antd css transitions.
Local deploy
[Reflame preview](https://app.highlight.io/1/errors?page=1&query=and%7C%7Cerror_state%2Cis%2COPEN&%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201HNY1S0S7W5R4NB3K7ZNTTF2C%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22hig-4267-get-rid-of-color-transition-on-nav-items%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D).
https://www.loom.com/share/c30df263b0d346928c402b6c00580b7a
No
Yes
=> turn off antd transitions

frontend/src/__generated/ve/pages/Traces/TracePanel.css.js, frontend/src/pages/Traces/TracePage.tsx, frontend/src/pages/Traces/TracePanel.css.ts
Makes the header of the trace details panel stick to the top rather than scroll with the main content.
**Before**
**After**
N/A
No - this change was requested by the @julian-highlight himself!
=> Make header of trace panel fixed to top

frontend/src/components/Header/Header.tsx, frontend/src/routers/ProjectRouter/WorkspaceRouter.tsx
Fixes a bug where we would redirect a user to a project from a different workspace after switching workspaces. The new logic ensures we wipe the project ID we store in local storage if it doesn't not exist in the current workspace. It also enhances the back button by showing the project name references in local storage even if you are on a workspace settings page.
https://www.loom.com/share/d91b88e3c9a943a39e0221513d930460
N/A
N/A
=> Don't redirect to projects outside workspace

frontend/src/pages/Player/RightPlayerPanel/components/NetworkResourcePanel/NetworkResourceInfo.tsx
Update Session Network Request View/Panel to show Array json payload together instead of splitting it down to
various objects. Did same for request and response payload
Check the network request payload (that is an array) under a session.
Observe that the formatting is as intended in the issue description.
For example that array payloads are shown as one ('json payload') instead of being broken down 
into separate objects and labeled by their index in the array.
No
No
fixes #6267
/claim #6267
=> fix: network response payload display bugs

backend/main.go, backend/util/tracer-graphql.go
We used to have request logging from the backend to help demo logs association
with frontend sessions. This got accidentally removed in #7203. Noticed this when working on 
#7655 where I was not able to find backend logs associated to a frontend session.
Local deploy.
No
No
=> readd private graph request logging

frontend/src/pages/ErrorsV2/ErrorInstance/ErrorInstance.tsx, frontend/src/pages/ErrorsV2/ErrorInstance/RelatedTrace.tsx
Allow users to see the related trace from the error details
1) View an error
https://www.loom.com/share/cea8e54253d54edab83e9c8e3bedc6ef?sid=252e4aa7-ee7d-4519-a63d-5bbc0454b66b
N/A
N/A
=> Errors: add link to related trace

backend/clickhouse/traces.go, backend/otel/otel.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/LogsPage/LogsTable/LogDetails.tsx, frontend/src/pages/LogsPage/LogsTable/LogsTable.tsx, frontend/src/pages/LogsPage/useGetLogs.ts, frontend/src/pages/Traces/CustomColumns/columns.ts, frontend/src/pages/Traces/utils.ts
Allow users to see the related trace from the logs
1) View a log
2) Expand the row
3) Click on related trace link
https://www.loom.com/share/d6c0739dbf684aec8d6949eca7a3c291?sid=67b9efd5-c305-4a22-b158-101ed649b486
N/A
N/A
=> Logs: add link to related trace

frontend/src/components/CustomColumnPopover/index.tsx, packages/ui/src/__generated/ve/components/ComboboxSelect/styles.css.js, packages/ui/src/components/ComboboxSelect/ComboboxSelect.tsx, packages/ui/src/components/ComboboxSelect/styles.css.ts
Make the following updates to the custom column popover:
- add loading state
- add empty state
- remove tooltip and rely on title
1) Load the traces or logs page
2) Open the custom column selector on the far right of the table
3) Hover over a key
3) Type in a query
4) Type in a key that does not exist
General
N/A
Sure
=> Custom columns: popover updates

backend/clickhouse/log_row.go, sdk/highlight-py/tests/test_loguru.py
Python logging would report a log level string of `warning` which out backend was not mapping correctly
to the `WARN` log level. Correct the issue and add a python unit test for loguru to validate the SDK-side.
before
after
no
no
=> fix python warning log level handling

frontend/src/components/Search/SearchForm/SearchForm.tsx, frontend/src/pages/LogsPage/LogsTable/LogDetails.tsx
Fixes an issue where the query string was being prefixed with an extra space character when applying a filter from a log attribute. This caused a bit of jank in the UI.
I also looked at fixing the jank in the UI, which is reproducible by entering a query with a leading space character. This happens because we are using `word-spacing` to control the space between the filters since the default width of the space character in the font we are using is very narrow. However, `word-spacing` only applies between words and doesn't update the width of a leading space character. I filed https://linear.app/highlight/issue/HIG-4307/cursor-position-off-on-query-filters-when-there-is-a-prefix to follow up on this in the future, but I also added some logic to trim the leading space when we update the …
=> Trim extra space on query string when applying log filter

frontend/src/pages/LogsPage/LogsCount/LogsCount.tsx, frontend/src/pages/Traces/TracesPage.tsx
The histogram dates are using incorrect formatting:
- `MM` -> `mm`
- `SS` -> `ss`
- `H` -> `h`
More info [here](https://momentjscom.readthedocs.io/en/latest/moment/04-displaying/01-format/)
1) View the logs page
2) Manually set the date for logs
3) View the traces page
4) Manually set the date for traces
N/A
N/A
=> Fix histogram dates

frontend/src/components/Search/SearchForm/SearchForm.tsx
Adds an empty state for search filter values when there aren't any matches.
**Before**
**After**
Tested entering a search filter query that had no results in prod and on the PR preview to confirm things looked good and behaved as expected.
N/A
N/A
=> Empty state for search filter values

frontend/src/util/preload.ts
frontend network resource loading seems stable even with larger payloads.
since we don't preload session data and don't use indexeddb, increase this limit.
testing on a large customer [session](https://app.highlight.io/5403/sessions/614lzC3JdfJTJ3lu0GJs5rMvSKvI?page=1&query=and%7C%7Ccustom_processed%2Cis%2Ctrue&%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201HPFD0RQAG1P3BC7W9PEA78SN%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22vadim%2Fnetwork-resource-limit%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D) that has a large network payload
no
no
=> increase max network payload that can be previewed

frontend/src/components/Search/SearchForm/SearchForm.tsx
Using the `EXISTS` keyword causes an type error.,
1) Visit the logs or traces page
2) Type in that a key exists
N/A
N/A
=> EXISTS type error

backend/clickhouse/migrations/000084_rewrite_trace_attributes_mv.down.sql, backend/clickhouse/migrations/000084_rewrite_trace_attributes_mv.up.sql, backend/clickhouse/migrations/000085_rewrite_trace_state_mv.down.sql, backend/clickhouse/migrations/000085_rewrite_trace_state_mv.up.sql, backend/clickhouse/migrations/000086_rewrite_trace_span_name.down.sql, backend/clickhouse/migrations/000086_rewrite_trace_span_name.up.sql, backend/clickhouse/migrations/000087_rewrite_trace_span_kind.down.sql, backend/clickhouse/migrations/000087_rewrite_trace_span_kind.up.sql, backend/clickhouse/migrations/000088_rewrite_trace_service_name.down.sql, backend/clickhouse/migrations/000088_rewrite_trace_service_name.up.sql, backend/clickhouse/migrations/000089_rewrite_trace_service_version.down.sql, backend/clickhouse/migrations/000089_rewrite_trace_service_version.up.sql, backend/clickhouse/migrations/000090_rewrite_trace_environment.down.sql, backend/clickhouse/migrations/000090_rewrite_trace_environment.up.sql, backend/clickhouse/migrations/000091_rewrite_trace_has_errors.down.sql, backend/clickhouse/migrations/000091_rewrite_trace_has_errors.up.sql
- we don't use `trace_attributes` for anything and it uses a large number of parts, contributing to performance issues for trace ingest
- write key/value counts directly to `trace_key_values` (about 1000x fewer data)
- ran migration locally, ensured no new rows in `trace_attributes`, new rows for static and custom keys in `trace_key_values`
- no
- no
=> skip trace_attributes table, write directly to trace_key_values

backend/otel/extract.go, backend/otel/extract_test.go, backend/otel/otel.go
- this revives a PR from a few months ago that was applying this to logs
- changed limit to 2 hour to account for any potential daylight savings time weirdness
- expecting this to help clickhouse merge performance as effort won't have to be spent merging large parts in old partitions as new data won't be ingested for those partitions anymore
- unit test, clicktested locally to make sure new logs + traces were ingested
- no
=> enforce +/- 2 hour difference for ingested logs and traces

backend/clickhouse/traces.go, backend/public-graph/graph/resolver.go, sdk/highlight-go/otel.go
highlight-metric spans should be handled differently for time-series visualization.
since there isn't a reason to show them in the trace viewer, filter them out from the normal trace results
no highlight-metric spans shown
no
no
=> filter out metric spans

.reflame.config.jsonc, frontend/src/pages/Auth/SignIn.tsx, packages/ui/src/components/DatePicker/DateRangePicker/helpers.ts
I just shipped an update that makes the storybookCompatibility configurable per app/library instead of globally. This PR updates the config to make sure all existing stories are still covered.
Also fixes an `import x from '.'` that breaks dev mode deploys from the VSCode extension. I'm planning to add some lightweight url rewriting to support this to avoid having to do this in the future.
Reflame previews.
Component tests in frontend/src were [detected as new tests](https://github.com/highlight/highlight/pull/7748/checks?check_run_id=21552648479) because of some internal refactors I made to prep for supporting multiple apps deployed from the same repo. Should only happen this one time 🙏
=> Small updates for Reflame

backend/otel/otel.go
- fixes a bug with the quota lookup - use logRow.ProjectId instead of the map key (the obfuscated project id)
- clicktested locally with different quota settings to trigger filtering
- no
- no
=> use numeric project_id instead of obfuscated id

.changeset/afraid-ways-act.md, frontend/src/__generated/rr/rr.js, frontend/src/index.tsx, frontend/src/pages/Buttons/Buttons.tsx
innerHTML changes would not be obfuscated properly in default obfuscation mode.
https://github.com/highlight/rrweb/pull/116
fixes HIG-3970
before
after
new changeset
no
=> fix text obfuscation logic

backend/kafka-queue/kafkaqueue.go, backend/kafka-queue/types.go, backend/otel/otel.go, backend/otel/otel_test.go, backend/public-graph/graph/resolver.go, backend/worker/kafka_worker.go
- preparing to use Kafka Connect for writing traces to Clickhouse
- create a flattened traces format in Kafka, allow the current worker to read both the old and new formats
- copy trace filtering logic from `flushTraces` to `otel.go`
- clicktested locally to make sure traces were still ingested properly
- no
=> flattened format for traces, add filtering logic to otel.go

backend/public-graph/graph/resolver.go
Remove manual error filter patterns to be replaced with system configuration `ErrorFilters` entries
as part of the sampling logic determining ingest.
Ensure frontend error ingestion also goes through the same ingest sampling logic as backend errors.
Local deploy ingesting errors when no filter is applied, and not ingesting when filters are applied
converting static filters to project / global ones in the db as needed
no
=> clean up error filtering logic

docs-content/getting-started/fullstack-frameworks/next-js/1_overview.md, docs-content/getting-started/fullstack-frameworks/next-js/2_page-router.md, docs-content/getting-started/fullstack-frameworks/next-js/3_app-router.md, docs-content/getting-started/fullstack-frameworks/next-js/6_edge-runtime.md
I'm curious how everyone feels about this layout.
Originally we had a separate page for API wrappers, but now that those pages are all rolled into one, I've embedded the API Endpoints video in the Page Router, App Router, and Edge Runtime pages.
=> Next.js tutorial embeds

backend/otel/extract.go, backend/otel/otel.go, backend/public-graph/graph/resolver.go
- after some more investigation, noticed there was still data for past and future timestamps coming in, seemed to all be from highlight-metric traces
- apply the same `ClampTime` logic in `PushMetricsImpl`
- clicktested locally to make sure traces / metrics were still ingested normally
- no
- no
=> also clamp dates for metrics values to avoid too many old / future parts

backend/main.go
Recent change to run metric monitor / alert monitor in self-hosted deploy (all workers mode)
would prevent refreshing materialized views from running, which would avoid reporting usage metrics.
CI build of docker image + VM hobby deploy.
new docker image release
no
=> report usage as part of phonehome metrics

backend/event-parse/parse.go, backend/event-parse/parse_test.go, backend/event-parse/sample-events/output.json
When inlining stylesheets, we try to update relative assets to point to the absolute host to make sure
they resolve correctly at replay time (rather than remaining relative but to the wrong host, app.highlight.io).
The regex pattern for matching relative assets was incorrect (would not match valid relative assets such as
`url(hello.woff2)`. 
Note: we update the url to our CORS worker rather than to the absolute url since the assets will be served to app.highlight.io cross origin.
unit test
see updated output.json for correct payload
monitoring affected customer
no
=> fix incorrect logic for adding absolute url to relative stylesheet

backend/clickhouse/logs_test.go, backend/public-graph/graph/resolver.go, sdk/highlight-go/log/util.go, sdk/highlight-go/otel.go
* Traces from the frontend would pass the wrong environment value rather than using the one on the session.
* Logs from the frontend would not pass session metadata to the log.
before
after
before
after
no
no
=> propagate session environment to network request traces

.github/workflows/deploy.yml, deploy/collector-task.json, deploy/log-alerts-task.json, deploy/metric-monitor-task.json, deploy/private-graph-task.json, deploy/public-graph-task.json, deploy/public-worker-batched-service.json, deploy/public-worker-datasync-service.json, deploy/public-worker-main-service.json, deploy/public-worker-traces-service.json, deploy/worker-task.json
* GOMEMLIMIT allows triggering GC at a given memory usage to help with avoiding OOMs.
* Configurable via a GiB suffix to each service tasks' size.
Deploying to prod and monitoring memory usage having scaled clickhouse batch sizes.
no
no
=> add GOMEMLIMIT values to all containers

frontend/src/pages/IntegrationsPage/Integrations.tsx
- already validated that MS Teams integration works correctly with our manually uploaded app in Prod
- submitted MS Teams plugin for approval, need to remove this so they are able to test
- ensured teams was visible on integrations page
- no
- no
=> remove highlight admin guard for Teams integration

.changeset/mighty-ads-pump.md, docs-content/sdk/nextjs.md, sdk/highlight-next/src/util/highlight-webpack-plugin.ts, sdk/highlight-next/src/util/with-highlight-config.ts, sourcemap-uploader/src/index.ts, sourcemap-uploader/src/lib.ts
Self-hosted deploys may need to upload highlight sourcemaps to their local highlight.
Support that via a backend url option.
Local invocation of sourcemap uploader
changeset
no
=> support backend url for sourcemap uploader

docs-content/getting-started/fullstack-frameworks/next-js/3_app-router.md, e2e/nextjs/src/app/app-router/ssr/page.tsx
It turns out that RSCs have worked for a long while. They get filtered through `app/error.tsx` and caught by `appRouterSsrErrorHandler` from `@highlight-run/next/ssr`.
=> React Server Components testbed + docs comments [HIG-4346]

frontend/src/__generated/index.css, frontend/src/components/TagGroup/index.tsx, frontend/src/components/TagGroup/style.css.ts, frontend/src/pages/Traces/RelatedResourceButtons/index.tsx, frontend/src/pages/Traces/TracePage.tsx
We determine if a trace has an error on the client, but these errors could have gotten dropped down the process due to filters, quotas, etc. We don't currently have a way to update the trace, but we want to give the user a little more information due to the mismatch in info. In the meantime, give the user a tooltip with more info if the trace has errors but none were found.
More relevant for Highlight project than customers
Long term fix: https://linear.app/highlight/issue/HIG-4300/some-traces-have-has-errors=true-but-no-linked-errors-when-clicking-in
1) View traces
2) Click on a trace with no errors
3) Click on a trace that `has_errors-true` but no attached errors
4) Click on a trace that has_errors=true` and an attached error
https://www.loom.com/share/4e0c1e5d76d84540b64148c31f9ed689?si …
=> Show tooltip when unexpectedly no errors

sdk/highlightinc-highlight-datasource/README.md, sdk/highlightinc-highlight-datasource/dashboards/highlight-test-dashboard.json, sdk/highlightinc-highlight-datasource/src/plugin.json
- update provisioned dashboard based on updates to our query syntax and new features
- update plugin description, readme, and add links to docs page
- tested provisioned dashboard locally
- no, will build, sign, and update plugin submission after approval
- no
=> update plugin description and provisioned dashboard

.changeset/chatty-colts-argue.md, e2e/express/src/index.mjs, e2e/tests/src/test_sdk.py, sdk/highlight-node/src/client.ts, sdk/highlight-node/src/hooks.ts, sdk/highlight-node/src/types.ts
* Adds the `serializeConsoleAttributes` option to the node sdk `H.init` to allow serializing attributes into the message body.
changeset
no
=> keep console object serialized as json for body with sdk

frontend/src/components/Search/SearchForm/SearchForm.tsx, frontend/src/components/Search/utils.ts
There is some jumpiness in when selecting consecutive keys in search. Fix some of the logic to avoid jumping back in the search query
https://www.loom.com/share/243c2e5a7f7c4ffcbc12613d92e5a5a6?sid=7566fcb0-283d-419a-baca-1325336087ba
1. Select a key (preferable a long one for the second part, e.g. `environment`)
2. Select an operator
3) Select a value
4) Press space and select another key (shorter than current key + value length, e.g. `level`)
N/A
N/A
=> Fix cursor jumping in search

backend/clickhouse/query.go, backend/parser/listener/listener.go, frontend/src/components/Search/SearchForm/SearchForm.tsx
Support matching regex in the logs and traces search, and add a shortcut operator.
https://www.loom.com/share/acd783b81a1d4df6825a8bb4f31f56e8?sid=75469963-6482-42bc-becd-710f19e87ea8
1) Navigate to the logs/traces page
2) Select a string key to search by
4) Click on the "Contains" operator
5) Search for part of a string
6) Repeat for "does not match"
N/A
N/A
=> Support matching regex in searches

frontend/src/__generated/index.css, frontend/src/pages/LogsPage/LogsTable/CustomColumns/renderers.tsx, frontend/src/pages/LogsPage/LogsTable/LogDetails.tsx, frontend/src/pages/LogsPage/LogsTable/LogsTable.css.ts, frontend/src/pages/LogsPage/LogsTable/LogsTable.tsx, frontend/src/pages/Traces/CustomColumns/renderers.tsx, packages/ui/src/components/Table/Cell/Cell.tsx, packages/ui/src/components/Table/Cell/styles.css.ts
Show the matched attributes in a single line underneath each row to use the space more efficiently.
https://www.loom.com/share/922a8d28067f4f1ab774dd67db5000aa?sid=e8b38230-9420-4b5a-a211-816d3a866b79
1. View the logs table
2. Search by an attribute
3. Add another search attribute
4. Add another attribute
N/A
Yes - https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=15015%3A163252&mode=dev
=> Display inline search result attributes

backend/integrations/github/github.go, backend/integrations/gitlab/gitlab.go, backend/integrations/height/height.go, backend/integrations/jira/jira.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, backend/store/stacktraces_test.go, frontend/src/components/Comment/AttachmentList/AttachmentList.tsx, frontend/src/components/NewIssueModal/NewIssueModal.tsx, frontend/src/components/RadioGroup/RadioGroup.tsx, frontend/src/components/SearchIssues/SearchIssues.module.css, frontend/src/components/SearchIssues/SearchIssues.tsx, frontend/src/components/Select/SearchSelect/SearchSelect.tsx, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/mutation.gql, frontend/src/graph/operators/query.gql, frontend/src/pages/IntegrationsPage/Integrations.tsx, frontend/src/pages/Player/Toolbar/NewCommentForm/NewCommentForm.tsx
Fixes  #4460
/claim #4460
Introduce 'Link Issue' mode when creating issue for an error or session comment. 
All issue integrations are supported except **ClickUp**. According to [this](https://clickup.canny.io/public-api/p/using-api-get-tasks-to-search-by-title) and api documentation, they do not support searching issues via their rest api.
**On UI** this just means another radio button to determine whether the user prefers to create a new issue
or link an existing one. A search-select is provided for the user to search and choose an existing issue from their
selected issue integration.
https://github.com/highlight/highlight/assets/119384208/b0116ef5-6b9d-4d97-aff0-5839986bcde5
We needed a way to create attachment for existing issue and to search issues based on integration and a
search …
=> Support for searching issues when creating them - Search and link existing issues with error or session comments.

.changeset/eight-dingos-hammer.md, backend/public-graph/graph/resolver.go, frontend/src/hooks/useFeatureFlag/useFeatureFlag.ts, frontend/src/index.tsx, sdk/client/src/listeners/network-listener/utils/utils.ts
Avoid capturing traces / network request payloads for highlight.io traffic.
reflame preview
before
after
closes HIG-4364
changeset
no
=> filter network request recording for highlight.io traffic

docker/compose.hobby.yml
Fixes error thrown during running `run-hobby.sh`
```
Highlight infrastructure started
+ docker compose -f compose.hobby.yml pull
/highlight/docker/compose.hobby.yml: services.backend.environment array items[31,32] must be unique
```
Running `run-hobby.sh` locally again
no
no
=> fix docker compose hobby envs duplicates

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/Home/HomePageV2.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionsFeedV3.tsx, frontend/src/util/integrated.tsx
While pairing w/ @Vadman97 we noticed that the logic for `IsIntegrated` was only checking if we had any sessions for a project to determine if they are integrated at all. This logic is incorrect, and we determined we wanted to check if we had _any_ setup events for the project to say whether they have integrated.
Once I started looking at this I realized it doesn't seems like we need the `IsIntegrated` method at all anymore since we are using more specific checks to determine whether a project has integrated sessions/errors/logs. I ended up doing a brief audit of the usage of `IsIntegrated` and determined it would be more appropriate to use `useClientIntegration` instead and remove it entirely. I also cleaned up the logic for `IsBackendIntegrated` since we are using the …
=> Update IsIntegrated logic to pull from setup_events table

.github/workflows/docker.yml, frontend/src/pages/Billing/utils/utils.ts, frontend/src/pages/LogsPage/OverageCard/OverageCard.tsx, frontend/src/pages/Sessions/SessionsFeedV3/OverageCard/OverageCard.tsx
quota exceeded cards would not be shown because of an error in the frontend meter exceeded logic
before
after
fixes HIG-4388
no
no
=> show quota exceeded cards correctly

highlight.io/components/QuickstartContent/logging/docker.tsx, highlight.io/components/QuickstartContent/logging/fluentd.tsx
Set up new TLS listener for fluentforward on port 24284
Local docker deploy sending to new port
no
no
=> document fluentforward tls configuration

frontend/src/pages/LogsPage/useGetLogs.ts, frontend/src/pages/Traces/useGetTraces.ts
use the time of the last row to load more traces and logs
[reflame](https://app.highlight.io/1/logs?%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201HQVRESJXRFPFNN5CSRS8JWY4%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22vadim%2Ffetch-more%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D)
no
no
=> load more logs and traces from time of last row

docs-content/general/7_integrations/grafana-integration/2_setup.md
- our grafana plugin is published in the catalog - link out to Grafana's instructions for plugin setup.
- viewed doc page in preview
- no
- no
=> update grafana docs to reference plugin setup instructions

frontend/src/pages/Billing/BillingPageV2.tsx
Per request from the AWS MP team, avoid showing our sales email for workspaces on an AWS MP subscription.
reflame
no
no
=> avoid showing sales email for aws mp plans

.changeset/honest-trees-greet.md, sdk/client/src/listeners/console-listener.tsx, sdk/highlight-go/log/console_messages_parser.go
As with our Node.js SDK, allow our browser instrumentation to avoid serializing attributes into the
message body and instead report them only as structured attributes to produce cleaner log rows.
local deploy
changeset
no
=> allow customizing log attribute serialization

.github/workflows/rust-sdk.yml, sdk/highlight-rust/Cargo.toml, sdk/highlight-rust/highlightio-actix/Cargo.toml, sdk/highlight-rust/highlightio/Cargo.toml
This is a hotfix. Publishing CI failed because of unexpected behaviour of the used GitHub action (it iterates through every crate in the workspace instead of only publishing the ones we provide in the config). I've changed the Rust workspace to be compatible with this behaviour.
=> fix(sdk/rust): fix publish CI failing

frontend/src/pages/Setup/IntegrationBar.tsx
Fixes two issues:
1. The integration status in the top bar on the setup pages for sessions and errors was always saying "pending" and never said setup was complete.
2. We had an infinite loop fetching sessions and errors to figure out what to display in the integration bar.
This fixes the problem by ensuring the variables don't change for the session and error queries from one query to the next.
* Went to `/setup` locally and opened the network inspector. Note the continuous stream of requests hitting the sessions table in Clickhouse.
* Introduced my changes and reloaded to confirm there was only 1 request and that the status actually updates from pending to integrated.
* Same thing for errors.
* Ran the same checks on the Reflame preview.
N/A - this should reduce the number of queries …
=> Fix over fetching and wrong status on setup

backend/private-graph/graph/schema.resolvers.go, backend/worker/worker.go
For the sessions data export report, avoid including sessions with a negative active/total time.
Correct the root cause of reporting negative time caused by out of order session events.
=> avoid reporting negative session active time

frontend/src/pages/Billing/BillingPageV2.tsx, frontend/src/pages/Billing/UpdatePlanPage.tsx
Fixes base fee display for customers on an existing (non-graduated) pricing plan.
No
No
=> correctly show base fee for plans already subscribed

.changeset/funny-eggs-study.md, e2e/nextjs/package.json, e2e/remix/package.json, highlight.io/package.json, sdk/highlight-remix/package.json, yarn.lock
* Release new cloudflare workers sdks to fix opentelemetry dependency issue
* Merge more javascript dependency fixes
reflame
changeset
no
=> update javascript dependencies

.changeset/fresh-spoons-compare.md, sdk/highlight-next/package.json
I messed up on my earlier commit and moved `js-cookie` to `devDependencies` 🤦
Closes #7938
=> js-cookie is a real dependency

frontend/src/pages/Alerts/ErrorAlert/ErrorAlertPage.tsx, frontend/src/pages/Alerts/LogAlert/LogAlertPage.tsx, frontend/src/pages/Alerts/SessionAlert/SessionAlertPage.tsx
Allow `0` as a value for alert threshold since `greater than 0` would be 1 instance of a log.
https://www.loom.com/share/8f3987f0de12408d93a4a3b30154fec7
no
no
=> allow all alerts to notify for a single instance

frontend/src/pages/LogsPage/LogsTable/LogDetails.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/DevToolsWindowV2.tsx
Adds a `view in context` button to log rows to show the log among other logs
https://www.loom.com/share/6b8ad0c97dd9494a856a6b9adc9b943f
no
yes @julian-highlight
=> add a view in context button to log rows

backend/clickhouse/traces.go
- fixes issue where traces may be visible on the traces page but not possible to load from the `traces_by_id` table due to MV propagation delay
- manually tested the fallback path locally
- no
- no
=> fallback to main traces table if traces_by_id does not contain trace yet

backend/clickhouse/query.go, backend/parser/listener/listener.go, backend/parser/parser_test.go
Nested `!=` queries distribute the `!=` incorrectly.
For example, `environment!=(prod OR "on-prem")` => `environment NOT ILIKE 'prod' OR environment NOT ILIKE 'on-prem'`
Pull out the `NOT` keyword to spot in the tree in which it is written in the query.
`environment!=(prod OR "on-prem")` => `NOT (environment ILIKE 'prod' OR environment ILIKE 'on-prem')`
https://www.loom.com/share/c781d608aac54d1892a9436c7662cee5?sid=04a2d978-8d25-4f0f-a493-803d45de2596
1) Load the logs page
2) Make sure the following cases work:
N/A
N/A
=> Fix nested != queries

backend/Makefile, backend/alerts/logalerts.go, backend/alerts/sessionalerts.go, backend/clickhouse/sessions_test.go, backend/model/model.go, backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/generated/generated.go, backend/public-graph/graph/resolver.go, backend/public-graph/graph/schema.resolvers.go, backend/worker/worker.go
- removes `OrganizationID` fields - some of these were being migrated from int to bigint causing blocking
- manually tag current integer fields as `gorm:"type:integer"` to prevent attempted migration to bigint
- compared output against prod for the following to confirm int fields were created:
```select distinct table_name, column_name, column_default from information_schema.columns where table_schema = 'public' and table_name not
like 'error_object_embeddings_partitioned_%' and udt_name ilike 'int4' and column_default is null and table_name not ilike 'vadim%' and table_name
not ilike 'zane%' and column_name <> 'organization_id' and table_name not in ('events_objects_partitioned', 'awsdms_ddl_audit', 'pg_buffercache',
'organization_admins', 'spatial_ref_sys', 'geography_columns', …
```
=> cleanup unused fields

backend/model/model.go, backend/public-graph/graph/resolver_test.go
- newer version of GORM wants to migrate these fields to `type:text`, explicitly tag to make sure automigrate doesn't happen
- remove `Retryable` from automigrated models as it is unused, it also has `type:text` on this field
- ran `make start` locally to automigrate, made sure all of these columns had `jsonb` type
- want to deploy this to fix automigrate in previous GORM PR, can revert this and previous commit if issues
- no
=> add gorm type for JSONB fields

backend/clickhouse/errors.go
- despite being first in the `UNION ALL` statement, the total row might not be returned first for certain versions of clickhouse
- fixes #7786 
- was able to repro the original issue locally, confirmed that this change fixes it
- no
- no
=> fix percentage calculation for error metrics

.changeset/orange-cougars-admire.md, sdk/client/src/listeners/network-listener/utils/xhr-listener.ts
The XHR headers were being stringified with `toString()`, which does not do a deep stringify for objects, resulting in loss of info. Use `JSON.parse` to deep stringify the objects
https://www.loom.com/share/c98209ea9ce447008ff1caf5e6ceea03
1) In the browser console, test with the following variables: `JSON.parse(a)`
N/A
N/A
=> Deep stringify body objects

frontend/src/util/session/report.ts
Fixes frontend session export report generation for large reports.
before, report was truncated. now, full report is downloaded
no
no
=> correctly generate session reports for large projects

backend/clickhouse/errors.go, backend/clickhouse/migrations/000093_add_secure_id_to_errors.down.sql, backend/clickhouse/migrations/000093_add_secure_id_to_errors.up.sql, backend/clickhouse/sessions.go, frontend/src/components/CommandBar/context.tsx, frontend/src/pages/ErrorsV2/ErrorFeedCard/ErrorFeedCard.tsx, frontend/src/pages/Player/RightPlayerPanel/components/NetworkResourcePanel/NetworkResourceErrors.tsx, frontend/src/routers/ProjectRouter/ProjectRouter.tsx
* Populates the `SecureID` field on the `error_groups` Clickhouse table.
* Fixes the query fetching errors associated with a network resource ("Errors" tab on the network resource panel.
* Clean up an unused argument in `getErrorQueryImpl` (`retentionDate`).
* Fixes a bug with the "Enter" key not working or selecting a command bar item (an issue @Vadman97 and I noticed while pairing).
* Updates the local storage key for the active right panel when viewing a session (Closes HIG-4407).
* Viewed an error
* View the related session
* Viewed the network resource associated with the error and confirmed the "Errors" tab was populated correctly
* Viewed the network panel and confirmed the `GetErrorGroupsClickhouse` query was errored on prod and working on this branch
* Opened the command bar, …
=> Fix error group queries by secure ID

frontend/src/__generated/index.css, frontend/src/components/RelatedResources/ErrorPanel.tsx, frontend/src/components/RelatedResources/Panel.css.ts, frontend/src/components/RelatedResources/Panel.tsx, frontend/src/components/RelatedResources/RelatedResourcePanel.tsx, frontend/src/pages/Traces/TraceErrors.tsx, frontend/src/pages/Traces/TracePanel.tsx
Adds an animation to the related resource panel transitioning it in/out from the right side of the screen. There are also a couple bug fixes going out in this PR:
1. Prevents the text on related error buttons from spanning multiple lines in the errors list on a trace.
2. Fixes an issue where the hotkeys weren't behaving as expected when the trace dialog + the related resource dialog were being shown.
3. Updates the cursor on the reside handle to be `col-resize` instead of `ew-resize`.
4. Sets a max width you can drag the panel to.
**Before**
https://www.loom.com/share/2a01aa8400264fd9bf4884b051c65d5b
**After**
https://www.loom.com/share/d8951dff3e884546b468a3e492494ee0
Screen shared with Julian and click tested the until we were happy with the animation. Also click tested in PR preview to …
=> Animate related resource panel transitions

frontend/src/index.tsx, frontend/src/util/auth.tsx
Fixes issues with password auth mode.
* Auth logic would use sessionStorage which would prevent it from persisting across tabs
* Auth logic would fail to validate the token on refresh, causing failed network requests if the token expired. 
Closes HIG-4358
Closes HIG-4356
only affects hobby password auth
https://www.loom.com/share/d97916a494e44cb4aa07d327f1e74fea
new docker release
no
=> fix frontend auth logic failing to persist across tabs

backend/otel/extract.go, sdk/highlight-go/otel.go
Applies log `level` attributes when explicitly set to allow customizing log level.
Before
After
no
no
=> use level attribute on logs as the severity

frontend/src/pages/LogsPage/useGetLogs.ts, frontend/src/pages/Traces/useGetTraces.ts
When checking if more logs/traces exists, we use the timestamp of the last log/trace, which will include it in the query. Add one second to exclude this last log/trace
1) Load the logs/traces page
2) In the network request, check that the start time is after the last log/trace that is dispayed
https://www.loom.com/share/ea6aa1e5feb647e1acdeb0a44074d24a?sid=7dcce538-e1ba-4b19-bbeb-3a6c1ac20b54
N/A
N/A
=> Fetch future logs and traces exclusively

.changeset/thin-files-knock.md, cypress/e2e/client.cy.js, frontend/src/pages/Player/ResourcesContext/ResourcesContext.tsx, frontend/src/pages/Player/RightPlayerPanel/components/NetworkResourcePanel/NetworkResourceInfo.tsx, frontend/src/pages/Player/RightPlayerPanel/components/NetworkResourcePanel/NetworkResourceLogs.tsx, frontend/src/pages/Player/RightPlayerPanel/components/NetworkResourcePanel/NetworkResourcePanel.tsx, frontend/src/pages/Player/RightPlayerPanel/components/WebSocketMessages/WebSocketMessages.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindow/ResourcePage/components/RequestMetrics/RequestMetrics.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/NetworkPage/NetworkPage.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/utils.ts, sdk/client/src/listeners/network-listener/utils/models.ts, sdk/client/src/listeners/network-listener/utils/utils.ts, sdk/firstload/src/listeners/web-socket/index.ts
Currently network resources and websocket events use relative times to the start of the performance api. This time is based on the the window's start time, which is reset when the page is navigated to or refreshed. This causes the events to be out of order when viewing a session.
Update the events to use an absolute time to be placed in the correct spot in the session.
https://www.loom.com/share/af1ebe59557648abaa28c38945abefd1?sid=a65948e2-938a-4f9c-8fb2-3c2c94011879
1) Start a session
2) Let the page idle, navigate to and away, refresh the page
3) Complete some network requests in the window
4) Close the tab to let the session process
5) View the processed session
6) Test viewing in absolute and relative times
Let knows about how old versions of the SDK will be using `startTime` and …
=> Fix out of order session requests

.github/workflows/deploy.yml, .github/workflows/turbo.yml
- need to allowlist the Github action runner's IP address in the security group rules to allow db access
- added branch to action for testing, ran successfully; confirmed IP was added and later removed from security group
- no
- no
=> add github action runner IP to RDS security group

frontend/src/pages/Player/PlayerHook/PlayerHook.tsx, frontend/src/pages/Player/PlayerHook/PlayerState.ts
Support looping session playback via localstorage variable to allow easier demoing.
reflame
no
no
=> support looping sessions for demoing

frontend/src/pages/LogsPage/LogsTable/LogsTable.tsx, frontend/src/pages/LogsPage/utils.ts
The matching attributes under the logs row takes up space and is not helpful. This is repetitive as the user knows what is being searched for, can add the column to the table, and can expand the row.
https://www.loom.com/share/da0a81a2ba434386b771edc07d586d0e?sid=10e7e374-afb4-4b34-8ef7-72a3bfdad596
1) Load the logs table
2) Search an attribute
3) Update the search value to be in quotes
N/A
N/A
=> Remove matched attributes from logs table

frontend/src/__generated/index.css, frontend/src/__generated/ve/pages/Graphing/components/Table.css.js, frontend/src/pages/Graphing/GraphingEditor.tsx, frontend/src/pages/Graphing/components/BarChart.tsx, frontend/src/pages/Graphing/components/Graph.tsx, frontend/src/pages/Graphing/components/LineChart.tsx, frontend/src/pages/Graphing/components/Table.css.ts, frontend/src/pages/Graphing/components/Table.tsx
- implements the table metric visualization type
- clicktested on metrics page
https://www.loom.com/share/62258e131b4f4ccdbd9470d9e3dafdc5
- no, only affects metrics demo page
- @julian-highlight can review this preview or after deployment
=> add table metric visualization

backend/pricing/pricing.go
- query was reporting 0 if no rows in the materialized view during the current billing period
- start date of the fallback query should be either
- last date in the materialized view
- start date of the billing period if no rows in the materialized view
- ran updated query against prod for the Highlight project, confirmed accurate sessions and errors count
- no
- no
=> fix meter query if no rows in materialized view

backend/pricing/pricing.go
Reverts highlight/highlight#8077
possible performance regression, noticed using EXPLAIN
=> Revert "fix meter query if no rows in materialized view"

backend/clickhouse/migrations/000094_add_has_comments_to_sessions.down.sql, backend/clickhouse/migrations/000094_add_has_comments_to_sessions.up.sql, backend/clickhouse/sessions.go, backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go
The `Has Comments` filter stopped working when we transitioned to Clickhouse. Add this column to the Clickhouse table to support filtering sessions by having comments.
Note: This also adds the column to the Sessions table to help keep the state to send to clickhouse.
https://www.loom.com/share/f0b0d21951b24c0a99aba41b46f0ad10
1) Find a session
2) Add a comment
3) Filter out by sessions with comments
4) Add another comment and re-search
4) Delete one comment and re-search
4) Delete the other comment
N/A
N/A
=> Support filtering by HasComments

.changeset/orange-ravens-explode.md, sdk/highlight-go/highlight.go
We were reseting the config option, wiping out the defaults, resulting in no traces being recorded if `SamplingRateMap` was not set. Remove the unnecessary reinitialization .
1) Remove the `WithSamplingRateMap` from `backend/main.go` 
2) Start your backend and hit some endpoints
3) View traces/logs and confirm that they appear (check `service_name EXISTS`)
N/A
N/A
=> Remove overwriting sampling rate

.github/workflows/turbo.yml
- the other steps that rely on RDS access already have this same check - add it so it will not break workflows for external contributions
- will monitor this for future contributions
- no
- no
=> skip adding to security group for external contributions

frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/Billing/BillingPageV2.tsx, frontend/src/pages/Billing/UpdatePlanPage.tsx, frontend/src/pages/Billing/utils/utils.ts, frontend/src/pages/LogsPage/LogsOverageCard/LogsOverageCard.tsx, frontend/src/pages/Sessions/SessionsFeedV3/OverageCard/OverageCard.tsx
Frontend would incorrectly show overage cards when an account was on a free trial.
Reflame testing on affected customer page.
no
no
=> ensure frontend does not show overage card for free trial projects

backend/migrations/cmd/migrate-group-embeddings/main.go, backend/model/model.go
- adds `ErrorGroupEmbeddings` table to save average embedding per group
- adds script to migrate error group embeddings for project_id = 1
- script also creates an index and helper table so migration can run quicker in future, minimizing the amount of missed data when we cut over to use these group embeddings for all projects
- ran script multiple times locally, verified embeddings and counts are updated as more errors are added to the group
- will deploy a separate change to use these embeddings for project_id = 1 after migration
- no
=> add migration to save error object embeddings per group

backend/clickhouse/logs_test.go, backend/clickhouse/migrations/000095_add_session_location_state.down.sql, backend/clickhouse/migrations/000095_add_session_location_state.up.sql, backend/clickhouse/sessions.go, backend/clickhouse/testdata/fuzz/FuzzReadLogs/ef8aa3bf8c84a90c, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/public-graph/graph/resolver.go, frontend/src/components/QueryBuilder/QueryBuilder.tsx, frontend/src/graph/generated/schemas.tsx
Adds session `length` and `active_length` as valid session keys that are always provided by the resolver
so that they can be used by the grafana plugin as valid numeric attributes.
Indexes user State (US location) and allows searching for sessions by it.
Local deploy
support searching by state
no
no
=> add session duration keys as queryable

backend/migrations/cmd/migrate-group-embeddings/main.go, backend/model/model.go, backend/public-graph/graph/resolver.go, backend/public-graph/graph/resolver_test.go
- modify migration to run on batches of 100k embeddings (less memory use, can recover after crashing)
- for project_id = 1, use ErrorGroupingMethodGteLargeEmbeddingV3 as the matching method to match at the group level
- clicktested from buttons page locally, ensured new errors used the new matching method
- will monitor error grouping for project_id = 1 after deploying and migrate all projects' embeddings to the new table
- no
=> match embedding at group level for project 1

backend/clickhouse/query.go
The `NOT` filter has a child filter with no values, so it was always returning true and then negated by the `NOT`. As a result, all logs, traces, etc were being included.
Update the `NOT` logic to return the negated version of the child filter.
https://www.loom.com/share/d39d84adf6d6402da8a5bd66dcc6c34d?sid=4ee2d652-caff-4838-b044-6153bc6a30af
1) Update the workspace to be enterprise
2) Add a `[key]!=[value]` on one of the filters
4) Repeat for `NOT [key]=[value]`
N/A
N/A
=> Fix NOT filters

backend/parser/listener/listener.go, backend/parser/parser_test.go
Typing the duration in nanoseconds is burdensome on the user. Support using time suffixes to search numbers.
Supported suffixes:
```
h
m
s
ms
us
ns
```
https://www.loom.com/share/7c85288923864082bb9ce183fb39660b?sid=1a242ffd-02f6-467a-9354-6bb08191d45d
1) Visit the traces page (`/traces`)
2) Ensure duration is displayed on the table
3) Search using the numerical operators -> `>`, `>=`, `<`, `<=`, 
N/A
N/A
=> Support duration prefixes

backend/migrations/cmd/migrate-group-embeddings/main.go, backend/public-graph/graph/resolver.go
- enable new group-level matching for all projects by removing the project_id == 1 check
- updated migration script for better batching performance
- error group matching working well for project_id 1 in production
- will deploy after running the object -> group migration script once more
- can revert if issues as we're still writing object embeddings
- no
=> enable group-level matching for all projects

backend/private-graph/graph/schema.resolvers.go
- some customers use the auto-join feature and roles, should enforce that new auto-join users are members until manually upgraded
- went through the auto-join workflow locally, validated created user had role = member
- no
- no
=> auto join users should default to member role

backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver.go, backend/public-graph/graph/resolver_test.go, backend/store/error_groups.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/ErrorTags/ErrorTagsSearch.tsx
- remove table / partition creation for `error_object_embeddings_partitioned`
- remove reading / writing from `error_object_embeddings_partitioned`
- also removes the `find_similar_errors` resolver - this demo page doesn't seem to be working in prod?
- created errors from the `buttons` page, made sure they were grouped to existing error groups
- can revert if issues, will drop the `error_object_embeddings_partitioned` tables after all looks good
- no
=> remove error object embeddings

backend/main.go, backend/otel/extract.go, backend/otel/otel.go, backend/otel/otel_test.go, backend/private-graph/graph/resolver.go, sdk/highlight-go/otel.go
next.js and other customers may send traces that contain standard events (exception, log)
where they still want to record the trace which may contain other metadata and should be 
part of a larger flame graph.
start to capture those spans
* updates opentelemetry ingest processing to support some additional message keys
* fixes go sdk failing to sampling traces in if an empty sampling map was provided
local deploy
go logs coming thru
no
no
=> save traces that contain events

backend/clickhouse/query.go, backend/clickhouse/traces_test.go
Ingestion filters would fail for primary columns because of a recently-introduced `toString()`
wrapper around column keys that would interfere with the `KeysToColumns` map. cc @SpennyNDaJets 
new unit test
no
no
=> fix ingestion filters

backend/clickhouse/trace_row.go
- uses some logic for truncating large log values to apply to traces as well
- expecting this to solve our current issue with trace uploads where certain values are very large >10mb and failing to write to clickhouse
- tested the happy path locally to make sure traces are still ingested, will monitor the prod traces backlog after deployment
- no
- no
=> truncate trace values > 65536

.changeset/curvy-crabs-tan.md, __generated/rr/rrweb/rr.js, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts, sdk/highlight-next/CHANGELOG.md, sdk/highlight-next/package.json, sdk/highlight-remix/CHANGELOG.md, sdk/highlight-remix/package.json, turbo.json, yarn.lock
Fixes js release pipeline after #8058 broke it due to a changeset configuration issue
Releases:
-   highlight.run@8.11.0
-   @highlight-run/next@7.4.10
-   @highlight-run/remix@2.0.28
before
after
no
no
=> fix release process for bundled highlight.run client

backend/public-graph/graph/resolver.go
Fixes a bug where we would compare the excluded environments on an error alert against the session associated with the error rather than the error's environment. This can be problematic when there isn't an associated session.
Click tested to confirm I was getting alerts and that they stopped once I added the excluded environments locally.
Will follow up with customers impacted by this bug to let them know it should be resolved, but no major considerations here.
N/A
=> Compare excluded env against error env

sdk/highlightinc-highlight-datasource/src/datasource.ts
- interpolate variables in `queryText` before sending to backend datasource
- tested in local grafana instance
- no, will submit new plugin version to marketplace after some of the other planned Grafana changes
- no
=> interpolate query variables

backend/clickhouse/query.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, sdk/highlightinc-highlight-datasource/pkg/plugin/datasource.go, sdk/highlightinc-highlight-datasource/src/datasource.ts
- `CountDistinct` should operate almost exactly how `CountDistinctKey` does, but instead of using `highlight.key` should use a custom key
- click tested in grafana plugin locally
- no
- no
=> support count distinct in grafana

backend/clickhouse/errors.go, backend/clickhouse/logs.go, backend/clickhouse/query.go, backend/clickhouse/sessions.go, backend/clickhouse/traces.go, backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/schemas.tsx, sdk/highlightinc-highlight-datasource/dashboards/highlight-test-dashboard.json, sdk/highlightinc-highlight-datasource/docker-compose.yaml, sdk/highlightinc-highlight-datasource/package.json, sdk/highlightinc-highlight-datasource/pkg/plugin/datasource.go, sdk/highlightinc-highlight-datasource/src/components/QueryEditor.tsx, sdk/highlightinc-highlight-datasource/src/datasource.ts, sdk/highlightinc-highlight-datasource/src/plugin.json, yarn.lock
- adds support for a `None` function which calls a different resolver, returning raw results from the traces, logs, errors_joined, and sessions_joined tables
- for sessions_joined, the "body" is formatted as `{identifier}: {city}, {country}`
- these results can be used in log and table visualizations in Grafana following the logs data frame format https://grafana.com/developers/plugin-tools/tutorials/build-a-logs-data-source-plugin#logs-data-frame-format
- upgrades min Grafana version to 10.1.0 (which introduced the above logs format)
- refactors `*_metrics` queries to use the unified `metrics` resolver
- clicktested in local grafana instance, made sure existing metrics queries were still working correctly
https://www.loom.com/share/17537ee12ca948b998a070e23fa2176f
- will add `metrics` …
=> support logs visualization in grafana plugin

frontend/src/pages/Traces/TraceSpanAttributes.tsx, frontend/src/pages/Traces/utils.test.ts, frontend/src/pages/Traces/utils.ts
Fixes an issue where trace attributes weren't being shown on a trace ([more context in Slack](https://highlightcorp.slack.com/archives/C02N2AZS8BV/p1712175890638669)). Also tweaks the attribute cleaning logic so we don't filter out values like `0` or `null` which could be useful to the end user.
Click tested [the problematic trace](https://app.highlight.io/29954/traces/a8a037c749e30845c9c4a8517d7255fa/d4de3069dd0405ca?query=service_name%21%3Dmagicsky-frontend%20process.executable.path%3D%2Fvar%2Flang%2Fbin%2Fnode) in the PR preview to confirm the changes. Also added some unit tests around the formatting/attribute cleaning logic.
N/A
N/A
=> Fix trace attributes not appearing

backend/clickhouse/logs.go
You can't search logs using the `message` key on a filter. This is confusing because people see `message` in the log attributes and try to filter on it. This PR fixes that.
Performed a number of searches using the `message` key and confirmed the value was being mapped properly using a breakpoint in my IDE and checking the values.
N/A
N/A
=> Allow searching logs by `message` key

backend/clickhouse/errors.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/schemas.tsx
Make some backend updates to support swapping out the error search query in https://github.com/highlight/highlight/pull/8179, while being backwards compatible.
Updates:
- Group error objects for histogram
- Correct some sql bugs for using an inner query
- Support Error saved segment types
- Look up table to query when fetching key values
- Support non-string key values 
1. Ensure searching for errors works as anticipated
N/A
N/A
=> Update backend with supporting changes for query

sdk/highlightinc-highlight-datasource/src/components/QueryEditor.tsx
- count distinct was only showing numeric values - should support categorical ones as well (e.g. count of unique identifiers)
- clicktested in local grafana instance
- will include this fix in grafana plugin release
- no
=> use group by keys for count distinct

frontend/src/pages/Traces/TraceFlameGraphNode.tsx, frontend/src/pages/Traces/utils.ts
Tweaks the display of really small spans on the trace flame graph.
* Sets a minimum width for a span on the flame graph to make it easier to see and interact with spans that have a very short duration.
* Fixes the duration display for spans that report a `0` duration.
The previews below are looking at [this trace](https://app.highlight.io/1/traces/UGNvAHtaX3/ae30c0e32967e662) for reference.
**Before**
**After**
Click tested some traces in prod and contrasted them with the PR preview for the same trace (see before and after above).
N/A - client-side change only.
Will review the changes w/ Julian before merging.
=> Improve small span display on flame graph

frontend/src/__generated/index.css, frontend/src/__generated/ve/pages/Graphing/components/Graph.css.js, frontend/src/pages/Graphing/components/BarChart.tsx, frontend/src/pages/Graphing/components/Graph.css.ts, frontend/src/pages/Graphing/components/Graph.tsx, frontend/src/pages/Graphing/components/LineChart.tsx, frontend/src/pages/Graphing/components/Table.tsx
- adds a tooltip for line and bar charts matching figma design
- will merge in after `zane/dashboards` branch is merged
- @julian-highlight to review after deployment
=> metrics tooltips

backend/.golangci.yml, backend/pricing/pricing.go, backend/private-graph/graph/schema.resolvers.go, backend/store/workspaces.go, backend/worker/worker_test.go
https://github.com/highlight/highlight/pull/7638 introduced a bug with reporting logic that 
resulted us in under-reporting logs and traces overages for billing. This was caused
by a consolidation of shared [code](https://github.com/highlight/highlight/blob/8cb08386685dfeb287bbe1793228638279cd90a5/backend/pricing/pricing.go#L843-L846) used for overage calculation to a new function. We had previously queried workspaces
while [fetching their associated projects manually](https://github.com/highlight/highlight/blob/8cb08386685dfeb287bbe1793228638279cd90a5/backend/pricing/pricing.go#L909-L913), 
but the refactor failed to include the secondary loading.
This PR refactores the querying to use the `Store` object with a `Preload` statement to efficiently query projects.
after
before
no
no
=> correctly report logs and traces overages

backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/__generated/index.css, frontend/src/__generated/ve/pages/Graphing/DashboardOverview.css.js, frontend/src/components/TimeRangePicker/TimeRangePicker.tsx, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/Graphing/Dashboard.tsx, frontend/src/pages/Graphing/DashboardOverview.css.ts, frontend/src/pages/Graphing/DashboardOverview.tsx, frontend/src/pages/Graphing/DashboardRouter.tsx, frontend/src/pages/Graphing/ExpandedGraph.tsx, frontend/src/pages/Graphing/GraphingEditor.tsx, frontend/src/pages/Graphing/components/BarChart.tsx, frontend/src/routers/ProjectRouter/ApplicationRouter.tsx, frontend/src/util/graph.tsx
- adds visualizations resolver for fetching dashboard metadata for a project, queryable and paginated
- adds `DashboardOverview` page displaying a table of these dashboards, allowing users to click into or create a new one
- changed `/dashboards` endpoint to point at this new page
- some styling polish
- https://www.loom.com/share/9fa6b87cb8ef4be5aef898681054b497
- need to drop `visualization_project_id_name_idx` after deployment (decided not to enforce a unique constraint on name as this is kind of annoying in the UI and not super necessary)
- @julian-highlight can review after deployment
=> dashboard overview page

backend/clickhouse/errors.go, backend/clickhouse/errors_test.go, backend/clickhouse/logs.go, backend/clickhouse/query.go, backend/clickhouse/sessions.go, backend/clickhouse/traces.go, backend/public-graph/graph/resolver.go, backend/public-graph/graph/sampling.go
Error ingest filters would not work because of a number of complications around sharing the
ingest logic with the search logic (which for errors isn't ported over to clickhouse fully).
Updates the ingest filter logic to using a new table config that is correctly mapping to the `BackendErrorObjectInput` model.
Fixes issue with ingest filters where an invalid filter would result in overmatching.
new unit test
will be manually setting necessary error filtering for affected customer
no
=> correctly filter errors ingest

backend/scripts/migrate-error-segments/main.go, backend/scripts/migrate-error-segments/main_test.go
Add a task to convert the error segments to the new saved segment table.
https://www.loom.com/share/75b6865fb9734967ba04744e9db86f4e
1) Create a saved search for errors
2) Run the task in dry run mode (`doppler run -- go run backend/scripts/migrate-error-segments/main.go`)
3) Run the task in confirm mode (`doppler run -- go run backend/scripts/migrate-error-segments/main.go -confirm=true`)
4) Run again in confirm mode
1. Run a dry run to confirm working
2. Run the task
N/A
=> Add error segment migration task:

backend/pricing/pricing.go, backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go, docker/collector.Dockerfile, docker/compose.yml, docker/configure-collector.sh, docker/start-infra.sh
* Fixes billing issue for overage customers on a non-monthly and non-annual plan (ie. 6-month plan)
* Fixes self hosted cross-workspace access
* Simplifies collector deployment via `./start-infra.sh` in a docker container to avoid depending on `sed`
* Cleans up logging in the docker compose to avoid requiring `sed`.
* Defaults self hosted stack to `enterprise` quota to avoid ingestion limits.
local hobby testing, ec2 box docker image testing
no, will be released with new docker image
no
=> improvements to self hosted stack

backend/clickhouse/errors.go
Fix some backend bugs with the new error queries:
- Add order by to error group search
- Use `FINAL` tables
- Add timestamp clauses to error object search
- Pull out order by, group by, and select to higher level functions
Confirmed working in https://github.com/highlight/highlight/pull/8179
N/A - not used in prod
N/A
=> Some new error query fixes

frontend/src/pages/Traces/TraceFlameGraph.tsx
0 showing up in the flame graph
1) View trace [here](https://app.highlight.io/1/sessions/o1yhwFT9CRWjM7xYdvtI2Gt51guS?network-resource-id=264&page=1&query=and%7C%7Ccustom_processed%2Cis%2Ctrue&segment=%22undefined%22)
N/A
N/A
=> Fix empty flame graph

backend/clickhouse/migrations/000097_materialized_column.down.sql, backend/clickhouse/migrations/000097_materialized_column.up.sql
- applies some settings to `traces` and related tables for new parts to be created as wide parts
- adds materialized column for HighlightType
https://highlightcorp.slack.com/archives/C02CJANPHQS/p1712941635157209
- ran script locally
- will backfill data for the materialized column after deployment, then will cut over code to refer to this column
- no
=> create materialized column for TraceAttributes

backend/otel/otel.go
- saw more merge activity for the `logs` table than expected. was seeing old logs partitions with multiple parts, seemingly from recent inserts to the logs table.
- digging into the code, it looks like I missed setting `curTime` in one of the places we call `extractFields`. when this is not set, clamping is not applied
- ran backend locally to make sure traces/logs were still ingested
- no, will monitor 
- no
=> fix log timestamp clamping

sdk/highlight-py/e2e/highlight_fastapi/main.py, sdk/highlight-py/e2e/highlight_fastapi/work.py, sdk/highlight-py/highlight_io/integrations/django.py, sdk/highlight-py/highlight_io/integrations/fastapi.py, sdk/highlight-py/highlight_io/integrations/flask.py, sdk/highlight-py/highlight_io/sdk.py, sdk/highlight-py/pyproject.toml
* increase batching to help avoid dropping traces and logs
* add `debug` setting to turn on opentelemetry debug logging
* support custom log handler usage in python
* improve span names for web frameworks (django, fastapi, flask)
Closes HIG-4498
new python sdk version
no
=> improve python SDK

.changeset/sixty-pandas-travel.md, .changeset/wild-chairs-melt.md, backend/public-graph/graph/resolver.go, backend/public-graph/graph/resolver_test.go, backend/stacktraces/enhancer.go, backend/stacktraces/enhancer_test.go, sdk/highlight-next/src/util/with-highlight-config.ts, sourcemap-uploader/src/lib.ts
Closes HIG-2599
Closes HIG-4506
new unit testing
testing the sourcemap generation
before:
after:
will be looking at % of errors enhanced with sourcemap before/after merging this change
no
=> fall back to unversioned sourcemaps

frontend/src/pages/Player/RightPlayerPanel/components/NetworkResourcePanel/NetworkResourcePanel.tsx, frontend/src/pages/Traces/TraceFlameGraph.tsx, frontend/src/pages/Traces/TraceProvider.tsx, packages/ui/package.json, packages/ui/src/components/Tabs/Tabs.tsx, yarn.lock
Updates the behavior of tab content to not be mounted until the tab is shown. This is consistent with the behavior we had in our old `Tabs` component and fixes a bug where we don't calculate the `width` property on the trace flame graph when put behind a tab on the network resource panel.
In order to get this behavior working we also needed to upgrade Ariakit because there was a bug where the tabs would _never_ render when using the `unmountOnHide` prop.
View a fetch network resource in the session dev tools and ensure the trace flame graph is rendered correctly.
N/A
N/A
=> Fix flame graph not appearing on network resources

__generated/rr/rrweb/rr.js, frontend/src/components/Search/SearchForm/SearchForm.tsx, frontend/src/pages/Alerts/LogAlert/LogAlertPage.tsx
The logs alert page was using the `PreviousDateRangePicker`, but needed to use the values from the query passed into it. Swap it out with the search `DateRangePicker` and use the `useSearchTime` hooks to allow updating the url.
https://www.loom.com/share/82611b06d77941cba8b46fa7cdba8424?sid=d008b64e-5711-44d5-bfe3-89cf482df085
1) Make a log query in which the time is updated
2) Create an alert from that query
N/A
N/A
=> Swap date picker on log alerts

.changeset/chatty-adults-hammer.md, .changeset/curly-lobsters-bathe.md, .changeset/fuzzy-ties-repair.md, .changeset/stale-poems-think.md, backend/clickhouse/errors.go, backend/clickhouse/insert.go, backend/clickhouse/insert_test.go, backend/clickhouse/sessions.go, docs-content/sdk/nodejs.md, e2e/express-ts/src/express.ts, e2e/nestjs/src/app.controller.ts, e2e/nestjs/src/app.service.ts, e2e/nestjs/src/main.ts, sdk/highlight-apollo/src/apollo.test.ts, sdk/highlight-apollo/src/apolloV3.test.ts, sdk/highlight-nest/src/index.ts, sdk/highlight-node/src/client.ts, sdk/highlight-node/src/sdk.ts
* Updates node.js SDK export batch settings to help with dropped spans
* Fixes nestjs sdk crashing on endpoints where there was no returned data
* Improves nestjs spans and context propagation for parent->child spans
* Renames nodejs internal spans to make it easier to filter them out.
8844ac67c9b8a6f728a6b06168618c22420d9173 should fix HIG-4518
changeset
no
=> fix nestjs sdk requiring endpoint to return

e2e/nextjs/src/app/layout.tsx, e2e/nextjs/src/app/loading.tsx, e2e/nextjs/src/app/suspense/page.tsx, highlight.io/app/api/sitemap/route.ts
Add an example of an async page to our e2e next app to test highlight's impact on suspense page loading per customer request.
local deploy
no
no
=> add nextjs example of suspense loading

backend/scripts/migrate-error-segments/main.go, backend/scripts/migrate-error-segments/main_test.go, frontend/src/pages/ErrorsV2/ErrorInstance/SeeAllInstances.tsx
When clicking on the all instances link, it resets the search query for the overall search. Pass in the search to hold the current search values
1) Search for errors (not using the default search)
2) Click into and error and view all instances
N/A
N/A
=> Fix all instances link

backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver_test.go, backend/store/error_groups.go, backend/store/error_groups_test.go, backend/worker/autoresolver.go
The error group auto resolver passes in `nil` ids to the data sync queue. Pass in the param id, and refactor to never use the error group.
https://www.loom.com/share/83f8b158e4be4a6a93ef6cc2dccab35e?sid=43bad0d2-ba8d-4cc8-8d92-632dce2bda74
1) Search for `status=OPEN` errors
2) Update an error to be resolved
3) Refresh the search (may have a lag)
N/A
N/A
=> Fix error group autoresolver data sync

frontend/src/components/RelatedResources/SessionPanel.tsx, frontend/src/pages/Player/PlayerPage.tsx
Adds the empty states to the session player on the related resource panel and fixes a bug where we would get stuck in the loading state if the session wasn't playable.
Click tested and found some sessions that weren't playable to ensure the I saw the empty statel
N/A
N/A
=> Add empty state UI for sessions in related resource panel

frontend/src/pages/Player/PlayerPage.tsx, frontend/src/pages/Player/Toolbar/NewCommentForm/CommentTextBody/CommentTextBody.tsx, frontend/src/pages/Player/Toolbar/NewCommentForm/CommentTextBody/mentions.module.css, frontend/src/pages/Player/Toolbar/NewCommentForm/NewCommentForm.tsx, frontend/src/pages/Player/Toolbar/NewCommentModal/NewCommentModal.tsx
The slack `@` dropdown does not consistently render to the correct place. Drop the parent ref, and let react mentions render the dropdown under the input.
https://www.loom.com/share/ca0f989351a5480097812917614f8b0e
1) View a session
2) Click to add a comment
3) Type in the `@` symbol
N/A
N/A
=> Show slack dropdown consistently

backend/vercel/vercel.go, backend/vercel/vercel_test.go, sdk/highlight-go/log/util.go
Rather than using the vercel project id as the service name, use the vercel project name as the service name
for new log drains and send the vercel project id as a log attribute (`vercel.project`).
new unit testing
no
no
=> use vercel project name as service name

frontend/src/components/FeedResults/FeedResults.tsx, frontend/src/pages/ErrorsV2/SearchPanel/SearchPanel.tsx, frontend/src/pages/ErrorsV2/useGetErrors.ts, frontend/src/pages/LogsPage/LogsTable/LogsTable.tsx, frontend/src/pages/LogsPage/useGetLogs.ts, frontend/src/pages/Sessions/SessionsFeedV3/SessionsFeedV3.tsx, frontend/src/pages/Traces/TracesList.tsx, frontend/src/pages/Traces/useGetTraces.ts, frontend/src/util/search.ts
Stop polling once we hit the max number of results to show
Max resources per resource:
- Sessions: 10
- Errors: 10
- Logs: 50
- Traces: 50
https://www.loom.com/share/a909cf0fa1ba41b081b0d5dc6f67888f?sid=607e0452-e802-4905-9a18-2ee98ae4a396
1) Load a resource page and open the network tab
N/A
N/A
=> Optimize polling resources

frontend/src/pages/Player/RightPlayerPanel/components/NetworkResourcePanel/NetworkResourcePanel.tsx, packages/ui/src/components/Tabs/Tabs.tsx
- fixes issue where a tab panel within flex layout (network resources) had its overflow cut off and not scrollable
https://www.loom.com/share/d0b4c60e88ae4289b98797ee3dc7dcef
- no
- no
=> add scrollable prop to tabs to allow scrolling within individual tab panels

.changeset/proud-lobsters-rescue.md, __generated/rr/rrweb/rr.js
fixes incorrect `this` scoping breaking canvas snapshotting
merge conflict from latest rrweb upgrade
changeset
=> fix rrweb merge conflict breaking canvas recording

frontend/src/__generated/index.css, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ConsolePage/ConsolePage.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ConsolePage/style.css.ts, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/utils.ts
closes #4872 
/claim #4872
I noticed that the arrow icon in the network logs doesn't function, whereas it works as a 'go-to' button in error logs. Is this intentional or does it need fixing?
I also noticed that when switching tabs, if I'm at a certain timestamp in one tab and then switch to another tab, the new tab doesn't automatically scroll to the current active log.(By tab i mean console, error and network tabs)
[Screencast from 17-04-2024 10:58:45.webm](https://github.com/highlight/highlight/assets/112156147/8d35835e-14d1-4584-a32c-ac59886fa6d3)
[Screencast from 17-04-2024 10:27:46.webm](https://github.com/highlight/highlight/assets/112156147/45d0e7b7-e476-4f3a-87bd-24e495952177)
None
No
=> Add position indicator in session logs

__generated/rr/rrweb/rr.js, frontend/src/pages/ErrorsV2/ErrorInstances/ErrorInstancesTable.tsx
When clicking an error instance, the search gets cleared.
1) View the error search
2) Modify the search to not be the default search
3) Click into an error and view all instances
4) Click on an instance
N/A
N/A
=> Fix instance link

backend/clickhouse/query.go, backend/main.go, backend/redis/cache.go, backend/redis/utils_test.go, backend/stacktraces/enhancer.go, backend/stacktraces/enhancer_test.go, backend/storage/storage.go, sdk/highlight-go/trace/tracer.go
adds granular trace ingestion for private graph requests.
sourcemap processing has been slow due to repeated failing queries.
caching for 1 minute will help with perf while still updating frequently when sourcemaps / js files are uploaded
manual testing locally, unit tests
no
no
=> caching for sourcemaps

frontend/src/components/Header/Header.tsx, highlight.io/components/common/Navbar/Navbar.tsx
- adds banners in app and site linking to blog posts with tag `launch-week-5`
- should be deployed after blog content is added
- @julian-highlight feel free to review in preview
=> add banners for launch week 5

sdk/client/src/listeners/network-listener/utils/fetch-listener.ts
Customers have asked to capture CORS and other failed network requests in the session
network devtools tab. Ensure that we do not miss fetch errors by reporting additional metadata.
Closes WHO-2
changeset
no
=> report cors network request failures

frontend/src/__generated/index.css, frontend/src/components/Header/Header.tsx, frontend/src/hooks/useFeatureFlag/useFeatureFlag.ts, frontend/src/pages/Graphing/Dashboard.tsx, frontend/src/pages/Graphing/DashboardOverview.tsx, frontend/src/pages/Graphing/GraphingEditor.tsx, frontend/src/pages/Graphing/components/Graph.css.ts, frontend/src/routers/ProjectRouter/ApplicationRouter.tsx
- renames `Dashboard` to `Metrics` a few places in the UI and in the route
- legend is max 2 rows, row spacing increased so it doesn't feel so crowded
- no
- @julian-highlight fyi
=> rename dashboard -> metric in places, fix spacing in legend

frontend/src/pages/WorkspaceTeam/components/InviteMemberModal.tsx
Fixes a few issues with our member invite modal.
* Resets the form after successful submission
* Fixes the auto focus on the email input after successful submission
* Removes the alert if you close and reopen the modal
Click tested the following locally and in the PR preview.
* Invite a team member and ensure
* Email input was reset
* Email input was focused
* Closing and reopening the modal does not show the alert
N/A - all minor client-side changes
N/A
=> Fix issues with invite modal

frontend/src/components/RelatedResources/LogsPanel.tsx, frontend/src/pages/LogsPage/LogsPage.tsx, frontend/src/pages/LogsPage/LogsTable/LogsTable.tsx, frontend/src/pages/Player/RightPlayerPanel/components/NetworkResourcePanel/NetworkResourceLogs.tsx
Editing a search query on the logs page is sluggish and causes some jank in the UI. This is because we try to update the text highlight for query matches on every log row with every keystroke. This PR works around this issue by passing the needed query data down via props to the logs table and only passing the top-level `query` variable that is updated when the form is actually submitted.
* Open the logs page in production and enter some query data. Note the sluggishness when typing in the input.
* Open the PR preview for this branch. Things should be much more responsive now!
N/A - all client-side changes.
N/A - no visual change from this.
=> Fix performance issue with query editor on logs

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/mutation.gql, frontend/src/pages/Graphing/Dashboard.tsx, frontend/src/pages/Graphing/GraphingEditor.tsx, frontend/src/pages/Graphing/components/BarChart.tsx, frontend/src/pages/Graphing/components/Graph.tsx
- fixes a bug where a new graph may not be shown until refreshing the page
- uses apollo's `cache.modify` when creating/editing/deleting graphs and reordering or renaming a dashboard
- this optimistically modifies the cache with the updated state, while making another query to `GetVisualization` in case of an issue (similar to apollo's 'cache-and-network' mode)
https://www.loom.com/share/e8db544807ed430681450afef840887f
- svg mask seems to be a source of perf issues - replace with clipPath
- no
- no
=> use optimistic cache updates in metrics ui

frontend/src/pages/Graphing/DashboardOverview.tsx, frontend/src/pages/Graphing/components/CreateDashboardModal.tsx
- instead of defaulting all new dashboards to "Untitled dashboard", open a form in a modal for entering the dashboard name
- https://www.loom.com/share/9d274d7de8fc488493ca9d105b9753f5
- no
=> add form for name for new dashboards

backend/private-graph/graph/schema.resolvers.go, frontend/src/pages/WorkspaceTeam/components/InviteMemberModal.tsx
We currently allow people to send invites to existing admins and people who have already been invited to a workspace. This PR adds some validations and error handling to ensure this doesn't happen. The checks for existing emails are case-insensitive.
* Try inviting an existing admin and ensure you get an error.
* Try inviting someone who has already been invited and ensure you get an error.
* Ensure emails that don't match admins or existing invitees are created correctly.
Adds some DB load when creating a workspace invite, but only a few reads.
N/A
=> Don't allow inviting existing admins or invitees

backend/clickhouse/query.go
`toFloat64OrNull(...)` in clickhouse does not accept `int` or `float` values as arguments.
broken charts loading
count distinct still works
no
no
=> fixup! fix count distinct for metrics api (#8413)

frontend/src/__generated/index.css, frontend/src/__generated/ve/pages/Graphing/components/Table.css.js, frontend/src/pages/Graphing/Dashboard.tsx, frontend/src/pages/Graphing/DashboardOverview.tsx, frontend/src/pages/Graphing/ExpandedGraph.tsx, frontend/src/pages/Graphing/GraphingEditor.tsx, frontend/src/pages/Graphing/components/CreateDashboardModal.tsx, frontend/src/pages/Graphing/components/EmptyDashboardCallout.tsx, frontend/src/pages/Graphing/components/Table.css.ts, frontend/src/pages/Graphing/components/Table.tsx
- fixes issue where header could overflow (use ellipses and hide overflow when there are way too many cells)
- fixes issue where header/rows could wrap to multiple lines
- set a min-width on the first column so timestamps are always fully visible
- fixes issue where an overflowing table would cause funky dashboard grid sizes
- add empty state
- fix helmets and remove autocomplete
https://www.loom.com/share/2c74bffe247343c4a63a5bad915b75ac
https://www.loom.com/share/b1b49e18da3542db8fec8b7c21897509
- no
=> fix overflow issues on metrics table

docs-content/general/6_product-features/6_metrics/1_overview.md
- adds the launch week metrics video to the metrics overview docs
- no
- no
=> add metrics video to docs

frontend/src/pages/Graphing/components/LineChart.tsx
- adds to the line charts when data is missing on either side (avoids confusing invisible points on the graphs)
- no
- @julian-highlight if you have any style recommendation for these dots, right now they're just 2px filled circles
=> draw dots at line chart discontinuities

docs-content/getting-started/3_client-sdk/7_replay-configuration/iframes.md
Clarifies standalone cross origin iframe recording.
na
no
no
=> update docs for cross origin iframes recording in standalone mode

.changeset/slow-lizards-begin.md, sdk/client/src/types/types.ts, sdk/firstload/src/index.tsx
* expose the highlight recording state via an accessor method
local deploy
changeset
no
=> export highlight state on sdk

blog-content/lw5-d4-cohesion.md, highlight.io/pages/_document.js
Add tracking js script + fix launch week links.
=> Add tracking js script

backend/clickhouse/query.go, frontend/src/__generated/index.css, frontend/src/pages/Graphing/components/Graph.css.ts
- constrain tooltip to max height 180px to avoid escaping the graph when there are lots of series
- fix issue grouping on top-level non-string columns (e.g. errors.has_session)
- no
- no
=> more dashboard polish items

frontend/src/__generated/index.css, frontend/src/__generated/ve/pages/Graphing/components/Graph.css.js, frontend/src/hooks/useSearchTime.ts, frontend/src/pages/Graphing/Dashboard.tsx, frontend/src/pages/Graphing/ExpandedGraph.tsx, frontend/src/pages/Graphing/GraphingEditor.tsx, frontend/src/pages/Graphing/components/BarChart.tsx, frontend/src/pages/Graphing/components/Graph.css.ts, frontend/src/pages/Graphing/components/Graph.tsx, frontend/src/pages/Graphing/components/LineChart.tsx
- add the concept of a reference area to the common `Graph` file - when the x-axis is a timestamp, allow selecting a range in the graph to adjust the dates
- the date pickers were adding to the history whenever the date was changed, but pressing back would not revert to the previous date - for now, I'm making it replace the history
https://www.loom.com/share/59d9bb3c0af243f18bc161dd9f5b65c0
- no
- @julian-highlight to review range selecting functionality - I just used a recharts example as inspiration but let me know if I should adjust the colors or anything
=> add range select, make time selector replace history

backend/model/model.go, backend/private-graph/graph/resolver_test.go
- `AdminEmailAddresses` used in billing should return only users with `wa.role = 'ADMIN'`
- unit tested to ensure only admins in the input workspace are returned
- ran query against Highlight workspace to ensure non-admins were filtered out
- no
- no
=> send billing emails to role = admin only

backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/schemas.tsx
Now that error search and segments have been migrated and working for the past month, we can clean up the legacy error segment code.
Harder to revert error experience
N/A
=> Remove error segment code

frontend/src/hooks/useSearchTime.ts
- query param erased when changing the date - use `replaceIn` instead here
- preview env
- no
- no
=> use replaceIn to stop erasing other query params

frontend/src/pages/Alerts/ErrorAlert/ErrorAlertPage.tsx, frontend/src/pages/ErrorsV2/ErrorsV2.tsx, frontend/src/pages/ErrorsV2/SearchPanel/SearchPanel.tsx, frontend/src/pages/FrontPlugin/components/HighlightSessions.tsx, frontend/src/pages/Player/PlayerPage.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionsFeedV3.tsx, packages/ui/src/components/DatePicker/DateRangePicker/index.tsx
Allow errors and sessions to search back to 3 months.
https://www.loom.com/share/b168e296ea014fb5866cb1f2cacc6505?sid=619f9f32-945b-425e-bf4b-9caa6bd68ead
1. View the sessions page
2. Select the "Last 3 months" prefix
3. Select custom and select dates more than 30 days ago
N/A
N/A
=> Extend sessions and errors date range

frontend/src/pages/Graphing/components/BarChart.tsx, frontend/src/pages/Graphing/components/LineChart.tsx
- change line and bar chart components to use `dataMin, dataMax` as the x-axis domain instead of `auto, auto`
- fix dot logic which had bugs when multiple series were displayed (needed to check both undefined and null)
- fix categorical line charts not showing data
- no
- no
=> [HIG-4610] use dataMin, dataMax for x-axis, dot fixes

frontend/src/pages/Graphing/Dashboard.tsx, frontend/src/pages/Graphing/ExpandedGraph.tsx, frontend/src/pages/Graphing/GraphingEditor.tsx, frontend/src/pages/Graphing/components/Graph.tsx
Add polling to the metrics page to refresh data every minute
https://www.loom.com/share/d520058cc11d4437929ab0acdf8c779c
1. Load the metrics page with a preset time (i.e. "Last 15 minutes")
2. Change the time to a fixed time range
3. Change time back to a preset time 
4. Expanded a graph
5. Edit a graph
N/A
N/A
=> Metric polling

backend/clickhouse/trace_row.go, backend/clickhouse/traces.go, backend/clickhouse/traces_test.go, backend/kafka-queue/types.go, backend/otel/otel.go, backend/public-graph/graph/resolver.go, backend/worker/kafka_worker.go, backend/worker/worker_test.go
- convert to `ClickhouseTraceRow` before writing to kafka in order to match the Clickhouse schema (flattened Events and Links columns). the link and event columns were being sent to Clickhouse but ignored because they didn't match the schema
- ran locally to make sure traces were being saved correctly w/ events
- will monitor in prod after deploying
- no
- no
=> fix trace events and links

backend/go.mod, backend/go.sum, backend/main.go, backend/migrations/cmd/add-stripe-prices/main.go, backend/pricing/pricing.go, backend/private-graph/graph/middleware.go, backend/private-graph/graph/oauth.go, backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go, backend/redis/utils.go
* upgrades stripe API to latest version, supporting cross-api-version webhooks to ensure we do not miss events that recently failed that are retrying on the old api version
* adds caching to stripe API call used by the frontend `Header` component that is causing us to be rate limited
* fixes private graph span sampling to make sure we don't record all private graph traces
manual deploy to prod
no
no
=> resolve stripe rate limiting

frontend/src/pages/ErrorsV2/ErrorInstance/ErrorInstance.tsx
Fixes https://app.highlight.io/1/errors/FqTuzfLnrx1D23fyJzawqLIFE0iE
Where button was erroring because their was a `#` in the search query
e.g. `query=identifier=#123456789`
Video: TBD
1) Load an error with a session
2) Click on "All sessions for this user" button
N/A
N/A
=> Fix # in search params

frontend/src/components/Search/SearchForm/SearchForm.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionFeedConfigDropdown/index.tsx
Update the search popover to focus on the first item with a value (i.e. not "Show all results for [value]")
https://www.loom.com/share/f196d9a5d3e947f9b610170ed16886b2
1) Navigate to one of the product pages
2) Click into the query
3) Start typing
4) Select a value
5) Select an operator
6) Start typing
N/A
N/A
=> Fix search popover focus

backend/clickhouse/migrations/000100_recreate_sessions_joined_vw.down.sql, backend/clickhouse/migrations/000100_recreate_sessions_joined_vw.up.sql
The `sessions_joined_vw` has duplicates because it is not using the `FINAL` keyword when creating the view. Recreate the view with the `FINAL` keyword 
1) Load the sessions search
N/A
N/A
=> Remove duplicate sessions in sessions_joined_vw

frontend/src/pages/IntegrationAuthCallback/IntegrationAuthCallbackPage.tsx
- users who need to log in / sign up to highlight see a blank screen while going through the Vercel integration installation starting in Vercel
- fix this by going through the auth workflow, then redirecting back to the callback
- tested these cases in preview:
- already signed in - shown vercel settings in modal
- not signed in, account created - sign in, then redirected to vercel settings
- not signed in, no account - sign up, go through onboarding, then redirected to vercel settings
- no
- no
=> [SUP-9] fix vercel workflow for unauthed users

frontend/src/__generated/index.css, frontend/src/components/Search/SearchForm/SearchForm.css.ts, frontend/src/components/Search/SearchForm/SearchForm.tsx
- Wrap the contains and match operators in `"` to support the usage of reserved chars within it.
- Align the error/X with the bottom row
https://www.loom.com/share/d0d0b4d4acb74a139a91bfcd4cf91fb6?sid=441c1a9d-74f0-4b0a-b5a4-0de1f27988f4
1) Load the sessions page
2) Use the contains operator
3) Select a value that breaks to a new line
N/A
N/A
=> Wrap operators in quotes

.changeset/khaki-dolls-peel.md, sdk/client/src/listeners/first-load-listeners.tsx
Some external libraries (e.g. dynatrace) monkey patch `performance.clearResourceTimings()` to not clear the network resources, resulting in customers seeing duplicate network resources. Keep track of the last processed resource time, and filter out any resources before this time.
Before
After
1) Load main
2) Comment out the `performance.clearResourceTimings()` in `clearRecordedNetworkResources`
3) Complete a session for about a minute
4) View that sessions
5) Check out this branch
6) Complete a session for about a minute
7) View that sessions
=> Fix duplicate network requests

highlight.io/components/QuickstartContent/backend/php/shared-snippets.tsx
Original report from Arffeh viewed on discord.
Redirect link for the `logging setup guide` is broken on [this page](https://www.highlight.io/docs/getting-started/backend-sdk/php/other).
Checked that the new page redirection was working well
No
No
=> Fixed broken php log ingestion link 

backend/clickhouse/logs.go, backend/clickhouse/logs_test.go, backend/clickhouse/query.go, backend/clickhouse/traces.go, backend/clickhouse/traces_test.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, frontend/src/components/CustomColumnActions/index.tsx, frontend/src/components/CustomColumnHeader/index.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/pages/LogsPage/LogsTable/LogDetails.tsx, frontend/src/pages/Traces/TraceProvider.tsx, frontend/src/pages/Traces/TracesList.tsx, frontend/src/pages/Traces/TracesPage.tsx, frontend/src/pages/Traces/useGetTraces.ts, packages/ui/src/components/Table/Header/Header.tsx
This reverts commit 73d46ef992b844108101f294ab8927ce3e216163.
Believe this might be breaking fetching traces... It's working locally, but we're not seeing traces in the traces list in prod. Metrics are still loading, and the "X new traces" is still returning results sometimes 🤔
=> Revert "Allow users to sort traces (#8497)"

backend/parser/listener/listener.go, backend/parser/listener/listener_test.go
The `strconv.Unquote` is intended for use in cases where you are processing go source code, so there are some rough edges when trying to unquote a string passed in from the frontend. Mainly, it cannot parse `\d` or \w` and other regex expressions since they are not valid go escape keys.
Update the method to trim the quotes and replace any internal quotes with the non escaped version - like we previously did for single quotes `'`
https://www.loom.com/share/e30f51d823d541e0a78d194139b95a85?sid=c5f92a46-e7df-4709-a30a-12b648bd0649
1) Load one of the search experiences
2) Search with the `matches` operator
3) Add a search expression such as a number (`/n`) or word (`/w`) to the search within the quotes `"`
N/A
N/A
=> Fix unquoting queries with non escape characters

backend/clickhouse/logs.go, backend/clickhouse/logs_test.go, backend/clickhouse/migrations/000103_add_highlight_type_to_trace_sampling.down.sql, backend/clickhouse/migrations/000103_add_highlight_type_to_trace_sampling.up.sql, backend/clickhouse/query.go, backend/clickhouse/traces.go, backend/clickhouse/traces_test.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, frontend/src/components/CustomColumnActions/index.tsx, frontend/src/components/CustomColumnHeader/index.tsx, frontend/src/components/Search/SearchContext.tsx, frontend/src/components/Search/SearchForm/SearchForm.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/pages/LogsPage/LogsTable/LogDetails.tsx, frontend/src/pages/Traces/TraceProvider.tsx, frontend/src/pages/Traces/TracesList.tsx, frontend/src/pages/Traces/TracesPage.tsx, frontend/src/pages/Traces/useGetTraces.ts, packages/ui/src/components/Table/Header/Header.tsx
This PR reverts the revert of #8497 and introduces some fixes + improvements.
* We started using the `HighlightType` column rather than `TraceAttributes['highlight.type']` for default trace filters, which should provide a performance improvement.
* We only hit the sampling table for the inner query when selecting traces.
* Adds the sort param to the queries fetching additional results.
* Load the traces page and ensure results + stats in the top look correct
* Inspect SQL statements to ensure the `traces` table is being hit
* Click on a column header to sort results
* Ensure results are sorted correctly
* Inspect SQL and ensure the `traces_sampling` table is hit for the inner query and `traces` is hit for the outer query
* Ensure all other querying behavior works as expected, including …
=> Allow users to sort traces (take 2)

frontend/src/pages/Traces/TracesPage.tsx
Fixes an error we were seeing on the demo project when a user scrolls to the bottom and fetches more traces.
Tested scroll behavior in prod on the demo project in the PR preview and confirmed it worked as expected.
N/A
N/A
=> Fix error when fetching more traces on demo project

frontend/src/__generated/index.css, frontend/src/pages/Graphing/components/Graph.css.ts, frontend/src/pages/Graphing/components/Graph.tsx
- brings back the loading overlay, styles it similarly to the "No data found" badge
- continues to show old data while new data is loading
- no
=> [HIG-4638] revive loading overlay, show old data while loading

backend/stacktraces/enhancer.go, backend/stacktraces/enhancer_test.go, backend/stacktraces/test-files/1/version-a1b2c3/main.8344d167.chunk.js.map
* Fixes an issue in the versioned sourcemap processing version fallback logic that would not use the versioned sourcemap even if one was found in S3.
manual prod testing, new unit test
no
no
=> fix error enhancement for versioned sourcemaps

frontend/src/components/JsonViewer/utils.ts, frontend/src/components/Search/Parser/listener.ts
Fixes an error we were seeing when trying to parse an `EXISTS` or `NOT EXISTS` value on the `message` key of logs. Not sure what the use case was of this query, but we were [seeing a number of these errors](https://app.highlight.io/1/errors/TvTw1F1gtLqIwKV15U9Gh4ZDXCry/instances/269122414?referrer=slack).
* Load https://app.highlight.io/demo/logs?query=message%20EXISTS on prod - you should see the error boundry
* Load the same URL in the PR preview - it should load and render results correctly
N/A - client-side only bug fix
Nope!
=> Fix logs error when applying `message EXISTS` filter

frontend/src/pages/Traces/TraceFlameGraph.tsx
**Before**
**After**
* View the flame graph span tooltip on a span that has a long service name in prod - note the jankiness 😬
* View the same trace on the PR preview of this branch and config the jank is gone 🪄 
N/A
N/A
=> Allow flame graph tooltips to expand to width of content

frontend/src/__generated/index.css, frontend/src/__generated/ve/pages/Graphing/components/Table.css.js, frontend/src/components/Modal/ModalV2.tsx, frontend/src/pages/Graphing/Dashboard.tsx, frontend/src/pages/Graphing/GraphingEditor.tsx, frontend/src/pages/Graphing/components/Graph.css.ts, frontend/src/pages/Graphing/components/Graph.tsx, frontend/src/pages/Graphing/components/Table.css.ts, frontend/src/pages/Graphing/components/Table.tsx
- [HIG-4650] active_length already set up, but a small issue was causing tick markers to show the previous unit
- [HIG-4554] move legend below graphs
- [HIG-4546] make table scrollbar visible, add gutter to header and body
- [HIG-4490] use static-divider-weak color for editor background
- [HIG-4659] update modal z-index so it's on top of the header
- [HIG-4637] stop tooltip flickering in top left
- [SUP-12] add clone metric view option under graph menu
- clicktested w/ active_length, length, Jank
- no
- no
=> more dashboard polishing

frontend/src/index.css
fixes #8560 
/claim #8560
There was a class name conflict between two third party components 
1. react-command-pallette
2. react-syntax-highlighter
The react-command-pallete library comes with a default theme called "atom" that has a declaration for "atom-input"
This theme is imported whenever the react-command-pallete is used and was thus globally available.
Our graphql variable "Type" also has the class name atom-input and therefore inherits the global styling for the default
atom theme from the react-command-pallete component.
My proposed solution just overrides those styles by introducing a global declaration with higher specificity that
unsets the css declaration. I';ve seen similar done for the atom-overlay class.
This is imported as a global css by the library.
Click testing
No
No
=> fix: Formatted network request payload has weird formatting

backend/http/logging.go, backend/http/logging_test.go, backend/otel/otel.go, backend/public-graph/graph/resolver.go, backend/vercel/vercel_test.go, docs-content/getting-started/5_backend-logging/07_hosting/gcp.md, sdk/highlight-go/log/util.go, sdk/highlight-go/otel.go
* support arbitrary structured json logs ingestion from `/v1/logs/json`
* support ingesting log messages with no body but with attributes
* update gcp pub/sub example docs
new unit testing
no
no
=> support arbitrary structured json logs ingestion

.github/workflows/backend.yml, .github/workflows/deploy.yml, .github/workflows/docker.yml, .github/workflows/turbo.yml, backend/otel/otel.go, docker/backup_disk.xml, docker/compose.yml, docker/config.xml, docker/users.xml, e2e/tests/src/conftest.py, highlight.io/pages/customers/index.tsx, scripts/get_github_security.py, sdk/highlight-go/log/logrus.go, sdk/highlight-go/otel.go
Switch to github code build runners to avoid using AWS secrets to set up credentials.
Skip `highlight.go.log` spans from ingest to avoid recursive highlight app trace ingest.
Fix highlight.io customer testimonial sorting.
Closes SUP-33
https://github.com/highlight/highlight/actions/runs/9121209141/job/25079992204
will monitor main merge / deploy
no
=> use github code build runners

frontend/src/components/FeedResults/FeedResults.tsx, frontend/src/components/Search/SearchContext.tsx, frontend/src/pages/ErrorsV2/ErrorsV2.tsx, frontend/src/pages/ErrorsV2/SearchPanel/SearchPanel.tsx, frontend/src/pages/ErrorsV2/useGetErrors.ts, frontend/src/pages/LogsPage/LogsPage.tsx, frontend/src/pages/LogsPage/LogsTable/LogsTable.tsx, frontend/src/pages/LogsPage/useGetLogs.ts, frontend/src/pages/Player/PlayerPage.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionsFeedV3.tsx, frontend/src/pages/Sessions/useGetSessions.ts, frontend/src/pages/Traces/TracesList.tsx, frontend/src/pages/Traces/TracesPage.tsx, frontend/src/pages/Traces/useGetTraces.ts, frontend/src/util/search.ts, yarn.lock
- stop polling after 15 mins
- set a `pollingExpired` variable, show "load more results" after this time has passed
- clicktested locally w/ shorter polling expiry time
- no
- no
=> stop polling for more resources after 15 mins

frontend/src/pages/Graphing/components/Graph.tsx
- Previously, tooltips returned null if there was no data at a point. This was changed to fix a flickering issue, but certain inputs started crashing. Don't call getTickFormatter for these points as the `value` to format may be undefined.
- also fix `isEmpty` check so loading state doesn't have grey lines displayed
- clicktested locally with crash scenario
- no
- no
=> fix dashboard crash for tooltip for invalid point

frontend/src/pages/Traces/TracesPage.tsx
It doesn't make sense to fetch additional results when we are sorting traces by anything other than the default (timestamp desc), so disable it when a user is sorting on a column.
* View `GetTraces` queries happening in the background after loading the traces page
* Sort traces by clicking one of the column headers
* Confirm there are no additional `GetTraces` queries after the initial one
N/A - should only reduce the number of queries we are sending to fetch traces.
N/A
=> Disable polling if traces are sorted

frontend/src/pages/Player/PlayerHook/PlayerHook.tsx
When autoplay moves to the next session, it clears the search params. Redirect to the correct url with the search params.
https://www.loom.com/share/fb1a8752396e407ea7465b1c2963e2ce?sid=cbd6ec84-4cf9-4969-86b9-ebd4687d22fc
1) View the sessions page
2) Add a filter
3) Make sure autoplay sessions is on
4) Play a session
N/A
N/A
=> Fix autoplay redirect

frontend/src/components/Loading/Loading.tsx
As reported by a customer over discord,
Loading page would use `motion` to update CSS of the elements even when the page is not rendered.
reflame
=> avoid rendering css animation when loading page is hidden

backend/email/email.go, backend/model/model.go, backend/pricing/pricing.go, backend/public-graph/graph/resolver.go, backend/worker/worker_test.go
Send billing notifications per product for overage charges. 
For example, when `sessions` hit a monthly overage for the first time for a workspace,
notify the workspace admins about upcoming charges.
TODO
no
no
=> send billing notifications on new overage charges

.changeset/healthy-buckets-battle.md, .github/workflows/turbo.yml, backend/worker/worker.go, cypress/pages/local.html, e2e/nextjs/src/app/components/random.tsx, e2e/nextjs/src/app/page.tsx, e2e/tests/src/conftest.py, e2e/tests/src/test_cypress.py, e2e/tests/src/test_oauth_graphql.py, e2e/tests/src/test_sdk.py, e2e/tests/src/util.py, scripts/migrations/init.sql, sdk/client/src/constants/sessions.ts, sdk/client/src/index.tsx, sdk/client/src/listeners/network-listener/network-listener.ts, sdk/client/src/listeners/network-listener/utils/fetch-listener.ts, sdk/client/src/listeners/network-listener/utils/models.ts, sdk/client/src/listeners/network-listener/utils/utils.ts, sdk/client/src/listeners/network-listener/utils/xhr-listener.ts, sdk/client/src/types/types.ts, sdk/client/src/utils/graph.ts, sdk/client/src/utils/sessionStorage/highlightSession.ts, sdk/client/src/workers/highlight-client-worker.ts, sdk/client/src/workers/types.ts, sdk/firstload/src/index.tsx, sdk/firstload/src/listeners/web-socket/index.ts
* fixes client retry logic that caused the client to never retry on error
* removes isbeacon logic as it wasn't clear it was doing anything
* fixes session boundary (on 4 hour reset) not resetting `_sid`
* fixes session boundary (on 4 hour reset) not sending right session id in `x-highlight-request`
adds new e2e test that validates cypress session
manual testing of `onHighlightReady`
testing for memory leaks with loop recording large network requests
validating network request headers after session restart (locally changing 4 hour reset to 30 seconds)
changeset
no
=> make browser sdk more robust to avoid broken sessions

frontend/src/pages/Player/Toolbar/DevToolsWindowV2/DevToolsWindowV2.tsx
The search input should be aligned with the magnifying glass
1) View a session
2) Open the dev console and view the logs
N/A
N/A
=> Fix search input alignment

backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go, frontend/src/util/graph.tsx
Cleans up old cache policies that cause flicker on feeds.
Reflame
no
no
=> remove unnecessary apollo caching policies

scripts/migrations/init.sql, sdk/highlightinc-highlight-datasource/docker-compose.yaml, sdk/highlightinc-highlight-datasource/pkg/plugin/datasource.go, sdk/highlightinc-highlight-datasource/src/datasource.ts
Make the following grafana improvements:
- easier to start locally
- use refId for frame name to allow multiple frames
- support IN clauses with variables
https://www.loom.com/share/7a6112555c824b72a9762e05a24f3aa6?sid=f4207067-548d-44e2-b89b-3083cf550993
1) Go to an edit graph view
2) Open the query inspector and refresh the query
3) Add a multiple value variable
4) Add that value to a query i.e. `email=$foo`
N/A
N/A
=> Grafana improvements

frontend/src/pages/Billing/BillingPageV2.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionFeedCard/SessionFeedCard.tsx
* fixes billing history graphs not loading for active subscriptions
* fixes date ranges for each par on the billing history graphs
* adds a `daily` option to the billing history graphs
* fixes tooltip styling on sessions feed and on billing page
reflame billing page, session feed
no
yes
=> cleanup billing history graphs ranges and tooltips

backend/clickhouse/logs.go, backend/clickhouse/logs_test.go
Update the backend to fetch have all the log columns available for graph - this is needed to replace the console log table with the logs table in https://github.com/highlight/highlight/pull/8696
Want to get this in separately to test frontend performance 
1. Load a session
N/A
N/A
=> Console logs table backend

backend/email/email.go, backend/pricing/pricing.go, frontend/package.json, frontend/src/App.css, frontend/src/__generated/index.css, frontend/src/__generated/ve/components/CalendlyModal/styles.css.js, frontend/src/components/CalendlyModal/CalendlyModal.tsx, frontend/src/components/CalendlyModal/styles.css.ts, frontend/src/components/Header/Header.tsx, frontend/src/components/Header/useBillingHook.tsx, yarn.lock
Adds a `Book a call` button (primary for trial customers, secondary for others) that displays the calendly modal.
Closes HIG-4699
[reflame](https://app.highlight.io/1/sessions?%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201HXZFPY7SMRRDHXVM7QRFZA80%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22vadim%2Fenterprise-call%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D)
no
yes
=> add calendly modal to main app

backend/main.go
- Highlight doesn't use credentials for public graph requests, but we should not allow credentials in case this changes in future
- move cors configs within the public and private routers only - I don't think it's necessary to use cors on other routes (`/health`, `/otel`) and we should probably have separate public/private configs for hobby deploys too rather than using a single one for the `All` runtime - @Vadman97 can you confirm this last bullet point?
- clicktested locally to confirm functionality was working properly, tested cross-origin requests
- no
- no
=> [SUP-27] cors config updates

backend/main.go
- CORS was breaking for `ADMIN_PASSWORD` auth because the handler was defined outside the `r.Route` function that applied the CORS config
- tested locally w/ `ADMIN_PASSWORD` auth enabled, validated problem before, fix after. will confirm cypress test passes
- no
- no
=> move ADMIN_PASSWORD auth handler inside route

backend/model/model.go
Updates session_intervals model to `bigint` now that the `id` column is migrated in prod.
N/A
no
no
=> update session_intervals to bigint

backend/main.go, deploy/private-graph-task.json
Update private graph cors to allow all highlight.io subdomains.
CI
local deploy
no
no
=> update private graph CORS origins

frontend/src/__generated/index.css, frontend/src/pages/Alerts/components/AlertTitleField/AlertTitleField.tsx, frontend/src/pages/Alerts/components/AlertTitleField/styles.css.ts, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/DevToolsWindowV2.tsx, frontend/src/pages/Player/components/EventStreamV2/EventStreamV2.tsx
Fix the following inputs to be full length and aligned to the left
- search bar in dev tools
- search bar in session events
- alert titles
1) View a session
2) Create a new alert
N/A
N/A
=> Fix search input length

.reflame.config.jsonc, e2e/react-router/package.json, e2e/react-three-vite/package.json, frontend/package.json, frontend/src/pages/Auth/Firebase.tsx, frontend/src/pages/Auth/SignUp.tsx, frontend/src/routers/AppRouter/AppRouter.tsx, frontend/src/util/auth.tsx, packages/ui/package.json, sdk/client/package.json, sdk/firstload/package.json, yarn.lock
adds a new `/auth/action` endpoint to the frontend which performs firebase auth based on their callbacks.
this will allow us to update our firebase config to use app.highlight.io with our styling for auth requests
such as resetting password, recovering email, and verifying email, rather than using the firebase hosted app.
Closes SUP-29
manual local testing with firebase token from prod
https://www.loom.com/share/739d8020915c45b3a9d90a7aa5e0c26f
update https://console.firebase.google.com/u/1/project/highlight-f5c5b/authentication/emails?pli=1 to app.highlight.io once released
no
=> support a custom callback endpoint for firebase

backend/private-graph/graph/resolver_test.go, backend/private-graph/graph/schema.resolvers.go
- fix issue where the project dropdown for other workspaces was empty for super users
- attempted fix for test flakiness https://github.com/highlight/highlight/actions/runs/9407237601/job/25912686105?pr=8722#step:5:836 
- only the tests involving the demo project were failing - there's another test which can set a different project id so I think if that test runs first it was causing this test to fail. explicitly set `DEMO_PROJECT_ID = 0` to avoid that
- no
- no
=> [HIG-4723] return all projects in workspace for super users

docs-content/sdk/cloudflare.md
There seemed to be 2 issues with the snippet for `sendResponse` on the Cloudflare SDK documentation.
1. `return` when creating the response would prevent any following code from running
2. The function signature for `sendResponse` only takes in one argument, the response object. Not all 4 arguments being passed in the snippet.
From index.d.ts:
```ts
interface HighlightInterface {
init: (request: Request, env: HighlightEnv, ctx: ExecutionContext, service?: string) => WorkersSDK;
isInitialized: () => boolean;
consumeError: (error: Error) => void;
sendResponse: (response: Response) => void;
setAttributes: (attributes: ResourceAttributes) => void;
recordMetric: (metric: Metric) => void;
}
```
This is a documentation change, so no testing was done. Please verify as you can.
No migration or …
=> update sendResponse snippet in cloudflare sdk documentation

backend/private-graph/graph/schema.resolvers.go, frontend/src/routers/ProjectRouter/ProjectRouter.tsx
- return a default workspace id when the user is unauthenticated or not in the project
- use `errorPolicy: 'all'` so `joinable_workspaces` is available even though other resolvers (`project` and `workspace`) throw an authentication error
- clicktested unauthenticated and auto-join use cases locally
- no
- no
=> [SUP-52] ensure unauthed users don't get a NPE, fix join workflow

backend/clickhouse/migrations/000104_update_session_attributes.down.sql, backend/clickhouse/migrations/000104_update_session_attributes.up.sql, backend/clickhouse/sessions.go, backend/model/model.go, backend/parser/listener/listener.go
We're received recent report that our session search is not returning all attributes.
This was also visible from experimentation with new metric graphs where sessions
were not being returned.
The issue was that multiple values for a single attribute would not be shown (we would
build a map with only one of the values, picking one arbitrarily).
Converts the approach to using an array of attribute KV pairs, and searching across that
array for possible matches.
https://www.loom.com/share/b97f3ed97ca74b1da708bd20f5e185e2
no
no
=> fix session attribute search

frontend/src/pages/LogsPage/LogsPage.tsx, frontend/src/pages/LogsPage/LogsTable/LogsTable.tsx
Improve performance of logs table by:
- conditionally matchedAttributes attributes
- limit rerenders by reducing changes in `columnData`'s dependency array
1) View the logs table
2) Open the dev tools and start recording the performance
3) Scroll down a few pages
4) Open a logs row
5) Scroll down a few pages
N/A
N/A
=> Improve logs table performance

backend/main.go
- public graph used `NewDefaultServer` which configured introspection by default
- use `New` instead and configure it the same, minus introspection
- sent introspection gql request to public graph locally, got `introspection disabled` response
- no
=> disable introspection for public graph

sdk/highlight-go/log/console_messages_parser.go
- public graph deployment error since Friday - from the logs it appears to be caused by a nil map reference here:
https://github.com/highlight/highlight/commit/072137b69b7dfee81aca288cdaed5c4d621f8aac#diff-1e34df331d996d37ce29f5f628641b29174beec6e2e2a4a3b84bf21fa39598d2R53
- I think this code is supposed to use `msg` instead of `message`
- ensured logs / traces were still working locally
- no, will monitor public graph deploy
- no
=> fix public graph deployment issue

backend/alerts/logalerts.go, backend/alerts/sessionalerts.go, backend/clickhouse/migrations/000105_create_alert_state_changes_table.down.sql, backend/clickhouse/migrations/000105_create_alert_state_changes_table.up.sql, backend/migrations/cmd/alert-ids/main.go, backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver.go, backend/temp-alerts/temp-alerts.go, backend/worker/worker.go, frontend/src/graph/generated/schemas.tsx
Add the following tables to production:
- Alert (Postgres)
- AlertDestination (Postgres)
- AlertStateChange (Clickhouse)
More info: https://www.notion.so/runhighlight/Metric-Alerts-7b3080a13d8347c296cc263ad30e0b8c
1) Able to build backend
2) Can create/edit/delete/fire alert
Not used in production
N/A
=> Create new metric alert tables

frontend/src/pages/Graphing/components/Graph.tsx
- round to nearest 5 minutes when time range >= 4 hours to limit refetching when time range is likely a fraction of a bucket and improve the experience when navigating between pages as data doesn't have to be reloaded 
- testing in preview
- no
- no
=> [HIG-4714] longer rounding for longer time intervals for better caching

backend/clickhouse/query.go, backend/parser/listener/listener.go
`SessionAttributePairs` was not being used correctly for session metrics graphs, breaking the
`visited-url` chart in the default dashboard as well as other session attributes charts.
A consideration is still how we should process attributes with multiple values.
no
no
=> correctly process SessionAtrributes array in metrics

frontend/src/pages/LogsPage/LogsPage.tsx
Using the `query` and `queryParts` from the `SearchContext` is not the same as using the `useQueryParam` as the query changes with each keystroke, resulting in lots of searches.
Revert this change back
1) View the logs
2) Start typing in the search box
N/A
N/A
=> Bug fix - Reduce log searches

backend/clickhouse/errors.go, backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/ErrorsV2/ErrorFeedCard/ErrorFeedCard.tsx
The error groups are not setting the correct first and last instances
On search:
- First instance: `ErrorGroup.CreatedAt` -> min `ErrorObject.Timestamp`
- Last instance:  `ErrorGroup.UpdatedAt` -> max `ErrorObject.Timestamp`
On detail page
- First instance: missing -> min `ErrorObject.Timestamp`
- Last instance: missing -> max `ErrorObject.Timestamp`
https://www.loom.com/share/ec0409905c224529b5a642ea3ea9f489?sid=91e0bd44-7c9f-4b34-947d-4328dae80203
1) View the error search page
2) View the dates on the search card
3) Click into an error
Watch performance of `ErrorGroups` graphql query
N/A
=> Fix error group instances

backend/private-graph/graph/schema.resolvers.go
- the superadmin branch returns early, make sure default retention is set before that returns (graphql schema now enforces non-null retention)
- clicktesting locally
- no
- no
=> ensure retention set when super admin

backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/schemas.tsx
Add the following graphql queries and mutations:
- `createAlert` - create an alert with params
- `updateAlert` - update an alert with provided params
- `updateAlertDisabled` - update the disabled field of the alert
- `deleteAlert` - delete alert and destinations
- `alerts` - fetch alerts by project
- `alert` - fetch alert by id
- `alert_state_changes` - fetch state changes of an alert by alert id
TODOs will be addressed in the following cards:
- [Add destination creation](https://linear.app/highlight/issue/HIG-4746/allow-adding-of-destinations)
- [Send destination messages](https://linear.app/highlight/issue/HIG-4747/send-destinations-message-when-destination-is-createddeleted)
- [Fetch alert state changes](https://linear.app/highlight/issue/HIG-4749/add-alert-state-changes-to-alert-detail …
=> Add new alert queries and mutations

frontend/src/__generated/index.css, frontend/src/pages/Graphing/components/BarChart.tsx, frontend/src/pages/Graphing/components/Graph.css.ts, frontend/src/pages/Graphing/components/Graph.tsx, frontend/src/pages/Graphing/components/LineChart.tsx, frontend/src/pages/LogsPage/LogsHistogram/LogsHistogram.tsx
- remove the "verbose" tooltip option and always show the key in the tooltip, styled with a max width to avoid tooltip from becoming too large
- no
=> [HIG-4752] make verbose tooltips the default

backend/kafka-queue/kafkaqueue.go, deploy/public-worker-main-service.json
Had some OOming earlier in the week due to the main worker prefetching a lot of large messages.
Recently switched to r7g ec2 boxes as they are cheaper with spot instances than m7g 
which also have more memory per CPU, so adjusting the worker memory allocation accordingly.
deployed to prod manually which helped
no
no
=> update kafka settings to prevent OOM

frontend/src/components/Comment/utils/utils.ts
When clicking on a comment in the session, the search params are wiped out. Fix this to append the search params
1. Add a search param to the session search
2. Create a comment on a session
3. Click on the comment in the right panel
N/A
N/A
=> Fix comment link

frontend/src/pages/Graphing/components/Graph.tsx
- fixes grouping key logic by showing `<empty>` tag when results are grouped but that group is the empty string
- falls back to metric name only when results are not grouped
- tested in preview env
https://www.loom.com/share/4f2fb97b05d3411b959a0d7c393bb156
- no
- no
=> [HIG-4751] show <empty> for empty groups, fall back to metric name only when not grouped

frontend/src/pages/Player/PlayerHook/PlayerHook.tsx, frontend/src/pages/Player/PlayerHook/PlayerState.ts, frontend/src/pages/Player/ReplayerContext/index.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ConsolePage/ConsolePage.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ErrorsPage/ErrorsPage.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/NetworkPage/NetworkPage.tsx, frontend/src/pages/Player/Toolbar/TimelineIndicators/TimelinePopover/TimelinePopover.tsx, frontend/src/pages/Player/components/EventStreamV2/EventStreamV2.tsx, frontend/src/pages/Player/components/EventStreamV2/StreamEventV2/StreamEventV2.tsx
The events on a session are not scrolling correctly.
Update the algorithm to use a time based search, similar to logs, errors and network resources. Add a throttle for each of these resources to limit the browser computations.
https://www.loom.com/share/4b88dd5d7e2a44238a6ba27b9688561e?sid=86b4665b-84e7-4274-89a4-bb7333f82000
1. View a session
2. View the events
N/A
N/A
=> Fix events autoscrolling jumping around

frontend/src/pages/Sessions/useGetSessions.ts
We are seeing an issue where new sessions aren't appearing in the feed because of some logic we added to help with showing cached results immediately on page load. This fixes the issue by extending the end date time into the future before subtracting from it for rounding. We only do this when the user is trying to show real time results.
Click tested and checked the values using a debugger when using a fixed time and a relative time.
N/A
N/A
=> Ensure session feed query pulls in the latest sessions

frontend/src/pages/Graphing/GraphingEditor.tsx
/claim #8580 
/fixes #8580 
Group by options duplications were handled in the graph editor session
https://www.loom.com/share/c9c9b2e8be2745f898ec9d48cb61da01
=> fix:group by options duplication issue is fixed

backend/clickhouse/traces.go, backend/worker/kafka_worker.go
Having some trouble figuring out where messages may or may not have been drop, so add logging to help ensure everything is moving smoothly. Also change the kafka batch working resource to be the span name to help with optimized search.
1. Ensure logs and traces can be seen locally
Come back and clean up logs after debugging if appropriate
N/A
=> Additional logging and tracing for batch kafka workers

backend/clickhouse/traces.go, backend/otel/extract.go, backend/otel/otel.go, backend/parser/parser.go, backend/public-graph/graph/resolver.go, frontend/src/components/CustomColumnPopover/index.tsx, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/Traces/CustomColumns/accessors.ts, frontend/src/pages/Traces/CustomColumns/columns.ts, frontend/src/pages/Traces/CustomColumns/renderers.tsx, frontend/src/pages/Traces/TracesList.tsx, frontend/src/pages/Traces/utils.ts
Supports visualizing trace `metric.name` events as custom trace attributes
for visualizing metrics coming out of a session, such as web vitals of viewport size.
This allows searching for sessions where a given metric value is set.
Closes HIG-4575
no
no
=> support visualizing custom trace events

backend/worker/kafka_worker.go
Fixes panic from main when no batched queue messages are to be flushed.
Local deploy
no
no
=> fixup! Additional logging and tracing for batch kafka workers (#8832)

backend/otel/extract.go, backend/otel/otel.go, backend/otel/otel_test.go, backend/otel/samples/log.json, deploy/otel-collector.yaml, docker/collector.yml, sdk/highlight-go/otel.go
Adds support for OTLP HTTP header `x-highlight-project` for setting the highlight project
ID for data sent by a given opentelemetry collector.
Allows integration with Traceloop as documented in https://github.com/traceloop/docs/pull/33
unit test
no
no
=> support collector OTLP header authentication

backend/kafka-queue/kafkaqueue.go, backend/main.go, backend/public-graph/graph/resolver_test.go, backend/store/error_groups.go, backend/store/error_groups_test.go, backend/worker/autoresolver.go, backend/worker/autoresolver_test.go
Testing a hypothesis that autoresolver error group updates may be
missing from clickhouse because we were writing to the datasync queue
async and not waiting for a batched write flush. This is particularly noticeable
with the autoresolver where the job would run one-off and not
wait for the datasync queue write to complete.
deploying to prod
no
no
=> fix datasync queue

frontend/src/pages/Billing/BillingPageV2.tsx
Billing page was incorrectly showing included number of resources.
before
after
no
no
=> update billing page included counts

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, frontend/src/graph/generated/schemas.tsx, frontend/src/pages/Player/SessionView.tsx
- some of the newer exclusion reasons would show the default "session does not exist or has not been made public" error, which is confusing when a user gets linked to an excluded session e.g. from an alert
- update the logic to have all exclusion types
- relax `payload_updated_at` not-null requirement as some of these sessions do not have this set (e.g. if no events)
- no
=> HIG-4768 add new session exclusion reasons to ui

turbo.json
When running the app via `yarn dev:frontend` we rebuild the `highlight.io` package every time because we have `cache: false` set for the `dev` task. However, the contents of this package don't change often and it's not even a critical part of the main app. This PR sets `cache: true` for the `highlight.io#build` step which allows the cache to be hit and save a lot of time starting up the app locally.
Ran a `dev:frontend` build with and without the setting. Confirmed that with caching enabled the cache was leveraged locally and the time to start up the app was much faster.
No, I don't believe so. I think the cache is not leveraged in CI, so this only impacts local builds.
N/A
=> Enable caching for highlight.io#build

frontend/src/components/Header/Header.tsx, frontend/src/hooks/useFeatureFlag/useFeatureFlag.ts, frontend/src/pages/LogsPage/LogsPage.tsx, frontend/src/pages/Player/RightPlayerPanel/components/Tabs/index.tsx
Clean up the feature flags that are no longer used:
- `Feature.HistogramTimelineV2`: not references
- `Feature.AiSessionInsights`: ramped up to 100% for over a year
- `Feature.Analytics`: pages no longer exist
Add the following feature toggles:
- `Feature.AiQueryBuilder`: turns on logs query builder (only Highlight enabled)
- `Feature.MetricAlerts`: turns on new alerts page (no workspaces)
1. Builds successful
2. No links for Analytics and Dashboards for relevant projects
3. AiSessionInsights still works
N/A
N/A
=> Clean up feature flags

backend/clickhouse/migrations/000106_update_session_attributtes.down.sql, backend/clickhouse/migrations/000106_update_session_attributtes.up.sql
As reported by a customer, session attributes with a `_` in the value would
work because the `SessionAttributePairs` mv would incorrectly index them.
Locally testing new SQL migration against prod.
`select
arrayFilter((k, v) -> v like '%\_%', SessionAttributePairs)
from sessions_joined_vw;`
no
no
=> update session attributes to work for values with _

e2e/python/highlight_fastapi/main_2.py, sdk/highlight-py/highlight_io/sdk.py, sdk/highlight-py/pyproject.toml
- we fail to send logs to Highlight in FastAPI background tasks with our `FastAPIMiddleware` because the current span has ended (the request returned before the background task started)
- one workaround implemented here is to create a new span in the `LogRecordFactory` if the current span has stopped recording
- it also works to remove the `is_recording` check in the log hook - unsure if this causes issues elsewhere
closes #8827
- used e2e test to validate background task's logs were sent
- no
- no
=> [SUP-63] fix logging from background tasks

frontend/src/__generated/index.css, frontend/src/components/Search/SearchForm/AiSearch/index.tsx, frontend/src/components/Search/SearchForm/AiSearch/style.css.ts
Make the following UI updates to Harold:
1) Navigate to the logs page
2) When typing in a generated query ensure each of the following check points above is satisfied
N/A
N/A
=> Harold UI improvements

.changeset/witty-parents-relax.md, sdk/client/src/index.tsx, sdk/client/src/listeners/viewport-resize-listener.tsx, sdk/client/src/types/client.ts, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts, sdk/highlight-next/CHANGELOG.md, sdk/highlight-next/package.json, sdk/highlight-remix/CHANGELOG.md, sdk/highlight-remix/package.json
Adds `window.screen` metrics to the reported session metadata to report
full monitor size in addition to the window size.
local
changeset
no
=> report client screen size

backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/schemas.tsx
Make the following updates to the backend mutations/queries
- add `MetricId` and `FunctionColumn` to alert table
- change int `ThresholdCount` to float `ThresholdValue`
- Remove `disabled` var from create/update mutations
- Update `MetricId` when ever alert is updated
- Allow all fields to overwrite to null value
Test the create/update queries in postman
N/A
N/A
=> Update alert backend queries and mutations

backend/clickhouse/alerts.go, backend/jobs/metric-alerts/metric-alerts.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, frontend/src/graph/generated/schemas.tsx
- for the given alert id, load the last timestamp where that alert had fired for each groupbykey
- when evaluating the alert, check that the current time is greater than the last alert's time + cooldown period
- adds a new alerting state `AlertingSilently` to signify that it's still in an alert state but had not notified
- clicktested locally with a 120s cooldown period set:
- no
- no
=> [HIG-4777] cooldown logic for alerts

backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go
- heroku log drain integration was:
1. showing up as not integrated even after integrating due to a backend error
2. not being deleted as our api was making the assumption that it had to have a `integration_workspace_mapping`
- clicktested locally by adding / removing integration
- notify user in Discord after deployment
- no
=> [SUP-70] fix setup for heroku integration

frontend/src/pages/Player/PlayerPage.tsx, frontend/src/pages/Sessions/useGetSessions.ts
Session search researches after 10 seconds when the endDate is no longer near now - use the selectedPreset to determine time to add to the endDate.
1. View the sessions page
N/A
N/A
=> Fix re-searching sessions

.changeset/tiny-squids-raise.md, sdk/client/src/index.tsx, sdk/client/src/types/types.ts, sdk/client/src/utils/utils.ts, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts, sdk/highlight-next/CHANGELOG.md, sdk/highlight-next/package.json, sdk/highlight-remix/CHANGELOG.md, sdk/highlight-remix/package.json
- safari does not support the `image/webp` format and silently falls back to png, which uses ~10x as much data since it's lossless
- this change detects if the browser supports webp, and if not, uses jpeg at .6 quality to approximate the same size payload
- also adds a `H.init` option to override the format and quality settings
- clicktested in chrome / safari on `debug/canvas` page, monitored pushpayload size
- publish via changesets
- no
=> [SUP-71] fallback to jpeg dataurl when webp not supported

backend/otel/otel.go
Ruby SDK produces multiple span events resulting in duplicate exceptions being recorded.
Prod deploy monitoring customer project.
no, will debug why this is an issue only with ruby sdk
no
=> avoid processing multiple ruby span events

docker/frontend-entrypoint.py, frontend/src/util/auth.tsx
- `frontend-entrypoint` should replace env variables that were set during the frontend build - this wasn't happening because the released docker builds have production values instead of dev ones
- the `AUTH_MODE` checks were being inlined by rollup? - fix that by using a switch statement because rollup doesn't seem to touch that
- ran `doppler -c prod_aws run -- yarn build` and `python frontend-entrypoint.py` locally to validate that a `constants` file was created with all 4 variables and that all 4 were replaced
- will test this PR's docker image once it's built 
- will publish a new docker image after deploying
- no
=> [SUP-72] fix env replacements

backend/private-graph/graph/resolver.go
- for certain customers, calling this api without archived channels caused too many api requests and we were hitting a rate limit
- doesn't make sense to have a lot of spam from archived channels anyway
- clicktested locally, confirmed slack integration was working normally
- will validate customer issue after deployment
- no
=> [SUP-73] exclude archived slack channels

backend/private-graph/graph/schema.resolvers.go
Recent changes in #7909 mock the stripe client to make it possible to not use it, but some
places in our code still depend on the return value not being nil.
Local deploy (hobby mode) successfully creating a workspace
no
no
=> fix stripe issue breaking workspace creation on local deploy

frontend/src/pages/Graphing/components/BarChart.tsx
- removes the `maxBarSize` property so bar charts with a small number of buckets / groups will use more space
- no
=> [HIG-4781] remove max size from bar charts

backend/event-parse/parse.go, backend/store/project_assets.go
Ensure cached project asset transform is returned for the correct set of arguments.
New log entry
no
no
=> fix asset storage colision returning incorrect project asset transform

.changeset/small-peas-knock.md, sdk/client/src/index.tsx, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts, sdk/highlight-next/CHANGELOG.md, sdk/highlight-next/package.json, sdk/highlight-remix/CHANGELOG.md, sdk/highlight-remix/package.json
- looks like some earlier refactoring broke iframe recording - the child iframe would wait indefinitely for a message from the parent as `this._recordStop` was always true
- set up cross-origin iframe recording locally, validated issue before / fixed after
https://www.loom.com/share/142e5b5fd764453fb6691b86315b4895
- will release new client version w/ changeset
- no
=> fix cross-origin iframe parent recording start

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/__generated/index.css, frontend/src/__generated/ve/pages/Alerts/DestinationInput/styles.css.js, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/mutation.gql, frontend/src/graph/operators/query.gql, frontend/src/pages/Alerts/AlertForm/index.tsx, frontend/src/pages/Alerts/Alerts.tsx, frontend/src/pages/Alerts/DestinationInput/index.tsx, frontend/src/pages/Alerts/DestinationInput/styles.css.ts
Allow the alert form to add different destinations for the alert to be sent.
https://www.loom.com/share/b2c86216ea904ee6b8190af7f58bd797?sid=ad135e28-18ae-4166-93ab-a1c47e00749b
1) Create an alert
2) Add a destination before saving
3) Update the alert
4) Update the destination
5) Delete alert
N/A
N/A
=> Add destinations to alert form

frontend/src/__generated/index.css, frontend/src/__generated/ve/pages/Graphing/OptionDropdown/styles.css.js, frontend/src/pages/Graphing/OptionDropdown/index.tsx, frontend/src/pages/Graphing/OptionDropdown/styles.css.ts
If their are too many options for the option dropdown, it is impossible to reach some of them. Make it scrollable.
https://www.loom.com/share/9fb0d4b33fe84a4690fa82b9c2dfcfff?sid=4939ed20-3e76-4890-bc68-34d67a3a7bb8
1. View the new alert form (`/alerts/new`)
2. Click of alert frequency
N/A
N/A
=> Fix option dropdown scroll

backend/public-graph/graph/resolver.go
- seems that the http://geolocation-db.com website is down, use a shorter timeout to avoid initialize session taking so long
- testing initialize session locally to make sure sessions are still created
- will monitor backlog in prod after deployment
- no
=> use timeout for geolocation call

sdk/client/src/otel/index.ts, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts
The `PerformanceResourceTiming` events we get from `DocumentLoadInstrumentation` are reported in milliseconds while the other performance events are in nanoseconds. This PR converts ms => ns.
Also updates the span name for GraphQL requests from `${operation} (GraphQL ${pathname})` to `${operation} (GraphQL ${host + pathname})` which fixes the display of our span from `GetLogsIntegration (GraphQL: /)` to `GetLogsIntegration (GraphQL: pri.highlight.io/)`.
Rebuilt the SDK and click tested locally to ensure the changes look good.
N/A -> should only fix a minor issue with data reported from our SDKs.
N/A
=> Report resource timings in nanoseconds

backend/private-graph/graph/resolver.go
- restrict other common email domains in auto-join logic
- this is just a config change
- no
- no
=> add other common emails to denylist

backend/alerts/v2/alerts.go, backend/alerts/v2/destinations/destinations.go, backend/alerts/v2/destinations/discord/messages.go, backend/alerts/v2/destinations/email/messages.go, backend/alerts/v2/destinations/microsoft-teams/messages.go, backend/alerts/v2/destinations/slack/messages.go, backend/lambda/lambda.go, packages/react-email-templates/emails/errors-alert-v2.tsx, packages/react-email-templates/emails/index.tsx, packages/react-email-templates/emails/logs-alert-v2.tsx, packages/react-email-templates/emails/metrics-alert-v2.tsx, packages/react-email-templates/emails/sessions-alert-v2.tsx, packages/react-email-templates/emails/traces-alert-v2.tsx, packages/react-email-templates/src/index.ts
Start sending new alerts to emails
1) Create a new alert for each product type
2) Add an email channel for each alert
N/A
N/A
=> Start sending email alerts

backend/alerts/v2/alerts.go, backend/alerts/v2/destinations/destinations.go, backend/alerts/v2/destinations/discord/messages.go, backend/alerts/v2/destinations/email/messages.go, backend/alerts/v2/destinations/microsoft-teams/messages.go, backend/alerts/v2/destinations/slack/messages.go, backend/alerts/v2/destinations/webhook/messages.go, backend/lambda/lambda.go, backend/model/model.go, packages/react-email-templates/emails/errors-alert-v2.tsx, packages/react-email-templates/emails/index.tsx, packages/react-email-templates/emails/logs-alert-v2.tsx, packages/react-email-templates/emails/metrics-alert-v2.tsx, packages/react-email-templates/emails/sessions-alert-v2.tsx, packages/react-email-templates/emails/traces-alert-v2.tsx, packages/react-email-templates/src/index.ts
Start sending new alerts to webhooks
1) Create a new alert for each product type
2) Add a webhook channel for each alert
N/A
N/A
=> Start sending webhook alerts

backend/alerts/v2/alerts.go, backend/alerts/v2/destinations/destinations.go, backend/alerts/v2/destinations/discord/messages.go, backend/alerts/v2/destinations/email/messages.go, backend/alerts/v2/destinations/microsoft-teams/messages.go, backend/alerts/v2/destinations/microsoft-teams/templates/error-alert.go, backend/alerts/v2/destinations/microsoft-teams/templates/log-alert.go, backend/alerts/v2/destinations/microsoft-teams/templates/metric-alert.go, backend/alerts/v2/destinations/microsoft-teams/templates/session-alert.go, backend/alerts/v2/destinations/microsoft-teams/templates/trace-alert.go, backend/alerts/v2/destinations/slack/messages.go, backend/alerts/v2/destinations/webhook/messages.go, backend/lambda/lambda.go, backend/model/model.go, frontend/src/pages/Alerts/Alerts.tsx, packages/react-email-templates/emails/errors-alert-v2.tsx, packages/react-email-templates/emails/index.tsx, packages/react-email-templates/emails/logs-alert-v2.tsx, packages/react-email-templates/emails/metrics-alert-v2.tsx, packages/react-email-templates/emails/sessions-alert-v2.tsx, packages/react-email-templates/emails/traces-alert-v2.tsx, packages/react-email-templates/src/index.ts
Start sending new alerts to microsoft teams
1) Create a new alert for each product type
2) Add a microsoft team channel for each alert
N/A
N/A
=> Start sending new alerts to microsoft teams

backend/alerts/v2/alerts.go, backend/alerts/v2/destinations/destinations.go, backend/alerts/v2/destinations/discord/messages.go, backend/alerts/v2/destinations/email/messages.go, backend/alerts/v2/destinations/microsoft-teams/messages.go, backend/alerts/v2/destinations/microsoft-teams/templates/error-alert.go, backend/alerts/v2/destinations/microsoft-teams/templates/log-alert.go, backend/alerts/v2/destinations/microsoft-teams/templates/metric-alert.go, backend/alerts/v2/destinations/microsoft-teams/templates/session-alert.go, backend/alerts/v2/destinations/microsoft-teams/templates/trace-alert.go, backend/alerts/v2/destinations/slack/messages.go, backend/alerts/v2/destinations/webhook/messages.go, backend/lambda/lambda.go, backend/model/model.go, frontend/src/pages/Alerts/Alerts.tsx, packages/react-email-templates/emails/errors-alert-v2.tsx, packages/react-email-templates/emails/index.tsx, packages/react-email-templates/emails/logs-alert-v2.tsx, packages/react-email-templates/emails/metrics-alert-v2.tsx, packages/react-email-templates/emails/sessions-alert-v2.tsx, packages/react-email-templates/emails/traces-alert-v2.tsx, packages/react-email-templates/src/index.ts
Start sending new alerts to discord
1) Create a new alert for each product type
2) Add a discord channel for each alert
N/A
N/A
=> Start sending discord alerts to new alerts

frontend/src/components/Header/Header.tsx, highlight.io/components/common/Navbar/Navbar.tsx
- turns on launch week 6 banners in app and landing page
- testing in preview
- no
- no
=> enable launch week 6 banners

.github/workflows/turbo.yml
- use buildjet runner since running `yarn install` is hanging in codebuild for an unknown reason 
- remove session screenshot lambda tests as they require DB access - should replace this later
- increase timeout to 60 mins
- github actions
- will make monorepo check required after deploying this
- no
=> try github hosted runner

docs-content/getting-started/2_frontend-backend-mapping.md
- make it more clear that `tracingOrigins: true` is not enough for cross-origin requests
- preview
- no
- no
=> [SUP-81] call out tracingOrigins for cross-origin backends in docs

.github/workflows/turbo.yml
- running on buildjet at the moment - need credentials to upload lambda code to s3
- will monitor action after deploying 
- no
- no
=> add aws credentials to env for buildjet hosted runner

.github/workflows/turbo.yml
Publishing to `session-insights-email` lambda is blocked by a failing publish to render lambda. Switch the order to unblock while debugging
N/A
N/A
N/A
=> Switch turbo lambda order

backend/alerts/v2/alerts.go, backend/alerts/v2/destinations/destinations.go, backend/alerts/v2/destinations/discord/messages.go, backend/alerts/v2/destinations/email/messages.go, backend/alerts/v2/destinations/microsoft-teams/messages.go, backend/alerts/v2/destinations/microsoft-teams/templates/alert-upsert.go, backend/alerts/v2/destinations/slack/messages.go, backend/alerts/v2/destinations/webhook/messages.go, backend/lambda/lambda.go, backend/private-graph/graph/schema.resolvers.go, packages/react-email-templates/emails/alert-upsert.tsx, packages/react-email-templates/emails/index.tsx, packages/react-email-templates/src/index.ts
Send a confirmation notification to the destinations when an alert is created/updated
When creating an alert, add each type of destination to the alert. Confirm the confirmations for:
N/A
N/A
=> Send confirmation alerts

.github/workflows/turbo.yml, package.json
- publish:render was failing because it was not built
- will monitor github action after deploying
- no
- no
=> build screenshot lambda before publishing

backend/private-graph/graph/resolver_test.go, backend/private-graph/graph/schema.resolvers.go
Unsharing a session would not persist the update because gorm does not update a `false` value
without an explicit `Select()` statement listing the column, since `false` is the default value.
locally unsharing a session saving the update
new unit test
no
no
=> fix public session unsharing

backend/lambda-functions/deleteSessions/handlers/handlers.go, backend/util/runtime.go, backend/worker/worker.go, docker/compose.enterprise.yml, docker/configure-collector.sh
- otel endpoint was configured to use http despite SSL = true
- `StartSessionDeleteJob` was running in the `all` runtime, but an enterprise deployment uses separate containers with separate runtimes (frontend, backend, worker)
- create a new worker handler and add it to `compose.enterprise.yml`
- testing this docker image in an enterprise deployment
- will release new docker version after merging
- no
=> make session-delete-job worker handler for enterprise deployment

frontend/src/components/Header/Header.tsx
* Updates the `Chat / Support` button to our sales email.
[reflame](https://app.highlight.io/1/sessions?%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201J47FXHHJ6A9J99YECS7KEFDV%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22vadim%2Fsupport-button%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D)
no
no
=> update support button to reference email link

.changeset/calm-years-repeat.md, backend/assets/assets_test.go, backend/private-graph/graph/resolver_test.go, backend/stacktraces/enhancer_test.go, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts, sdk/firstload/src/index.tsx, sdk/highlight-next/CHANGELOG.md, sdk/highlight-next/package.json, sdk/highlight-remix/CHANGELOG.md, sdk/highlight-remix/package.json
Ensures that calling `H.startSpan()` before the otel library has loaded resolves 
and calls the `fn` but without a span, preventing a delay and crash of the library.
render preview of our frontend
changeset
no
=> fix otel webjs tracer creation when otel code has not loaded

backend/email/email.go, backend/private-graph/graph/resolver.go, backend/private-graph/graph/resolver_test.go
Product overage charges would be resent every time a billing update occurred because
the email history for those email types would be cleared.
Avoid clearing the overage email types and only clear other types after a billing period is over.
new unit test
no
no
=> avoid resending product overage emails

.changeset/thin-geese-hang.md, cypress/e2e/client.cy.js, sdk/client/src/constants/sessions.ts, sdk/client/src/index.tsx, sdk/client/src/utils/sessionStorage/highlightSession.ts, sdk/client/src/utils/sessionStorage/sessionStorageKeys.ts, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts, sdk/firstload/src/index.test.tsx, sdk/firstload/src/index.tsx, sdk/highlight-next/CHANGELOG.md, sdk/highlight-next/package.json, sdk/highlight-remix/CHANGELOG.md, sdk/highlight-remix/package.json, sdk/highlight-remix/src/client.tsx, sdk/highlight-remix/src/constants.ts, sdk/highlight-remix/src/server.ts, sdk/highlight-remix/tsconfig.json
* Fixes `getSessionURL` to return the full session url
* Updates `getSessionDetails` to return the URL with timestamp without blocking for the client.
new cypress test additions
changeset
no
=> fix highlight.run getSessionUrl only returning session ID 

backend/parser/listener/listener.go
- for exists / not exists queries when the attributes column is a list, check if the key exists in the array without comparing the value
- clicktested locally with grouped results
- no
- no
=> [HIG-4823] fix exists queries for sessions

render/package.json, sdk/firstload/src/index.test.tsx, yarn.lock
Fix the session screenshot lambda by updating `@sparticuz/chromium` and `puppeteer` 
to correct the lambda for the latest runtime. See https://www.reddit.com/r/aws/comments/1c774zh/aws_puppeteer_issues/
Deploying lambda
no
no
=> fix session screenshot lambda

backend/private-graph/graph/resolver_test.go
Improve backend unit test by ensuring `TestUpdateSessionIsPublic` flushes redis cache.
running unit test
no
no
=> improve TestUpdateSessionIsPublic to make the test less flaky

backend/clickhouse/errors.go, backend/clickhouse/logs.go, backend/clickhouse/metrics.go, backend/clickhouse/query.go, backend/clickhouse/sessions.go, backend/clickhouse/traces.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/Alerts/AlertForm/index.tsx, frontend/src/pages/Graphing/components/Graph.tsx
For alerts, bucket by the width of the alert window to allow for more accurate alert creation
https://www.loom.com/share/a5ab7c9dc2e84138b3e2bc567633c94f?sid=43bea6e3-da5e-4a63-bb7d-5b4cc5dad8c9
1. Create an alert
2. Change the alert threshold window
3. View dashboards
N/A
N/A
=> Fetch by threshold window for alerts

frontend/src/pages/Graphing/GraphingEditor.tsx
When working with funnels and retention charts, the source may be dependent on the type of chart. Change the order to have the type of chart above the source
1. View metrics
N/A
N/A
=> Flip view type and source form inputs

.changeset/hungry-ravens-invite.md, sdk/client/src/otel/user-interaction.ts, sdk/client/src/types/types.ts, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts, sdk/firstload/src/index.tsx, sdk/highlight-next/CHANGELOG.md, sdk/highlight-next/package.json, sdk/highlight-remix/CHANGELOG.md, sdk/highlight-remix/package.json
* Fix opentelemetry webjs SDK plugin breaking mouse event listeners due to debouncing logic.
https://www.loom.com/share/675d34193d3e4c98b72518f23863e5f9
changeset
no
=> fix otel webjs event monkeypatch breaking mouse event listeners

backend/private-graph/graph/schema.resolvers.go
Make the following improvements to the `AiQuerySuggestion` query
- Add examples and make sure they are added to the chat
- Remove duplicate keys
- Log request/response in one log
1. On a product search, click to use Harold AI suggestion
N/A
N/A
=> Clean up AI query prompt

frontend/src/components/Search/SearchForm/SearchForm.tsx, frontend/src/pages/Alerts/AlertForm/index.tsx
Update the log's "Create Alert" button to link to the new alert form with the correct prefilled inputs.
https://www.loom.com/share/b2dd6fbb4be049b08fa199d05b65ef43?sid=2aabd1b7-a65e-4876-a555-2367c38daab3
1. Create an alert from the logs page
N/A
N/A
=> Fix logs's create alert link

frontend/src/__generated/index.css, frontend/src/pages/Player/styles.css.ts
Fix the overflow of the dev tool tips menus, and make sure the resource panel is not affected
1. View a session
2. Open the Network tab in Highlight dev tools
3. Click on a network resource
N/A
N/A
=> Fix dev-tools overflow

highlight.io/pages/_document.js
Installs a JS script for [Zoho's PageSense](https://www.zoho.com/pagesense/) tool, which we will be using for running some A/B tests on our marketing site.
Confirmed my session was tracked on [the project dashboard](https://pagesense.zoho.com/pagesense/#/space/highlight/project/my-project/experiments/web-analytics/all-traffic/channels), and I ran the verification process on the Vercel preview which told me the installation was correct.
N/A
N/A
=> Add Zoho PageSense to marketing site

frontend/src/components/Billing/EnterpriseFeatureButton.tsx, frontend/src/pages/WorkspaceTeam/WorkspaceTeam.tsx, frontend/src/pages/WorkspaceTeam/components/InviteMemberModal.tsx
* fixes an issue with the `Invite Members` modal breaking interactivity with the page after modal is closed
* fixes pending invite deletion confirmation modal triggering invite members modal
https://www.loom.com/share/b7b0d543c7c64353b8d01154af1eab19
no
no
=> fix member invite modal

.changeset/sixty-pans-tan.md, sdk/client/src/constants/sessions.ts, sdk/client/src/index.tsx, sdk/client/src/workers/highlight-client-worker.ts, sdk/client/src/workers/types.ts, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts, sdk/highlight-next/CHANGELOG.md, sdk/highlight-next/package.json, sdk/highlight-react/CHANGELOG.md, sdk/highlight-react/package.json, sdk/highlight-remix/CHANGELOG.md, sdk/highlight-remix/package.json
stop recording data when the highlight.run sdk uploads cannot keep up with `PushPayload`
this typically happens due to canvas / video element recording not being able to
upload quickly enough given upload BW restrictions. stopping recording will
prevent an OOM that would otherwise happen due to garbage collection not being
able to release the canvas / video element bitmaps.
requested by a customer that is using the video element serialization feature
https://www.loom.com/share/1b49bc8236d34c58b2ba00390237b74d
minor version
no
=> stop recording data when the highlightrun sdk uploads cannot keep up

frontend/src/pages/Player/MetadataBox/MetadataBox.tsx
Updates the user identifier search design to make it more obvious that there is a clickable button.
no
@julian-highlight thoughts? i don't know if i love the hover state
=> update identifier search button icon

backend/clickhouse/migrations/000109_remove_session_fingerprint.down.sql, backend/clickhouse/migrations/000109_remove_session_fingerprint.up.sql, backend/clickhouse/sessions.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls
Fingerprint column was storing an Int32 value which would overflow.
Switch to using the `SessionAttributePairs` searching by `device_id` which was already recorded.
Closes SUP-98
`device_id` filter applies correctly
no
no
=> use session attributes to filter sessions on device id

backend/clickhouse/errors.go, backend/clickhouse/logs.go, backend/clickhouse/logs_test.go, backend/clickhouse/metrics.go, backend/clickhouse/query.go, backend/clickhouse/sessions.go, backend/clickhouse/traces.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/components/Search/SearchForm/SearchForm.tsx, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql
Currently when fetching key values for the searches, we fetch up to 400 results, and do any filtering on the frontend. We only show 25 results on the UI at a time.
Update this to only fetch 25 results, but allow the key values to refetch with a debounced query.
https://www.loom.com/share/e1f47a4503214181ab98488ebb67dba8?sid=e907dbc6-59ff-4ff7-96fc-85034bf9e51f
1. Search values with a query for each of the following products
2. Repeat on metrics/alerts
N/A
N/A
=> Support backend filtering of key values

frontend/src/pages/Alerts/Alerts.tsx, frontend/src/pages/Graphing/DashboardOverview.tsx
Update the metric and alert pages to always have a link to learn more about the feature. Update the callout copies to just link to the documentation (can watch the video on that page)
1. View the metrics page
1. View the errors page
N/A
N/A
=> Update tutorial copies

.github/workflows/turbo.yml
`yarn changeset version` would run in every branch resulting in https://github.com/highlight/highlight/pull/9153
we should only run this in main 
CI
no
no
=> update changeset on push to main

backend/clickhouse/metrics.go, backend/clickhouse/query.go, backend/model/model.go, frontend/src/pages/Graphing/components/Graph.tsx
Fix how metrics are fetched and calculated
- Use correct spot for grabbing metric value out of trace row
- Provide default trace keys to metric search
- Don't use metric column when function is `Count` and there is not option to change
https://www.loom.com/share/f7b41f41c90f4d27b13801e09beaeeb1?sid=642cc4ac-1b33-4ce1-955a-9c95a5fe44cb
N/A
N/A
=> Fix metric queries

frontend/src/pages/Graphing/GraphingEditor.tsx
- accidentally removed this with interval changes - add combobox back to select the bucketing field, right now it's always timestamp for new graphs 
- also change default bucketing back to `count`
- no
- no
=> add bucketing field back to ui

highlight.io/pages/docs/[[...doc]].tsx
Only return metadata, simple_path, array_path, hasContent in docOptions for smaller payload
Closes GRO-119
Click through links, see if pages still render correctly, check payload sizes in dev tools
|Before|After|
|--|--|
|![image](https://github.com/user-attachments/assets/1257413e-c910-4290-86cc-c60862fc36f4)|![image](https://github.com/user-attachments/assets/baea76e0-35ea-4c5e-9fa4-5f04369b7bb2)|
No
No
=> Only return necessary props in docOptions for smaller payload

frontend/src/pages/ErrorsV2/ErrorFeedHistogram/ErrorFeedHistogram.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionsFeedV3.tsx
Reduce number of requests sent for errors and sessions histogram -> only refetch when the search executes
1. View sessions
2. Start typing in the search query
3. Hit enter
N/A
N/A
=> Reduce fetches for errors/sessions histogram

frontend/src/pages/Auth/AdminForm.tsx, frontend/src/pages/Auth/InviteTeam.tsx, frontend/src/routers/AppRouter/AppRouter.tsx
When an admin user is invited to a workspace, they will overwrite the autojoin email domain field. ONly show this for newly created workspaces.
https://www.loom.com/share/a3cd4544ff55450ba5df5d2ac529f611
1. Create a new user and new project
2. Add multiple emails in settings to auto join domain
3. Invite a new user as an admin
4. Sign up as that invited admin
5. Delete created users in Firebase (if necessary)
N/A
N/A
=> Hide autojoin input for not new workspaces

docs-content/getting-started/4_backend-sdk/06_ruby/1_overview.md, docs-content/getting-started/5_backend-logging/04_ruby/1_overview.md, e2e/ruby/rails/demo/Gemfile, e2e/ruby/rails/demo/Gemfile.lock, e2e/ruby/rails/demo/app/controllers/application_controller.rb, e2e/ruby/rails/demo/config/initializers/highlight.rb, highlight.io/components/Products/products.ts, highlight.io/components/QuickstartContent/backend/ruby/other.tsx, highlight.io/components/QuickstartContent/backend/ruby/rails.tsx, highlight.io/components/QuickstartContent/backend/ruby/shared-snippets.tsx, highlight.io/components/QuickstartContent/logging/ruby/other.tsx, highlight.io/components/QuickstartContent/logging/ruby/rails.tsx, sdk/highlight-ruby/highlight/CHANGELOG.md, sdk/highlight-ruby/highlight/lib/highlight.rb, sdk/highlight-ruby/highlight/lib/highlight/version.rb
Updates the Ruby SDK and docs.
* Eliminates the need to set up the `around_action` to instrument requests by adding a `Railtie` and setting up the `around_action` as part of the initialization logic.
* Adds an `init` alias so you can call `Highlight.init` rather than `Highlight::H.new`.
* Fixes an issue where we were seeing warnings about incompatibility with `ActiveSupport::LoggerSilence`.
* Updates the Ruby/Rails documentation.
* Adds a `/for` page for Rails.
* Fixes some broken links on existing `/for` pages.
Closes HIG-4900
Click tested locally in the E2E app + a local instance of the docs site.
New SDK version going out. Will see if I can get recent articles published about the Ruby SDK updated.
N/A
=> Improve Ruby SDK setup and update docs

sdk/highlight-py/highlight_io/sdk.py, sdk/highlight-py/pyproject.toml
- Respect the log level passed into the Highlight initialization for Python's built in logging.
- Pass in the logger name to the log info
1. Start a Python E2E app
2. Create your own logger: `logger = logging.getLogger("pr_test")
3. Add two logs to an endpoint
a. logging.info("Test info")
b. logging.error("Test error")
4. Hit the endpoint
5. Add `log_level=Logging.Error` into the Python initialization
6. Hit the endpoint
N/A
N/A
=> Python logging improvements

.changeset/tough-seahorses-kiss.md, sdk/client/src/utils/sessionStorage/highlightSession.ts
Fixes an issue in highlight.run 9.3.0 where the `x-highlight-request`
would be missing the highlight session id because of the duplicate tab feature
incorrectly interacting with the cookie session propagation.
changeset
no
=> ensure duplicate tab functionality does not break x-highlight-request header

.changeset/shaggy-games-flow.md, sdk/client/src/workers/highlight-client-worker.ts
Require multiple PushPayload timeouts before the client stops recording
with the built in kill switch.
locally testing app
https://www.loom.com/share/a5284b3a7f0b45a0aa8c3f394e62b5bd
changeset
no
=> make client kill switch less likely to trigger by requiring multiple failures

highlight.io/pages/docs/[[...doc]].tsx
Filter out unnecessary Quick Start documentation content with regex, reducing ISR payloads (~50kb to ~15kb)
Fixes GRO-118
|Before|After|
|--|--|
|<img width="795" alt="image" src="https://github.com/user-attachments/assets/e7d543c9-7fd0-4446-9876-876a8e99e976">|<img width="808" alt="image" src="https://github.com/user-attachments/assets/403503bd-f04d-4105-a21c-774356d7451e">|
Click through each quick start doc page
No
No
=> Add function to filter quickStartContent and use in getStaticProps

frontend/src/components/RelatedResources/Panel.tsx, frontend/src/pages/ErrorsV2/ErrorsV2.tsx, frontend/src/pages/Player/PlayerPage.tsx
Fixes a bug with the side panel resize logic where you could not get out of drag mode after clicking to resize.
https://www.loom.com/share/87f4174444d24cc582cd6db371071734
Click tested locally and in the Reflame PR preview.
N/A
N/A
=> Fix drag to resize on side panels

frontend/package.json, frontend/src/index.tsx, frontend/src/pages/Player/RightPlayerPanel/components/EventDetails/EventDetails.tsx, frontend/src/pages/Player/StreamElement/StreamElement.tsx, frontend/src/pages/Player/components/EventStreamV2/EventStreamV2.tsx, frontend/src/pages/Player/components/EventStreamV2/utils.ts, frontend/src/routers/AppRouter/AppRouter.tsx, frontend/src/util/analytics.ts, yarn.lock
* Fixes filtering logic for session events that would incorrectly include events when a search term was set
* Shows comments in the session events feed supporting filtering
* Uses AND logic for multiple search terms in the events feed
* Fixes rudderanalytics attributes to avoid sending `id` term which was throwing a warning
* Improves frontend `identify` call in our app to report more attributes
https://www.loom.com/share/38ee44b7ded344f690b883ec24ca3ca2
no
no
=> improve session events filtering logic

backend/env/environment.go, backend/go.mod, backend/main.go, backend/storage/storage.go, deploy/collector-task.json, deploy/log-alerts-task.json, deploy/metric-monitor-task.json, deploy/private-graph-task.json, deploy/public-graph-task.json, deploy/public-worker-batched-service.json, deploy/public-worker-datasync-service.json, deploy/public-worker-main-service.json, deploy/public-worker-traces-service.json, deploy/worker-task.json
Support running the highlight backend via an IAM role rather than the AWS ID / secret.
manually deploying to production
locally testing with new IAM role set
monitoring deploy
no
=> support running backend using iam role for cloud auth

.changeset/small-cups-lay.md, frontend/src/pages/Player/StreamElement/StreamElement.tsx, frontend/src/pages/Player/components/EventStreamV2/utils.ts, sdk/client/src/index.tsx, sdk/client/src/workers/highlight-client-worker.ts
Click events would not properly report the clickTextContent as a searchable attribute in the sessions feed.
Update the client to report the events correctly and ensure 
Builds on events feed changes in https://github.com/highlight/highlight/pull/9227 (to be merged first)
locally building client
https://www.loom.com/share/4f4d046659aa4f4a8ed326b412c062cb
changeset
no
=> make clicktextcontent searchable in right panel session

highlight.io/components/common/Navbar/Navbar.tsx
- Change month from "Septemper" to "September"
- Fixes GRO-129
Visual check:
| Before | After |
|--|--|
|<img width="1020" alt="image" src="https://github.com/user-attachments/assets/e4d31a75-11fa-4f3a-bddc-e9d0a0beac28">|<img width="1020" alt="image" src="https://github.com/user-attachments/assets/54692df4-b0f2-4af4-a162-d6adfb064e92">|
No
No
=> Fix livestream banner typo

frontend/package.json, yarn.lock
Remove rudderstack sdk update which sets up bugsnag.
Bugsnag causing a memory leak / OOM in our app.
reflame preview
before
after
no
no
=> revert rudderstack upgrade

frontend/src/pages/Player/RightPlayerPanel/components/NetworkResourcePanel/NetworkResourcePanel.tsx
Correctly query time range for session related traces.
before
after
no
no
=> fix related trace query for session network requests

highlight.io/components/QuickstartContent/backend/python/django.tsx, highlight.io/components/QuickstartContent/backend/python/fastapi.tsx, highlight.io/components/QuickstartContent/backend/python/flask.tsx, highlight.io/components/QuickstartContent/traces/python/django.tsx, highlight.io/components/QuickstartContent/traces/python/fastapi.tsx, highlight.io/components/QuickstartContent/traces/python/flask.tsx
Python install docs were using the `[framework]` instasll flavors which are no longer relevant.
CI
no
no
=> fix python sdk install docs

.changeset/cool-papayas-compete.md, e2e/nextjs/next.config.mjs, sdk/highlight-next/src/util/with-highlight-config.ts
When next.js rewrites are defined, update existing ones correctly
rather than replacing when the definition is a `Rewrite[]`.
local debugger
before
after
changeset
no
=> correctly update rewrites for /highlight-events proxy when existing rewrites are defined

backend/enterprise/enterprise.go, backend/main.go, backend/model/model.go
Self hosted deployments would not set up certain business tier features
even with an enterprise license. 
Configure feature flags accordingly based on the enterprise configuration.
no
no
=> turn on enterprise features on self hosted enterprise deployments

frontend/src/@types/window.d.ts, frontend/src/components/DemoModal/DemoModal.tsx, frontend/src/pages/Auth/SignUp.tsx, frontend/src/util/analytics.ts, frontend/src/util/integrated.tsx
Adds GA tracking for some key events.
Ran through some of the conversion events and checked that they appeared in `window.dataLayer` correctly + showed up in the event stream for tag manager on the preview deploy.
N/A
N/A
=> Add Google analytics conversion events

frontend/src/pages/Traces/TraceFlameGraphNode.tsx
Fixes a bug where the flame graph tooltip could be shown when clicking and dragging to resize the side panel or dragging to select an area of the span to zoom in on.
Click tested locally by:
1. Dragging the resize panel quickly back and forth over an area where a span is displayed on the flame graph and ensuring the tooltip is not rendered.
2. Hovering over a span then clicking and dragging on the graph to zoom in, ensuring the tooltip is not rendered.
N/A - only a bit of UI polish ✨ 
N/A
=> Disable flame graph interactions when clicked

frontend/src/util/integrated.tsx
Per the request of Nathan, include the `email` attribute in our `integrated_*` events we send to Google.
Click tested with a new account to confirm the data was present in `window.dataLayer`.
N/A
N/A
=> Include email in GA integration events

backend/alerts/v2/destinations/slack/messages.go, backend/jobs/metric-alerts/metric-alerts.go, frontend/src/pages/Alerts/AlertForm/index.tsx
Error alerts send notifications for errors that are ignored. Add a default filter to only alert OPEN errors.
Note: Resolved errors should be reopened in a different process.
1. Create an error alert
2. Cause an error
3. Ignore the error
4. Cause the error again
N/A
N/A
=> Only alert OPEN errors

backend/clickhouse/query.go, frontend/src/pages/LogsPage/useGetLogs.ts, frontend/src/pages/Traces/TracesPage.tsx, frontend/src/pages/Traces/useGetTraces.ts
There is a race condition that causing use to double fetch logs on the infinite scroll. Fix this by adding a debounce and cleaning up some of the outdated code
https://www.loom.com/share/be2c80f36b6140deac8e384651168989
1. Log the logs page
2. Scroll to the bottom of the table
4. Repeat for traces
N/A
N/A
=> Fix log page ordering

frontend/src/__generated/index.css, frontend/src/pages/Alerts/AlertForm/index.tsx, frontend/src/pages/Graphing/GraphingEditor.css.ts, frontend/src/pages/Graphing/GraphingEditor.tsx
Not able to scroll the metric form to the bottom of the screen when necessary
1. Create a metric
2. Cut off the form so scroll is necessary
N/A
N/A
=> Fix metric graph scroll

backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/mutation.gql, frontend/src/pages/Alerts/AlertForm/index.tsx, frontend/src/pages/Alerts/AlertsRouter.tsx, frontend/src/pages/Alerts/ErrorAlert/ErrorAlertPage.tsx, frontend/src/pages/Alerts/LogAlert/LogAlertPage.tsx, frontend/src/pages/Alerts/LogAlert/LogAlertRouter.tsx, frontend/src/pages/Alerts/SessionAlert/SessionAlertPage.tsx, frontend/src/pages/Setup/SetupRouter/AlertsSetup.tsx
In the setup page, we create old default alerts for the new user if they request. Update these to be the new alerts.
Three alerts:
- New user sessions
- Error alerts
- Error logs
Additional notes
- Also removes being able to create legacy alerts.
- Removes routes from router
1. Create a new user/workspace
2. Sign up for the new alerts via the alert menu option
3. Create a manual alert
=> New default alerts

.reflame.config.jsonc, frontend/src/index.tsx
Improve app startup performance when slow loading of the highlight.run client
causes the firebase login flow to be blocked (because `H.startSpan` cannot execute)
https://www.loom.com/share/a76a392b816a438a9d83c865625e7146
no
no
=> remove span around admin fetch

.changeset/slimy-pots-greet.md, sdk/client/src/listeners/network-listener/utils/fetch-listener.ts, sdk/client/src/listeners/network-listener/utils/utils.test.ts, sdk/client/src/listeners/network-listener/utils/utils.ts, sdk/client/src/listeners/network-listener/utils/xhr-listener.ts, sdk/client/src/otel/index.ts
* Apply the `urlBlocklist` as a denylist to the tracing logic to avoid adding `x-highlight-request` to blocked APIs in scenarios where it is easier to block out a list of URLs rather than include all in the `tracingOrigins`
unit test
changeset
no
=> block tracing via x-highlight-request header via urlblocklist

.changeset/shiny-buckets-sparkle.md, __generated/rr/rrweb/rr.js, __generated/rr/rrweb/rr.min.css, backend/clickhouse/cursor.go, backend/clickhouse/cursor_test.go, backend/clickhouse/logs.go, backend/clickhouse/query.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver.go, frontend/src/components/Header/CommandBar/CommandBarCommands.tsx, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/index.tsx, frontend/src/pages/Player/ResourcesContext/ResourcesContext.tsx, frontend/src/pages/Player/RightPlayerPanel/components/NetworkResourcePanel/NetworkResourcePanel.tsx, frontend/src/pages/Player/TimelineIndicatorsContext/TimelineIndicatorsContext.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/NetworkPage/NetworkPage.tsx, frontend/src/pages/Player/WebSocketContext/WebSocketContext.tsx, frontend/src/pages/Traces/useGetTraces.ts, frontend/src/util/preload.ts, sdk/client/src/listeners/network-listener/utils/utils.ts
Updates the session dev tools `network` page to load data from `Traces`.
Updates the Resource context to use traces to load session network data across the product.
Doesn't yet switch to the new traces table to render network resources, but should make it easy to do so in the future.
* tested with otel frontend traces
* tested with frontend network requests recorded as traces
https://www.loom.com/share/3a252f8576e84405aa5ac6ded29868dd
monitoring in prod, will follow up to clean up network request files
no
=> chunk network resources

highlight.io/next.config.js, highlight.io/pages/_app.tsx, highlight.io/pages/api/og/blog/[slug].tsx, highlight.io/pages/api/og/customer/[slug].tsx, highlight.io/pages/api/og/doc/[[...doc]].tsx, highlight.io/pages/docs/[[...doc]].tsx
Addresses the following warnings we were seeing in our build logs:
```sh
In React 18, SSRProvider is not necessary and is a noop. You can remove it from your app.
In React 18, SSRProvider is not necessary and is a noop. You can remove it from your app.
In React 18, SSRProvider is not necessary and is a noop. You can remove it from your app.
In React 18, SSRProvider is not necessary and is a noop. You can remove it from your app.
In React 18, SSRProvider is not necessary and is a noop. You can remove it from your app.
In React 18, SSRProvider is not necessary and is a noop. You can remove it from your app.
In React 18, SSRProvider is not necessary and is a noop. You can remove it from your app.
```
```sh
59:6  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider …
```
=> Fix Next.js build warnings and broken links

backend/private-graph/graph/schema.resolvers.go
- after clickhouse query, there was also an order by for the sql query
- remove that and replace with in-memory sort according to `LastOccurrence`
- no
- no
=> fix errors sort order

backend/go.mod, e2e/go/Dockerfile, e2e/go/go.mod, e2e/nextjs/go-service/go.mod, go.work, sdk/highlight-go/go.mod, sdk/highlightinc-highlight-datasource/go.mod, sdk/highlightinc-highlight-datasource/go.sum
Was investigating [an error I was seeing locally](https://highlightcorp.slack.com/archives/C02CJANPHQS/p1727195920289109) running the backend and saw somewhere upgrading Go might resolve the issue. It does seem to have fixed my local build, and didn't see any harm in upgrading so thought I'd propose the change.
Also updates our Go E2E app to use the same version of Go as everywhere else.
Local backend build using `make start` from `./backend` and then click tested locally. Also ran the go E2E app to ensure that worked too.
N/A
N/A
=> Upgrade go to v1.23.1

frontend/src/pages/Player/MetadataBox/MetadataBox.tsx, frontend/src/pages/Sessions/SessionsFeedV3/MinimalSessionCard/utils/utils.ts
Fixes the link to see all sessions for a user by:
1. Updating the logic for finding the identifier
2. Ensure values are quoted if necessary (had some users saying their identifier was first/last name including spaces)
Click tested locally and in PR preview by:
1. Going to a session
2. Opening the user metadata panel
3. Clicking the "Sessions >" button
4. Confirming results look correct in the sidebar with the filters applied
I tested this on some of our project's settings and on the session that was reported as problematic (see Linear ticket for details).
N/A - just need to report back to users who have said this isn't working.
N/A
=> Fix all sessions for user link

backend/lambda-functions/deleteSessions/handlers/handlers.go, backend/storage/storage.go
- enforces raw event cleanup by removing any folders in the `raw-events` directory > 1 day old
- applies only when the `SESSION_RETENTION_DAYS` env var is set
- ran locally + debugged
- no
- no
=> cleanup raw events as part of session deletion job

packages/ui/src/components/Select/Select.stories.tsx, packages/ui/src/components/Select/Select.tsx
We only update the options state when the select is a multiselect. Move the `setOptions` out of the value array check.
Note: also adds created value to options for non-array case
1. Start story book
2. Naviage to the `[Single Select Dynamic Options And Custom Types](http://localhost:6006/?path=/story/components-select--single-select-dynamic-options-and-custom-types)` select
N/A
N/A
=> Update select options

frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ConsoleTable/index.tsx, packages/ui/src/components/Select/Select.tsx
1. Don't autoscroll when player is paused
2. Don't add blank items to select list
1. View a session's logs with autscroll
2. Create new user
N/A
N/A
=> Some small fixes

frontend/src/__generated/index.css, frontend/src/pages/Player/PlayerHook/PlayerState.ts, frontend/src/pages/Player/styles.css.ts, frontend/src/pages/Player/utils/utils.ts
Fixes an issue where the mouse would be shown initially very large and in the center of the replayer, then reposition to the top left corner once the replayer's size was adjusted. This PR hides the cursor until we get a mouse event that which contains positioning data for the mouse to display it in the correct spot on the replayer.
* On production, view a session and click around playing different sessions. Note the flicker on the replayer where you see the cursor incorrectly positioned briefly.
* Perform the same test on the PR preview and ensure the behavior looks better.
N/A
N/A
=> Hide mouse cursor until replayer is ready

backend/clickhouse/migrations/000122_create_event_key_values_new.down.sql, backend/clickhouse/migrations/000122_create_event_key_values_new.up.sql, backend/clickhouse/migrations/000123_create_event_keys_new.down.sql, backend/clickhouse/migrations/000123_create_event_keys_new.up.sql, backend/clickhouse/migrations/000124_create_event_keys_new_mv.down.sql, backend/clickhouse/migrations/000124_create_event_keys_new_mv.up.sql, backend/clickhouse/migrations/000125_create_event_attributes_new_mv.down.sql, backend/clickhouse/migrations/000125_create_event_attributes_new_mv.up.sql, backend/clickhouse/migrations/000126_write_event_event_name_new.down.sql, backend/clickhouse/migrations/000126_write_event_event_name_new.up.sql, backend/clickhouse/migrations/000127_write_event_session_fields_new.down.sql, backend/clickhouse/migrations/000127_write_event_session_fields_new.up.sql
We want to be able to fetch key and value recommendations based on the event name. Recreate the tables adding an `Event` column.
See follow up PR: https://github.com/highlight/highlight/pull/9400
https://www.loom.com/share/17eb2f77a4ed4ab4aa24a9b090735b80?sid=66db46e6-550e-41d8-bb1a-5a777e95e370
Delete old tables and views after deployment in follow up
N/A
=> Create new event keys

frontend/src/__generated/index.css, frontend/src/__generated/ve/pages/Graphing/EventSelection/styles.css.js, frontend/src/pages/Graphing/EventSelection/index.tsx, frontend/src/pages/Graphing/EventSelection/styles.css.ts, frontend/src/pages/Graphing/OptionDropdown/index.tsx
1. Fixes this error where the "Events" source can result in a type error due to changing options: https://app.highlight.io/1/errors/5f4oxCMXTGBYlr80SqGOakR7Y41W
2. Fix filters dropdown from being cutoff in `<article>` tag
1. Go to the metrics page
2. Select the "Events" source
3. Click to add filters
N/A
N/A
=> Event UX improvements

backend/clickhouse/events.go, backend/public-graph/graph/resolver.go
Issue in Clickhouse with too many parts from inserting session events. Update this to write async to avoid too many writes.
1. Start a session
2. Look at the events on clickhouse
Keep an eye on parts
N/A
=> Write events to clickhouse async

.changeset/bright-frogs-crash.md, .changeset/hungry-peas-live.md, .changeset/rare-rocks-beam.md, __generated/rr/rrweb/rr.js, sdk/client/src/index.tsx
* Fixes video element recording and replay dimensions
* Improves performance issues with canvas recording during snapshot due to lack of resizing
* Support shadow DOM canvas element recording with efficient webworker serialization
See rrweb changes
Closes SUP-76
https://preview.highlight.io/1/sessions/K2IaqbpSLUS8dTMOOTp7zPpVoiEZ?%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201J8G8RQTEMGG5CMPDXVYDR944%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22sup-123-performance-issues-with-canvas-recording-during-highlight%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D …
=> address performance issues with canvas recording during snapshot

frontend/src/__generated/index.css, frontend/src/__generated/ve/pages/Graphing/Combobox/styles.css.js, frontend/src/pages/Graphing/Combobox/index.tsx, frontend/src/pages/Graphing/Combobox/styles.css.ts, frontend/src/pages/Graphing/EventSelection/ClickFilters.tsx, frontend/src/pages/Graphing/EventSelection/NavigateFilters.tsx, frontend/src/pages/Graphing/EventSelection/TrackFilters.tsx
The graphing combobox width can extend too far. Fix this width to about the length of the right panel.
1. View the metrics page (`/metrics`)
2. Start creating an "Event" metric
3. Click on "Click" event type
4. Expand the "Text" dropdown
N/A
N/A
=> Fix width of graphing combobox dropdown

frontend/src/pages/Traces/TracesPage.tsx
The traces page on demo is looping in redirects causing lots of network requests to be sent and cancelled. Fix the use effect to no longer loop.
1. Visit the demo traces page (`/demo/traces`)
N/A
N/A
=> Fix trace redirection loop

frontend/index.html, highlight.io/pages/_app.tsx, highlight.io/pages/_document.js
Cleans up a couple things on our main app and website templates:
* Removes a duplicate Hubspot tracking script from the marketing site
* Removes duplicate `<title>` tags on both the marketing site and app
* Formats the templates using Prettier
Click tested the main app the marketing site in local previews. Ensured the Hubspot script was being loaded correctly.
N/A
N/A
=> Clean up Hubspot tracking and dup title tags

frontend/src/components/Search/SearchForm/SearchForm.tsx
- when `defaultValueOptions` was undefined, was skipping values entirely
- no
- no
=> fix search suggestions when no defaultValueOptions provided

backend/public-graph/graph/sampling.go, backend/public-graph/graph/sampling_test.go
Update session sampling logic to use the user identifier as the key when possible to be able to capture all sessions of a given user
unit test
no, single customer using session sampling
no
=> sample sessions by user when possible

highlight.io/components/Pricing/EstimatorDetails.ts, highlight.io/package.json, highlight.io/pages/pricing/[[...customer]].tsx, yarn.lock
* Updates the highlight.io pricing page to support custom enterprise pricing in the pricing calculator
* URL of /pricing/for/X can be used to look up custom pricing for the calculator
[vercel](https://highlight-landing-git-vadim-custom-pricing-page-highlight-run.vercel.app/pricing/for/example)
no
no
=> add custom customer pricing

frontend/src/pages/Alerts/AlertForm/index.tsx, frontend/src/pages/Graphing/EventSelection/ClickFilters.tsx, frontend/src/pages/Graphing/EventSelection/NavigateFilters.tsx, frontend/src/pages/Graphing/EventSelection/index.tsx, frontend/src/pages/Graphing/GraphingEditor.tsx, frontend/src/pages/Graphing/OptionDropdown/index.tsx, frontend/src/pages/Graphing/components/Graph.tsx, frontend/src/pages/Graphing/constants.tsx, frontend/src/pages/IntegrationsPage/components/ClickUpIntegration/ClickUpListSelector.tsx, frontend/src/pages/IntegrationsPage/components/GitHubIntegration/GitHubRepoSelector.tsx, frontend/src/pages/IntegrationsPage/components/GitlabIntegration/GitlabProjectSelector.tsx, frontend/src/pages/IntegrationsPage/components/HeightIntegration/HeightListSelector.tsx, frontend/src/pages/IntegrationsPage/components/JiraIntegration/JiraProjectSelector.tsx, frontend/src/pages/IntegrationsPage/components/LinearIntegration/LinearTeamSelector.tsx
Since passing in the `options` directly to the `<Select/>` in https://github.com/highlight/highlight/pull/9402, the Select is just rendering the selected value and not using the custom renderer. Update to use the renderer properly. 
https://www.loom.com/share/5dc6caa895fd45fdb5101b128a839b2e?sid=6e4c2729-8abb-4f7e-8231-850c0abb78fe
1. Make a new alert on the alerts page (`/alerts`)
2. Select a source
4. Select one of the frequency dropdowns (i.e. numbers with labels)
N/A
N/A
=> Fix option dropdown renderer

backend/http/logging.go, backend/http/logging_test.go, docs-content/getting-started/5_backend-logging/07_hosting/aws.md, sdk/highlight-go/highlight.go, sdk/highlight-go/log/util.go, sdk/highlight-go/otel.go
Ensures the `/logs/firehose` endpoint supports firelens structured logs
New unit tests
testing deployed in prod
no
no
=> support firelens structured logging from kinesis firehose

frontend/src/components/RelatedResources/SessionPanel.tsx, sdk/base.Dockerfile
The SessionPanel is crashing - `useResizePlayer` calls `useReplayerContext` , so it must be called within the `ReplayerContextProvider`. Move the call into a Base component of the SessionPanel.
1. View traces
2. Use the search `secure_session_id EXISTS`
3. Click on the session id to play
N/A
N/A
=> Fix session related resource player error

backend/clickhouse/query.go
- session fields are stored differently and expected to have many more rows
- in our project, value suggestions are breaking for variables because of this
- increase the rows max in the `AllKeyValues` function to account for this
- will monitor in prod after deploying
- no
- no
=> increase limit for all key value lookup to account for fields

highlight.io/components/common/CallToAction/OSSCallToAction.tsx, highlight.io/components/common/Footer/Footer.tsx, highlight.io/components/common/Navbar/Navbar.tsx, highlight.io/components/common/Navbar/ResourceDropdown.tsx
Updates the stale banner content and OSS CTA to point people to the upcoming livestream on optimizing AI applications.
Also adds a link to the podcast in the main nav and footer.
Local website preview click test.
N/A
N/A
=> Update website banner to point to upcoming livestream

.changeset/giant-penguins-watch.md, frontend/src/hooks/useFeatureFlag/useFeatureFlag.ts, frontend/src/pages/Player/PlayerHook/PlayerHook.tsx, frontend/src/pages/Player/PlayerHook/PlayerState.ts
Fixes a race condition that has been around in the session player for a while
causing the replay to freeze when chunks were being loaded.
https://www.loom.com/share/86b09c571b554b3695d2ab19f9e757db?from_recorder=1&focus_title=1
no
no
=> race condition when playing sessions causing pausing

backend/jobs/metric-alerts/metric-alerts.go, frontend/src/pages/Alerts/AlertForm/index.tsx
Alert page crashing due to trying to call useContext from outside wrapper -> wrap the form in the GraphContextProvider
N/A
N/A
=> Fix alert page crash

backend/clickhouse/sessions.go, backend/lambda-functions/deleteSessions/handlers/handlers.go, backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/components/Search/SearchContext.tsx, frontend/src/components/Search/SearchForm/SearchForm.tsx, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/hooks/useFeatureFlag/useFeatureFlag.ts, frontend/src/pages/ErrorsV2/SearchPanel/SearchPanel.tsx, frontend/src/pages/FrontPlugin/components/HighlightSessions.tsx, frontend/src/pages/Player/PlayerHook/PlayerState.ts, frontend/src/pages/Player/PlayerPage.tsx, frontend/src/pages/Player/SessionView.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionFeedConfigDropdown/helpers.ts, frontend/src/pages/Sessions/SessionsFeedV3/SessionFeedConfigDropdown/index.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionsFeedV3.tsx, frontend/src/pages/Sessions/SessionsFeedV3/context/SessionFeedConfigurationContext.ts, frontend/src/pages/Sessions/SessionsFeedV3/hooks/useSessionFeedConfiguration.ts, frontend/src/pages/Sessions/useGetSessions.ts
Add a session feed configuration option that allows rendering the session total time rather than count.
Automatically enabled by default for certain workspaces.
reflame
no
no
=> support showing active hours in session feed ui

sdk/.gitignore, sdk/highlight-java/highlight-common/pom.xml, sdk/highlight-java/highlight-common/src/main/java/io/highlight/sdk/common/HighlightHeader.java, sdk/highlight-java/highlight-common/src/main/java/io/highlight/sdk/common/HighlightOptions.java, sdk/highlight-java/highlight-common/src/main/java/io/highlight/sdk/common/Severity.java, sdk/highlight-java/highlight-framework/highlight-framework-spring/pom.xml, sdk/highlight-java/highlight-framework/pom.xml, sdk/highlight-java/highlight-log/highlight-log-api/pom.xml, sdk/highlight-java/highlight-log/highlight-log-java/pom.xml, sdk/highlight-java/highlight-log/highlight-log-log4j/pom.xml, sdk/highlight-java/highlight-log/pom.xml, sdk/highlight-java/highlight-sdk/pom.xml, sdk/highlight-java/highlight-sdk/src/main/java/io/highlight/sdk/Highlight.java, sdk/highlight-java/highlight-sdk/src/main/java/io/highlight/sdk/HighlightOpenTelemetry.java, sdk/highlight-java/highlight-sdk/src/main/java/io/highlight/sdk/HighlightSession.java, sdk/highlight-java/highlight-sdk/src/main/java/io/highlight/sdk/HighlightTracer.java, sdk/highlight-java/pom.xml
chore: cleanup some classes
fix: code spacing in some classes
Cleanup the java sdk and add some missing commands.
Also made the ``servername`` optionaly.
Localy
No
No
=> Cleanup Java SDK

frontend/package.json, packages/ui/package.json, packages/ui/src/components/ComboboxSelect/ComboboxSelect.tsx, yarn.lock
Adds the [`@reflame/testing`](https://github.com/reflame/testing) package to provide better types for Reflame component tests, and provide some inline documentation.
=> Add types for reflame component tests

backend/clickhouse/query.go
Up the max buckets to 240 - alerts look at [4 hour windows](https://github.com/highlight/highlight/blob/main/backend/jobs/metric-alerts/metric-alerts.go#L76-L78) with [1 minute buckets](https://github.com/highlight/highlight/blob/main/backend/jobs/metric-alerts/metric-alerts.go#L76-L78), so they need 240 buckets to correctly calculate the `bucket_index` and metric_history `timestamp`.
```
// uses bucket max of 100
bucketIndex = toUInt64(intDiv((timetamp - min) * bucketCount(max of 100) / (max - min)))
// uses the original bucket count of 240
Timestamp = fromUnixTimestamp(toInt64(bucket_index*(max-min)/bucketCount + min))
After cancelation
Timestamp = timetamp *  bucketCount(max of 100) / bucketCount
```
1. Create an log alert
2. Let it run
N/A
N/A
=> Fix alert bucketing

.changeset/light-olives-design.md, docs-content/getting-started/fullstack-frameworks/remix.md, e2e/remix/app/entry.server.tsx, sdk/highlight-remix/src/server.ts
`DataFunctionArgs` type has been deprecated in Remix v2.4.0 (see [changelog](https://github.com/remix-run/remix/blob/e8d1aea4fb023b0967da02914d630b1f1c4a35e4/CHANGELOG.md#minor-changes-6)). Therefore, I have updated this type to `LoaderFunctionArgs | ActionFunctionArgs` (Ref: [handleError documentation](https://remix.run/docs/en/main/file-conventions/entry.server#handleerror)).
No
No
No
=> Update deprecated types in Remix

frontend/src/pages/Alerts/AlertEnableSwitch/AlertEnableSwitch.tsx, frontend/src/pages/Alerts/AlertForm/index.tsx, frontend/src/pages/Alerts/AlertPage/index.tsx, frontend/src/pages/Alerts/Alerts.tsx
Fixes the following bugs on the alert page
- creating a new alert redirects to the alert correctly after creation
- Pressing cancel on the new alert form redirects back to the alerts page
- Pausing/enabling an alert on the alerts page does not redirect
- Only refetch the updated alert when updating an alert (previously refetched all cached alerts - event deleted ones)
- Don't refetch any alerts when creating a new alert
1. Create a new alert but cancel
2. Create a new alert and save
3. Modify alert and save
4. Delete an alert
5. Click into another alert
6. Enable/Pause the alert
7. Enable an alert from the alerts page
https://www.loom.com/share/294789372200465f814849f8b810dc64?sid=f3294439-6395-4b79-bc80-0a2f97c69e52
N/A
N/A
=> Fix alert UX bugs

frontend/src/components/CreateAlertButton/CreateAlertButton.tsx, frontend/src/pages/ErrorsV2/ErrorsV2.tsx, frontend/src/pages/Player/SessionLevelBar/SessionLevelBarV2.tsx
The session and errors page have alert links to pages that do not exist. Update to link to the correct page and update the logic to check if a new alert exists.
1. With no session alerts, view a session
2. Click on the "Turn on alerts" button
3. Create an alert
4. View the session again
5. Repeat for errors
N/A
N/A
=> Fix session and error alert links

highlight.io/components/QuickstartContent/traces/node-js/manual.tsx
Fixes some misleading information about methods that did not exist on our Node SDK (`startSpan` and `endSpan`).
Checked docs in PR preview.
N/A
N/A
=> Fix incorrect API reference in Node docs

backend/public-graph/graph/resolver.go, backend/worker/worker.go
* Ensure that click events are written as session fields
session showing up with `clickTextContent` filter
no
no
=> fix writing session click events as fields

backend/private-graph/graph/schema.resolvers.go, frontend/src/components/Billing/EnterpriseFeatureButton.tsx, frontend/src/pages/Auth/InviteTeam.tsx, frontend/src/pages/WorkspaceTeam/WorkspaceTeam.tsx, frontend/src/pages/WorkspaceTeam/components/InviteMemberModal.tsx
Update the application to not allow member users to send invites to Highlight:
- Disable button to invite for non-admin
- Redirect from invite_team page for non-admin
- Secure backend for no non-admin invites
1. As a admin invite a member
2. Sign up as the member
3. Try to invite another member on the team settings
N/A
N/A
=> Only admin admins to invite

.changeset/four-lizards-mix.md, sdk/client/src/otel/index.test.ts, sdk/client/src/otel/index.ts, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts, sdk/highlight-next/CHANGELOG.md, sdk/highlight-next/package.json, sdk/highlight-react/CHANGELOG.md, sdk/highlight-react/package.json, sdk/highlight-remix/CHANGELOG.md, sdk/highlight-remix/package.json
Ensures that the `traceparent` header is only assigned on requests to URLs that match the `tracingOrigins` setting on the client config. Previously, we were adding the `traceparent` header to all requests.
Added some unit tests for the logic behind the new config setting and tested locally by inspecting network traffic with different settings - see results below.
**`['pri.highlight.io', 'localhost:8082/private']` (default - header included)**
**`['pri.highlight.io']` (header not included)**
**`true` (header included)**
Need to notify some customers about this change since they have been waiting on the fix.
N/A
=> Respect `tracingOrigins` network instrumentation context propagation

backend/clickhouse/events.go, backend/kafka-queue/kafkaqueue.go, backend/kafka-queue/types.go, backend/public-graph/graph/resolver.go, backend/worker/kafka_worker.go, backend/worker/worker.go
Move the session event processing to the DataSyncQueue so it does not block push payload
1. Run the app and click around
1. How will this additional load add to the DataSync Queue?
2. How will it scale with Production data?
N/A
=> Move session event processing to kafka queue

backend/jobs/metric-alerts/metric-alerts.go
Metric monitors are not sending alerts due to nil pointer - reference the pointer more safely
1. Create a log, trace, error, and session alert
Monitor for any downstream errors
N/A
=> Check buckets

frontend/src/components/RelatedResources/RelatedResourceList.tsx
Allow users to expand the resource list to the product's search experience when relevant
1. Make a graph of traces
2. Click on a data point to drilldown
3. Repeat for errors
5. Repeat for sessions
7. Repeat for events
N/A
N/A
=> Expand resource lists

render/src/index.ts, render/src/render.ts, render/src/serial.ts
Sets up oauth API access in the render lambda to get a project token and configure the puppeteer instance
with the project token cookie for loading replaced assets . This allows loading custom media and CSS that is
replaced with a pri.highlight.io/assets/... URL.
* Improves rendering speed of lambda by speeding up playback
Closes SUP-146
https://highlight-session-render.s3.us-east-2.amazonaws.com/5403/W3Hfwlqq0DxPuL395GjZssKqF72h.mp4
no
no
=> fix session video export with replaced assets

frontend/src/pages/Graphing/components/Graph.tsx
- this state was being tracked to determine whether or not to show a pointer for drilldown - this will cause a pointer to always be shown but will speed up perf for complex graphs significantly due to not having to rerender on mouse move
- clicktested locally w/ complex group by
- no
- no
=> remove mouseMoveState for perf

backend/alerts/v2/alerts.go, backend/jobs/metric-alerts/metric-alerts.go
Add logging when metric alerts are being processed
Can see logs printed
N/A
N/A
=> Add logging to alerts

backend/alerts/predictions/predictions.go, backend/clickhouse/metric_history.go, backend/clickhouse/query.go, backend/jobs/metric-alerts/metric-alerts.go
- don't want to have to migrate old alerts to ensure alerts keep working for on-prem customers
- logic assumes alerts default to constant / above threshold
- ensuring evaluation running locally for null entries
- no
- no
=> make checks backwards compatible with null threshold/condition

backend/clickhouse/sessions.go, backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/Sessions/SessionsFeedV3/SessionFeedConfigDropdown/helpers.ts, frontend/src/pages/Sessions/SessionsFeedV3/SessionFeedConfigDropdown/index.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionsFeedV3.tsx, frontend/src/pages/Sessions/SessionsFeedV3/context/SessionFeedConfigurationContext.ts, frontend/src/pages/Sessions/SessionsFeedV3/hooks/useSessionFeedConfiguration.ts, frontend/src/util/time.ts
* Visualize active/inactive session time in hours
* Support new session histogram format of session active vs inactive time
Closes SUP-128
no
no
=> update session results format

e2e/nextjs/pages/api/hello.ts, e2e/nextjs/pages/api/winston.config.ts, highlight.io/next.config.js, sdk/highlight-go/log/util.go
Supports ingesting structured json messages that have a message that is json.
This now unwraps the inner json to be top level attributes, in addition to serializing the top json payload as the message.
no
no
=> support winston json formatted log messages

frontend/src/pages/Graphing/components/Graph.tsx, frontend/src/pages/Graphing/components/Table.tsx
- use local storage variables to store the sort column and asc/desc by visualization id
- no
- no
=> persist table sort order by id

docs-content/general/4_company/open-source/contributing/adding-an-sdk.md, highlight.io/components/QuickstartContent/backend/otlp.tsx, highlight.io/components/QuickstartContent/logging/otlp.tsx, highlight.io/components/QuickstartContent/traces/otlp.tsx
Add highlight project ID to the OpenTelemetry docs to make it more clear how
to configure project ID propagation in various OTeL SDKs.
[Vercel preview
](https://highlight-landing-git-vadim-otlp-project-docs-highlight-run.vercel.app/)
no
no
=> document opentelemetry project id attributes

frontend/src/components/CustomColumnPopover/index.tsx, frontend/src/components/RelatedResources/LogsPanel.tsx, frontend/src/components/RelatedResources/RelatedResourceList.tsx, frontend/src/components/RelatedResources/ResourceTable.tsx, frontend/src/pages/ErrorsV2/CustomColumns/columns.ts, frontend/src/pages/Graphing/components/Graph.tsx, frontend/src/pages/Sessions/CustomColumns/columns.ts
Allow users to customize their related resource tables and sort if the table supports it (i.e. only traces)
https://www.loom.com/share/d9478badded3411686478b160ccd4b2f?sid=bd2d47b9-a03a-4297-b311-39e0b17d6310
1. Create a graph or alert of traces
2. Drill down to a timestamp
3. Close the related resources and reopen
4. View trace table
5. Repeat for sessions, errors, logs, and events
N/A
N/A
=> Customize related resource table

frontend/src/pages/Alerts/DestinationInput/index.tsx, frontend/src/pages/Alerts/LogAlert/LogAlertPage.tsx, frontend/src/pages/Alerts/components/AlertNotifyForm/AlertNotifyForm.tsx
* Support custom inputs for email box of alert destinations
no
no
=> support custom email inputs for alert destinations

frontend/src/pages/Graphing/Dashboard.tsx, frontend/src/pages/Graphing/GraphingEditor.tsx, frontend/src/pages/Graphing/context/GraphContext.ts, frontend/src/pages/Graphing/hooks/useGraphData.tsx
* Uses a `ref` for the graph data since the data is used for data export 
* Updates the editor for funnel charts to avoid showing limit
[reflame](https://preview.highlight.io/1/metrics/20560?relative_time=last_7_days&%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201JBYE2RM1B9F5XD7N6M8FW76X%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22vadim%2Fdashboard-rerendering%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D)
no
no
=> fix dashboard re-rendering due to context loop

backend/model/model.go, frontend/src/pages/IntegrationsPage/components/HerokuIntegration/HerokuIntegration.tsx, frontend/src/pages/IntegrationsPage/components/HerokuIntegration/utils.ts
* Allows multiple heroku log drain tokens to be associated with the same highlight project
https://www.loom.com/share/bf68f9c79ddd41a79386df0568ba74f0
remove`idx_integration_project_mapping_project_id_integration_type` in production`
no
=> support multiple heroku tokens for the same highlight project

.changeset/odd-fireants-melt.md, docs-content/getting-started/fullstack-frameworks/next-js/2_page-router.md, docs-content/getting-started/fullstack-frameworks/next-js/3_app-router.md, docs-content/getting-started/fullstack-frameworks/next-js/7_advanced-config.md, docs-content/sdk/nodejs.md, e2e/express-ts/package.json, e2e/express-ts/src/express.ts, e2e/express-ts/src/pino.ts, e2e/express/src/index.mjs, e2e/nestjs/src/app.service.ts, e2e/nextjs/pages/api/page-router-trace.ts, e2e/nextjs/src/app/_utils/app-router-highlight.config.ts, e2e/nextjs/src/app/api/app-router-trace/route.ts, highlight.io/components/QuickstartContent/traces/node-js/manual.tsx, highlight.io/components/QuickstartContent/traces/node-js/nextjs.tsx, sdk/highlight-apollo/src/apollo.ts, sdk/highlight-apollo/src/apolloV3.ts, sdk/highlight-next/src/util/highlight-edge.ts, sdk/highlight-next/src/util/types.ts, sdk/highlight-next/src/util/with-highlight-edge.ts, sdk/highlight-next/src/util/with-highlight-nodejs-app-router.ts, sdk/highlight-next/src/util/with-highlight-nodejs-page-router.ts, sdk/highlight-node/src/client.ts, sdk/highlight-node/src/handlers.ts, sdk/highlight-node/src/sdk.ts, yarn.lock
* Names the `Handlers.middleware` `@highlight-run/node` spans based on the request method / route
* Fixes `Handlers.middleware` in `@highlight-run/node` not propagating span context correctly to child middleware invocation
* Updates apollo and next sdks accordingly
e2e/express app [traces](https://app.highlight.io/1/traces?query=service_name%3De2e-express&related_resource=eyJ0eXBlIjoidHJhY2UiLCJpZCI6IjZhNmQ4YTAxZDM4ZTJmMzdjNDYyODhmYmNhNGM2M2JiIiwidGltZXN0YW1wIjoiMjAyNC0xMS0wNlQwNDo1NTo1My4yNjlaIiwic3BhbklEIjoiNzg4YjI3ZDcxYTYxMTJlMSJ9)
changeset
no
=> report better middleware spans from @highlight-run/node

backend/clickhouse/events.go, backend/clickhouse/logs.go, backend/clickhouse/logs_test.go, backend/clickhouse/sessions.go, backend/clickhouse/traces.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, frontend/src/graph/generated/schemas.tsx, frontend/src/pages/Graphing/Dashboard.tsx, frontend/src/pages/Graphing/components/Graph.tsx, packages/ui/src/components/DatePicker/DateRangePicker.stories.tsx, packages/ui/src/components/DatePicker/DateRangePicker/index.tsx
- allow timestamp to be used as y axis field (formatted as a date)
- add default selection to date picker as a submenu
- fix loading state padding bug
- no
- no
=> allow timestamp to be graphed as y axis, add default option to date picker

frontend/package.json, frontend/src/components/Header/InkeepChatSupportMenuItem.tsx, frontend/src/pages/Setup/SetupInkeepChatButton.tsx, highlight.io/components/common/Navbar/InkeepSearchBar.tsx, highlight.io/package.json, yarn.lock
* Resolve live mode issue caused by unintentional upgrade of `@apollo/client` in frontend
Closes SUP-158
reflame
https://www.loom.com/share/677350561a0540ccb8791c604ea9897b
no
no
=> fix live mode sessions breaking due to @apollo/client package update

.changeset/metal-foxes-teach.md, docs-content/getting-started/fullstack-frameworks/next-js/2_page-router.md, docs-content/getting-started/fullstack-frameworks/next-js/3_app-router.md, e2e/nextjs/pages/api/page-router-trace.ts, e2e/nextjs/src/app/_utils/app-router-highlight.config.ts, e2e/nextjs/src/app/api/app-router-trace/route.ts, e2e/nextjs/src/app/layout.tsx, sdk/highlight-apollo/CHANGELOG.md, sdk/highlight-apollo/package.json, sdk/highlight-nest/CHANGELOG.md, sdk/highlight-nest/package.json, sdk/highlight-next/CHANGELOG.md, sdk/highlight-next/package.json, sdk/highlight-node/CHANGELOG.md, sdk/highlight-node/package.json, sdk/highlight-node/src/client.ts, sdk/highlight-remix/CHANGELOG.md, sdk/highlight-remix/package.json
* Correctly configures trace context propagators in the @highlight-run/node sdk
* Defines an example of outgoing `fetch` context propagation via `@opentelemetry/api`
* Documents trace context propagation
changeset
no
=> fix @highlight-run/node & next propagation of w3c context

frontend/src/pages/Traces/TraceHeader.tsx, packages/ui/src/components/Heading/Heading.tsx
Ensures trace titles are truncated if they are longer than 2 lines.
**Before**
**After**
Click tested in the PR preview (see screenshots ☝️).
N/A
N/A
=> Limit trace title to 2 lines

backend/clickhouse/query.go, frontend/src/pages/Graphing/GraphingEditor.tsx
- skip the inner where clause (e.g. `g0 in (select * from traces where ... limit 10)`) for no-limit queries
- apply group not empty filter (e.g. `g0 != ''`) to top level where
- tested limit / no limit queries locally
- debugged to look at generated sql queries
- no, is backwards compatible
- no
=> skip second filter for no limit queries

backend/model/model.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, frontend/src/components/Billing/EnterpriseFeatureButton.tsx, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/IntegrationsPage/components/Integration.tsx
- on the integrations page, put the Jira and Teams toggles behind the enterprise feature gate
- clicktested locally with and without settings enabled
- after deploying, will run this script to enable the enterprise settings for anyone already using jira / teams
```
update all_workspace_settings 
set enable_teams_integration = true 
where workspace_id in (
select id from workspaces where microsoft_teams_tenant_id is not null
)
update all_workspace_settings 
set enable_jira_integration = true 
where workspace_id in (
select workspace_id from integration_workspace_mappings where integration_type = 'Jira'
)
```
- no
=> gate teams and jira as enterprise features

backend/otel/extract_test.go, backend/public-graph/graph/resolver.go
- now that we don't use the clickhouse setting to force merge parts after 1 hour, it shouldn't be as big of a performance issue to have data for old / future parts ingested
- changes the time clamping setting to +/- 30 days
- ensured logs/traces still ingested locally
- will monitor perf and part count and revert if there's significant degradation
- no
=> update time clamping to +/- 30 days

backend/public-graph/graph/sampling.go, backend/worker/kafka_worker.go
- lots of `IsIngestedBy` spans are getting created while ingesting a large number of historical logs, disable these for now
- run unit tests in `sampling_test.go` to make sure nothing is affected
- no
- no
=> remove IsIngestedBy spans for now

backend/clickhouse/errors.go, backend/clickhouse/events.go, backend/clickhouse/logs.go, backend/clickhouse/metrics.go, backend/clickhouse/query.go, backend/clickhouse/sessions.go, backend/clickhouse/traces.go
- `SAMPLE N` queries are not working in current version
- also hard to predict if sampling is needed without checking source tables
- make `EXPLAIN ESTIMATE` query to any relevant tables to get a row estimate, then calculate the sampling ratio manually if the estimate is greater than the sampling threshold
- tested metrics locally w/ all product types
- no
- no
=> dynamic sampling

backend/model/model.go, backend/otel/otel.go
The `highlight.log` traces in the tracing project can be noisy and not very helpful for many users, but some users request them. Feature flag the ingestion of these traces to allow users to hide/show the `highlight.log` traces.
1. Start the Django app
2. Send a curl request to the app
2. Update the `AllWorkspaceSetting.EnableLogTraceIngestion` to `true` in Postgres
3. Restart the app and backend
4.  Send a curl request to the app
Fix boolean for appropriate organizations
N/A
=> Feature flag highlight.log traces

backend/private-graph/graph/schema.resolvers.go
The request time in the "Session Export Requests" table shows the time of the session, when it should be showing the time of the request. Update the request to use the session export `created_at` date and order by this date.
1. Make sure the `enable_session_export` is set to true for the workspace settings
2. View and download a session
3. View the Project settings
4. Navigate to the session replay section and view the "Session Export Requests" table
N/A
N/A
=> Fix data export table

backend/clickhouse/query.go
- eliminates subquery in group by w/ limit queries to scan over the dataset once instead of twice, speeding up these queries by ~2x
- example query:
```
SELECT bucket_index, sample_factor, min, max, correlation_id, metric_value0, g0, limit_rank 
FROM (
SELECT bucket_index, any(_sample_factor) as sample_factor, any(min) as min, any(max) as max, toInt64(0) as correlation_id, round(count() * any(_sample_factor)) as metric_value0, g0, dense_rank() over (order by limit_metric desc, g0) as limit_rank
FROM (
SELECT toUInt64(intDiv((toFloat64(Timestamp) - 1729464000.0) * 30, (1732059600.0 - 1729464000.0))) AS bucket_index, 1729464000.0 AS min, 1732059600.0 AS max, _sample_factor, 1.0 AS metric_value, toString(SpanName) AS g0, quantile(.5)(Duration) OVER (PARTITION BY g0) as limit_metric
FROM …
```
=> optimize group w/ limit queries

backend/clickhouse/query.go
- Vadim discovered this query was faster using `ProjectId=1` instead:
```
select distinct Timestamp, UUID
from logs
where ProjectId in (1)
and Timestamp < now()
and Timestamp > now() - interval '30 days'
order by Timestamp DESC, UUID DESC
limit 51
```
- clicktested locally, ensured query was generated with equals
- no
=> add special case for project id where clause

.changeset/long-plums-wait.md, sdk/highlight-node/src/client.ts
Updates the `@highlight-run/node` sdk to avoid setting up noisy instrumentations (`fs` and `http`) by default.
CI
no fs spans recorded
changeset
no
=> disable fs and http instrumentation by default

backend/private-graph/graph/auth_client.go, backend/private-graph/graph/middleware.go, highlight.io/pages/otel-course-signup.tsx
* Ensure that OIDC Verifier claim expiration resets to the Sign In page by logging user out
* Add data layer event to course submit.
vercel preview, CI
no
no
=> Ensure that OIDC Verifier claim expiration resets to the Sign In page

frontend/src/pages/Billing/BillingPageV2.tsx
- new format expects data to be stored under `seriesKey`
- should change the type signature of `data` to prevent this
- no
- no
=> fix crash on billing page

frontend/src/pages/Graphing/components/Graph.tsx
- fixes a few errors:
`Cannot read properties of undefined (reading 'column')`
`Cannot read properties of undefined (reading 'series')`
- remove some debug code
- repro'd crashing locally, confirmed fixed
- no
- no
=> fix a couple crashes from undefined series

.changeset/thirty-flies-swim.md, sdk/client/src/otel/exporter.ts, sdk/client/src/otel/index.ts
Adjust OTeL WebJS traces export to support multiple export retries for transient network failures.
simulating export failure
changeset
no
=> tune opentelemetry traces export from highlight.run

highlight.io/components/QuickstartContent/backend/php/shared-snippets.tsx
- PHP quickstart guide contained text pertaining to Maven (probably residual from this guide being copied over), updated.
- The 'record custom errors' example was incorrect - `captureException` is a static method and there is no such syntax as `Highlight->captureException` in PHP (I've tested this to verify).
=> Fix incorrect text and code examples in the PHP getting started guide

backend/jobs/metric-alerts/metric-alerts.go
For session and error alerts, they have always have a bucket, even if no sessions/alerts are being have occurred. This was causing an issue where no `alert_state_changes` were being written to Clickhouse. Update this case, to write a normal state to Clickhouse
1. Create a session/error alert which will return no data.
2. Let the alert watcher run for a couple minutes
3. Check the alert detail page
N/A
N/A
=> Write normal states for sessions and errors

highlight.io/components/common/CallToAction/OSSCallToAction.tsx, highlight.io/components/common/Navbar/Navbar.tsx
We have some stale CTAs on our website pointing to the CNCF webinar that has come and gone already. This PR updates them to point to our new OTeL course.
Local click test. Can also be confirmed in the PR preview.
N/A
N/A - running copy by @jay-khatri and @Vadman97 before launching.
=> Update CTAs on website for CNCF webinar

frontend/src/pages/Graphing/components/Graph.tsx
When we are grouping a graph that only has one group, it can be confusing what that group actually is, as it shows up as the function name on the legend. Update to always show the group when possible.
1. Create a new graph
2. Add filters that would result in only one group (email for sessions)
3. Group by the key
N/A
N/A
=> Show group on single group graphs

frontend/src/pages/Graphing/components/Graph.tsx
- `btoa` breaking when group has utf8 characters - use `encodeURIComponent`
- no
- no
=> escape utf8 characters in key

frontend/src/util/attribution.ts, highlight.io/utils/attribution.ts
According to the [js-cookie docs on the `expires` attribute](https://github.com/js-cookie/js-cookie?tab=readme-ov-file#expires):
> Define when the cookie will be removed. Value must be a Number which will be interpreted as days from time of creation or a Date instance. If omitted, the cookie becomes a session cookie.
This means our current cookie is being set as a session cookie. We want to store this longer than that.
Also updates our logic for storing UTM params to always store any available.
N/A
N/A
=> Extend duration we store attribution cookie

frontend/src/pages/Player/PlayerHook/PlayerHook.tsx
Fixes bug with blocking chunk load logic that would cause session to jump to 0:00
Closes HIG-5037
[Reflame preview on session with blocking load at 4:53](https://preview.highlight.io/1/sessions/zmXYhJp213xt6DQlrdWdeGUfjQAe)
https://www.loom.com/share/79dfa2eb68654d3a9ccf088223b31690
no
no
=> fix playback skipping on blocking chunk load

backend/event-parse/parse_test.go, backend/otel/extract.go, sdk/highlight-go/otel.go
* Pull out `environment` attribute to the top level `Environment` column to ensure correct search on the reserved attribute.
https://www.loom.com/share/435e9729fb804cef95f2bfb29b167ca4
no
no
=> correctly map the environment attribute to the top level column

.github/workflows/turbo.yml, frontend/package.json, frontend/scripts/publish.mjs, package.json
* Deploys the frontend from github actions to an S3 bucket which is used to host app.highlight.io
* For branch PR previews, deploys the frontend from github actions to a `/preview/<sha>/index.html` path as well.
The previews currently do not load due to the app redirecting from that URL, but we use reflame for previews anyway.
The preview uploads can be used to quickly revert the prod build by copying the output to the top level.
running deploy to prod, app.highlight.io now hosted from CloudFront that points to this s3 bucket
test upload to prod from [this job](https://github.com/highlight/highlight/actions/runs/12285836160/job/34284726719)
allows for further cloudfront configuration such as WAF. turned off billing for render.com
no
=> host frontend on s3

frontend/src/components/Header/Header.tsx, frontend/src/components/RelatedResources/LogsPanel.tsx, frontend/src/components/Search/SearchForm/SearchForm.tsx, frontend/src/pages/LogsPage/LogsPage.tsx, frontend/src/pages/LogsPage/LogsTable/LogsTable.tsx, frontend/src/pages/Player/RightPlayerPanel/components/NetworkResourcePanel/NetworkResourceLogs.tsx, frontend/src/pages/Traces/TracesList.tsx, frontend/src/pages/Traces/TracesPage.tsx, packages/ui/src/components/Table/Head/Head.tsx, packages/ui/src/components/Table/Table.tsx
The traces/logs tables height is fixed depending on the elements above. However, it doesn't take into account the banner. Update the traces/logs tables to not use a fixed height and flex appropriately.
1. Turn a banner on within the app
2. Navigate to the logs page
2. Create a logs graph
3. Drill down into the logs
4. Navigate to the traces page
N/A
N/A
=> Fix traces/logs table height

backend/clickhouse/traces.go
- now that we're saving and querying keys in other specialized columns, remove them from `TraceAttributes` to improve query perf
- ensured new traces are queryable by these attributes and show these attributes in the trace viewer (tested `http.response.body` and `db.statement`)
- validated new traces do not have the same attributes duplicated in `TraceAttributes`
- no
- no
=> remove special keys from trace attributes, they're saved in other columns

frontend/src/pages/Graphing/Dashboard.tsx, frontend/src/pages/Graphing/components/BarChart.tsx, frontend/src/pages/Graphing/components/Graph.tsx, frontend/src/pages/Graphing/components/LineChart.tsx
When hovering over one chart, we should should the same points on other charts on the dashboard. Making it easier to relate charts to each other.
1. Create multiple line charts on the same dashboard.
2. Hover over one of the line charts
N/A
N/A
=> Sync timestamp charts

frontend/src/components/JsonViewer/JsonViewerObject.tsx, frontend/src/components/JsonViewer/JsonViewerV2.tsx, frontend/src/components/Search/SearchContext.tsx, frontend/src/components/Search/SearchForm/SearchForm.tsx, frontend/src/components/Search/SearchForm/hooks.ts, frontend/src/components/Search/SearchForm/utils.test.ts, frontend/src/components/Search/SearchForm/utils.ts, frontend/src/pages/LogsPage/LogsTable/LogDetails.tsx, frontend/src/pages/LogsPage/LogsTable/LogsTable.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ConsoleTable/index.tsx, frontend/src/pages/Traces/TraceSpanAttributes.tsx
Fixes some issues with the query builder:
1. Ensures we don't replace parenthesis and `NOT` operator in certain queries. e.g. if you enter `NOT(service_name=all)` and select `all` from the dropdown items, it would replace the query with just `service_name=all`.
2. Eliminates `stringifySearchQuery` and the need to build a search string for structured params.
3. Fixes a bug where the typeahead wasn't being shown when entering a space after a completed search param.
4. Simplified the logic for storing and filtering recent searches.
Click tested with a number of different queries + added unit tests for bugs I encountered throughout the process. Would appreciate if the reviewer could also click test in the PR preview.
N/A
N/A
=> Fix query string replacement on item selection

backend/main.go, backend/util/runtime.go, backend/worker/worker.go, docker/compose.enterprise.yml
The on-prem instances are not running the alert checks. Update the yml file to start the scheduled tasks
Note: update the all service to use the same schedule tasks logic.
1. Run the enterprise app
2. Create a log alert
3. Run an E2E app to kick off logs
N/A
N/A
=> Add scheduled tasks for enterprise

docs-content/getting-started/5_backend-logging/03_python/1_overview.md, docs-content/getting-started/5_backend-logging/03_python/otel.md, highlight.io/components/QuickstartContent/QuickstartContent.tsx, highlight.io/components/QuickstartContent/logging/python/otel.tsx
Adds a simple python logging OTEL quickstart guide.
n/a
n/a
n/a
=> Add a python logging OTEL quickstart guide

frontend/src/components/RelatedResources/hooks.ts, frontend/src/hooks/useSearchTime.ts, frontend/src/pages/Alerts/AlertGraph/index.tsx, frontend/src/pages/Graphing/Dashboard.tsx, frontend/src/pages/Graphing/ExpandedGraph.tsx, frontend/src/pages/Graphing/GraphingEditor.tsx, frontend/src/pages/Graphing/components/BarChart.tsx, frontend/src/pages/Graphing/components/FunnelChart.tsx, frontend/src/pages/Graphing/components/Graph.tsx, frontend/src/pages/Graphing/components/LineChart.tsx, frontend/src/pages/Graphing/components/Table.tsx, frontend/src/pages/Graphing/hooks/useGraphingVariables.tsx, frontend/src/pages/Traces/CustomColumns/renderers.tsx
- unnecessary dependencies were causing graphs to rerender when opening the related resources panel
- memoize graphs and certain props to limit react rendering
- used the react profiler locally to make sure graphs weren't rerendering + clicktesting in preview env
- no
- no
=> refactor / memoize dashboard dependencies to speed up rendering for related resources

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, e2e/tests/pyproject.toml, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/mutation.gql, frontend/src/pages/ProjectSettings/DangerForm/DangerForm.tsx, frontend/src/pages/WorkspaceSettings/FieldsForm/FieldsForm.module.css, frontend/src/pages/WorkspaceSettings/FieldsForm/FieldsForm.tsx, frontend/src/pages/WorkspaceSettings/WorkspaceSettings.tsx, packages/predictions/pyproject.toml
Member level users should not be able to edit the names of workspaces/projects or delete projects.
Frontend:
Add frontend level validation to not allow member level edits of these properties. Give a tooltip to explain why the fields are disabled with next steps. Hides delete input entirely to non admin roles.
Also made a couple small tweaks to clean up and low effect style changes to better match other forms.
https://www.loom.com/share/aeadfb8096824627901b1aab0f848954?sid=d4e63bed-8974-48d6-afef-8704c1bec783
Backend:
1. [DeleteProject](https://github.com/highlight/highlight/blob/main/backend/private-graph/graph/schema.resolvers.go#L911) - already limited to only admin level roles
2. EditProject - limit to only admin level roles (only use for name and billing email)
3. EditProjectSettings …
=> Project and workspace settings admin validation

highlight.io/components/QuickstartContent/logging/python/otel.tsx
Update the copy for the Python / OTEL / Logging text so it reads nicer in the tutorial / docs. 
Before this change it looked like this:
=> Update Python / OTEL Copy

frontend/src/pages/Graphing/components/BarChart.tsx, frontend/src/pages/Graphing/components/Graph.tsx, frontend/src/pages/Graphing/components/LineChart.tsx, frontend/src/pages/Graphing/components/utils.ts
Sync the timestamps of dashboards by the closest value of the timestamp - do not sync graphs that are not bucketed by timestamp.
https://www.loom.com/share/8678ed33fec14ce9aaef0ee96c865f11?sid=4341add1-f031-4c28-96b3-5463a68769e0
1. Create a line chart that is grouped by timestamp and 30 minute intervals
2. Create a line chart that is grouped by timestamp and 1 hour intervals
3. Create a bar chart that is grouped by timestamp and 30 minute intervals
4. Create a line chart that is grouped by something other than timestamp
N/A
N/A
=> Sync timestamp graphs

backend/main.go, backend/otel/otel.go, backend/worker/kafka_worker.go, sdk/highlight-go/log/console_messages_parser.go, sdk/highlight-go/trace/tracer.go
Removes a number of noisy logs based on 
https://app.highlight.io/1/metrics/21286/view/48313?relative_time=last_7_days and https://app.highlight.io/1/metrics/21286/view/48358?relative_time=last_7_days
These are currently adding substantially to our CloudWatch bill.
Local deploy still working correctly
no
no
=> cleanup noisy backend logs

frontend/src/pages/Graphing/components/DashboardCard.tsx, frontend/src/pages/Graphing/components/Graph.tsx
- store state in local storage to track if user has used drilldown already
- if so, don't show the `click to drilldown` hint
- no
- no
=> hide use drilldown hint when user is aware

frontend/src/pages/Alerts/AlertForm/index.tsx
Constant threshold alerts for errors and sessions only support grouping by `secure_id`. However, if you switch to anomaly alerts, you can clear/change the group by key. Update the form to reset the `group_by_key` to `secure_id` for constant threshold alerts for errors and sessions.
1. Create a constant threshold alert for sessions/errors
2. Switch it to an anomaly alert
3. Clear the Group By field
4. Switch back to a constant threshold alert
5. Save
Check the Prod DB for any alerts that are out of sync
N/A
=> Fix bug when switching between threshold and anomaly alerts

frontend/src/pages/Graphing/Dashboard.tsx, frontend/src/pages/Graphing/hooks/exportGraph.ts, frontend/src/util/session/report.ts
- splits the session csv and graph csv `processRows` logic into 2 to account for the new format for graph data
- `useGraphContext` to make sure context is shared between all `DashboardCell` instances now
- clicktested locally with different graph permutations
- no
- no
=> fix [object Object] in graph csv export

backend/worker/worker.go, e2e/tests/src/test_cypress.py
* Ensure that sessions with the last interval as inactive record that correctly
* Calculate active time based on user activity rather than relying on rrweb event intervals
local deploy
more accurate active duration reported on a session that was closed and reloaded
monitoring new active time, customer outreach
no
=> correct active interval calculation logic

frontend/src/pages/WorkspaceTeam/WorkspaceTeam.tsx, frontend/src/pages/WorkspaceTeam/components/AllMembers.tsx
Update styling of workspace members page to make it possible to see user emails in the list.
Feedback from customer who found it hard to audit project level access by email.
[reflame](https://preview.highlight.io/w/27699/team?%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201JHVCVRHJDMJG9MFXCFA84T8N%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22vadim%2Fworkspace-page-improvements%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D)
no
yes
=> display admin emails on workspace members page

docs-content/getting-started/fullstack-frameworks/next-js/3_app-router.md
app folder is used when using the app router instead of having a pages folder.
=> fix: update `pages` to `app` for app router

.changeset/neat-foxes-pull.md, sdk/highlight-next/src/next-client.tsx, sdk/highlight-next/src/util/with-highlight-config.ts
The getHighlightConfig function also returns configureHighlightProxy.
In the component, set the backendUrl to /highlight-events if configureHighlightProxy is enabled in the next config. The properties of the next config can be accessed using the getInfo function from next/config.
Supercedes https://github.com/highlight/highlight/pull/9710
Closes #9042
Closes HIG-4835
local deploy
changeset
no
=> fix: nextjs sdk proxy configuration

frontend/src/pages/Graphing/components/Table.tsx
Some dashboard tables are causing frontend performance issues. Optimize by:
- virtualize the table
- memoize data sorting and filtering
- break out row into new component to avoid re-rendering
- remove tooltips for titles
1. Create a table or view a table with lots of rows
2. Load the page
N/A
N/A
=> Fix table latency on dashboards

backend/alerts/v2/destinations/email/messages.go
Creating / updating alerts would trigger a notification to pagerduty resulting in a false alarm.
Avoid sending modification alerts to `steelhouse.pagerduty.com` emails.
checking filtering logic
no
no
=> avoid sending alert modification notifications for pagerduty

.github/workflows/deploy.yml, .github/workflows/docker.yml, docker/.env, docker/compose.enterprise.yml, docker/env.sh
* Support pinning docker images in the `docker/.env` 
* Fix how metrics workers are spun up in the enterprise deploy
* Push dedicated images for each versioned release (each docker-tag).
CI
will be released with new tag
no
=> improve enterprise deploy

backend/private-graph/graph/schema.resolvers.go, frontend/src/pages/Player/components/EventStreamV2/EventStreamV2.tsx
Sessions like /26425/sessions/owVTdWNf043ha1xxtUwlhN5gu8RF
would crash rendering because they were missing web vitals and the new
query path would require web vitals to be present.
[reflame](https://preview.highlight.io/26425/sessions/owVTdWNf043ha1xxtUwlhN5gu8RF)
checking web vitals loading correctly
no
no
=> fix frontend rendering of missing webvitals

backend/private-graph/graph/schema.resolvers.go, backend/public-graph/graph/resolver.go, frontend/src/pages/Player/StreamElement/Renderers/WebVitals/utils/WebVitalsUtils.ts, frontend/src/pages/Player/components/EventStreamV2/EventStreamV2.tsx
Correct web vitals filtering logic on the frontend to make sure sessions with web vitals have their metrics loaded.
Add `INP` as another web vital rendered for sessions
in [reflame](https://preview.highlight.io/1/sessions/O7HqhjYdzmg7vCRIEvfXr0GTW4YB?%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201JJCT1Y85VXY8NZ82YZX1HFQT%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22vadim%2Ffix-session-web-vitals%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D)
no
no
=> correctly render session web vitals fetched via metrics

blog-content/supporting-opentelemetry-metrics.md
Adds a new blog on our metrics ingest approach.
[vercel](https://highlight-landing-git-vadim-otel-metrics-blog-highlight-run.vercel.app/blog/supporting-opentelemetry-metrics?vercelToolbarCode=GC0OZerIhkrmYcG)
no
no
=> add blog on opentelemetry metrics ingest

frontend/src/pages/Home/components/KeyPerformanceIndicators/utils/utils.ts, frontend/src/pages/Player/components/EventStreamV2/utils.ts
Fix frontend crash due to new web socket metrics format.
[reflame](https://preview.highlight.io/1/sessions/E53sxIIb1A4HPCqJPI9rO3SXe8v9?%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201JJPX07V7ET3JRK2QTPNY8DGB%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22sup-178-errorboundary-cmtolowercase-is-not-a-function%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D)
no
no
=> fix frontend crash due to new web socket metrics format

packages/ui/src/css/theme.css.ts
- Updated the secondary overlay hover opacity in `packages/ui/src/css/theme.css.ts`
- Changed the hover color in the `interactive.overlay.secondary` theme from `rgba(238, 237, 239, 0.05)` to `rgba(22, 22, 24, 0.05)` (#1616180D)
- This affects all components using the secondary overlay hover state, including bar charts
```tsx
// packages/ui/src/css/theme.css.ts
secondary: {
enabled: 'rgba(238, 237, 239, 0.0)',
hover: 'rgba(22, 22, 24, 0.05)', // Updated this line to use 5% opacity
pressed: '#e9e8ea',
...
}
Fixes #9811
=> fix: update bar chart hover opacity to 5% (#9811)

.changeset/loud-pandas-tease.md, __generated/rr/rrweb/rr.js, sdk/client/src/index.tsx, sdk/client/src/listeners/console-listener.tsx, sdk/client/src/listeners/error-listener.tsx, sdk/client/src/utils/errors.ts
Consolidate the `ErrorStackParser.parse` logic and ensure exceptions raised by the method are caught.
local sdk testing catching errors
changeset
no
=> reduce noisy ErrorStackParser.parse failures when failing to parse provided error

backend/clickhouse/migrations/000140_readonly_metrics.down.sql, backend/clickhouse/migrations/000140_readonly_metrics.up.sql, backend/private-graph/graph/schema.resolvers.go, frontend/src/pages/Graphing/components/SqlEditor.tsx
- previously, was querying keys once without a query to return a list of the most popular keys
- this will re-query keys using the current word
- support metrics queries
https://www.loom.com/share/9a79b10f23af4751a912d6e3d7ce00a4
- no
- no
=> improve sql editor autocomplete by querying keys

backend/clickhouse/migrations/000141_metrics_table_reduce_raw_ttl.down.sql, backend/clickhouse/migrations/000141_metrics_table_reduce_raw_ttl.up.sql
Ingest metrics tables have high granularity data that is rolled up into the `metrics` table via MVs.
The retention based TTL should only be applied to the destination `metrics` table.
local deploy
will help reduce storage cost of metrics
no
=> update TTL of raw metrics tables

.changeset/config.json, .changeset/fair-dryers-behave.md, cypress/e2e/login.cy.js, cypress/pages/local.html, e2e/react-native/package.json, frontend/src/pages/Buttons/Buttons.tsx, packages/mock-otel-server/package.json, packages/mock-otel-server/src/index.ts, sdk/client/package.json, sdk/client/src/index.tsx, sdk/client/src/otel/exporter.ts, sdk/client/src/otel/index.ts, sdk/client/src/otel/user-interaction.ts, sdk/client/src/types/types.ts, sdk/firstload/src/index.tsx, turbo.json, yarn.lock
Introduces OTLP metrics export to the highlight.run SDK.
Adds a `H.gauge` function to supercede the legacy `pushMetrics` GraphQL export.
Migrates existing auto-reported metrics to the new export format.
changeset
no
=> add basic opentelemetry metrics support to highlight.run

.changeset/swift-bears-compete.md, cypress/e2e/client.cy.js, sdk/client/src/index.tsx, sdk/client/src/listeners/network-listener/performance-listener.ts, sdk/client/src/listeners/performance-listener/performance-listener.ts
Adds a new `navigator.connection` periodic listener that emits metrics throughout the session
showing browser estimates of network performance along with connection attributes.
changeset
no
=> add internet speed instrumentation to the highlight.run web sdk

highlight.io/app/api/sitemap/route.ts
I noticed in our Google Search Console that a bunch of links weren't working for competitor pages. I think we forgot to update the sitemap URLs after changing the structure of them.
Hit http://localhost:4000/sitemap.xml to verify the changes.
N/A
N/A
=> Fix competitor URLs in sitemap

backend/clickhouse/query.go, frontend/src/pages/Alerts/AlertGraph/index.tsx
- non-memoized `expressions` was causing graph to be redrawn repeatedly and lagging / crashing the UI
- no data (e.g. an alert that did not trigger in the shown time period) was displaying as unix zero time
- should refactor useEffect in `Graph` to prevent non-memoized arguments from doing this in the future
- no
=> fix alert graph loop, graphs with time range and no rows

frontend/src/pages/Player/StreamElement/Renderers/WebVitals/WebVitalRender.tsx
- seems there are some new web vitals causing the right feed to break
- clicktested locally, with this fix web vitals is just a blank entry:
- no
- no
=> test fix in preview

backend/clickhouse/migrations/000139_create_readonly_user.up.sql, backend/clickhouse/query.go, backend/clickhouse/sessions.go, backend/private-graph/graph/schema.resolvers.go, frontend/src/pages/Graphing/GraphingEditor.tsx, frontend/src/pages/Graphing/components/Graph.tsx
- instead of transforming the input into a sqlbuilder select query, keep it in parsed form
- this allows more flexible types of input query (e.g. CTEs, union queries, nested selects)
- identify parts querying the main product tables and apply default filters to those only
- add other filters to the parsed form before transforming back into a string
- clicktested locally for multiple resource types, complex queries
- no
- no
=> SQL builder - support more complex queries

frontend/src/components/KeyboardShortcutsEducation/KeyboardShortcutsEducation.tsx, frontend/src/components/Search/SearchContext.tsx, frontend/src/components/SearchPagination/SearchPagination.tsx, frontend/src/pages/Alerts/AlertPage/index.tsx, frontend/src/pages/ErrorsV2/ErrorsV2.tsx, frontend/src/pages/ErrorsV2/useGetErrorGroups.ts, frontend/src/pages/Player/PlayerHook/utils/index.tsx, frontend/src/pages/Player/PlayerPage.tsx, frontend/src/pages/Player/SessionLevelBar/SessionLevelBarV2.tsx, frontend/src/pages/Player/utils/PlayerHooks.tsx, frontend/src/pages/Sessions/useGetSessions.ts
`j` and `k` buttons would switch between next/previous sessions and error groups.
When a page boundary is encountered, the next/previous resource would not be loaded
as the frontend relies on the contents of the current page to include the resource.
Updates the logic to rely on the resource index, loading the desired page to find the necessary resource.
The logic can be summarized as follows:
```
Instead of thinking in terms of “page 1, element 5”, you maintain a single state that represents the absolute index of the selected item in the overall list. For example, if each page shows 10 items, then:
•	The first page contains indices 0–9.
•	The second page contains indices 10–19.
•	And so on.
* When the user hits the next key:
•	You increment the absolute index.
•	Then you calculate the …
```
=> support session and error j/k shortcuts crossing page boundary

frontend/src/pages/WorkspaceTeam/components/AllMembers.tsx, frontend/src/pages/WorkspaceTeam/components/InviteMemberModal.tsx
Corrects an issue in the new member invite modal that would send
all project IDs for a `MEMBER` invite when specific projects were selected.
no
no
=> fix project ids sent by frontend with member project level access

.changeset/shiny-hats-hope.md, .changeset/strong-rules-destroy.md, backend/otel/metrics.go, highlight.io/components/QuickstartContent/server/dotnet/dot-net-4.tsx, highlight.io/components/QuickstartContent/server/dotnet/dot-net.tsx, highlight.io/components/QuickstartContent/traces/dotnet/dot-net-4.tsx, highlight.io/components/QuickstartContent/traces/dotnet/dot-net.tsx, highlight.io/instrumentation.ts, highlight.io/pages/_app.tsx, sdk/client/src/index.tsx, sdk/highlight-next/src/next-client.tsx, sdk/highlight-next/src/util/with-highlight-config.test.ts, sdk/highlight-next/src/util/with-highlight-config.ts
Use the `<HighlightInit>` component and turn off features that may affect site performance.
Updates the `@highlight-run/next` SDK to proxy frontend OpenTelemetry requests.
new session captured https://app.highlight.io/demo/sessions/lIM6TmDQUWE6ardqPfan5JR5LiWQ
vercel preview
proxying tested for otlp endpoints
no
no
=> update configuration of highlight sdk on landing page

backend/clickhouse/migrations/000142_trace_mvs.down.sql, backend/clickhouse/migrations/000142_trace_mvs.up.sql
- there were no MVs to write these attributes to the `trace_key_values` table, so they're missing from key and value suggestions
- checked a couple fields (e.g. `telemetry.distro.name`) after running migration script locally
- no
- no
=> add missing fields to mvs

backend/clickhouse/query.go
- fix issue w/ event table references
- if timestamp is used in the where clause, override the default timestamp (this is helpful for calculating backward-looking things like MAU)
- https://www.loom.com/share/0d6338c12de144cd8837d0eb1e7f9d23
- no
- no
=> fix events, add timestamp override

.changeset/curly-tables-mate.md, .changeset/lovely-tips-speak.md, .changeset/rich-roses-breathe.md, highlight.io/next.config.js, sdk/client/src/index.tsx, sdk/client/src/listeners/first-load-listeners.tsx, sdk/client/src/listeners/network-listener/utils/utils.test.ts, sdk/client/src/listeners/network-listener/utils/utils.ts, sdk/client/src/otel/index.ts, sdk/firstload/src/index.tsx
The `@highlight-run/next` SDK proxied
`/highlight-events`, `/v1/traces`,  `/v1/logs`, and  `/v1/metrics` endpoints would be recorded
by the highlight network request recording because they were referring to the hostname of the
page by the proxying. This would result in main loop blocking from large payload serialization.
vercel preview
captured session with correct data
https://app.highlight.io/demo/sessions/hWfL4lYZhAeasJoVCP5KD9uJjduo
changeset
Fixes HIG-5147
no
=> avoid recording proxied highlight next.js requests

backend/event-parse/parse.go
Resolves a noisy log from processing `blob:` urls server side
that were not recorded client side (only can be captured client side as these are JS video streams).
CI
no
no
=> avoid trying to server-side download blob assets

backend/clickhouse/query.go, backend/clickhouse/sessions.go, backend/go.mod, backend/go.sum, go.work.sum
- support joins for non-resource tables, fix certain window expressions by forking the parser
- eventually we can support joins for resource tables, but the default filtering logic is difficult to apply
- clicktested locally w/ window function
- no
- no
=> support join for non-resource tables, fix issues w/ OVER ROWS expressions

frontend/src/pages/Graphing/hooks/exportGraph.ts, frontend/src/pages/LogsPage/LogsCount/LogsCount.tsx, frontend/src/pages/LogsPage/LogsPage.tsx, frontend/src/pages/LogsPage/utils.ts, frontend/src/util/session/report.ts
Adds a new download button to the logs count display that allows downloading the current loaded logs as a CSV.
[reflame preview](https://preview.highlight.io/1/sessions?%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22ewr%22%2C%22variantId%22%3A%2201JKSNK581E7JYEWMEFXWYFYJW%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22sup-184-download-filtered-logs-as-json%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D)
currently only logs; will add for traces if there is a customer use-case
yes @julian-highlight
=> add basic ability to download logs

.changeset/large-houses-own.md, sdk/client/src/index.tsx, sdk/client/src/types/types.ts
Introduces new `inlineVideos` client setting that enables recording any `<video>` elements
as a canvas. This allows capturing `<video>` elements that may reference a `src="https://short-lives-url"`
that would not be accessible after the session is over, and ones that cannot be replaced server-side
because the highlight backend would not be authorized.
local SDK build [capturing session](https://app.highlight.io/5403/sessions/h26yBQ4XdD7Oxs9JmXEzVpFwG28A)
original element is `<video crossorigin="anonymous" src="https://s3-signed-url...">`
changeset 
no
=> support inlining remote video elements using the canvas manager

highlight.io/app/api/rss/route.ts, highlight.io/components/Blog/BlogPage.tsx, highlight.io/next.config.js, highlight.io/package.json, yarn.lock
Adds an RSS feed for the Highlight.io blog.
Local + PR preview click test. I ran the XML through an RSS validator as well.
* PR Preview RSS Feed: https://highlight-landing-lko6eysa0-highlight-run.vercel.app/blog/rss.xml
* PR Preview Blog: https://highlight-landing-lko6eysa0-highlight-run.vercel.app/blog
N/A - should only be adding a new route that nobody is hitting yet. Will verify behavior by importing posts into dev.to once this is live.
N/A
=> Add RSS feed for blog

backend/worker/worker.go, docker/collector.Dockerfile, docker/compose.yml
* Addresses cardinality of worker session processing metric
* Mounts SSL certificate into the docker deploy opentelemetry collector
CI
no
no
=> fix worker.session.initialize.count metric cardinality

backend/pricing/pricing.go
Stripe payment method check would be too strict in validating the CVC 
(some mastercard customers may fail the check even with a valid payment method).
checking behavior in production
clear `cannot show billing banner` for affected customer
no
=> fix stripe payment method check

backend/kafka-queue/kafkaqueue.go, backend/kafka-queue/kafkaqueue_test.go, backend/kafka-queue/types.go, backend/otel/otel_test.go, backend/worker/kafka_worker.go
Propagate the trace context via the kafka message headers in our backend.
Helps with debugging kafka processing and demoing the distributed tracing.
will monitor number of spans created in prod in case this affects sampling
no
=> setup trace context propagation through kafka

deploy/otel-collector.yaml, docker/.env, docker/collector.yml, docker/configure-collector.sh
Support `collector://` hosts sending requests to our OTeL collectors by
allowing them in the CORS policy.
locally deploying collector
no
no
=> update collector CORS configuration

backend/clickhouse/errors.go, backend/clickhouse/migrations/000144_add_error_groups_snoozed_until.down.sql, backend/clickhouse/migrations/000144_add_error_groups_snoozed_until.up.sql, backend/clickhouse/migrations/000145_reacreate_errors_joined_vw.up.sql, backend/clickhouse/migrations/000145_recreate_errors_joined_vw.down.sql, backend/jobs/metric-alerts/metric-alerts.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/schema.graphqls, frontend/src/graph/generated/schemas.tsx
Snoozed errors are still alerting
1. Create an error alert that reports to Slack
2. Cause an error
3. Snooze the error
4. Cause the error
5. After snooze expires
6. Cause the error
N/A
N/A
=> Snooze error alerts

backend/event-parse/parse.go, backend/event-parse/parse_test.go, backend/main.go, backend/public-graph/graph/resolver.go, backend/redis/cache.go, backend/worker/worker.go
- there are a few places in pushPayload that we marshal/unmarshal to transform between types; however this is expensive and circumvents the type system
- clicktested locally to make sure sessions were being recorded correctly
- observed logs to check for 
- will monitor prod after deployment - able to revert and replay the sessions queue if issues
- no
=> remove extra marshalling/unmarshalling in pushPayload

frontend/src/pages/Graphing/GraphingEditor.tsx, frontend/src/pages/Graphing/components/SqlEditor.tsx
- convert settings to SQL when switching editor modes
- https://www.loom.com/share/98f6c63ac38a4af4bc65afffb580f838
- no
- no
=> convert graphing editor settings to sql

backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/model/models_gen.go, backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/graph/generated/schemas.tsx, frontend/src/pages/Graphing/components/CreateDashboardModal.tsx
- when creating a dashboard, can select "AWS Metrics" or "Frontend Metrics"
- no
- no
=> add default dashboards for AWS and frontend metrics

frontend/src/__generated/index.css, frontend/src/__generated/ve/pages/Graphing/EventSelection/EventSteps.css.js, frontend/src/pages/Graphing/EventSelection/EventSteps.css.ts, frontend/src/pages/Graphing/EventSelection/EventSteps.tsx, frontend/src/pages/Graphing/GraphingEditor/FormPanel/VisualizationSection.tsx, frontend/src/pages/Graphing/components/BarChart.tsx, frontend/src/pages/Graphing/components/Graph.tsx
Update the funnels view to:
- add actions to funnel steps (edit/move/etc)
- step UI
- allow funnels to be selected without events selected (switches to events)
- add labels when viewing a bar chart (not applied to line graphs)
1. Create a new graph
2. Select a funnel
3. Create a new funnel
4. Confirm the UI
N/A
N/A
=> Funnel improvements

.changeset/early-timers-clean.md, blog-content/monitoring-browser-applications-with-opentelemetry.md, docs-content/getting-started/3_browser/7_replay-configuration/opentelemetry.md, docs-content/sdk/client.md, sdk/client/src/index.tsx, sdk/client/src/listeners/first-load-listeners.tsx, sdk/client/src/listeners/network-listener/network-listener.ts, sdk/client/src/listeners/network-listener/utils/fetch-listener.ts, sdk/client/src/listeners/network-listener/utils/utils.ts, sdk/client/src/listeners/network-listener/utils/xhr-listener.ts, sdk/client/src/types/types.ts, sdk/firstload/src/index.test.tsx, sdk/firstload/src/index.tsx, sdk/firstload/src/listeners/web-socket/index.ts
Adds an option to disable browser OTel changes, using the removed changes from https://github.com/highlight/highlight/pull/9598 as a guide.
1. Start a session
2. View traces
3. Set `disableOtelTracing: true` in the Highlight initialization
4. Start a new session
5. View traces
Bump minor version
N/A
=> Frontend trace killswitch

backend/public-graph/graph/schema.resolvers.go
- increase ingest sampling rate to 50%
- will monitor production traffic
- 10% sampling is still in effect for pushPayload processing. Increase ingest rate first, then increase processing sampling if all looks good
- no
=> increase ingest sampling rate to 50%

backend/private-graph/graph/schema.resolvers.go, frontend/src/components/Billing/EnterpriseFeatureButton.tsx, frontend/src/pages/Graphing/DashboardOverview.tsx
Bug reported that they cannot create a dashboard despite only having 1 dashboard - DB confirms only 1 dashboard
- add logging
- remove unnecessary queries
- update wording on frontend to say "3 dashboards" as per the backend and [pricing page](https://www.highlight.io/pricing)
1. Create a new workspace
2. Try to create a new dashboard
3. Try to create a new dashboard
4. Try to create another dashboard
Remove unnecessary logs after debug
N/A
=> Debug enable business dashboards

.changeset/early-timers-clean.md, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts, sdk/highlight-next/CHANGELOG.md, sdk/highlight-next/package.json, sdk/highlight-react/CHANGELOG.md, sdk/highlight-react/package.json, sdk/highlight-remix/CHANGELOG.md, sdk/highlight-remix/package.json
`Publish npm packages` is failing - left out bumping the version using this PR as a guide: https://github.com/highlight/highlight/pull/9598
N/A
N/A
N/A
=> Bump version

.changeset/great-carrots-retire.md, docs-content/sdk/cloudflare.md, e2e/cloudflare-worker/package.json, e2e/cloudflare-worker/src/index.ts, e2e/cloudflare-worker/tsconfig.json, sdk/highlight-cloudflare/CHANGELOG.md, sdk/highlight-cloudflare/package.json, sdk/highlight-cloudflare/src/exporter.ts, sdk/highlight-cloudflare/src/sdk.ts, sdk/highlight-cloudflare/tsconfig.json, sdk/highlight-next/CHANGELOG.md, sdk/highlight-next/package.json, yarn.lock
The `@highlight-run/cloudflare` SDK would use an exporter that `extends OTLPTraceExporter`
which would break in the cloudflare runtime, because that required importing JS implementation for
`@opentelemetry/otlp-exporter-base` which is not cloudflare runtime compatible.
Replace the `extends` call with a class that implements the necessary methods.
Fixes HIG-5168
Fixes HIG-5167
before
after (expected sample error from e2e cloudflare app)
cloudflare worker proxied html
data coming through in highlight
new versions released in branch
`yarn changeset add; yarn changeset version`
no
=> fix @highlight-run/cloudflare SDK using invalid OTel class extension

backend/go.mod, backend/go.sum, backend/public-graph/graph/resolver.go, backend/public-graph/graph/sampling.go, backend/public-graph/graph/sampling_test.go, backend/worker/kafka_worker.go
- in production, the `public-graph.pushPayload.parseEvents.remarshalEvents` span is 30%-40% of the total processPayload time for larger messages
- this change switches every `resolver.go` json.Marshal / Unmarshal call to use an alternate library
- change sampling logic to sample in 1/1000 of processPayload messages to ingest more processPayload spans and avoid overrepresenting larger messages
- ran locally, saw an improvement in the remarshal spans
- no, can revert if issues 
- no
=> push payload perf

backend/private-graph/graph/auth_client.go, frontend/src/routers/ProjectRouter/ProjectRouter.tsx
* Periodic `/project-token` requests would break auth by forcing a logout due to using an old login token
* Use the user `name` claim for OAuth SSO
preview, deploying to prod
no
no
=> avoid project-token refresh breaking auth

.changeset/clean-balloons-pump.md, highlight.io/components/QuickstartContent/backend/shared-snippets.tsx, highlight.io/components/QuickstartContent/traces/dotnet/shared-snippets.tsx, sdk/client/src/index.tsx, sdk/client/src/types/types.ts, sdk/firstload/src/index.tsx
Replace the `skipCookieSessionDataLoad` setting with an opt-in version (`sessionCookie: true`)
to default to not using the session cookie. While the cookie technique is useful to associate
server-side rendering context with the frontend session replay which starts after the trace,
the cookies cause HTTP request bloat when multiple navigations occur since they are not cleared.
Recommend the setting be used only when needed (for .NET Blazer apps, for instance).
CI
changeset included
no
=> turn off session cookie storage by default

backend/clickhouse/query.go, frontend/src/pages/Graphing/components/Graph.tsx, frontend/src/pages/Graphing/components/Table.tsx
- user wants to create table with a timestamp series; right now we automatically bucket by timestamp
- this allows series/group behavior to be overridden by aliasing the column to "x_series" or "x_group"
- no
- no
=> use aliases to override group/series/bucket behavior

backend/public-graph/graph/resolver.go, backend/worker/worker.go
- need to add new fields to the cached session object; affecting session exclusion logic for queries using custom fields
- tested session ingestion locally, will monitor in prod
- no
- no
=> fix field caching

backend/public-graph/graph/resolver.go
- because sessionObj.Fields was populated, this was causing unnecessary writes to `session_fields` and `fields`
- debug logging locally
- no
- no
=> fix issue where fields were written unnecessarily

frontend/src/pages/Alerts/AlertForm/index.tsx, frontend/src/pages/Alerts/constants.ts, frontend/src/pages/Graphing/EventSelection/ClickFilters.tsx, frontend/src/pages/Graphing/EventSelection/NavigateFilters.tsx, frontend/src/pages/Graphing/EventSelection/index.tsx, frontend/src/pages/Graphing/GraphingEditor/FormPanel/GroupBySection.tsx, frontend/src/pages/Graphing/GraphingEditor/FormPanel/QueryBuilder.tsx, frontend/src/pages/Graphing/OptionDropdown/index.tsx, frontend/src/pages/Graphing/components/Graph.tsx, frontend/src/pages/Graphing/components/VariablesModal.tsx, frontend/src/pages/Graphing/constants.tsx
Improve the view type option dropdown to:
- show icons
- add a info tooltip for funnels
1. Create a new graph
2. Expand the "View type" option dropdown
N/A
N/A
=> Improve funnel option dropdown

.changeset/clean-balloons-pump.md, .changeset/config.json, .changeset/rude-ghosts-unite.md, .changeset/tough-wolves-explain.md, .github/workflows/turbo.yml, e2e/aws-lambda/package.json, sdk/client/src/index.tsx, sdk/firstload/CHANGELOG.md, sdk/firstload/package.json, sdk/firstload/src/__generated/version.ts, sdk/highlight-apollo/CHANGELOG.md, sdk/highlight-apollo/package.json, sdk/highlight-hono/CHANGELOG.md, sdk/highlight-hono/package.json, sdk/highlight-nest/CHANGELOG.md, sdk/highlight-nest/package.json, sdk/highlight-next/CHANGELOG.md, sdk/highlight-next/package.json, sdk/highlight-node/CHANGELOG.md, sdk/highlight-node/package.json, sdk/highlight-react/CHANGELOG.md, sdk/highlight-react/package.json, sdk/highlight-remix/CHANGELOG.md, sdk/highlight-remix/package.json, yarn.lock
Make sure that the `sendMode: 'local'` setting correctly increments `payloadId` with each submission.
before
payload 1
payload 2
after
changeset
no
=> fix local sendmode in highlight.run sdk

.github/workflows/docker.yml, .github/workflows/e2e.yml, backend/private-graph/graph/auth_client.go, cypress/e2e/sso.cy.js
Since the same client can be configured for more than one domain, this causes
an issue with the `user email x@y.z does not match allowed domains` check because
one of the domains will be picked rather than all being scanned.
new e2e cypress test validating SSO working
local testing
no
no
=> fix sso breaking when multiple domains are set up for the same client

e2e/python/highlight_kafka/README.md, e2e/python/highlight_kafka/kafka.mjs, e2e/python/highlight_kafka/kafka.py, e2e/python/highlight_kafka/package.json, e2e/python/highlight_script/kafka.py, e2e/python/poetry.lock, e2e/python/pyproject.toml, package.json, yarn.lock
Adds a new e2e example app that sets up a Python Kafka producer and a Node.js Kafka consumer,
demonstrating trace context propagation between the two services.
no
no
=> add e2e python to node kafka example

backend/private-graph/graph/auth_client.go, backend/private-graph/graph/middleware.go
The frontend expects a 401 when the login expires to retrigger a login.
Make sure expected auth errors return 401 to avoid the frontend getting stuck in a loading loop.
local deploy with SSO setup
no
no
=> improve error handling when oauth token is expired

frontend/src/pages/Player/Toolbar/ToolbarControlBar/ToolbarControlBar.tsx, frontend/src/pages/Player/utils/PlayerHooks.tsx
The log and trace information is not accessible for logged out users, even if the session is public. Disable the dev tools for users that are not logged in.
1. View a session while signed in and make the session public
2. View the session in an incognito window while logged out
N/A
N/A
=> Disable dev tools for public users

backend/private-graph/graph/auth_client.go
Support a login flow initiated by the SSO provider such as Okta
which will request using the `iss` query string paramater.
In these cases, the oauth middleware will redirect back to the SSO provider
initiating the OAuth2 flow.
deploying to prod w okta
no
no
=> support ISS SSO login initiation

frontend/src/components/RelatedResources/TracePanel.tsx, frontend/src/pages/Traces/TraceSpanAttributes.tsx
Fixes [an error](https://app.highlight.io/1/errors/1DytS4emiHuLuF2m1Pw6lSHHgETd/instances/510389460?search=false) we were seeing from trying to access a context outside its provider.
Click tested locally with the following steps to repro the issue and ensure the fix worked as expected.
N/A
N/A
=> Fix error using context outside provider

backend/go.mod, backend/public-graph/graph/resolver.go
- seems like memory leaks started around when this was originally introduced - switch back to `encoding/json` to test
- will monitor in prod
- no, can revert if performance regresses too much
- no
=> use standard json library

.reflame.config.jsonc
Reflame deploys on main were broken because we were depending on earlier versions of highlight libraries that lacked some of the expected changes.
This PR just bumps those libs to the latest available on NPM.
Clicked the [preview link](https://preview.highlight.io/?%7Er_preview=%7B%22action%22%3A%22start%22%2C%22variantId%22%3A%2201JTGWV01BM7ZXTHS2XJ5BZPZ2%22%2C%22region%22%3A%22ewr%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22bump-reflame-deps%5C%22%2C%5C%22forkSpecifier%5C%22%3A%5C%22lewisl9029%2Fhighlight%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D)
=> Bump reflame deps

frontend/src/pages/Player/PlayerHook/utils/usePlayerConfiguration.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/DevToolsWindowV2.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/PerformancePage/PerformancePage.tsx, frontend/src/pages/Sessions/SessionsFeedV3/SessionFeedConfigDropdown/helpers.ts, packages/ui/src/components/Tabs/Tabs.test.tsx, packages/ui/src/components/Tabs/Tabs.tsx
Make the following bug fixes and optimizations:
- show milliseconds with 2 digits (i.e. 8 -> 08)
- memoize devtool performance graph appropriately
- hide tab children when not rendered
- pass in selected tab id into dev tools tabs to load when page reloads
1. View a session
2. Swap Date format to include date and milliseconds
3. Open the dev tools
4. Swap to performance tab and play session
N/A
N/A
=> Bug fixes and performance optimizations

.github/workflows/e2e.yml, __generated/rr/rrweb/rr.js, frontend/src/pages/Billing/UpdatePlanPage.tsx, frontend/src/pages/Buttons/Buttons.module.css, frontend/src/pages/Buttons/Buttons.tsx, frontend/src/pages/Player/PlayerHook/PlayerHook.tsx, frontend/src/pages/Player/PlayerHook/PlayerState.ts, frontend/src/pages/Player/SessionLevelBar/utils/utils.ts, packages/ui/src/components/Tabs/Tabs.tsx
A few optimizations to the session replayer:
* Changes how rrweb replaces actions by completely replacing the array rather than using `splice` to reset it. This seems to fix an infinite loop we were seeing, though probably has some tradeoffs with creating a new array rather than reusing the existing.
* Filters out custom events before passing events to rrweb since those are only used on the timeline, not for replay.
* Adds some mechanisms for creating many track events at once and viewing very large DOM trees to test those scenarios in recording/replay.
* Prevents Stripe from loading when any page is rendered in our app and lazy loads it only when needed on the update plan page.
Click tested locally and in the Reflame preview, which included the rrweb updates. Compared prod session …
=> Replayer performance optimizations

docs-content/general/7_integrations/nuxt-integration/index.md
- Provides step-by-step instructions for integrating Highlight with Nuxt 3, including:
- SDK installation
- Client-side instrumentation example
- Server-side instrumentation example
- Configuration in `nuxt.config.ts`
- Sourcemap upload instructions
- Manual error reporting example
- Verification steps to confirm setup
- Troubleshooting for common issues
- Updates the integrations index to include the Nuxt guide for discoverability.
- References relevant Highlight and Nuxt documentation.
Closes #6136
/claim #6136
=> docs: add Nuxt integration guide and example instrumentation

backend/private-graph/graph/resolver.go, backend/private-graph/graph/schema.resolvers.go
- we're using the incorrect retention date when querying for errors, noticeable for a customer with sessions retention = 7 days and errors retention = 6 months
- patched from LD repo
- tested in other branch, will validate customer issue after deploying 
- no
- no
=> use correct retention date for errors

deploy/kafka-connect.Dockerfile, deploy/opentelemetry-collector.Dockerfile
Pin OpenTelemetry collector version to avoid 0.131 `snappy` collector breaking changes being deployed.
CI (e2e job)
no
no
=> pin docker image versions

backend/clickhouse/traces.go, backend/clickhouse/traces_test.go, backend/private-graph/graph/generated/generated.go, backend/private-graph/graph/schema.graphqls, backend/private-graph/graph/schema.resolvers.go, frontend/src/components/RelatedResources/RelatedResourceList.tsx, frontend/src/graph/generated/hooks.tsx, frontend/src/graph/generated/operations.tsx, frontend/src/graph/generated/schemas.tsx, frontend/src/graph/operators/query.gql, frontend/src/pages/Player/ResourcesContext/ResourcesContext.tsx, frontend/src/pages/Player/Toolbar/DevToolsWindowV2/TracesPage/TracesPage.tsx, frontend/src/pages/Traces/TracesPage.tsx, frontend/src/pages/Traces/useGetTraces.ts
https://launchdarkly.atlassian.net/browse/O11Y-389
This is a performance improvement. Most places that traces are fetched, the response / request body is not used, though it often is very large. This leads to the client fetching a lot more data than is actually needed.
Tested with local front-end. No changes should be apparent to user other than increased performance. Additionally, added some new go tests to test the new parameter.
Backend change needs to be deployed before frontend change can be deployed
No
=> Adding optional parameter to omit http response / request body when fetching trace information
